CREATE TABLE [dbo].[tbl_Fact_Inventory_Snapshot_Extended] (

	[InventorySnapshotKey] bigint NULL, 
	[CMPNY] varchar(8000) NULL, 
	[Site_ID] varchar(8000) NULL, 
	[Warehouse_ID] varchar(8000) NULL, 
	[Snapshot_Date] date NULL, 
	[Snapshot_Date_Key] int NULL, 
	[Product_ID] varchar(8000) NULL, 
	[ProductName] varchar(8000) NULL, 
	[ProductSearchName] varchar(8000) NULL, 
	[Phantom_Product] varchar(3) NULL, 
	[Inventory_UoM] varchar(8000) NULL, 
	[inventstatusid] varchar(8000) NULL, 
	[location] varchar(8000) NULL, 
	[licenseplateid] varchar(8000) NULL, 
	[inventbatchid] varchar(8000) NULL, 
	[inventserialid] varchar(8000) NULL, 
	[arrived] decimal(38,6) NULL, 
	[availordered] decimal(38,6) NULL, 
	[availphysical] decimal(38,6) NULL, 
	[deducted] decimal(38,6) NULL, 
	[onorder] decimal(38,6) NULL, 
	[ordered] decimal(38,6) NULL, 
	[physicalinvent] decimal(38,6) NULL, 
	[picked] decimal(38,6) NULL, 
	[postedqty] decimal(38,6) NULL, 
	[received] decimal(38,6) NULL, 
	[registered] decimal(38,6) NULL, 
	[reservordered] decimal(38,6) NULL, 
	[reservphysical] decimal(38,6) NULL, 
	[postedcostamount] decimal(38,6) NULL, 
	[arrived_LBs] decimal(38,6) NULL, 
	[availordered_LBs] decimal(38,6) NULL, 
	[availphysical_LBs] decimal(38,6) NULL, 
	[deducted_LBs] decimal(38,6) NULL, 
	[onorder_LBs] decimal(38,6) NULL, 
	[ordered_LBs] decimal(38,6) NULL, 
	[physicalinvent_LBs] decimal(38,6) NULL, 
	[picked_LBs] decimal(38,6) NULL, 
	[postedqty_LBs] decimal(38,6) NULL, 
	[received_LBs] decimal(38,6) NULL, 
	[registered_LBs] decimal(38,6) NULL, 
	[reservordered_LBs] decimal(38,6) NULL, 
	[reservphysical_LBs] decimal(38,6) NULL, 
	[primaryvendorid] varchar(8000) NULL, 
	[Source] varchar(6) NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[VendorKey] bigint NOT NULL, 
	[StandardCostKey] bigint NULL, 
	[BatchKey] bigint NOT NULL, 
	[SerialNumberKey] bigint NOT NULL
);