table 'Date Table'
	lineageTag: cbbe63fe-3d99-4700-acad-44362a9ba616
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_Date]
	dataCategory: Time

	measure 'Selected Fiscal Year' =
			
			SELECTEDVALUE ( 'Date Table'[Fiscal Year] )
		formatString: 0
		isHidden
		lineageTag: ea74d0cc-cca4-49b4-accc-8f57c6dde5ee

		changedProperty = Name

		changedProperty = IsHidden

	measure 'Prior Fiscal Year' =
			
			VAR _fy = [Selected Fiscal Year]
			RETURN
			    IF ( NOT ISBLANK ( _fy ), _fy - 1 )
		formatString: 0
		isHidden
		lineageTag: e5bc8f88-c401-4307-bfbe-8f59af47dff4

		changedProperty = Name

		changedProperty = IsHidden

	measure 'Selected Fiscal Period' =
			
			SELECTEDVALUE ( 'Date Table'[Fiscal Period] )
		formatString: 0
		isHidden
		lineageTag: 79aefc5b-dd2e-4d35-b175-d8d2bde64ae9

		changedProperty = Name

		changedProperty = IsHidden

	measure 'Valid YoY Selection' =
			
			IF (
			    NOT ISBLANK ( [Selected Fiscal Year] )
			        && NOT ISBLANK ( [Selected Fiscal Period] ),
			    1,
			    0
			)
		formatString: 0
		isHidden
		lineageTag: 3195d58c-365f-488a-a1f4-64eaec60535b

		changedProperty = Name

		changedProperty = IsHidden

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7157049c-0e00-4b98-9423-7c55280c5734
		sourceLineageTag: DateKey
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: be043647-47f4-4df7-a373-48f244696fb4
		sourceLineageTag: RecId
		summarizeBy: none
		sourceColumn: RecId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8de448c4-07a1-4bc5-8f3f-a0f5a6d7221f
		sourceLineageTag: FiscalQuarterNum
		summarizeBy: none
		sourceColumn: FiscalQuarterNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: c4e303a8-1e1e-430b-a5da-f43eb9d1e56d
		sourceLineageTag: FiscalYear
		summarizeBy: none
		sourceColumn: FiscalYear

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fa15d150-b0d8-4ae7-aa3d-8d81aff2345e
		sourceLineageTag: CalendarYear
		summarizeBy: none
		sourceColumn: CalendarYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 88bf490c-b354-4a3b-834e-943f56e5ce8a
		sourceLineageTag: CalendarQuarterNum
		summarizeBy: none
		sourceColumn: CalendarQuarterNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthNameShort
		dataType: string
		lineageTag: 011d47fc-54e8-4253-99a0-254dd30cdfdc
		sourceLineageTag: MonthNameShort
		summarizeBy: none
		sourceColumn: MonthNameShort

		annotation SummarizationSetBy = Automatic

	column WeekdayNameLong
		dataType: string
		isHidden
		lineageTag: 1c866d12-5e6b-4984-bdbb-2dc09872b455
		sourceLineageTag: WeekdayNameLong
		summarizeBy: none
		sourceColumn: WeekdayNameLong

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Invoice Date'
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 71bf8fd6-9013-4af1-b8e5-842599646f5b
		sourceLineageTag: Date
		summarizeBy: none
		sourceColumn: Date

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column FiscalDayNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8b27570e-1076-4984-8fff-93674b8b3817
		sourceLineageTag: FiscalDayNum
		summarizeBy: none
		sourceColumn: FiscalDayNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayUs
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3a329b9d-cd46-4f82-a702-35868be4b7ce
		sourceLineageTag: IsWorkingDayUs
		summarizeBy: none
		sourceColumn: IsWorkingDayUs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayBvba
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6169f310-f970-45dc-8996-0fc333761ac7
		sourceLineageTag: IsWorkingDayBvba
		summarizeBy: none
		sourceColumn: IsWorkingDayBvba

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayTeda
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 61549979-7060-48ba-9e1a-383f51a17b89
		sourceLineageTag: IsWorkingDayTeda
		summarizeBy: none
		sourceColumn: IsWorkingDayTeda

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekStartDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 71c9421d-ca79-41dc-9010-9003a6af9fca
		sourceLineageTag: WeekStartDate
		summarizeBy: none
		sourceColumn: WeekStartDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 08dc2688-05d4-490b-8288-c998e29a5c39
		sourceLineageTag: MonthStartDate
		summarizeBy: none
		sourceColumn: MonthStartDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentFiscalDayNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f60b0a64-d69b-49ce-b12d-e87cfb69f55e
		sourceLineageTag: CurrentFiscalDayNum
		summarizeBy: none
		sourceColumn: CurrentFiscalDayNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentFiscalYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ae43d79c-962a-4e09-86f6-bd2b414a6e9f
		sourceLineageTag: CurrentFiscalYear
		summarizeBy: none
		sourceColumn: CurrentFiscalYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthNameLong
		dataType: string
		lineageTag: 7ce4fc51-8b09-450c-a3fa-ee1a78d2ee56
		sourceLineageTag: MonthNameLong
		summarizeBy: none
		sourceColumn: MonthNameLong

		annotation SummarizationSetBy = Automatic

	column YearMonthNum
		dataType: string
		isHidden
		lineageTag: 07603bb6-d0af-48ec-9392-b1e1089d48f3
		sourceLineageTag: YearMonthNum
		summarizeBy: none
		sourceColumn: YearMonthNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearMonthLabel
		dataType: string
		isHidden
		lineageTag: 2d50d885-e2f6-45ca-aa1d-af9640496f11
		sourceLineageTag: YearMonthLabel
		summarizeBy: none
		sourceColumn: YearMonthLabel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterLabel
		dataType: string
		isHidden
		lineageTag: fb9e493a-530b-4852-a132-e2754a248271
		sourceLineageTag: CalendarQuarterLabel
		summarizeBy: none
		sourceColumn: CalendarQuarterLabel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CalendarYearQuarterNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 68fae5c3-a6ce-4a5a-b252-05770caba6f0
		sourceLineageTag: CalendarYearQuarterNum
		summarizeBy: none
		sourceColumn: CalendarYearQuarterNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterLabel
		dataType: string
		lineageTag: 5926b946-a647-48a1-b694-3c4e4e16d33d
		sourceLineageTag: FiscalQuarterLabel
		summarizeBy: none
		sourceColumn: FiscalQuarterLabel
		sortByColumn: FiscalQuarterNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FiscalYearQuarterNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d4416cf4-2e8f-4b5e-a9d4-7d50b9a1d153
		sourceLineageTag: FiscalYearQuarterNum
		summarizeBy: none
		sourceColumn: FiscalYearQuarterNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekdayNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 936b10ee-0ac6-4019-ab8a-52f8e472dbd2
		sourceLineageTag: WeekdayNum
		summarizeBy: none
		sourceColumn: WeekdayNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekdayNameShort
		dataType: string
		isHidden
		lineageTag: 751ed66c-f95d-4879-a349-e696c32ea2ad
		sourceLineageTag: WeekdayNameShort
		summarizeBy: none
		sourceColumn: WeekdayNameShort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearWeekNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7f7f8422-bc5b-4412-a775-3cc0d1625767
		sourceLineageTag: YearWeekNum
		summarizeBy: none
		sourceColumn: YearWeekNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalYearWeekNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4689e401-6194-42df-bfbf-cb503452f01a
		sourceLineageTag: FiscalYearWeekNum
		summarizeBy: none
		sourceColumn: FiscalYearWeekNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayOfYearNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 39dc0ed5-7d87-49a6-b996-6f7b3379b4b3
		sourceLineageTag: DayOfYearNum
		summarizeBy: none
		sourceColumn: DayOfYearNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e0391d60-5177-47c7-8d82-835fb4dbe099
		sourceLineageTag: IsWeekend
		summarizeBy: none
		sourceColumn: IsWeekend

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsToday
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ff2b2736-208f-4262-9117-daf3dcb08c76
		sourceLineageTag: IsToday
		summarizeBy: none
		sourceColumn: IsToday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsCurrentMonth
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a84cb7fb-b694-4d29-a00a-ee9e3d8cedfd
		sourceLineageTag: IsCurrentMonth
		summarizeBy: none
		sourceColumn: IsCurrentMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsCurrentFiscalYear
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 023bb59a-ca43-40bb-a454-d034437c8483
		sourceLineageTag: IsCurrentFiscalYear
		summarizeBy: none
		sourceColumn: IsCurrentFiscalYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalPeriodLabel
		dataType: string
		isHidden
		lineageTag: 7efceeb3-a05d-4cf8-8d3b-228913e0b78b
		sourceLineageTag: FiscalPeriodLabel
		summarizeBy: none
		sourceColumn: FiscalPeriodLabel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Original FISCAL YR'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bf6ea3f6-7423-49c3-9aa3-ceae1d55f214
		sourceLineageTag: Original FISCAL YR
		summarizeBy: none
		sourceColumn: Original FISCAL YR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Original FISCAL PERIOD'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0f7b0a8f-a9b0-483b-b0b3-0130c2732c73
		sourceLineageTag: Original FISCAL PERIOD
		summarizeBy: none
		sourceColumn: Original FISCAL PERIOD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Reconciliation Year'
		dataType: string
		isHidden
		lineageTag: 1b54d955-6b22-4378-b8b6-16022ad0dbe9
		sourceLineageTag: Reconciliation Year
		summarizeBy: none
		sourceColumn: Reconciliation Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Period'
		dataType: int64
		formatString: 0
		lineageTag: d49bcae3-253c-4a77-9536-01226d9c666a
		sourceLineageTag: FiscalPeriodNum
		summarizeBy: none
		sourceColumn: FiscalPeriodNum

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column FiscalWeekNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 33304b99-6cf6-48d2-98ff-71df7c07fa5c
		sourceLineageTag: FiscalWeekNum
		summarizeBy: none
		sourceColumn: FiscalWeekNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeeksInPeriod
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ce6589db-d2e8-4ba8-beb7-c760e20c72fd
		sourceLineageTag: WeeksInPeriod
		summarizeBy: none
		sourceColumn: WeeksInPeriod

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekOfYearNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 71971653-92a3-4499-8e62-8a5cb6bd1444
		sourceLineageTag: WeekOfYearNum
		summarizeBy: none
		sourceColumn: WeekOfYearNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayOfMonthNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5085f774-0525-40c3-b02c-a8af61da147e
		sourceLineageTag: DayOfMonthNum
		summarizeBy: none
		sourceColumn: DayOfMonthNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthNum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9b789d30-ddce-41f6-a1b5-fc0b79eb66fe
		sourceLineageTag: MonthNum
		summarizeBy: none
		sourceColumn: MonthNum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekStartDateSunday
		dataType: dateTime
		formatString: General Date
		lineageTag: 3bb62f4b-c8a2-478b-8bfc-bdad49eda7fe
		sourceLineageTag: WeekStartDateSunday
		summarizeBy: none
		sourceColumn: WeekStartDateSunday

		annotation SummarizationSetBy = Automatic

	partition 'Date Table' = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_Date
			schemaName: dbo
			expressionSource: 'DirectLake - WH_Curated'

	changedProperty = Name

