table Dim_StandardCost
	isHidden
	lineageTag: 86bade1c-c71b-4cf4-9746-95a4b0ee7ba6
	sourceLineageTag: [dbo].[mtbl_EDW_DIM_StandardCost]

	measure TotalOverheadStandardCost = ```
			
			    // Overhead Cost
			    SUM(Dim_StandardCost[Overhead_Depreciation_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Indirect_Supervisor_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Maintenance_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Manufacturing_Admin_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Miscellaneous_Manufacturing_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Quality_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Warehouse_Cost_Standard])
			
			```
		isHidden
		lineageTag: 80342f31-972b-49a5-8b78-1b1ef939d53b

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalDirectStandardCost = ```
			
			    // Direct Cost
			    SUM(Dim_StandardCost[Direct_Labor_Cost_Standard])
			  + SUM(Dim_StandardCost[Direct_Material_Cost_Standard])
			  + SUM(Dim_StandardCost[Direct_Utility_Cost_Standard])
			    // Outside Processing Cost
			  + SUM(Dim_StandardCost[Outside_Processing_Cost_Standard])
			    // Packaging Cost
			  + SUM(Dim_StandardCost[Packaging_Cost_Standard])
			
			```
		isHidden
		lineageTag: b550bf80-a79b-4852-97ff-958e0b98469a

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StandardCostKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 701d2b70-25b7-4abc-8f99-a37e5a35f37c
		sourceLineageTag: StandardCostKey
		summarizeBy: none
		sourceColumn: StandardCostKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CMPNY
		dataType: string
		isHidden
		lineageTag: 09a89d69-6c5a-48d9-bea4-18dfc5fe366f
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		isHidden
		lineageTag: f6d565a8-4c9e-42aa-aabf-2e6661f50783
		sourceLineageTag: Product_ID
		summarizeBy: none
		sourceColumn: Product_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SiteID
		dataType: string
		isHidden
		lineageTag: 28e9fef3-70ad-4365-a63c-701948c23863
		sourceLineageTag: SiteID
		summarizeBy: none
		sourceColumn: SiteID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Costing_Version
		dataType: string
		isHidden
		lineageTag: 6a5fcc2d-bd92-4e84-a0f8-bf9033c7fcdb
		sourceLineageTag: Costing_Version
		summarizeBy: none
		sourceColumn: Costing_Version

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentActiveCost
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1e386867-4ddf-448a-9933-97621aafb1fa
		sourceLineageTag: CurrentActiveCost
		summarizeBy: none
		sourceColumn: CurrentActiveCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Direct_Material_Cost_Standard
		dataType: double
		isHidden
		lineageTag: 91b3eedf-7c4b-4bed-88cc-6d3b8cd254b3
		sourceLineageTag: Direct_Material_Cost_Standard
		summarizeBy: none
		sourceColumn: Direct_Material_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Packaging_Cost_Standard
		dataType: double
		isHidden
		lineageTag: 983ed710-7327-4d1e-9c62-57b04cba4360
		sourceLineageTag: Packaging_Cost_Standard
		summarizeBy: none
		sourceColumn: Packaging_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direct_Labor_Cost_Standard
		dataType: double
		isHidden
		lineageTag: 68e7a284-244a-4748-8a82-63b1b365305a
		sourceLineageTag: Direct_Labor_Cost_Standard
		summarizeBy: none
		sourceColumn: Direct_Labor_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direct_Utility_Cost_Standard
		dataType: double
		isHidden
		lineageTag: c8763b96-48a1-4211-b4f9-0dc142d21dd1
		sourceLineageTag: Direct_Utility_Cost_Standard
		summarizeBy: none
		sourceColumn: Direct_Utility_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Warehouse_Cost_Standard
		dataType: double
		isHidden
		lineageTag: 6b511a10-d79f-47ab-b5d9-c94ecd1938bc
		sourceLineageTag: Overhead_Warehouse_Cost_Standard
		summarizeBy: none
		sourceColumn: Overhead_Warehouse_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Indirect_Supervisor_Cost_Standard
		dataType: double
		isHidden
		lineageTag: 970242c7-7185-42a4-afe1-3ab9a5a9f17e
		sourceLineageTag: Overhead_Indirect_Supervisor_Cost_Standard
		summarizeBy: none
		sourceColumn: Overhead_Indirect_Supervisor_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Quality_Cost_Standard
		dataType: double
		isHidden
		lineageTag: 8c215128-319b-4e39-9cf2-9deaba3f179f
		sourceLineageTag: Overhead_Quality_Cost_Standard
		summarizeBy: none
		sourceColumn: Overhead_Quality_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Maintenance_Cost_Standard
		dataType: double
		isHidden
		lineageTag: e2fcc78e-8fb5-4799-9877-faff09775ae7
		sourceLineageTag: Overhead_Maintenance_Cost_Standard
		summarizeBy: none
		sourceColumn: Overhead_Maintenance_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Manufacturing_Admin_Cost_Standard
		dataType: double
		isHidden
		lineageTag: cc910734-4ac3-4391-abb2-6d72884bc892
		sourceLineageTag: Overhead_Manufacturing_Admin_Cost_Standard
		summarizeBy: none
		sourceColumn: Overhead_Manufacturing_Admin_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Depreciation_Cost_Standard
		dataType: double
		isHidden
		lineageTag: 0bd7849a-5785-40bd-95c0-ea0bfd06531d
		sourceLineageTag: Overhead_Depreciation_Cost_Standard
		summarizeBy: none
		sourceColumn: Overhead_Depreciation_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Miscellaneous_Manufacturing_Cost_Standard
		dataType: double
		isHidden
		lineageTag: a465d216-02d3-45bf-b866-3dc712a6d5b6
		sourceLineageTag: Overhead_Miscellaneous_Manufacturing_Cost_Standard
		summarizeBy: none
		sourceColumn: Overhead_Miscellaneous_Manufacturing_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalCost
		dataType: double
		isHidden
		lineageTag: 110c8e71-56ae-49af-915d-6dadd9c9a1e7
		sourceLineageTag: TotalCost
		summarizeBy: none
		sourceColumn: TotalCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column accountingcurrency
		dataType: string
		isHidden
		lineageTag: ad72f689-d9f3-4f8e-842a-d12b44ae3ab3
		sourceLineageTag: accountingcurrency
		summarizeBy: none
		sourceColumn: accountingcurrency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveStartDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 09ef331f-3cd5-4bf9-8009-da8f91e3d732
		sourceLineageTag: RecordEffectiveStartDate
		summarizeBy: none
		sourceColumn: RecordEffectiveStartDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveEndDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 945bf4c9-f201-4d03-be89-e18d82df7ef2
		sourceLineageTag: RecordEffectiveEndDate
		summarizeBy: none
		sourceColumn: RecordEffectiveEndDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecordStatus
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a6f55e1e-f317-42b5-a1bf-db7bb3b15a44
		sourceLineageTag: RecordStatus
		summarizeBy: none
		sourceColumn: RecordStatus

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		isHidden
		lineageTag: 8a7638e0-4b66-49ff-b34d-5d64e3674284
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Total_Overhead_Cost_Standard
		dataType: double
		isHidden
		lineageTag: 5eff8b81-415e-4604-9c41-5dfef33db1d3
		sourceLineageTag: Total_Overhead_Cost_Standard
		summarizeBy: none
		sourceColumn: Total_Overhead_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Direct_Cost_Standard
		dataType: double
		isHidden
		lineageTag: ff803496-58fc-4eb5-8aa0-031421b77891
		sourceLineageTag: Total_Direct_Cost_Standard
		summarizeBy: none
		sourceColumn: Total_Direct_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Outside_Processing_Cost_Standard
		dataType: double
		isHidden
		lineageTag: c5ccd7e5-0ae6-41ed-8d3b-97e801a4a92e
		sourceLineageTag: Outside_Processing_Cost_Standard
		summarizeBy: none
		sourceColumn: Outside_Processing_Cost_Standard

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LegacyProductCode
		dataType: string
		isHidden
		lineageTag: e2abac6e-f421-41c1-97ef-fa5a1d9fa819
		sourceLineageTag: LegacyProductCode
		summarizeBy: none
		sourceColumn: LegacyProductCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ActivationDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 99e2c2af-4ec9-4a9f-9d95-302690a03bba
		sourceLineageTag: ActivationDate
		summarizeBy: none
		sourceColumn: ActivationDate

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 25a751f7-63dd-47bf-8ae1-5425bc6d9730
		sourceLineageTag: EndDate
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

	partition Dim_StandardCost = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_StandardCost
			schemaName: dbo
			expressionSource: 'DirectLake - WH_Curated'

	changedProperty = Name

	changedProperty = IsHidden

