table 'Sales Table'
	lineageTag: 202cee69-41bd-4a96-b75e-00b145449da0
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_Sales]

	measure Revenue =
			
			SUM ( 'Sales Table'[Amount] )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4665352d-50ec-4633-9ea9-502f0b0997d3

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Qty LBS' =
			
			SUM ( 'Sales Table'[Quantity_LBs] )
		lineageTag: ad229135-053b-4cf5-9ea2-6fdc373d31f9

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Direct Std Cost Dollar' =
			
			SUMX (
			    'Sales Table',
			    VAR _qty = 'Sales Table'[Quantity_LBs]
			    VAR _directStd =
			        COALESCE ( RELATED ( Dim_StandardCost[Total_Direct_Cost_Standard] ), 0 )
			    VAR _packagingStd =
			        COALESCE ( RELATED ( Dim_StandardCost[Packaging_Cost_Standard] ), 0 )
			    RETURN
			        _qty * ( _directStd + _packagingStd )
			)
		isHidden
		lineageTag: bed06d5f-b8bc-47fb-a9fa-66dd8cd657ad

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Overhead Std Cost Dollar' =
			
			SUMX (
			    'Sales Table',
			    VAR _qty = 'Sales Table'[Quantity_LBs]
			    VAR _overheadStd =
			        COALESCE ( RELATED ( Dim_StandardCost[Total_Overhead_Cost_Standard] ), 0 )
			    RETURN
			        _qty * _overheadStd
			)
		isHidden
		lineageTag: 0affeab2-23cd-45cd-83be-ae4235b0db8c

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Std Cost Dollar' =
			
			SUMX (
			    'Sales Table',
			    VAR _qty = 'Sales Table'[Quantity_LBs]
			    VAR _totalStd =
			        COALESCE ( RELATED ( Dim_StandardCost[TotalCost] ), 0 )
			    RETURN
			        _qty * _totalStd
			)
		isHidden
		lineageTag: f8cdaf13-f476-4630-8f88-6fa39dd72a2f

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASP =
			
			DIVIDE ( [Revenue], [Qty LBS] )
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		isHidden
		lineageTag: 2bafd780-5709-406c-9c5f-04613950e39d

		changedProperty = Name

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CM Dollar' =
			
			[Revenue] - [Direct Std Cost Dollar]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		isHidden
		lineageTag: 7c5366da-6ae4-424a-b10b-78fd329dd238

		changedProperty = Name

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CM Percent' =
			
			DIVIDE ( [CM Dollar], [Revenue] )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		isHidden
		lineageTag: 22c1c600-4539-4eb4-80a7-f12694454ad8

		changedProperty = Name

		changedProperty = IsHidden

		changedProperty = FormatString

	measure 'SGM Dollar' =
			
			[Revenue] - [Total Std Cost Dollar]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		isHidden
		lineageTag: 77a16fd9-d93f-47f7-a5bd-51a4713f9f1e

		changedProperty = Name

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'SGM Percent' =
			
			DIVIDE ( [SGM Dollar], [Revenue] )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		isHidden
		lineageTag: ec6650fe-b8b9-4a5e-b400-e46ca6741c47

		changedProperty = Name

		changedProperty = IsHidden

		changedProperty = FormatString

	measure 'VC per LB Base' =
			
			DIVIDE ( [Direct Std Cost Dollar], [Qty LBS] )
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		isHidden
		lineageTag: 4ceeb422-c2a6-4560-bba1-8373fe901f38

		changedProperty = Name

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'VC per LB Display' =
			
			- [VC per LB Base]
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		isHidden
		lineageTag: 7167626a-0918-42bc-b0b3-ef51a6a3c4d1

		changedProperty = Name

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Vol LBS PY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Prior Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [Qty LBS],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: 0
		lineageTag: d60e88d0-f895-4f57-a5e6-efb58c581654

		changedProperty = Name

		changedProperty = FormatString

	measure 'Vol LBS CY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Selected Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [Qty LBS],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: 0
		lineageTag: 34301670-780d-438f-bcb3-ce9ab914cfa9

		changedProperty = Name

		changedProperty = FormatString

	measure 'Vol Delta' =
			
			VAR _cy = [Vol LBS CY]
			VAR _py = [Vol LBS PY]
			RETURN
			    _cy - _py
		lineageTag: fc13d4f5-b550-48e9-ab9b-785653dbf9ca

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vol Percent Delta' =
			
			VAR _py = [Vol LBS PY]
			VAR _delta = [Vol Delta]
			VAR _result = DIVIDE ( _delta, _py )
			RETURN
			    IF (
			        OR ( ISBLANK ( _result ), _result = 0 ),
			        BLANK (),
			        _result
			    )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 8938ad64-42df-4c83-beb1-42d7b4ef91b6

		changedProperty = Name

		changedProperty = FormatString

	measure 'Rev PY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Prior Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [Revenue],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2751d4e7-ea15-46ba-88ec-9df0f42abafc

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Rev CY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Selected Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [Revenue],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 492d6609-72d8-470a-9676-9a533a5052c3

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Rev Dollar Delta' =
			
			VAR _cy = [Rev CY]
			VAR _py = [Rev PY]
			RETURN
			    IF ( OR ( ISBLANK ( _cy ), ISBLANK ( _py ) ), BLANK(), _cy - _py )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4bc879f6-109c-41eb-a8c0-746e377177f3

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Rev Percent Delta' =
			
			VAR _cy = [Rev CY]
			VAR _py = [Rev PY]
			VAR _result = DIVIDE ( _cy - _py, _py )
			RETURN
			    IF ( OR ( ISBLANK ( _result ), _result = 0 ), BLANK(), _result )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: b6e70fc6-6ed9-457b-a0a3-77914b1f5c40

		changedProperty = Name

		changedProperty = FormatString

	measure 'ASP PY' =
			
			VAR _rev = [Rev PY]
			VAR _vol = [Vol LBS PY]
			RETURN
			    DIVIDE ( _rev, _vol )
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		lineageTag: 40185d3c-add8-44de-814f-ae99d98c907b

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'ASP CY' =
			
			VAR _rev = [Rev CY]
			VAR _vol = [Vol LBS CY]
			RETURN
			    DIVIDE ( _rev, _vol )
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		lineageTag: 0557bce3-9e3d-4ff0-8ca7-89f40960c65b

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'ASP Dollar Delta' =
			
			VAR _cy = [ASP CY]
			VAR _py = [ASP PY]
			RETURN
			    IF ( OR ( ISBLANK ( _cy ), ISBLANK ( _py ) ), BLANK(), _cy - _py )
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		lineageTag: 4aec9489-85b9-4c19-8324-f626d58b092b

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'ASP Percent Delta' =
			
			VAR _cy = [ASP CY]
			VAR _py = [ASP PY]
			VAR _result = DIVIDE ( _cy - _py, _py )
			RETURN
			    IF ( OR ( ISBLANK ( _result ), _result = 0 ), BLANK(), _result )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 0923c96f-31b6-4caa-8ecc-6a39f33ea00d

		changedProperty = Name

		changedProperty = FormatString

	measure 'CM PY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Prior Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [CM Dollar],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8aa513fd-3867-4fba-a2ef-4880f5e3389e

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CM CY' = ```
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Selected Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [CM Dollar],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 839b00f0-6e48-431c-8539-963c86dd607d

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CM Dollar Delta' =
			
			VAR _cy = [CM CY]
			VAR _py = [CM PY]
			RETURN
			    IF ( OR ( ISBLANK ( _cy ), ISBLANK ( _py ) ), BLANK(), _cy - _py )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a1217754-8472-4415-88c8-a62bd8243ed9

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CM Percent PY' =
			
			VAR _cm = [CM PY]
			VAR _rev = [Rev PY]
			RETURN
			    DIVIDE ( _cm, _rev )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 709be94b-ec7f-420c-869c-74c83df35933

		changedProperty = Name

		changedProperty = FormatString

	measure 'CM Percent CY' =
			
			VAR _cm = [CM CY]
			VAR _rev = [Rev CY]
			RETURN
			    DIVIDE ( _cm, _rev )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 976a3f98-cebc-4882-88d6-7d73d7790f72

		changedProperty = Name

		changedProperty = FormatString

	measure 'CM Percent Delta' =
			
			VAR _cy = [CM Percent CY]
			VAR _py = [CM Percent PY]
			RETURN
			    _cy - _py
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 07fc82cc-18f3-4a9a-8a6f-27fbf923f4a9

		changedProperty = Name

		changedProperty = FormatString

	measure 'CM YoY Percent' =
			
			VAR _cy = [CM CY]
			VAR _py = [CM PY]
			VAR _result = DIVIDE ( _cy - _py, _py )
			RETURN
			    IF ( OR ( ISBLANK ( _result ), _result = 0 ), BLANK(), _result )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: f49b659e-592f-439b-bad7-b1c203e0946d

		changedProperty = Name

		changedProperty = FormatString

	measure 'SGM PY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Prior Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [SGM Dollar],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 82a72ec6-f66a-4a86-ba72-5581effcfe53

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'SGM CY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Selected Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [SGM Dollar],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 33835cb4-1dd5-40fe-a56e-5a989e4d047f

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'SGM Dollar Delta' =
			
			VAR _cy = [SGM CY]
			VAR _py = [SGM PY]
			RETURN
			    _cy - _py
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ef44b6d6-1aba-4c16-8e79-ee48c0840501

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'SGM Percent PY' =
			
			VAR _sgm = [SGM PY]
			VAR _rev = [Rev PY]
			RETURN
			    DIVIDE ( _sgm, _rev )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 71ef324a-a756-427a-b42b-57d7dca94430

		changedProperty = Name

		changedProperty = FormatString

	measure 'SGM Percent CY' =
			
			VAR _sgm = [SGM CY]
			VAR _rev = [Rev CY]
			RETURN
			    DIVIDE ( _sgm, _rev )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: b8f99a6d-17b8-4639-9f15-2a3c95204a51

		changedProperty = Name

		changedProperty = FormatString

	measure 'Std VC Dollar PY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Prior Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [Direct Std Cost Dollar],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 1a264f4e-ebfc-42d1-a93b-586e8e5ca489

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Std VC Dollar CY' =
			
			VAR _valid = [Valid YoY Selection]
			VAR _fy = [Selected Fiscal Year]
			VAR _fp = [Selected Fiscal Period]
			RETURN
			    IF (
			        _valid <> 1,
			        BLANK(),
			        CALCULATE (
			            [Direct Std Cost Dollar],
			            REMOVEFILTERS ( 'Date Table'[Fiscal Year], 'Date Table'[Fiscal Period] ),
			            'Date Table'[Fiscal Year] = _fy,
			            'Date Table'[Fiscal Period] <= _fp
			        )
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 07096d5f-6939-4ceb-b5ee-24f9954d8504

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'VC per LB PY' =
			
			VAR _cost = [Std VC Dollar PY]
			VAR _vol = [Vol LBS PY]
			RETURN
			    - DIVIDE ( _cost, _vol )
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		lineageTag: ddbf38a0-c653-42c2-9d62-3c95325b7aaa

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'VC per LB CY' =
			
			VAR _cost = [Std VC Dollar CY]
			VAR _vol = [Vol LBS CY]
			RETURN
			    - DIVIDE ( _cost, _vol )
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		lineageTag: cbb076e2-dec6-4aef-8cea-fc227b6b0f3e

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'VC Delta' =
			
			VAR _py = [VC per LB PY]
			VAR _cy = [VC per LB CY]
			RETURN
			    _py - _cy
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 46158637-f1df-49df-b6d2-28c1e2d06a4d

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sales Price Per LB' = Divide([Revenue] , [Qty LBS])
		isHidden
		lineageTag: 5ef31449-6e34-49db-8088-c07de71811f1

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XL_Revenue =
			
			SUM ( 'Sales Table'[Amount] )
		lineageTag: 4af35266-0411-4b10-b824-8d5aeb4a215e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XL_Qty_LBS =
			
			SUM ( 'Sales Table'[Quantity_LBs] )
		lineageTag: a9008f2a-8e8a-4c3f-a31f-a99d4579dfb0

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XL_Direct_Std_Cost_Dollar =
			
			[Direct Std Cost Dollar]
		lineageTag: 6daf16dd-65c4-4f9c-944c-b776bfd12616

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XL_Overhead_Std_Cost_Dollar =
			
			[Overhead Std Cost Dollar]
		lineageTag: 6a68c447-e6f2-4e9f-b384-1b0a3a42aee8

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure XL_Total_Std_Cost_Dollar =
			
			[Total Std Cost Dollar]
		lineageTag: 070aab16-53f8-47a1-b861-586b9b0f1c7a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RecordID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 70245b3d-832c-463e-a981-2f33fb82a0ac
		sourceLineageTag: RecordID
		summarizeBy: count
		sourceColumn: RecordID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CMPNY
		dataType: string
		isHidden
		lineageTag: 1176d6a9-313c-41e1-a625-d9028a18d5d6
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Status'
		dataType: string
		lineageTag: 14f925d7-ee0c-43df-ac28-a37b662f6138
		sourceLineageTag: SalesLine_Status
		summarizeBy: none
		sourceColumn: SalesLine_Status

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column DATE
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 4959733b-0291-4fb5-8f60-0392beef4b87
		sourceLineageTag: DATE
		summarizeBy: none
		sourceColumn: DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DATEKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 86fa8a4b-bee0-4c18-a6e5-7fd7c2f4b971
		sourceLineageTag: DATEKey
		summarizeBy: count
		sourceColumn: DATEKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 0f5bde17-e920-427c-bcd1-0021ddfb6c12
		sourceLineageTag: OrderDate
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee1203ff-3334-4a31-9590-ccfba099ad0e
		sourceLineageTag: OrderDateKey
		summarizeBy: count
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_RequestedShipDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: a3016225-5cf8-48f1-91d9-00f2dc9e5a63
		sourceLineageTag: SalesLine_RequestedShipDate
		summarizeBy: none
		sourceColumn: SalesLine_RequestedShipDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_RequestedShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 47f883b3-2bde-4b45-81b8-09f8ca69c0c8
		sourceLineageTag: SalesLine_RequestedShipDateKey
		summarizeBy: count
		sourceColumn: SalesLine_RequestedShipDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_ShipDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 6f530b3f-45ca-4c15-befc-aa6da274b7c1
		sourceLineageTag: SalesLine_ShipDate
		summarizeBy: none
		sourceColumn: SalesLine_ShipDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_ShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7067945c-b9bd-4062-9280-80f91c33a20c
		sourceLineageTag: SalesLine_ShipDateKey
		summarizeBy: count
		sourceColumn: SalesLine_ShipDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_DeliveryDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 734bda51-26f0-47d5-954a-d8298daca7fe
		sourceLineageTag: SalesLine_DeliveryDate
		summarizeBy: none
		sourceColumn: SalesLine_DeliveryDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_DeliveryDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 00fc7812-43c2-482d-ab83-c43e727474bb
		sourceLineageTag: SalesLine_DeliveryDateKey
		summarizeBy: count
		sourceColumn: SalesLine_DeliveryDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InvoiceDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: cf19d57b-87ff-4ae5-8f0e-192ccac86484
		sourceLineageTag: InvoiceDate
		summarizeBy: none
		sourceColumn: InvoiceDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InvoiceDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 911192c9-1fc4-449b-be68-e5e0e52b00f2
		sourceLineageTag: InvoiceDateKey
		summarizeBy: none
		sourceColumn: InvoiceDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Legal_Entity_ID
		dataType: string
		isHidden
		lineageTag: 2d49a0fc-8809-4be2-8c47-3af732f003b2
		sourceLineageTag: Legal_Entity_ID
		summarizeBy: none
		sourceColumn: Legal_Entity_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: bb5ab536-2a44-4b93-82b8-f719d386985a
		sourceLineageTag: CustomerID
		summarizeBy: none
		sourceColumn: CustomerID

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column InvoiceAccount
		dataType: string
		isHidden
		lineageTag: ee773241-1e58-4686-bf05-3bf1c7c249bb
		sourceLineageTag: InvoiceAccount
		summarizeBy: none
		sourceColumn: InvoiceAccount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		isHidden
		lineageTag: 3f74fe34-a702-4b7c-929a-acf46fd9a317
		sourceLineageTag: ProductID
		summarizeBy: none
		sourceColumn: ProductID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CPCID
		dataType: string
		isHidden
		lineageTag: 9413d8a3-00c9-408e-8c7f-ac68d15290e5
		sourceLineageTag: CPCID
		summarizeBy: none
		sourceColumn: CPCID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InvoiceNo
		dataType: string
		isHidden
		lineageTag: ddd9ea29-6be1-4b0e-af12-c0e774ca16dd
		sourceLineageTag: InvoiceNo
		summarizeBy: none
		sourceColumn: InvoiceNo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Order ID'
		dataType: string
		lineageTag: 04b6f2b4-2e3d-4c23-93e3-a1d2751b9214
		sourceLineageTag: Customer_Order_Number
		summarizeBy: none
		sourceColumn: Customer_Order_Number

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		isHidden
		lineageTag: 0bd929da-398e-4728-9f07-49bd7e3fe01b
		sourceLineageTag: Quantity
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity_UoM
		dataType: string
		isHidden
		lineageTag: 474c8980-ad38-4a16-8ef1-043f975488b3
		sourceLineageTag: Quantity_UoM
		summarizeBy: none
		sourceColumn: Quantity_UoM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity_LBs
		dataType: double
		isHidden
		lineageTag: 7c4b45cf-6796-4968-88bc-d0f4c3ca2e11
		sourceLineageTag: Quantity_LBs
		summarizeBy: sum
		sourceColumn: Quantity_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: double
		isHidden
		lineageTag: 1c9db8d4-c8e6-449c-b3f0-2097b4217750
		sourceLineageTag: Volume
		summarizeBy: sum
		sourceColumn: Volume

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume_UoM
		dataType: string
		isHidden
		lineageTag: 85642bca-3200-4218-8a45-db92b5f4d5f6
		sourceLineageTag: Volume_UoM
		summarizeBy: none
		sourceColumn: Volume_UoM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		isHidden
		lineageTag: 1381bf94-97b7-4e4b-a067-2863cf694512
		sourceLineageTag: Price
		summarizeBy: sum
		sourceColumn: Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency
		dataType: string
		isHidden
		lineageTag: 4a9f5307-49bd-47a7-b041-dc41ab8b4c00
		sourceLineageTag: Currency
		summarizeBy: none
		sourceColumn: Currency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		isHidden
		lineageTag: 8a7d6fdf-201f-4ab2-9658-02b224070232
		sourceLineageTag: Amount
		summarizeBy: sum
		sourceColumn: Amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Amount_Currency
		dataType: string
		isHidden
		lineageTag: e7211ead-229a-4382-9d67-28351ba15e56
		sourceLineageTag: Amount_Currency
		summarizeBy: none
		sourceColumn: Amount_Currency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Returned_Quantity
		dataType: double
		isHidden
		lineageTag: 37428961-8700-4580-bb61-c78100fdca39
		sourceLineageTag: Returned_Quantity
		summarizeBy: sum
		sourceColumn: Returned_Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Returned_Amount
		dataType: double
		isHidden
		lineageTag: 7377b336-3dda-46af-bf59-c2e20cb71e97
		sourceLineageTag: Returned_Amount
		summarizeBy: sum
		sourceColumn: Returned_Amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesLine_Salesman_ID
		dataType: string
		isHidden
		lineageTag: bbd37673-c8f2-4a84-9f3a-90aebde12755
		sourceLineageTag: SalesLine_Salesman_ID
		summarizeBy: none
		sourceColumn: SalesLine_Salesman_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Customer_Salesman_ID
		dataType: string
		isHidden
		lineageTag: 815d8916-d76d-4b00-af05-a434c8a449cb
		sourceLineageTag: Customer_Salesman_ID
		summarizeBy: none
		sourceColumn: Customer_Salesman_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		isHidden
		lineageTag: 17f0e628-fb3e-4325-9d35-ea843b91a328
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HistoricCustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a1c07219-59f4-43d6-92e3-0a52b6a887c7
		sourceLineageTag: HistoricCustomerKey
		summarizeBy: count
		sourceColumn: HistoricCustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ba08298b-782f-4a02-a503-b4bbfd3a145b
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HistoricProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 218056d0-10d9-4a29-86af-744cd45a8b83
		sourceLineageTag: HistoricProductKey
		summarizeBy: count
		sourceColumn: HistoricProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4184d29b-bea8-4469-b34a-da584f03773d
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StandardCostKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 23f3c422-2062-42dd-9c06-6db848314c1f
		sourceLineageTag: StandardCostKey
		summarizeBy: none
		sourceColumn: StandardCostKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fc7191cf-d35f-4af8-90b7-64bb74616d8a
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SiteKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f87639a2-601a-4c0f-80ba-98f87d6fb425
		sourceLineageTag: SiteKey
		summarizeBy: count
		sourceColumn: SiteKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a86ca5cd-0803-4b86-afb9-100431a2d2df
		sourceLineageTag: SalesLine_EmployeeKey
		summarizeBy: count
		sourceColumn: SalesLine_EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustAcct_EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4dc394cc-f39d-497c-924d-af4101341859
		sourceLineageTag: CustAcct_EmployeeKey
		summarizeBy: none
		sourceColumn: CustAcct_EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesTaker_EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f80beced-85d5-4500-967d-7d78596e4f48
		sourceLineageTag: SalesTaker_EmployeeKey
		summarizeBy: count
		sourceColumn: SalesTaker_EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WarehouseKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5b22fcdf-5e59-4952-a590-9aa96b4f614c
		sourceLineageTag: WarehouseKey
		summarizeBy: none
		sourceColumn: WarehouseKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesOrderKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f8846234-a627-4905-9272-fbef11cb9a23
		sourceLineageTag: SalesOrderKey
		summarizeBy: none
		sourceColumn: SalesOrderKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OnHold
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 06111f1e-ee38-4e23-97cf-2f70de89a1f2
		sourceLineageTag: OnHold
		summarizeBy: sum
		sourceColumn: OnHold

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderOnHold
		dataType: string
		isHidden
		lineageTag: 9eed38e8-1b69-41d4-ac15-bd9a1695bc02
		sourceLineageTag: OrderOnHold
		summarizeBy: none
		sourceColumn: OrderOnHold

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HoldCode
		dataType: string
		isHidden
		lineageTag: 42ea917e-9651-4858-9d38-d9c20cc9d4ce
		sourceLineageTag: HoldCode
		summarizeBy: none
		sourceColumn: HoldCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HoldReasonCode
		dataType: string
		isHidden
		lineageTag: 0cae962a-6a86-4179-a1ae-c0368bded71e
		sourceLineageTag: HoldReasonCode
		summarizeBy: none
		sourceColumn: HoldReasonCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SO Line'
		dataType: double
		isHidden
		lineageTag: 7b065806-2c86-42c4-b77d-dfaa6aa35e23
		sourceLineageTag: SalesOrderLineNumber
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesLineCreatedDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 791febbe-1103-487d-8531-fd4dfa590d65
		sourceLineageTag: SalesLineCreatedDate
		summarizeBy: none
		sourceColumn: SalesLineCreatedDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLineCreatedDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 120b9094-16fb-4e73-9614-df415557589c
		sourceLineageTag: SalesLineCreatedDateKey
		summarizeBy: count
		sourceColumn: SalesLineCreatedDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MarketSegmentationKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 58fffaee-f3a7-452e-a6b7-57a1cd7c1daa
		sourceLineageTag: MarketSegmentationKey
		summarizeBy: none
		sourceColumn: MarketSegmentationKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PurchaseOrderFormNumber
		dataType: string
		isHidden
		lineageTag: 570df4f4-273c-4b7a-bd80-de552490bc6e
		sourceLineageTag: PurchaseOrderFormNumber
		summarizeBy: none
		sourceColumn: PurchaseOrderFormNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DeliveryAddressKey
		dataType: int64
		formatString: 0
		lineageTag: c875ffbd-e067-476c-99fd-108a29242c66
		sourceLineageTag: DeliveryAddressKey
		summarizeBy: count
		sourceColumn: DeliveryAddressKey

		annotation SummarizationSetBy = Automatic

	partition 'Sales Table' = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_Sales
			schemaName: dbo
			expressionSource: 'DirectLake - WH_Curated'

	changedProperty = Name

