table Dim_Date
	lineageTag: 8fcbf747-a811-4276-b9cf-c4463e7568b7
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_Date]
	dataCategory: Time

	measure InvoiceDate = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[InvoiceDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 4aef1cda-0675-46ce-914e-f2a006a4eb5f

		changedProperty = Name

	measure 'SalesLine Created Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLineCreatedDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 6deb54bb-f17f-4b4e-b819-ad60187a4e3b

		changedProperty = Name

	measure 'Finished Good Throughput Title' =
			
			VAR SelectedGrainTable =
			    SELECTCOLUMNS (
			        SUMMARIZE (
			            'Date Grain',
			            'Date Grain'[Date Grain],
			            'Date Grain'[Date Grain Fields]
			        ),
			        "Grain", 'Date Grain'[Date Grain]
			    )
			VAR Grain =
			    IF (
			        COUNTROWS ( SelectedGrainTable ) = 1,
			        MAXX ( SelectedGrainTable, [Grain] ),
			        "Date"
			    )
			RETURN
			    "Finished Good Throughput by " & Grain
		lineageTag: 593c06df-c2a9-4826-89a5-b0a55550cae2

		changedProperty = Name

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 54a8c3ce-fa90-4221-8ca1-2983f299652f
		sourceLineageTag: DateKey
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecId
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4066121c-f114-4de7-803c-0986f51d6f7c
		sourceLineageTag: RecId
		summarizeBy: none
		sourceColumn: RecId

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: df5ab4e4-659c-4fea-a976-9a134341e589
		sourceLineageTag: FiscalQuarterNum
		summarizeBy: none
		sourceColumn: FiscalQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: a9160bbd-2d67-4d1d-b138-e6013fb61eca
		sourceLineageTag: FiscalYear
		summarizeBy: none
		sourceColumn: FiscalYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalPeriodNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2940af5a-d6c1-4295-a262-da0ac1e44c10
		sourceLineageTag: FiscalPeriodNum
		summarizeBy: none
		sourceColumn: FiscalPeriodNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1f822fff-fb33-417c-b1a6-2b591a09126a
		sourceLineageTag: FiscalWeekNum
		summarizeBy: none
		sourceColumn: FiscalWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CalendarYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 263683d5-648e-4ad2-9291-d212ef1a93ef
		sourceLineageTag: CalendarYear
		summarizeBy: none
		sourceColumn: CalendarYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CalendarQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 8a190568-2bb8-48bc-8e07-5de9c53838dc
		sourceLineageTag: CalendarQuarterNum
		summarizeBy: none
		sourceColumn: CalendarQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column MonthNameShort
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 75afa553-b127-46fe-9f10-9a41d0600ef2
		sourceLineageTag: MonthNameShort
		summarizeBy: none
		sourceColumn: MonthNameShort
		sortByColumn: YearMonthNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WeekdayNameLong
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: 69f132ef-8a4d-448c-bc1d-ab8695e7e4db
		sourceLineageTag: WeekdayNameLong
		summarizeBy: none
		sourceColumn: WeekdayNameLong

		annotation SummarizationSetBy = Automatic

	column WeekOfYearNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 98557ae8-687b-45ff-90cb-d544ac555632
		sourceLineageTag: WeekOfYearNum
		summarizeBy: none
		sourceColumn: WeekOfYearNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column Date
		dataType: dateTime
		isKey
		formatString: mm/dd/yy
		sourceProviderType: date
		lineageTag: 9a2620a3-5161-4cbb-9c39-c2e7d8b32242
		sourceLineageTag: Date
		summarizeBy: none
		sourceColumn: Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column DayOfMonthNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 6e08df99-8226-4557-8c1d-07cb82644aba
		sourceLineageTag: DayOfMonthNum
		summarizeBy: none
		sourceColumn: DayOfMonthNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalDayNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 12890bcc-a326-4813-8304-52c7d525945b
		sourceLineageTag: FiscalDayNum
		summarizeBy: none
		sourceColumn: FiscalDayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsWorkingDayUs
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 167572bf-21cf-4400-8aba-af52a5bef287
		sourceLineageTag: IsWorkingDayUs
		summarizeBy: none
		sourceColumn: IsWorkingDayUs

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayBvba
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: abaf4e89-5122-4547-a50c-52abac2270f3
		sourceLineageTag: IsWorkingDayBvba
		summarizeBy: none
		sourceColumn: IsWorkingDayBvba

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayTeda
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: d5e9d71f-da56-41dc-b9c5-9724d145d64e
		sourceLineageTag: IsWorkingDayTeda
		summarizeBy: none
		sourceColumn: IsWorkingDayTeda

		annotation SummarizationSetBy = Automatic

	column WeekStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 2ea7c352-3aab-4941-ae09-532a583cf257
		sourceLineageTag: WeekStartDate
		summarizeBy: none
		sourceColumn: WeekStartDate

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: bfd8e636-3b67-46fc-bf15-b338b19354ed
		sourceLineageTag: MonthStartDate
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

	column CurrentFiscalDayNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 3bb57d93-aa29-46cf-b2e7-e372e894c9ef
		sourceLineageTag: CurrentFiscalDayNum
		summarizeBy: none
		sourceColumn: CurrentFiscalDayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CurrentFiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 2b04bad6-cf8c-4252-9ef7-29748d523c65
		sourceLineageTag: CurrentFiscalYear
		summarizeBy: none
		sourceColumn: CurrentFiscalYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column MonthNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ec71211f-5d41-49bc-afb9-a4b2e0837d36
		sourceLineageTag: MonthNum
		summarizeBy: none
		sourceColumn: MonthNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column MonthNameLong
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: d14b0ce4-38dc-4376-84d8-8c5333283e82
		sourceLineageTag: MonthNameLong
		summarizeBy: none
		sourceColumn: MonthNameLong

		annotation SummarizationSetBy = Automatic

	column YearMonthNum
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: d9c52431-7ab2-44ca-9a0f-ff2ad6747c9f
		sourceLineageTag: YearMonthNum
		summarizeBy: none
		sourceColumn: YearMonthNum

		annotation SummarizationSetBy = Automatic

	column YearMonthLabel
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: 5688a480-1d60-4618-9afa-4ade78872ed5
		sourceLineageTag: YearMonthLabel
		summarizeBy: none
		sourceColumn: YearMonthLabel

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterLabel
		dataType: string
		sourceProviderType: varchar(2)
		lineageTag: 41934234-7402-46da-9c87-c0a7e45f76ef
		sourceLineageTag: CalendarQuarterLabel
		summarizeBy: none
		sourceColumn: CalendarQuarterLabel

		annotation SummarizationSetBy = Automatic

	column CalendarYearQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d0492984-3859-4338-95e4-6c3a6822df01
		sourceLineageTag: CalendarYearQuarterNum
		summarizeBy: none
		sourceColumn: CalendarYearQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalQuarterLabel
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: d005ee02-5fff-4762-9a75-6dd0bed61502
		sourceLineageTag: FiscalQuarterLabel
		summarizeBy: none
		sourceColumn: FiscalQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FiscalYearQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 80771358-31d2-4b83-a4ce-2e5cfa637d76
		sourceLineageTag: FiscalYearQuarterNum
		summarizeBy: none
		sourceColumn: FiscalYearQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WeekdayNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b3b58d2b-32ba-49b3-9e52-3f8ee7180684
		sourceLineageTag: WeekdayNum
		summarizeBy: none
		sourceColumn: WeekdayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WeekdayNameShort
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 9f69e73e-de59-4cb6-ba71-5e4e03f03ce1
		sourceLineageTag: WeekdayNameShort
		summarizeBy: none
		sourceColumn: WeekdayNameShort

		annotation SummarizationSetBy = Automatic

	column YearWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 66aa23a1-1650-46b1-ac73-6fe468073fb1
		sourceLineageTag: YearWeekNum
		summarizeBy: none
		sourceColumn: YearWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalYearWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e65e56b6-d12a-42dc-bcc1-3a4c1428a992
		sourceLineageTag: FiscalYearWeekNum
		summarizeBy: none
		sourceColumn: FiscalYearWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column DayOfYearNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 929c65dd-7c8d-45f6-90fa-7ba057bc5bbf
		sourceLineageTag: DayOfYearNum
		summarizeBy: none
		sourceColumn: DayOfYearNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: d70e6376-979a-4f27-aed2-deec0f0dbe1f
		sourceLineageTag: IsWeekend
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsToday
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e49a9fe6-7816-4797-a7c7-bdfc46d98c54
		sourceLineageTag: IsToday
		summarizeBy: none
		sourceColumn: IsToday

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsCurrentMonth
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 56589f15-8d90-4f5f-8160-10c7d0916494
		sourceLineageTag: IsCurrentMonth
		summarizeBy: none
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentFiscalYear
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 57ff94fa-39ba-494f-834f-93b308d946ee
		sourceLineageTag: IsCurrentFiscalYear
		summarizeBy: none
		sourceColumn: IsCurrentFiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalPeriodLabel
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 594827a6-0c4b-41eb-8aff-ef47b6f0576f
		sourceLineageTag: FiscalPeriodLabel
		summarizeBy: none
		sourceColumn: FiscalPeriodLabel

		annotation SummarizationSetBy = Automatic

	column 'Original FISCAL YR'
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: ea5de5e0-29fc-468c-a6ba-6a5f8882ec65
		sourceLineageTag: Original FISCAL YR
		summarizeBy: none
		sourceColumn: Original FISCAL YR

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column 'Original FISCAL PERIOD'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1b400203-bf5b-4153-8d59-ebf10bc27d5f
		sourceLineageTag: Original FISCAL PERIOD
		summarizeBy: none
		sourceColumn: Original FISCAL PERIOD

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column 'Reconciliation Year'
		dataType: string
		sourceProviderType: varchar(20)
		lineageTag: e09de438-bd0c-45ab-be48-63506939a30b
		sourceLineageTag: Reconciliation Year
		summarizeBy: none
		sourceColumn: Reconciliation Year

		annotation SummarizationSetBy = Automatic

	column WeeksInPeriod
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 81202813-d2ca-4595-a929-ca128d21cc4c
		sourceLineageTag: WeeksInPeriod
		summarizeBy: none
		sourceColumn: WeeksInPeriod

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WeekStartDateSunday
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 36c0ce97-ab06-449f-a0cd-6227a4ba0b6c
		sourceLineageTag: WeekStartDateSunday
		summarizeBy: none
		sourceColumn: WeekStartDateSunday

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 294fd95a-2686-4abf-91e5-ae1c27e0d6b5

		level FiscalYear
			lineageTag: a253f652-403f-4bfb-b664-7eb0c7c6c98f
			column: FiscalYear

		level MonthNameShort
			lineageTag: 93b57d5c-0aeb-4a73-9390-fc371a5150a2
			column: MonthNameShort

		level WeekStartDate
			lineageTag: 5b799d3b-1a0f-4014-8b21-0c98b6b8cf99
			column: WeekStartDate

		level Date
			lineageTag: e209a181-72a0-4923-a677-d98825cbe03b
			column: Date

		changedProperty = Name

	partition Dim_Date = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_Date
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

