table Fact_SupplyChain_JobCard
	lineageTag: 11d75275-941b-4a1c-ad48-95ec4e374850
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_SupplyChain_JobCard]

	measure 'Job Hours' = sum(Fact_SupplyChain_JobCard[JobHours])
		lineageTag: 5b583fd5-efe1-4718-adfe-bb2bc4aea422

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Qty Good' = sum(Fact_SupplyChain_JobCard[JobQtyGood])
		lineageTag: 14b44b2c-9e86-4d27-830a-463f0c93b08a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Job Qty Error' = sum(Fact_SupplyChain_JobCard[JobQtyError])
		lineageTag: 651a3c90-f5b6-473d-80e4-b667f52ec17d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMPNY
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: ca27c040-d02e-4085-b1a8-a7757560584c
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProdId
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 7962d367-bb8c-4002-82ed-f87dd0fd7468
		sourceLineageTag: ProdId
		summarizeBy: none
		sourceColumn: ProdId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ItemId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: bc6fbb6c-ea61-4aa4-84d6-bb894ac43c86
		sourceLineageTag: ItemId
		summarizeBy: none
		sourceColumn: ItemId

		annotation SummarizationSetBy = Automatic

	column JournalId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: daa453ff-1c59-4f8e-951d-661c305f6c5a
		sourceLineageTag: JournalId
		summarizeBy: none
		sourceColumn: JournalId

		annotation SummarizationSetBy = Automatic

	column linenum
		dataType: double
		sourceProviderType: decimal(38, 16)
		lineageTag: 9c722fcd-bcbc-49ef-a032-b6b86f555630
		sourceLineageTag: linenum
		summarizeBy: none
		sourceColumn: linenum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OprNum
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: cfd51e93-1e92-4bd2-8135-3e9989ce62f7
		sourceLineageTag: OprNum
		summarizeBy: none
		sourceColumn: OprNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column OprId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 84ade83d-317d-4f1f-9870-b9ba9395d2f2
		sourceLineageTag: OprId
		summarizeBy: none
		sourceColumn: OprId

		annotation SummarizationSetBy = Automatic

	column oprpriority
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 6f51f151-b992-4f3e-9499-ceecf07c2b5c
		sourceLineageTag: oprpriority
		summarizeBy: none
		sourceColumn: oprpriority

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column oprpriority_$label
		dataType: string
		sourceProviderType: varchar(11)
		lineageTag: f1808fda-ab99-496e-95bd-50e539e5cbc3
		sourceLineageTag: oprpriority_$label
		summarizeBy: none
		sourceColumn: oprpriority_$label

		annotation SummarizationSetBy = Automatic

	column posteddatetime
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 366d0588-18e6-43a4-941d-117c6255b8e9
		sourceLineageTag: posteddatetime
		summarizeBy: none
		sourceColumn: posteddatetime

		annotation SummarizationSetBy = Automatic

	column JobHours
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: b312dbd8-f057-430d-a206-8344e727fa43
		sourceLineageTag: JobHours
		summarizeBy: sum
		sourceColumn: JobHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column JobQtyGood
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 13f55dcb-d771-47f7-9370-134e47b64f4f
		sourceLineageTag: JobQtyGood
		summarizeBy: sum
		sourceColumn: JobQtyGood

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column JobQtyError
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 7a559465-9516-4ef6-81cc-ec18091dbe96
		sourceLineageTag: JobQtyError
		summarizeBy: sum
		sourceColumn: JobQtyError

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column wrkctrid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a8bed12d-2d74-4527-b69a-d541a30b3b95
		sourceLineageTag: wrkctrid
		summarizeBy: none
		sourceColumn: wrkctrid

		annotation SummarizationSetBy = Automatic

	column worker
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fb957ab7-f7e0-4a1e-91f7-700a904c6bde
		sourceLineageTag: worker
		summarizeBy: none
		sourceColumn: worker

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column person
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 92026245-cb7e-45e7-b4ac-6b7d1bd11075
		sourceLineageTag: person
		summarizeBy: none
		sourceColumn: person

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column personnelnumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1b45e9eb-b122-4571-a5a0-75a503161d89
		sourceLineageTag: personnelnumber
		summarizeBy: none
		sourceColumn: personnelnumber

		annotation SummarizationSetBy = Automatic

	column transdate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 444e5060-f809-41d1-adf1-62f3c6269ece
		sourceLineageTag: transdate
		summarizeBy: none
		sourceColumn: transdate

		annotation SummarizationSetBy = Automatic

	column dataareaid
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 1978c8c1-ee66-4c92-8300-ab4ca7fb927e
		sourceLineageTag: dataareaid
		summarizeBy: none
		sourceColumn: dataareaid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column oprfinished_$label
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 62e0290d-19bd-4aab-91c0-7c2a3e769b45
		sourceLineageTag: oprfinished_$label
		summarizeBy: none
		sourceColumn: oprfinished_$label

		annotation SummarizationSetBy = Automatic

	column jobtype_$label
		dataType: string
		sourceProviderType: varchar(11)
		lineageTag: 38052a8a-ce8f-4d4c-9308-38d29c64759c
		sourceLineageTag: jobtype_$label
		summarizeBy: none
		sourceColumn: jobtype_$label

		annotation SummarizationSetBy = Automatic

	column jobfinished_$label
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 1d925c46-4ddc-49a4-81e3-134179c965ce
		sourceLineageTag: jobfinished_$label
		summarizeBy: none
		sourceColumn: jobfinished_$label

		annotation SummarizationSetBy = Automatic

	column voucher
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1a6f9ccd-14f1-4417-8ca1-fa62a5386edb
		sourceLineageTag: voucher
		summarizeBy: none
		sourceColumn: voucher

		annotation SummarizationSetBy = Automatic

	column executedpct
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 3439e4e7-4513-4272-9f59-984166621274
		sourceLineageTag: executedpct
		summarizeBy: none
		sourceColumn: executedpct

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column jobid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: abaf3b66-6481-4587-9585-2092b595a8d1
		sourceLineageTag: jobid
		summarizeBy: none
		sourceColumn: jobid

		annotation SummarizationSetBy = Automatic

	column inventdimid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 032cf029-77c5-40c9-8630-494de8ea1fea
		sourceLineageTag: inventdimid
		summarizeBy: none
		sourceColumn: inventdimid

		annotation SummarizationSetBy = Automatic

	column journaltype_$Label
		dataType: string
		sourceProviderType: varchar(24)
		lineageTag: b32b3be7-eda3-4570-a7ae-a0ade7c3bd7f
		sourceLineageTag: journaltype_$Label
		summarizeBy: none
		sourceColumn: journaltype_$Label

		annotation SummarizationSetBy = Automatic

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fb75424f-32cc-40b5-a7f3-7036c7917366
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 8aa4800f-836b-46d0-91ae-1b78518e38f9
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductionBatchOrderKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 8ff2d24d-b983-41a3-b92f-c8721762b022
		sourceLineageTag: ProductionBatchOrderKey
		summarizeBy: none
		sourceColumn: ProductionBatchOrderKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: a53ee7b9-538b-44c7-9cdd-53346400dc5e
		sourceLineageTag: EmployeeKey
		summarizeBy: none
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fromtime
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 52dba5f5-7b70-405f-b723-5476a8f94149
		sourceLineageTag: fromtime
		summarizeBy: sum
		sourceColumn: fromtime

		annotation SummarizationSetBy = Automatic

	column totime
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 0daf01bd-fa4f-4fa7-9360-ce924bf06864
		sourceLineageTag: totime
		summarizeBy: sum
		sourceColumn: totime

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e11e8e88-bd00-432c-b321-1d159de42414
		sourceLineageTag: description
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column SiteKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 60f1b82d-abaa-4d89-b361-647b86740b81
		sourceLineageTag: SiteKey
		summarizeBy: none
		sourceColumn: SiteKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column WarehouseKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 06eaddee-3400-4a2d-9fd9-3cee2f8ba82c
		sourceLineageTag: WarehouseKey
		summarizeBy: none
		sourceColumn: WarehouseKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column BatchKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fa16f648-4a49-4924-9f6f-996e0cea5014
		sourceLineageTag: BatchKey
		summarizeBy: none
		sourceColumn: BatchKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column RouteKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 1569b440-8f06-4c57-82c1-565b50b4378b
		sourceLineageTag: RouteKey
		summarizeBy: none
		sourceColumn: RouteKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition Fact_SupplyChain_JobCard = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_SupplyChain_JobCard
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

