table Fact_QualityOrderLineResults
	lineageTag: 3b88ae89-f80b-4efb-8bd6-3cc2b31a2702
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_QualityOrderLineResults]

	measure 'Qty Good for Quality Row' =
			
			VAR PBO =
			    SELECTEDVALUE ( Fact_QualityOrderLineResults[InventRefId] )
			VAR Serial =
			    SELECTEDVALUE ( Fact_QualityOrderLineResults[inventserialid] )
			RETURN
			IF (
			    ISBLANK ( PBO ),
			    BLANK (),
			    IF (
			        NOT ISBLANK ( Serial ),
			        CALCULATE (
			            [Qty Good],
			            TREATAS ( { PBO }, Dim_ProductionBatchOrder[ProductionBatchOrder] ),
			            TREATAS ( { Serial }, Dim_SerialNumber[SerialNumber] )
			        ),
			        CALCULATE (
			            [Qty Good],
			            TREATAS ( { PBO }, Dim_ProductionBatchOrder[ProductionBatchOrder] ),
			            REMOVEFILTERS ( Dim_SerialNumber )
			        )
			    )
			)
		lineageTag: 982b2752-f36b-49b6-92de-5b5b33fb93d7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Qty by Test Result' =
			
			VAR Subjects =
			    SUMMARIZE (
			        Fact_QualityOrderLineResults,
			        Fact_QualityOrderLineResults[InventRefId],
			        Fact_QualityOrderLineResults[inventserialid]
			    )
			RETURN
			SUMX (
			    Subjects,
			    VAR PBO = [InventRefId]
			    VAR Serial = [inventserialid]
			    RETURN
			        IF (
			            NOT ISBLANK ( Serial ),
			            CALCULATE (
			                [Qty Good],
			                TREATAS ( { PBO }, Dim_ProductionBatchOrder[ProductionBatchOrder] ),
			                TREATAS ( { Serial }, Dim_SerialNumber[SerialNumber] )
			            ),
			            CALCULATE (
			                [Qty Good],
			                TREATAS ( { PBO }, Dim_ProductionBatchOrder[ProductionBatchOrder] ),
			                REMOVEFILTERS ( Dim_SerialNumber )
			            )
			        )
			)
		lineageTag: 98a54c57-0059-448e-bd20-a711ac11f8d4

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Good Qty of Selected Total' =
			
			DIVIDE (
			    [Good Qty by Test Result],
			    CALCULATE (
			        [Good Qty by Test Result],
			        ALLSELECTED ( Fact_QualityOrderLineResults[testresultvalueoutcome] )
			    )
			)
		lineageTag: ca6bcf65-af15-4039-8b7a-970c28279dc4

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distinct Subjects Count' =
			
			COUNTROWS (
			    SUMMARIZE (
			        Fact_QualityOrderLineResults,
			        Fact_QualityOrderLineResults[InventRefId],
			        Fact_QualityOrderLineResults[inventserialid]
			    )
			)
		formatString: 0
		lineageTag: f80f572e-9d09-47ea-b0c9-ca15f83ce34d

		changedProperty = Name

	measure 'RAF Manufacturing Date' =
			
			VAR PBO =
			    SELECTEDVALUE ( Fact_QualityOrderLineResults[InventRefId] )
			VAR Serial =
			    SELECTEDVALUE ( Fact_QualityOrderLineResults[inventserialid] )
			VAR DateKey =
			    IF (
			        ISBLANK ( PBO ),
			        BLANK (),
			        IF (
			            NOT ISBLANK ( Serial ),
			            CALCULATE (
			                SELECTEDVALUE ( Fact_SupplyChain_RAF[TransDateKey] ),
			                TREATAS ( { PBO }, Dim_ProductionBatchOrder[ProductionBatchOrder] ),
			                TREATAS ( { Serial }, Dim_SerialNumber[SerialNumber] )
			            ),
			            CALCULATE (
			                SELECTEDVALUE  ( Fact_SupplyChain_RAF[TransDateKey] ),
			                TREATAS ( { PBO }, Dim_ProductionBatchOrder[ProductionBatchOrder] ),
			                REMOVEFILTERS ( Dim_SerialNumber )
			            )
			        )
			    )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( Dim_Date[Date] ),
			    TREATAS ( { DateKey }, Dim_Date[DateKey] )
			)
		formatString: General Date
		lineageTag: c728c691-0440-4731-a7ee-567e45aead16

		changedProperty = Name

	measure 'Test Result Outcome' =
			
			SELECTEDVALUE ( Fact_QualityOrderLineResults[testresultvalueoutcome] )
		lineageTag: 4fdf7148-74fc-45fe-ab39-582581617772

		changedProperty = Name

	measure 'Test ID' =
			
			SELECTEDVALUE ( Fact_QualityOrderLineResults[testid] )
		lineageTag: 161aaf61-68a8-4162-85ce-407b9897cc18

		changedProperty = Name

	column CMPNY
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 41fc2a8e-613e-49b7-957c-531e043187c3
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		annotation SummarizationSetBy = Automatic

	column qualityorderid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5d9505df-c959-4d8d-80af-3f84bb3dc662
		sourceLineageTag: qualityorderid
		summarizeBy: none
		sourceColumn: qualityorderid

		annotation SummarizationSetBy = Automatic

	column testsequence
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5abfb57e-774b-45b1-b4a6-ed429de6ce60
		sourceLineageTag: testsequence
		summarizeBy: sum
		sourceColumn: testsequence

		annotation SummarizationSetBy = Automatic

	column linenum
		dataType: double
		sourceProviderType: decimal(38, 16)
		lineageTag: f92d2c2f-75b5-4fb4-abfa-9e884dde3f67
		sourceLineageTag: linenum
		summarizeBy: sum
		sourceColumn: linenum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column testid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 3c8fa484-8493-4415-b03c-945678c08642
		sourceLineageTag: testid
		summarizeBy: none
		sourceColumn: testid

		annotation SummarizationSetBy = Automatic

	column qmsskiptest
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 023ae08c-a486-448e-aa1d-a0f68ed05376
		sourceLineageTag: qmsskiptest
		summarizeBy: sum
		sourceColumn: qmsskiptest

		annotation SummarizationSetBy = Automatic

	column qmsskiptest_$label
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: b0bc66e6-43f4-499e-8900-9dd8f52a6967
		sourceLineageTag: qmsskiptest_$label
		summarizeBy: none
		sourceColumn: qmsskiptest_$label

		annotation SummarizationSetBy = Automatic

	column testresult
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 509793e0-10e2-4fc0-84d9-5a62923d0c47
		sourceLineageTag: testresult
		summarizeBy: sum
		sourceColumn: testresult

		annotation SummarizationSetBy = Automatic

	column testresult_$label
		dataType: string
		sourceProviderType: varchar(4)
		lineageTag: e3f1b6e7-5cbd-4e84-b428-ff7899a0c045
		sourceLineageTag: testresult_$label
		summarizeBy: none
		sourceColumn: testresult_$label

		annotation SummarizationSetBy = Automatic

	column testresultquantity
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 103c9914-c5ba-4987-a06b-c53f40828943
		sourceLineageTag: testresultquantity
		summarizeBy: sum
		sourceColumn: testresultquantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column testresultvalueoutcome
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 21b23b35-e2f4-4e5a-8a15-6517af43898e
		sourceLineageTag: testresultvalueoutcome
		summarizeBy: none
		sourceColumn: testresultvalueoutcome

		annotation SummarizationSetBy = Automatic

	column testresultvaluereal
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 9bff1764-66b5-4b03-b504-17a2428cdd50
		sourceLineageTag: testresultvaluereal
		summarizeBy: sum
		sourceColumn: testresultvaluereal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lowerlimit
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 4c8d3b56-772c-4cf6-a7f7-73c5025179e9
		sourceLineageTag: lowerlimit
		summarizeBy: sum
		sourceColumn: lowerlimit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lowertolerance
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 32482842-5257-40ca-b1b5-7def609edc7a
		sourceLineageTag: lowertolerance
		summarizeBy: sum
		sourceColumn: lowertolerance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pdsattribvalue
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e015da6b-3748-4d18-ba24-6f528d38f494
		sourceLineageTag: pdsattribvalue
		summarizeBy: none
		sourceColumn: pdsattribvalue

		annotation SummarizationSetBy = Automatic

	column pdsbatchattribid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 21b08e0d-2cbe-4e65-91ad-f4ed82f6ca19
		sourceLineageTag: pdsbatchattribid
		summarizeBy: none
		sourceColumn: pdsbatchattribid

		annotation SummarizationSetBy = Automatic

	column pdsorderlineresult
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ac519bf2-6fbe-42fa-ae10-4d84bbee3550
		sourceLineageTag: pdsorderlineresult
		summarizeBy: none
		sourceColumn: pdsorderlineresult

		annotation SummarizationSetBy = Automatic

	column standardvalue
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 08b1e8e2-348a-439d-b935-5091e3f9c7ee
		sourceLineageTag: standardvalue
		summarizeBy: sum
		sourceColumn: standardvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column testinstrumentid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 0a246cd5-74b7-4bfe-88c6-785f2c7e042b
		sourceLineageTag: testinstrumentid
		summarizeBy: none
		sourceColumn: testinstrumentid

		annotation SummarizationSetBy = Automatic

	column testunitid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c10d0511-01f3-4764-aca1-82c0d58d4e40
		sourceLineageTag: testunitid
		summarizeBy: none
		sourceColumn: testunitid

		annotation SummarizationSetBy = Automatic

	column upperlimit
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 0c0f770e-1445-48f4-a977-39c0f994c485
		sourceLineageTag: upperlimit
		summarizeBy: sum
		sourceColumn: upperlimit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column uppertolerance
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 5334a8f6-1e6b-4a60-94b4-fb362f33a409
		sourceLineageTag: uppertolerance
		summarizeBy: sum
		sourceColumn: uppertolerance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column variableid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: aec95eb3-10d7-4612-9c32-b4916f6c4446
		sourceLineageTag: variableid
		summarizeBy: none
		sourceColumn: variableid

		annotation SummarizationSetBy = Automatic

	column variableoutcomeidstandard
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: fe8f829a-159b-4dbc-aabc-7a2ab7420cd5
		sourceLineageTag: variableoutcomeidstandard
		summarizeBy: none
		sourceColumn: variableoutcomeidstandard

		annotation SummarizationSetBy = Automatic

	column inventrefid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e0cdc753-8ac6-4221-8948-1d9f172ea982
		sourceLineageTag: inventrefid
		summarizeBy: none
		sourceColumn: inventrefid

		annotation SummarizationSetBy = Automatic

	column inventsiteid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ed2fd6f3-f173-4b4a-844d-9377779e535f
		sourceLineageTag: inventsiteid
		summarizeBy: none
		sourceColumn: inventsiteid

		annotation SummarizationSetBy = Automatic

	column inventlocationid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 84a86360-4658-4c81-83aa-1f84cc737634
		sourceLineageTag: inventlocationid
		summarizeBy: none
		sourceColumn: inventlocationid

		annotation SummarizationSetBy = Automatic

	column inventbatchid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 163e5deb-e17d-408a-8a46-1014a9b7614e
		sourceLineageTag: inventbatchid
		summarizeBy: none
		sourceColumn: inventbatchid

		annotation SummarizationSetBy = Automatic

	column inventserialid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: fcc1a02d-5e51-4b7c-b61e-16b284df76ca
		sourceLineageTag: inventserialid
		summarizeBy: none
		sourceColumn: inventserialid

		annotation SummarizationSetBy = Automatic

	column licenseplateid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c8d41560-ec6f-43aa-bd0c-24544a078fe8
		sourceLineageTag: licenseplateid
		summarizeBy: none
		sourceColumn: licenseplateid

		annotation SummarizationSetBy = Automatic

	column wmslocationid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 169ba335-dec4-469d-9645-dec84648cd7f
		sourceLineageTag: wmslocationid
		summarizeBy: none
		sourceColumn: wmslocationid

		annotation SummarizationSetBy = Automatic

	column inventstatusid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 139cd91d-45a9-41d7-9c02-cc1cf4357369
		sourceLineageTag: inventstatusid
		summarizeBy: none
		sourceColumn: inventstatusid

		annotation SummarizationSetBy = Automatic

	column LineCreatedDateTime
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 85a42797-9454-4ca9-b01b-81d5a1a24c5a
		sourceLineageTag: LineCreatedDateTime
		summarizeBy: none
		sourceColumn: LineCreatedDateTime

		annotation SummarizationSetBy = Automatic

	column LineCreatedDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: db997129-cb99-4a8a-bd4c-cb4e0d6f35bf
		sourceLineageTag: LineCreatedDateKey
		summarizeBy: none
		sourceColumn: LineCreatedDateKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column validatedbyworker
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2bf477b1-e53c-4a3b-89f2-3cf1255be0a8
		sourceLineageTag: validatedbyworker
		summarizeBy: sum
		sourceColumn: validatedbyworker

		annotation SummarizationSetBy = Automatic

	column ValidatedDateTime
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 64148305-b2e5-4f72-9090-1c1d3ddab47b
		sourceLineageTag: ValidatedDateTime
		summarizeBy: none
		sourceColumn: ValidatedDateTime

		annotation SummarizationSetBy = Automatic

	column ValidatedDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 806e0af0-e012-471c-903c-86ea39bbc8ed
		sourceLineageTag: ValidatedDateKey
		summarizeBy: none
		sourceColumn: ValidatedDateKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column accountrelation
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 104c8268-bee8-4b0a-9590-a488f56d3d55
		sourceLineageTag: accountrelation
		summarizeBy: none
		sourceColumn: accountrelation

		annotation SummarizationSetBy = Automatic

	column wrkctrid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a732755d-5b15-4526-af06-c55a083f2d87
		sourceLineageTag: wrkctrid
		summarizeBy: none
		sourceColumn: wrkctrid

		annotation SummarizationSetBy = Automatic

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: dd651622-dacf-4ecc-adae-509e9613f0ac
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: a7f69d1a-0f9d-47f8-983f-8ede5db7fcd9
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column ProductionBatchOrderKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: aae336b7-cf17-4aa1-9095-ad97f65754cf
		sourceLineageTag: ProductionBatchOrderKey
		summarizeBy: none
		sourceColumn: ProductionBatchOrderKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column PurchaseOrderKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 9467fbe0-d388-42d1-bbb1-698737c1e66a
		sourceLineageTag: PurchaseOrderKey
		summarizeBy: none
		sourceColumn: PurchaseOrderKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column SalesOrderKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: b5853824-4557-4833-8700-fd9870b41bfb
		sourceLineageTag: SalesOrderKey
		summarizeBy: none
		sourceColumn: SalesOrderKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column RouteKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: e888ffea-e3fb-4eae-bb98-985c1b6b8c10
		sourceLineageTag: RouteKey
		summarizeBy: none
		sourceColumn: RouteKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column SiteKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 39fd9e70-c25c-4fe2-98c2-df6bdc925701
		sourceLineageTag: SiteKey
		summarizeBy: none
		sourceColumn: SiteKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WarehouseKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: bdf6c92f-3733-4880-9225-cb18c51d0a7d
		sourceLineageTag: WarehouseKey
		summarizeBy: none
		sourceColumn: WarehouseKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column BatchKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 1f90ba56-74da-4607-8fe1-c7e5422c2be5
		sourceLineageTag: BatchKey
		summarizeBy: none
		sourceColumn: BatchKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column SerialNumberKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 48390345-ece6-4661-bba5-6fc10c089568
		sourceLineageTag: SerialNumberKey
		summarizeBy: none
		sourceColumn: SerialNumberKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column VendorKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 8144ddd1-f795-471e-b1a2-fb5232c2c9d1
		sourceLineageTag: VendorKey
		summarizeBy: none
		sourceColumn: VendorKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c7b30be3-c1bd-43e5-ad8d-323da34defa8
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WorkCenterKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ecfe5f0f-9778-49ab-9718-e664b5989e7b
		sourceLineageTag: WorkCenterKey
		summarizeBy: none
		sourceColumn: WorkCenterKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column QuaityOrderStatus
		dataType: string
		sourceProviderType: varchar(4)
		lineageTag: 3b0b7827-1a84-40a5-95f6-23e393e50929
		sourceLineageTag: QuaityOrderStatus
		summarizeBy: none
		sourceColumn: QuaityOrderStatus

		annotation SummarizationSetBy = Automatic

	column testgroupid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 763ca825-8ea1-400b-b1a8-10973d9301e4
		sourceLineageTag: testgroupid
		summarizeBy: none
		sourceColumn: testgroupid

		annotation SummarizationSetBy = Automatic

	column TestGroupKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 1b54f5ea-56fb-4100-a675-cf3523b6177e
		sourceLineageTag: TestGroupKey
		summarizeBy: none
		sourceColumn: TestGroupKey

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	partition Fact_QualityOrderLineResults = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_QualityOrderLineResults
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

