table Fact_SupplyChain_PickList
	lineageTag: e59dd7b3-1691-4dbc-9a46-1662f857ee85
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_SupplyChain_PickList]

	measure 'BOM Consumption' = sum(Fact_SupplyChain_PickList[bomconsump])
		lineageTag: b9ea0dea-c782-41db-90e3-f50858e0046a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BOM Proposal' = sum(Fact_SupplyChain_PickList[bomproposal])
		lineageTag: 855eb578-9d03-4df2-bc73-e4095aad7c15

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BOM Scrap' = sum(Fact_SupplyChain_PickList[bomscrap])
		lineageTag: 711a5c3c-0736-4143-a6e0-278492598cab

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inventory Consumption' = sum(Fact_SupplyChain_PickList[inventconsump])
		lineageTag: 7bdb5876-78e3-4b94-8a7f-df6a715d78a7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inventory Proposal' = sum(Fact_SupplyChain_PickList[inventproposal])
		lineageTag: 6f4f72dc-14a9-406e-affe-4fa72b6d8b43

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMPNY
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 76c1ed45-7b6c-40fb-8eaa-8144a11729ee
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProdId
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: e6bb9ec5-d22f-4790-a021-7f0bf267cf38
		sourceLineageTag: ProdId
		summarizeBy: none
		sourceColumn: ProdId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column itemid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 52955dd8-0c79-429d-bc3b-3e7a535fb1c5
		sourceLineageTag: itemid
		summarizeBy: none
		sourceColumn: itemid

		annotation SummarizationSetBy = Automatic

	column JournalId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 72805e02-e4a8-43aa-ba72-ff581f8b61e9
		sourceLineageTag: JournalId
		summarizeBy: none
		sourceColumn: JournalId

		annotation SummarizationSetBy = Automatic

	column LotID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 3393fd7f-00d4-436a-bcf7-16a74be99fe2
		sourceLineageTag: LotID
		summarizeBy: none
		sourceColumn: LotID

		annotation SummarizationSetBy = Automatic

	column transdate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: f57e1a1c-dc2f-408a-91b6-7f6f57e71201
		sourceLineageTag: transdate
		summarizeBy: none
		sourceColumn: transdate

		annotation SummarizationSetBy = Automatic

	column resource
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: cfe18f8d-fd25-4293-a501-317fe2ad7585
		sourceLineageTag: resource
		summarizeBy: none
		sourceColumn: resource

		annotation SummarizationSetBy = Automatic

	column bomproposal
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: e5422d03-91fa-4cf2-9a20-54f37704051d
		sourceLineageTag: bomproposal
		summarizeBy: sum
		sourceColumn: bomproposal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bomconsump
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: d680e83e-8024-4f01-b05e-1f8bed3637b0
		sourceLineageTag: bomconsump
		summarizeBy: sum
		sourceColumn: bomconsump

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bomunitid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c8038b73-77d8-4a68-8456-36bf272e8b59
		sourceLineageTag: bomunitid
		summarizeBy: none
		sourceColumn: bomunitid

		annotation SummarizationSetBy = Automatic

	column endconsump
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 17c8b1e5-f8bf-47ed-bf9d-239c655d0b6b
		sourceLineageTag: endconsump
		summarizeBy: none
		sourceColumn: endconsump

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column endconsump_$label
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 2a90969e-58c8-4a45-b2e4-81f07fdbaa67
		sourceLineageTag: endconsump_$label
		summarizeBy: none
		sourceColumn: endconsump_$label

		annotation SummarizationSetBy = Automatic

	column matchid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 93b261bd-61ec-4a34-ac54-b65be447c449
		sourceLineageTag: matchid
		summarizeBy: none
		sourceColumn: matchid

		annotation SummarizationSetBy = Automatic

	column voucher
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c27fcaeb-b3cc-4f59-bd07-725219e6b7fb
		sourceLineageTag: voucher
		summarizeBy: none
		sourceColumn: voucher

		annotation SummarizationSetBy = Automatic

	column bomscrap
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 3fc4f023-7ad7-438c-be40-b36a148c76de
		sourceLineageTag: bomscrap
		summarizeBy: sum
		sourceColumn: bomscrap

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column errorcause
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: f0d0808c-d087-49eb-968e-b6e93e80729d
		sourceLineageTag: errorcause
		summarizeBy: none
		sourceColumn: errorcause

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column errorcause_$label
		dataType: string
		sourceProviderType: varchar(14)
		lineageTag: 7b8ffadb-6340-46a4-9327-5038bdc6450c
		sourceLineageTag: errorcause_$label
		summarizeBy: none
		sourceColumn: errorcause_$label

		annotation SummarizationSetBy = Automatic

	column inventproposal
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 901af5a6-0ebb-48d1-8e9f-1b9d50ee4991
		sourceLineageTag: inventproposal
		summarizeBy: sum
		sourceColumn: inventproposal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inventconsump
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 33035ea0-fe34-4aa5-bcbe-45fa61a97f25
		sourceLineageTag: inventconsump
		summarizeBy: sum
		sourceColumn: inventconsump

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InventoryNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 960f685a-608a-4c05-9230-c38513d993c7
		sourceLineageTag: InventoryNumber
		summarizeBy: none
		sourceColumn: InventoryNumber

		annotation SummarizationSetBy = Automatic

	column oprnum
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: f6925b86-9d2d-4764-bf18-1875663babe3
		sourceLineageTag: oprnum
		summarizeBy: none
		sourceColumn: oprnum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column position
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4e7e86df-743a-428f-bd1b-8f43d4f6d4e0
		sourceLineageTag: position
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column inventdimid
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 7835a413-48ab-4749-902d-c6ce219595f6
		sourceLineageTag: inventdimid
		summarizeBy: none
		sourceColumn: inventdimid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column journaltype_$Label
		dataType: string
		sourceProviderType: varchar(24)
		lineageTag: 9998df2b-bec4-40d8-ac1e-1466d24749f7
		sourceLineageTag: journaltype_$Label
		summarizeBy: none
		sourceColumn: journaltype_$Label

		annotation SummarizationSetBy = Automatic

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 260df3c9-1475-4d87-91dd-b96afe82801b
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: bad4d160-df52-4628-9076-c0345e2e375b
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductionBatchOrderKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 91258ad2-363a-4eb7-9fa8-383144da02f6
		sourceLineageTag: ProductionBatchOrderKey
		summarizeBy: none
		sourceColumn: ProductionBatchOrderKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SiteKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 22fc56e1-1464-4672-946e-be690d3ec816
		sourceLineageTag: SiteKey
		summarizeBy: none
		sourceColumn: SiteKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WarehouseKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3b285c83-f6b0-4496-87a7-b62ef7b464e8
		sourceLineageTag: WarehouseKey
		summarizeBy: none
		sourceColumn: WarehouseKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column BatchKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 0147132d-295a-4ced-bd3d-ae50e59b3820
		sourceLineageTag: BatchKey
		summarizeBy: none
		sourceColumn: BatchKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column RouteKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 776e307d-8961-4cd4-8b72-750b62ea2059
		sourceLineageTag: RouteKey
		summarizeBy: none
		sourceColumn: RouteKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	partition Fact_SupplyChain_PickList = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_SupplyChain_PickList
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

