table Dim_StandardCost
	lineageTag: 3009f9d5-a083-4da1-b973-c16d728ed776
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_StandardCost]

	measure ContributionAmount_Inv = ```
			
			[Invoice Line Amount] - [DirectCostAmount_Inv]
			
			```
		lineageTag: a296153a-e157-47eb-b4f8-4438f0813045

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ContributionAmount_Sales = ```
			
			[SalesAmount] - [DirectCostAmount_Sales]
			
			```
		lineageTag: d9e40512-71a2-4725-9000-304f3bddd9a6

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ContributionPct_Inv = ```
			
			DIVIDE ( [ContributionAmount_Inv], [Invoice Line Amount] )
			
			```
		lineageTag: ca4f3a6a-e8a4-4f11-80a2-193a3c3595f6

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ContributionPct_Sales = ```
			
			DIVIDE ( [ContributionAmount_Sales], [SalesAmount] )
			
			```
		lineageTag: 9ed72018-a743-4593-af7d-047f45521409

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ContributionPerLB_Inv = ```
			
			[InvoicePricePerLB] - [DirectCostPerLB_Inv]
			
			```
		lineageTag: 8c07dd9c-e3e9-407f-86e6-f8cfe8d01581

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ContributionPerLB_Sales = ```
			
			[SalesPricePerLB] - [DirectCostPerLB_Sales]
			
			```
		lineageTag: 9e87b52c-5dba-4577-bb42-fef18afaaaf4

		changedProperty = Name

	measure DirectCostAmount_Inv =
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [TotalDirectStandardCost] )
			)
		lineageTag: 95f909e0-3e45-444e-a864-25e2f4341486

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DirectCostAmount_OnH_Phy =
			
			SUMX (
			    Fact_Inventory_Snapshot,
			    Fact_Inventory_Snapshot[physicalinvent_LBs] * CALCULATE ( [TotalDirectStandardCost] )
			)
		lineageTag: 10a6a70d-c464-4596-836c-fad857489d66

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DirectCostAmount_OnH_Pos =
			
			SUMX (
			    Fact_Inventory_Snapshot,
			    Fact_Inventory_Snapshot[postedqty_LBs] * CALCULATE ( [TotalDirectStandardCost] )
			)
		lineageTag: af815cd6-09e1-4751-a4a7-2a5bcc48cad8

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DirectCostAmount_Sales = ```
			
			SUMX (
			    Fact_Sales,
			    Fact_Sales[Quantity_LBs] * CALCULATE ( [TotalDirectStandardCost] )
			)
			
			```
		lineageTag: 7d2b27b1-fa17-4e90-b183-b13b8c10d426

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DirectCostPerLB_Inv = ```
			
			DIVIDE ( [DirectCostAmount_Inv], [Invoice Quantity (LBs)] )
			
			```
		lineageTag: 489d9bf1-7634-486d-b5c4-f2c30e389841

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DirectCostPerLB_Sales = ```
			
			DIVIDE ( [DirectCostAmount_Sales], [QuantityLBs] )
			
			```
		lineageTag: 839c1be2-e72a-43db-a2eb-db84e98e334d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DirectLaborCostStandard = ```
			
			    SUM(Dim_StandardCost[Direct_Labor_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7f992897-1980-4b17-8f9f-4aac047188dc

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure DirectLaborCostTotal_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [DirectLaborCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 52c3875c-7b5e-4570-9db4-f863944619d9

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure DirectLaborCostTotal_Sales = ```
			
			SUMX (
			    Fact_Sales,
			    Fact_Sales[Quantity_LBs] * CALCULATE ( [DirectLaborCostStandard] )
			)
			
			```
		lineageTag: 600cf7af-07ed-4aac-a26b-181cca7656c1

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DirectMaterialCostStandard = ```
			
			SUM(Dim_StandardCost[Direct_Material_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6381cfd6-3ab7-426d-8015-e00a7ef1dfda

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure DirectMaterialCostTotal_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [DirectMaterialCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4f9731e7-4952-41da-9a1b-3d01592b93cf

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure DirectMaterialCostTotal_Sales = ```
			
			SUMX (
			    Fact_Sales,
			    Fact_Sales[Quantity_LBs] * CALCULATE ( [DirectMaterialCostStandard] )
			)
			
			```
		lineageTag: ccf92d46-ee3d-4ed1-8f7a-76458fa65a3f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DirectUtilityCostStandard = ```
			
			  SUM(Dim_StandardCost[Direct_Utility_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f037cf2d-94c8-4abd-9e3a-6f3da426e6ea

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure DirectUtilityCostTotal_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [DirectUtilityCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fa1ab6e6-c95a-46d1-a2bc-1ab10b077603

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure DirectUtilityCostTotal_Sales = ```
			
			SUMX (
			    Fact_Sales,
			    Fact_Sales[Quantity_LBs] * CALCULATE ( [DirectUtilityCostStandard] )
			)
			
			```
		lineageTag: 360ee318-569d-4f2c-87f7-b57fdb53720a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossAmount_Inv = ```
			
			[Invoice Line Amount] - [GrossCostAmount_Inv]
			
			```
		lineageTag: adfd4543-d9c1-429c-bf99-8623528a082b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossAmount_Sales = ```
			
			[SalesAmount] - [GrossCostAmount_Sales]
			
			```
		lineageTag: 9170b9da-b4bd-4a17-86ae-979542effa38

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossCostAmount_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [TotalStandardCost] )
			)
			
			```
		lineageTag: 9aca39f4-2d77-4b9f-a11d-35f0164428ae

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossCostAmount_Sales = ```
			
			SUMX (
			    Fact_Sales,
			    Fact_Sales[Quantity_LBs] * CALCULATE ( [TotalStandardCost] )
			)
			
			```
		lineageTag: 66309909-3f49-44ee-a3ce-d3370c98785e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossMarginPct_Inv = ```
			
			DIVIDE ( [ProfitAmount_Inv], [Invoice Line Amount] )
			
			```
		lineageTag: 557d0b7f-e8d8-4083-a7f6-4a3fdf6916d7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossMarginPct_Sales = ```
			
			DIVIDE ( [ProfitAmount_Sales], [SalesAmount] )
			
			```
		lineageTag: d8242900-7a49-4e48-bc37-59ac1383161d

		changedProperty = Name

	measure OutsideProcessingCostStandard = ```
			
			SUM(Dim_StandardCost[Outside_Processing_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 28eb3ef7-a774-4269-80f4-480aa8ba01e7

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OutsideProcessingCostTotal_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [OutsideProcessingCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4075d383-4e7d-47bd-bbe8-4cf627cd547c

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OutsideProcessingCostTotal_Sales = ```
			
			SUMX (
			    Fact_Sales,
			    Fact_Sales[Quantity_LBs] * CALCULATE ( [OutsideProcessingCostStandard] )
			)
			
			```
		lineageTag: b82b3a3a-21be-4baa-add8-8e4fd3a5b12e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OverheadCostAmount_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [TotalOverheadStandardCost] )
			)
			
			```
		lineageTag: 63f678d9-d536-4b07-aeab-6066ad9f8b96

		changedProperty = Name

	measure OverheadCostAmount_OnH_Phy = ```
			
			SUMX (
			    Fact_Inventory_Snapshot,
			    Fact_Inventory_Snapshot[physicalinvent_LBs] * CALCULATE ( [TotalOverheadStandardCost] )
			)
			
			```
		lineageTag: f9c64e2c-55cb-43bb-8c3a-22669d6e3243

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OverheadCostAmount_OnH_Pos = ```
			
			SUMX (
			    Fact_Inventory_Snapshot,
			    Fact_Inventory_Snapshot[postedqty_LBs] * CALCULATE ( [TotalOverheadStandardCost] )
			)
			
			```
		lineageTag: 96ed5afd-91f7-4689-ae08-619fe6f7d562

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OverheadCostAmount_Sales = ```
			
			SUMX (
			    Fact_Sales,
			    Fact_Sales[Quantity_LBs] * CALCULATE ( [TotalOverheadStandardCost] )
			)
			
			```
		lineageTag: 78c95a0d-bdc9-457d-a610-8a55455d4a9a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OverheadCostPerLB_Inv = ```
			
			DIVIDE ( [OverheadCostAmount_Inv], [Invoice Quantity (LBs)] )
			
			```
		lineageTag: 14716def-0d50-44a6-8e78-d7017355bd0b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OverheadCostPerLB_Sales = ```
			
			DIVIDE ( [OverheadCostAmount_Sales], [QuantityLBs] )
			
			```
		lineageTag: 4fc504b7-362f-4303-a2b1-0625f7571254

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OverheadDepreciationCost_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [OverheadDepreciationCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 14dc64f9-c27f-49d4-afdc-e7820b2065cf

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadDepreciationCostStandard = ```
			
			    SUM(Dim_StandardCost[Overhead_Depreciation_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a33e4736-422d-4b93-89be-87bb12ef20d0

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadIndirectSupervisorCost_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [OverheadIndirectSupervisorCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 1e65f334-9ff5-4c4a-981b-66183bd59f3e

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadIndirectSupervisorCostStandard = ```
			
			    SUM(Dim_StandardCost[Overhead_Indirect_Supervisor_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8ecd3564-7ade-4ccc-9b1f-595164bd2067

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadMaintenanceCost_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [OverheadMaintenanceCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e9eda4df-6819-4a5e-9fff-18eb5180e839

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadMaintenanceCostStandard = ```
			
			    SUM(Dim_StandardCost[Overhead_Maintenance_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b2fa0895-227a-4332-a99a-57d62597e361

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadManufacturingAdminCost_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [OverheadManufacturingAdminCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 63b4340f-8e84-464d-bf5f-1669188f5608

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadManufacturingAdminCostStandard = ```
			
			    SUM(Dim_StandardCost[Overhead_Manufacturing_Admin_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0a142d3c-9f73-4cfe-85d2-90c6ef036f50

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadMiscellaneousManufacturingCost_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [OverheadMiscellaneousManufacturingCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 56e6b98b-30dc-4424-bec3-c0e10c8aed0b

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadMiscellaneousManufacturingCostStandard = ```
			
			    SUM(Dim_StandardCost[Overhead_Miscellaneous_Manufacturing_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 281b0cde-ea9f-4a48-90a0-d583d7df4482

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadQualityCost_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [OverheadQualityCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b3f8e1d0-9d1d-4f5a-99e4-4a86e7c2fe72

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadQualityCostStandard = ```
			
			    SUM(Dim_StandardCost[Overhead_Quality_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5be35b34-58af-4ba3-b1af-bfd2b4b77551

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadWarehouseCost_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [OverheadWarehouseCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7a13bb89-16a1-43dc-a46e-533d7c90c9fc

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OverheadWarehouseCostStandard = ```
			
			    SUM(Dim_StandardCost[Overhead_Warehouse_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 82eab2cd-6e6c-4ff9-86b0-814f4e95963c

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure PackagingCostStandard = ```
			
			SUM(Dim_StandardCost[Packaging_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ff8ac294-d0c1-4ca1-b3f7-a36fc9b3e3a4

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure PackagingCostTotal_Inv = ```
			
			SUMX (
			    Fact_Customer_Invoices,
			    Fact_Customer_Invoices[Quantity_LBs] * CALCULATE ( [PackagingCostStandard] )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bf064f28-9e28-4cc3-b8c6-de070b45b743

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure PackagingCostTotal_Sales = ```
			
			SUMX (
			    Fact_Sales,
			    Fact_Sales[Quantity_LBs] * CALCULATE ( [PackagingCostStandard] )
			)
			
			```
		lineageTag: f33cff2f-daa1-4962-94d7-3c2c5517fb07

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ProfitAmount_Inv = ```
			
			[Invoice Line Amount] - [TotalCostAmount_Inv]
			
			```
		lineageTag: 7cbdd919-d686-4577-863f-a655b6c716c4

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ProfitAmount_Sales = ```
			
			[SalesAmount] - [TotalCostAmount_Sales]
			
			```
		lineageTag: 6054b5fe-891d-4f93-af76-18484e749d13

		changedProperty = Name

	measure ProfitPerLB_Inv = ```
			
			DIVIDE ( [ProfitAmount_Inv], [Invoice Quantity (LBs)] )
			
			```
		lineageTag: 71cc3be5-74c1-4d9a-9790-c1e446ce4e2e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ProfitPerLB_Sales = ```
			
			DIVIDE ( [ProfitAmount_Sales], [QuantityLBs] )
			
			```
		lineageTag: dce58fdd-a349-4f9e-bc26-55b5dd75dc95

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cost Transactions' = COUNTROWS(Dim_StandardCost)
		formatString: 0
		lineageTag: ed2fa92e-fd0a-437a-8316-0ed716616655

		changedProperty = Name

	measure TotalCostAmount_Inv = ```
			
			[DirectCostAmount_Inv] + [OverheadCostAmount_Inv]
			
			```
		lineageTag: fa01ca8a-2ae9-45be-a888-5d8013d8db09

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalCostAmount_OnH_Phy = ```
			
			[DirectCostAmount_OnH_Phy] + [OverheadCostAmount_OnH_Phy]
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 52d53dbe-6c19-4f36-9d8d-f4cc9fbca234

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure TotalCostAmount_OnH_Pos = ```
			
			[DirectCostAmount_OnH_Pos] + [OverheadCostAmount_OnH_Pos]
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 382d828f-b580-4db4-9ea0-5f02c7d8f823

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure TotalCostAmount_Sales = ```
			
			[DirectCostAmount_Sales] + [OverheadCostAmount_Sales]
			
			```
		formatString: 0
		lineageTag: 7d3e3e4c-f997-4066-8565-20f07186c428

		changedProperty = Name

	measure TotalCostPerLB_Inv = ```
			
			DIVIDE ( [TotalCostAmount_Inv], [Invoice Quantity (LBs)] )
			
			```
		lineageTag: b0eac69f-5b5e-4399-9a3b-a50d5984734b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalCostPerLB_Sales = ```
			
			DIVIDE ( [TotalCostAmount_Sales], [QuantityLBs] )
			
			```
		lineageTag: 2a957e4b-7171-40d7-8e5a-06ae335aa11c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalDirectStandardCost = ```
			
			    // Direct Cost
			    SUM(Dim_StandardCost[Direct_Labor_Cost_Standard])
			  + SUM(Dim_StandardCost[Direct_Material_Cost_Standard])
			  + SUM(Dim_StandardCost[Direct_Utility_Cost_Standard])
			    // Outside Processing Cost
			  + SUM(Dim_StandardCost[Outside_Processing_Cost_Standard])
			    // Packaging Cost
			  + SUM(Dim_StandardCost[Packaging_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ee76c9aa-d702-4d94-b95b-d3d411ca5d57

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure TotalOverheadStandardCost = ```
			
			    // Overhead Cost
			    SUM(Dim_StandardCost[Overhead_Depreciation_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Indirect_Supervisor_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Maintenance_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Manufacturing_Admin_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Miscellaneous_Manufacturing_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Quality_Cost_Standard]) +
			    SUM(Dim_StandardCost[Overhead_Warehouse_Cost_Standard])
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c162169c-fb4c-4c22-8625-59bfcd96fa72

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure TotalStandardCost = ```
			
			[TotalDirectStandardCost] + [TotalOverheadStandardCost]
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0e85ddd1-a067-48db-aa3e-bdae4b260b31

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Is the displayed cost active?' =
			
			VAR ProductIDCount =
			    DISTINCTCOUNT ( 'Dim_StandardCost'[Product_ID] )
			
			VAR ActiveCount =
			    CALCULATE (
			        COUNTROWS ( 'Dim_StandardCost' ),
			        'Dim_StandardCost'[RecordStatus] = 1
			    )
			
			VAR InactiveCount =
			    CALCULATE (
			        COUNTROWS ( 'Dim_StandardCost' ),
			        'Dim_StandardCost'[RecordStatus] = 0
			    )
			
			RETURN
			    SWITCH (
			        TRUE (),
			
			        ProductIDCount <> 1, "Keep selecting",
			
			        ActiveCount > 0 && InactiveCount = 0, "Yes",
			
			        InactiveCount > 0 && ActiveCount = 0, "No",
			
			        ActiveCount > 0 && InactiveCount > 0, "Keep selecting",
			
			        "No Data"
			    )
		lineageTag: 64c2ba03-f01d-4e6e-af37-c7901f475688

		changedProperty = Name

	column StandardCostKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: a0d58eaf-344b-41c3-84ee-ad105c4b30fd
		sourceLineageTag: StandardCostKey
		summarizeBy: none
		sourceColumn: StandardCostKey

		annotation SummarizationSetBy = Automatic

	column CMPNY
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 054993a8-a36a-4843-bf5a-488c8e937096
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 01fd1710-d00a-4746-a5ab-3a49293c69e8
		sourceLineageTag: Product_ID
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column LegacyProductCode
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 8c734730-cdb8-4576-a582-0db47a214647
		sourceLineageTag: LegacyProductCode
		summarizeBy: none
		sourceColumn: LegacyProductCode

		annotation SummarizationSetBy = Automatic

	column SiteID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 445250fe-6d6e-492d-884c-dbe4a7df9ca5
		sourceLineageTag: SiteID
		summarizeBy: none
		sourceColumn: SiteID

		annotation SummarizationSetBy = Automatic

	column ActivationDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: b3550119-ac7c-43c8-be52-64c7b745f1aa
		sourceLineageTag: ActivationDate
		summarizeBy: none
		sourceColumn: ActivationDate

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 43e39fdd-2ce7-4153-927e-c20a0586d4f6
		sourceLineageTag: EndDate
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

	column Costing_Version
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7dbbad43-bda1-459f-8536-337287df3f54
		sourceLineageTag: Costing_Version
		summarizeBy: none
		sourceColumn: Costing_Version

		annotation SummarizationSetBy = Automatic

	column CurrentActiveCost
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d8b28730-f818-4399-8626-b5e104e568e1
		sourceLineageTag: CurrentActiveCost
		summarizeBy: sum
		sourceColumn: CurrentActiveCost

		annotation SummarizationSetBy = Automatic

	column Direct_Material_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 326625ae-cd96-4dbe-8344-9b05d1f92f19
		sourceLineageTag: Direct_Material_Cost_Standard
		summarizeBy: sum
		sourceColumn: Direct_Material_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Packaging_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 744ad0f7-e548-4e40-93d3-065c71733e6e
		sourceLineageTag: Packaging_Cost_Standard
		summarizeBy: sum
		sourceColumn: Packaging_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direct_Labor_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 3d32d8b4-f1f8-4aef-8f2c-354a17a1f957
		sourceLineageTag: Direct_Labor_Cost_Standard
		summarizeBy: sum
		sourceColumn: Direct_Labor_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direct_Utility_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: d61fdcbc-35d9-418b-aafc-fbf9083457a9
		sourceLineageTag: Direct_Utility_Cost_Standard
		summarizeBy: sum
		sourceColumn: Direct_Utility_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Warehouse_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 38b53250-10dd-4058-a899-9a9d48e525f6
		sourceLineageTag: Overhead_Warehouse_Cost_Standard
		summarizeBy: sum
		sourceColumn: Overhead_Warehouse_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Indirect_Supervisor_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 783a2bc3-845d-4b93-ab95-a4c09973850c
		sourceLineageTag: Overhead_Indirect_Supervisor_Cost_Standard
		summarizeBy: sum
		sourceColumn: Overhead_Indirect_Supervisor_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Quality_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: e40ba7aa-8c07-410c-bd4c-2fcf5f09d1c3
		sourceLineageTag: Overhead_Quality_Cost_Standard
		summarizeBy: sum
		sourceColumn: Overhead_Quality_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Maintenance_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 6017673d-09ef-481d-b488-d2c3aaef3597
		sourceLineageTag: Overhead_Maintenance_Cost_Standard
		summarizeBy: sum
		sourceColumn: Overhead_Maintenance_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Manufacturing_Admin_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 8300af2d-fc8f-4fca-9856-00da944700ed
		sourceLineageTag: Overhead_Manufacturing_Admin_Cost_Standard
		summarizeBy: sum
		sourceColumn: Overhead_Manufacturing_Admin_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Depreciation_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: a1c67b27-03d7-402d-a0e4-f20a43e65e2f
		sourceLineageTag: Overhead_Depreciation_Cost_Standard
		summarizeBy: sum
		sourceColumn: Overhead_Depreciation_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overhead_Miscellaneous_Manufacturing_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 92d1abd0-f325-4b94-b36f-2ad498eb299b
		sourceLineageTag: Overhead_Miscellaneous_Manufacturing_Cost_Standard
		summarizeBy: sum
		sourceColumn: Overhead_Miscellaneous_Manufacturing_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Outside_Processing_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 68d61541-56f6-4724-b6c8-01d66e2bc3f7
		sourceLineageTag: Outside_Processing_Cost_Standard
		summarizeBy: sum
		sourceColumn: Outside_Processing_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Direct_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 32695a31-d041-4a3f-a672-dbe0c76764c7
		sourceLineageTag: Total_Direct_Cost_Standard
		summarizeBy: sum
		sourceColumn: Total_Direct_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Overhead_Cost_Standard
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 85ba4ce8-663e-47cd-a287-44cb84f1980c
		sourceLineageTag: Total_Overhead_Cost_Standard
		summarizeBy: sum
		sourceColumn: Total_Overhead_Cost_Standard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalCost
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: afdbe59e-f176-42a3-b7f9-d02a1e373f2e
		sourceLineageTag: TotalCost
		summarizeBy: sum
		sourceColumn: TotalCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column accountingcurrency
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a2c35ecd-95ea-444c-9f1d-6e09a990e2b8
		sourceLineageTag: accountingcurrency
		summarizeBy: none
		sourceColumn: accountingcurrency

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: b6743442-b2e3-4334-97be-cec163168bca
		sourceLineageTag: RecordEffectiveStartDate
		summarizeBy: none
		sourceColumn: RecordEffectiveStartDate

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveEndDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: a17e7919-8b34-4317-8aa9-d1b80ee90ef4
		sourceLineageTag: RecordEffectiveEndDate
		summarizeBy: none
		sourceColumn: RecordEffectiveEndDate

		annotation SummarizationSetBy = Automatic

	column RecordStatus
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 36bfbe97-c115-4d46-94c0-5b7ba45f27f0
		sourceLineageTag: RecordStatus
		summarizeBy: sum
		sourceColumn: RecordStatus

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		sourceProviderType: varchar(6)
		lineageTag: d7687d4f-7b38-4d64-a531-c005e8fbfdc4
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 867739da-ac40-4247-906a-a2cf73f18cdc
		sourceLineageTag: ProductName
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ProductSearchName
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: fba1cac8-45fb-45f7-9a53-e08915d43e1d
		sourceLineageTag: ProductSearchName
		summarizeBy: none
		sourceColumn: ProductSearchName

		annotation SummarizationSetBy = Automatic

	partition Dim_StandardCost = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_StandardCost
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

