table Fact_CustTrans
	lineageTag: ec7771b0-8d9d-46da-b398-88bf5b5f2124
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_CustTrans]

	/// Determines the effective “run date” for the aging report. Uses the maximum visible DimDate[Date] in the current filter context (typically “today” via a relative date filter), capped at TODAY() to avoid future dates. Always returns a date (never blank).
	measure 'Report Run Date' = ```
			
			VAR MaxVisibleDate = MAX(Dim_Date[Date])
			-- Safety: if your date table goes into the future, don't accidentally use 12/31/2099.
			RETURN
			COALESCE( MIN( TODAY(), MaxVisibleDate ), TODAY() )
			
			```
		formatString: General Date
		lineageTag: 102a54a5-31f1-4bd5-9b0b-177bbff24b9a

		changedProperty = Name

		changedProperty = Description

	/// Computes the aging “as of” date as the end of the prior month relative to [Report Run Date] (EOMONTH([Report Run Date], -1)). Example: any day in Feb → 1/31. Always returns a date (never blank).
	measure 'Aging As Of Date' = ```
			
			EOMONTH( [Report Run Date], -1 )
			
			```
		formatString: General Date
		lineageTag: 44984a29-13c9-4ccd-b8ee-89e3d6911799

		changedProperty = Name

		changedProperty = Description

	/// Calculates customer open A/R as of [Aging As Of Date] in accounting currency (MST) using amountmst, settleamountmst, closed, and lastsettledate.
	/// 
	/// Includes transactions with TransactionDate <= BalanceDate.
	/// 
	/// Removes DimDate filters to avoid slicing the fact down to only the current day/month.
	/// 
	/// Open-as-of logic:
	/// 
	/// If closed after BalanceDate: treat as fully open as-of (uses full amountmst).
	/// 
	/// If closed on/before BalanceDate: treat as 0.
	/// 
	/// If not closed: uses current open estimate (amountmst - settleamountmst).
	/// Returns 0 when no rows qualify (never blank).
	measure 'Balance as of (MST)' = ```
			
			VAR BalanceDate = [Aging As Of Date]
			
			-- Remove date filters from the model so the page's "today" filter doesn't restrict fact rows.
			VAR BaseRows =
			    CALCULATETABLE(
			        Fact_CustTrans,
			        REMOVEFILTERS(Dim_Date)
			    )
			
			VAR Result =
			    SUMX(
			        FILTER(
			            BaseRows,
			            Fact_CustTrans[TransactionDate] <= BalanceDate
			        ),
			        VAR Amt      = COALESCE(Fact_CustTrans[amountmst], 0)
			        VAR Settled  = COALESCE(Fact_CustTrans[settleamountmst], 0)
			        VAR ClosedN  = COALESCE(Fact_CustTrans[closed], 0)
			        VAR LastSet  = Fact_CustTrans[lastsettledate]
			        VAR IsClosed = ClosedN = 1   -- If your field is TRUE/FALSE, change to: ClosedN = TRUE()
			
			        VAR OpenAsOf =
			            SWITCH(
			                TRUE(),
			                -- Closed after the as-of date: treat as fully open for last-month snapshot purposes
			                IsClosed && NOT ISBLANK(LastSet) && LastSet > BalanceDate, Amt,
			
			                -- Closed on/before the as-of date (or "closed but no date"): not open
			                IsClosed, 0,
			
			                -- Still open: use current open amount
			                Amt - Settled
			            )
			        RETURN
			            OpenAsOf
			    )
			
			RETURN
			COALESCE(Result, 0)
			
			```
		lineageTag: ea6ad0e0-adf7-4e17-af59-017f326a25e2

		changedProperty = Name

		changedProperty = Description

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Returns the portion of [Balance as of (MST)] that falls into the current Moody’s aging bucket row context using DIM_AgingBuckets[FromDays] and [ToDays].
	/// 
	/// DaysOverdue = DATEDIFF(dueDate, BalanceDate, DAY)
	/// 
	/// Blank due dates are treated as current (DaysOverdue = 0).
	/// 
	/// Removes DimDate filters and evaluates transactions up to BalanceDate.
	/// Uses the same open-as-of logic as [Balance as of (MST)].
	/// Returns 0 when empty (never blank).
	measure 'Aged Balance (MST)' = ```
			
			VAR BalanceDate = [Aging As Of Date]
			VAR MinDays     = MIN(Dim_AgingBuckets[FromDays])
			VAR MaxDays     = MAX(Dim_AgingBuckets[ToDays])
			
			VAR BaseRows =
			    CALCULATETABLE(
			        Fact_CustTrans,
			        REMOVEFILTERS(Dim_Date)
			    )
			
			VAR BucketRows =
			    FILTER(
			        BaseRows,
			        Fact_CustTrans[TransactionDate] <= BalanceDate
			            &&
			        VAR DueDate =
			            Fact_CustTrans[duedate]
			        VAR DaysOverdue =
			            IF(
			                ISBLANK(DueDate),
			                0,  -- missing due date = treat as current
			                DATEDIFF(DueDate, BalanceDate, DAY)
			            )
			        RETURN
			            DaysOverdue >= MinDays
			            && DaysOverdue <= MaxDays
			    )
			
			VAR Result =
			    SUMX(
			        BucketRows,
			        VAR Amt      = COALESCE(Fact_CustTrans[amountmst], 0)
			        VAR Settled  = COALESCE(Fact_CustTrans[settleamountmst], 0)
			        VAR ClosedN  = COALESCE(Fact_CustTrans[closed], 0)
			        VAR LastSet  = Fact_CustTrans[lastsettledate]
			        VAR IsClosed = ClosedN = 1   -- If boolean: ClosedN = TRUE()
			
			        VAR OpenAsOf =
			            SWITCH(
			                TRUE(),
			                IsClosed && NOT ISBLANK(LastSet) && LastSet > BalanceDate, Amt,
			                IsClosed, 0,
			                Amt - Settled
			            )
			        RETURN
			            OpenAsOf
			    )
			
			RETURN
			COALESCE(Result, 0)
			
			```
		lineageTag: 2c9556bf-a2c8-48dd-834a-c23f9f7fad71

		changedProperty = Name

		changedProperty = Description

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Moody’s “Current (with terms)” bucket (DaysOverdue ≤ 0). Wrapper over [Aged Balance (MST)] filtered to AgingBucketKey = 1. Returns 0 (never blank).
	measure 'CURRENT AMT' = ```
			
			CALCULATE( [Aged Balance (MST)], Dim_AgingBuckets[AgingBucketKey] = 1 )
			
			```
		lineageTag: c7dfc17a-efde-4c2e-95b7-4d88441d8e54

		changedProperty = Name

		changedProperty = Description

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Moody’s “1–30 days beyond terms” bucket. Wrapper over [Aged Balance (MST)] filtered to AgingBucketKey = 2. Returns 0 (never blank).
	measure 'PAST DUE 1-30' = ```
			
			CALCULATE( [Aged Balance (MST)], Dim_AgingBuckets[AgingBucketKey] = 2 )
			
			```
		lineageTag: 9d429045-27c3-4eb5-99b6-5bb8b210c632

		changedProperty = Name

		changedProperty = Description

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Moody’s “31–60 days beyond terms” bucket. Wrapper over [Aged Balance (MST)] filtered to AgingBucketKey = 3. Returns 0 (never blank).
	measure 'PAST DUE 31-60' = ```
			
			CALCULATE( [Aged Balance (MST)], Dim_AgingBuckets[AgingBucketKey] = 3 )
			
			```
		lineageTag: 3d4b4c5a-bcc8-41ac-8db5-9d1abd197b19

		changedProperty = Name

		changedProperty = Description

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Moody’s “61–90 days beyond terms” bucket. Wrapper over [Aged Balance (MST)] filtered to AgingBucketKey = 4. Returns 0 (never blank).
	measure 'PAST DUE 61-90' = ```
			
			CALCULATE( [Aged Balance (MST)], Dim_AgingBuckets[AgingBucketKey] = 4 )
			
			
			```
		lineageTag: 7aabda35-6ed0-4761-9665-7b53817bd858

		changedProperty = Name

		changedProperty = Description

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Moody’s “90+ days beyond terms” bucket (DaysOverdue ≥ 91). Wrapper over [Aged Balance (MST)] filtered to AgingBucketKey = 5. Returns 0 (never blank).
	measure 'PAST DUE 90+' = ```
			
			CALCULATE( [Aged Balance (MST)], Dim_AgingBuckets[AgingBucketKey] = 5 )
			
			```
		lineageTag: 265269d5-57e0-4220-b764-2f6c96223839

		changedProperty = Name

		changedProperty = Description

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Presentation alias for [Balance as of (MST)] to match D365 column naming. Returns 0 (never blank).
	measure 'Balance as of' = ```
			[Balance as of (MST)]
			
			```
		lineageTag: c25fb94b-72f1-4085-8e5f-15b1981b721a

		changedProperty = Name

		changedProperty = Description

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Visual filter helper to mimic D365 parameter “Exclude zero balance accounts = Yes”. Returns 1 when [Balance as of] <> 0, else 0. Use as a visual-level filter (= 1). Never blank.
	measure 'Has Nonzero Balance' = ```
			
			VAR Bal = [Balance as of]
			RETURN IF( Bal <> 0, 1, 0 )
			
			```
		formatString: 0
		lineageTag: 358e54d8-dac0-45f3-9743-e32da8b6a078

		changedProperty = Name

		changedProperty = Description

	measure 'Total Balance' =
			
			
			[CURRENT AMT] + [PAST DUE 1-30] + [PAST DUE 31-60] + [PAST DUE 61-90] +  [PAST DUE 90+]
		lineageTag: f87fb42c-ab3c-4e0d-a199-7c4490187650

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Company
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ef1b8b4e-cba6-4d6f-97e1-cb00417e1274
		sourceLineageTag: Company
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column voucher
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1db6e32d-435f-4478-9c0c-da9c5dcbf341
		sourceLineageTag: voucher
		summarizeBy: none
		sourceColumn: voucher

		annotation SummarizationSetBy = Automatic

	column Customer_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 15989e56-3caa-432c-986b-78944c0f26a1
		sourceLineageTag: Customer_ID
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column TransactionDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: b4f871a2-6acd-4ec6-953b-dc76cf442160
		sourceLineageTag: TransactionDate
		summarizeBy: none
		sourceColumn: TransactionDate

		annotation SummarizationSetBy = Automatic

	column TransactionDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 9ea0c3be-8c57-4d72-918c-abfa31743ab5
		sourceLineageTag: TransactionDateKey
		summarizeBy: none
		sourceColumn: TransactionDateKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column GL_TransType
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4a81e3b7-35f3-4d4c-b89c-3c08284ae1bd
		sourceLineageTag: GL_TransType
		summarizeBy: none
		sourceColumn: GL_TransType

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column GLTransTypeDesc
		dataType: string
		sourceProviderType: varchar(49)
		lineageTag: 92d1f551-577f-4fb1-b35f-2c51be77d694
		sourceLineageTag: GLTransTypeDesc
		summarizeBy: none
		sourceColumn: GLTransTypeDesc

		annotation SummarizationSetBy = Automatic

	column currencycode
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: debff544-ee6a-4f64-813a-3213e17fc8f9
		sourceLineageTag: currencycode
		summarizeBy: none
		sourceColumn: currencycode

		annotation SummarizationSetBy = Automatic

	column Invoice_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: bfd93863-fb8d-4ce3-8cdc-8fd98b635459
		sourceLineageTag: Invoice_ID
		summarizeBy: none
		sourceColumn: Invoice_ID

		annotation SummarizationSetBy = Automatic

	column closed
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 34471507-0bf2-4dd8-bd89-0937786c284a
		sourceLineageTag: closed
		summarizeBy: none
		sourceColumn: closed

		annotation SummarizationSetBy = Automatic

	column ClosedDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: dd810c2d-7142-432c-a0e8-9cdbf432f822
		sourceLineageTag: ClosedDateKey
		summarizeBy: none
		sourceColumn: ClosedDateKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column duedate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 39868cf9-c114-4c40-a904-45ba3750297d
		sourceLineageTag: duedate
		summarizeBy: none
		sourceColumn: duedate

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 8fde0713-681e-4165-8911-fefa996d6950
		sourceLineageTag: DueDateKey
		summarizeBy: none
		sourceColumn: DueDateKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column OpenID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d6228656-8f89-4b1c-8ab6-2c271125f3c4
		sourceLineageTag: OpenID
		summarizeBy: none
		sourceColumn: OpenID

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column DaysOverdue
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3c3dbf09-ff16-4fde-9f8c-1f6a39a052f8
		sourceLineageTag: DaysOverdue
		summarizeBy: none
		sourceColumn: DaysOverdue

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column AgingBucketKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: fb8557da-986a-4f34-ba27-c9f389c4325b
		sourceLineageTag: AgingBucketKey
		summarizeBy: none
		sourceColumn: AgingBucketKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Description
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: 1e767446-614f-46f6-bd9d-5d87e00049fd
		sourceLineageTag: Description
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column amountcur
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 1c9f278f-b1a7-45a0-b218-27fc443ed2d7
		sourceLineageTag: amountcur
		summarizeBy: none
		sourceColumn: amountcur

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amountmst
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 9c36c3af-bd26-443a-b32c-7dc000bd16c0
		sourceLineageTag: amountmst
		summarizeBy: none
		sourceColumn: amountmst

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column custexchadjustmentrealized
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 5a5b0452-52cc-4603-832e-b4f296f239f4
		sourceLineageTag: custexchadjustmentrealized
		summarizeBy: none
		sourceColumn: custexchadjustmentrealized

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column custexchadjustmentunrealized
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 915eb335-4691-4082-82bf-ec87baa67d5b
		sourceLineageTag: custexchadjustmentunrealized
		summarizeBy: none
		sourceColumn: custexchadjustmentunrealized

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column settleamountmst
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 4f715354-21ad-4977-95de-bba4405b0755
		sourceLineageTag: settleamountmst
		summarizeBy: none
		sourceColumn: settleamountmst

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Amount
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: b4bfe919-d12b-4def-985f-5800ee7a58ac
		sourceLineageTag: Amount
		summarizeBy: none
		sourceColumn: Amount

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DaysOutstanding
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a5b24391-6e75-4e00-a9f3-60244c4095de
		sourceLineageTag: DaysOutstanding
		summarizeBy: none
		sourceColumn: DaysOutstanding

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column lastsettledate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 6d3b072e-2386-4730-945b-6e213a5688d1
		sourceLineageTag: lastsettledate
		summarizeBy: none
		sourceColumn: lastsettledate

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 43670724-7ee3-486f-88aa-d4c5c76d8639
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5263d4f6-374b-4427-9ddd-17eb1f6ed92f
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition Fact_CustTrans = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_CustTrans
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

