table Fact_Sales
	lineageTag: 406cd4fb-0c84-413a-a8e1-e0857bddec88
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_Sales]

	measure QuantityLBs = SUM(Fact_Sales[Quantity_LBs])
		lineageTag: 8c03a59c-eb96-40ff-be4c-0b1b9984450f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ReturnedAmount = SUM(Fact_Sales[Returned_Amount])
		lineageTag: 28cff6d8-358f-41d4-a14c-0eef3541b40d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ReturnedQuantity = SUM(Fact_Sales[Returned_Quantity])
		lineageTag: 5b8ef249-a940-4edb-9503-c7130e1aa570

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesQuantity = SUM(Fact_Sales[Quantity])
		lineageTag: 3f0307a4-9750-42fb-a948-fe3167caca85

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesAmount =
			
			SUM (Fact_Sales[Amount])
		lineageTag: 785fa62c-5035-4dba-908a-61be6ed2c9b0

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesPricePerLB = Divide([SalesAmount] , [QuantityLBs])
		lineageTag: 071ba01a-8ba4-492f-a698-6f006ce31365

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = COUNTROWS(Fact_Sales)
		formatString: 0
		lineageTag: 747d0174-19f6-4ff0-839a-075d3286b0da

		changedProperty = Name

	measure 'Weekly Average Revenue (Sales Days)' = ```
			
			
			VAR wkStart =
			    SELECTEDVALUE ( Dim_Date[WeekStartDate] )
			RETURN
			IF (
			    ISBLANK ( wkStart ),
			    BLANK (),
			    VAR wkEnd = wkStart + 6
			
			    VAR TodayDate = TODAY ()
			    VAR NowEST =
			        NOW() - TIME ( 5, 0, 0 )   -- adjust to EST (or 4 for EDT)
			
			    VAR AfterCutoffToday =
			        NowEST >= ( TodayDate + TIME ( 19, 0, 0 ) )
			
			    -- Dates in the selected week, excluding future days,
			    -- and excluding "today" until after 7PM
			    VAR WeekDatesEligible =
			        FILTER (
			            DATESBETWEEN ( Dim_Date[Date], wkStart, wkEnd ),
			            Dim_Date[Date] <= TodayDate
			                && ( Dim_Date[Date] < TodayDate || AfterCutoffToday )
			        )
			
			    VAR TrackedSites =
			        FILTER (
			            ALL ( Dim_Warehouse ),
			            CONTAINSSTRING ( Dim_Warehouse[Site_Name], "Kentucky" )
			                || CONTAINSSTRING ( Dim_Warehouse[Site_Name], "New Jersey" )
			                || CONTAINSSTRING ( Dim_Warehouse[Site_Name], "South Carolina" )
			        )
			
			    -- Numerator: all eligible dates in the week (Mon-Sun),
			    -- so weekend catch-up is included in the week's total
			    VAR RevenueIncluded =
			        CALCULATE (
			            [SalesAmount],
			            WeekDatesEligible,
			            KEEPFILTERS ( TrackedSites )
			        )
			
			    -- Denominator: only Mon-Fri dates with any records/orders
			    VAR WeekdayOrderDays =
			        FILTER (
			            WeekDatesEligible,
			            WEEKDAY ( Dim_Date[Date], 2 ) <= 5
			                && CALCULATE ( [Total Orders], KEEPFILTERS ( TrackedSites ) ) > 0
			        )
			
			    VAR SalesDaysIncluded =
			        COUNTROWS ( WeekdayOrderDays )
			
			    RETURN
			        DIVIDE ( RevenueIncluded, SalesDaysIncluded )
			)
			
			```
		lineageTag: a8e5b858-5f3f-4f23-9bca-03178303348d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced + Open Quantity – Selected Period' = ```
			
			VAR StartDate =
			    [BaseMonthStart]
			VAR EndDate =
			    [BaseMonthEnd]
			
			-- Only this month's invoiced amount (by invoice date)
			VAR ClosedAmtSelectedPeriod =
			    CALCULATE (
			        (SUM ( Fact_Customer_Invoices[Quantity_LBs])),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= StartDate &&
			            Dim_Date[Date] <= EndDate
			        )
			    )
			
			-- Open amount for all orders with requested ship date up to *end* of month
			VAR OpenAmtUpToPeriod_ReqShip =
			    CALCULATE (
			        SUM ( Fact_Sales[Quantity_LBs] ),
			        Fact_Sales[SalesLine_Status] IN { "Open", "Delivered" },
			        USERELATIONSHIP (
			            Fact_Sales[SalesLine_RequestedShipDateKey],
			            Dim_Date[DateKey]
			        ),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] <= EndDate        -- cumulative up to the end of the selected month
			        )
			    )
			
			RETURN
			    ClosedAmtSelectedPeriod + OpenAmtUpToPeriod_ReqShip
			
			```
		lineageTag: b0b76134-18d9-4a8f-931e-1383f40809cd

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced + Open Amount – Selected Period' = ```
			
			VAR StartDate =
			    [BaseMonthStart]
			VAR EndDate =
			    [BaseMonthEnd]
			
			-- Only this month's invoiced amount (by invoice date)
			VAR ClosedAmtSelectedPeriod =
			    CALCULATE (
			        (SUM ( Fact_Customer_Invoices[LineAmount]) + SUM(Fact_Customer_Invoices[Fuel_Charge]) + SUM(Fact_Customer_Invoices[Freight]) + SUM(Fact_Customer_Invoices[PLT_Brk_Ch]) + SUM(Fact_Customer_Invoices[Tariff_SC])),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= StartDate &&
			            Dim_Date[Date] <= EndDate
			        )
			    )
			
			-- Open amount for all orders with requested ship date up to *end* of month
			VAR OpenAmtUpToPeriod_ReqShip =
			    CALCULATE (
			        SUM ( Fact_Sales[Amount] ),
			        Fact_Sales[SalesLine_Status] IN { "Open", "Delivered" },
			        USERELATIONSHIP (
			            Fact_Sales[SalesLine_RequestedShipDateKey],
			            Dim_Date[DateKey]
			        ),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] <= EndDate        -- cumulative up to the end of the selected month
			        )
			    )
			
			RETURN
			    ClosedAmtSelectedPeriod + OpenAmtUpToPeriod_ReqShip
			
			```
		lineageTag: 3edaf6ff-90fe-45b8-a81e-8c8d00e57518

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced + Open Amount – Next Month' = ```
			
			VAR StartDate = [NextMonthStart]
			VAR EndDate   = [NextMonthEnd]
			VAR NullDate = DATE(2025,10,1)
			
			VAR MonthDates =
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= StartDate &&
			        Dim_Date[Date] <= EndDate
			    )
			
			VAR ClosedAmtNextMonth =
			    CALCULATE (
			         (SUM ( Fact_Customer_Invoices[LineAmount]) + SUM(Fact_Customer_Invoices[Fuel_Charge]) + SUM(Fact_Customer_Invoices[Freight]) + SUM(Fact_Customer_Invoices[PLT_Brk_Ch]) + SUM(Fact_Customer_Invoices[Tariff_SC])),
			        MonthDates
			    )
			
			VAR OpenAmtNextMonth_ReqShip =
			    CALCULATE (
			        SUM ( Fact_Sales[Amount] ),
			        Fact_Sales[SalesLine_Status] = "Open",
			        USERELATIONSHIP ( Fact_Sales[SalesLine_ShipDateKey], Dim_Date[DateKey] ),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= StartDate &&
			            Dim_Date[Date] <= EndDate
			        )
			    )
			RETURN
			    ClosedAmtNextMonth + OpenAmtNextMonth_ReqShip
			
			```
		lineageTag: 0652e6b8-abd6-498d-9788-c7a54dce2bd7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced + Open Quantity – Next Month' = ```
			
			VAR StartDate = [NextMonthStart]
			VAR EndDate   = [NextMonthEnd]
			VAR NullDate = DATE(2025,10,1)
			
			VAR MonthDates =
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= StartDate &&
			        Dim_Date[Date] <= EndDate
			    )
			
			VAR ClosedVolNextMonth =
			    CALCULATE (
			        (SUM ( Fact_Customer_Invoices[Quantity_LBs])),
			        MonthDates
			    )
			
			VAR OpenVolNextMonth_ReqShip =
			    CALCULATE (
			        SUM ( Fact_Sales[Quantity_LBs] ),
			        Fact_Sales[SalesLine_Status] = "Open",
			        USERELATIONSHIP ( Fact_Sales[SalesLine_ShipDateKey], Dim_Date[DateKey] ),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= StartDate &&
			            Dim_Date[Date] <= EndDate
			        )
			    )
			
			RETURN
			    ClosedVolNextMonth + OpenVolNextMonth_ReqShip
			
			```
		lineageTag: 6b2ab597-e1fa-4175-a05b-8e6ed4505a98

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced Amount – Selected Period' = ```
			
			
			VAR StartDate = [BaseMonthStart]
			VAR EndDate   = [BaseMonthEnd]
			VAR MonthDates =
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= StartDate &&
			        Dim_Date[Date] <= EndDate
			    )
			RETURN
			CALCULATE (
			    CALCULATE (
			        (SUM ( Fact_Customer_Invoices[LineAmount]) + SUM(Fact_Customer_Invoices[Fuel_Charge]) + SUM(Fact_Customer_Invoices[Freight]) + SUM(Fact_Customer_Invoices[PLT_Brk_Ch]) + SUM(Fact_Customer_Invoices[Tariff_SC])),
			        MonthDates
			))
			
			```
		lineageTag: 0adb4187-7ff2-4d8e-b034-598e74d64ac6

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced Quantity – Selected Period' = ```
			
			
			VAR StartDate = [BaseMonthStart]
			VAR EndDate   = [BaseMonthEnd]
			VAR MonthDates =
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= StartDate &&
			        Dim_Date[Date] <= EndDate
			    )
			RETURN
			CALCULATE (
			    CALCULATE (
			        (SUM ( Fact_Customer_Invoices[Quantity_LBs])),
			        MonthDates
			))
			
			```
		lineageTag: 70feb52b-235e-4432-b41c-633a288c43ee

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Avg Revenue (30-day)' = ```
			
			VAR RevenuePerMonth =
			    CALCULATE (
			        [SalesAmount],
			        ALLEXCEPT ( 'Dim_Date', 'Dim_Date'[MonthStartDate] )
			    )
			RETURN
			DIVIDE ( RevenuePerMonth, 30 )
			
			```
		lineageTag: 1451ce4f-a63d-446f-bd04-61b035341984

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Moving Avg (4 Weeks)' = ```
			
			VAR CurrentWeek =
			    MAX ( 'Dim_Date'[WeekStartDate] )
			VAR Last4Weeks =
			    TOPN (
			        4,
			        FILTER (
			            ALL ( 'Dim_Date'[WeekStartDate] ),
			            'Dim_Date'[WeekStartDate] <= CurrentWeek
			        ),
			        'Dim_Date'[WeekStartDate],
			        DESC
			    )
			RETURN
			AVERAGEX ( Last4Weeks, [Weekly Average Revenue (Sales Days)] )
			
			```
		lineageTag: b886cf22-be56-486c-896c-cfa905223f89

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Moving Avg (3 Months)' = ```
			
			VAR ThisWeek =
			    MAX ( 'Dim_Date'[WeekStartDate] )
			
			-- first day of the month 3 months before current month
			VAR WindowStart =
			    EOMONTH ( ThisWeek, -3 ) + 1
			
			VAR WeeksInRange =
			    FILTER (
			        ALL ( 'Dim_Date'[WeekStartDate] ),
			        'Dim_Date'[WeekStartDate] >= WindowStart
			            && 'Dim_Date'[WeekStartDate] <= ThisWeek
			    )
			RETURN
			AVERAGEX ( WeeksInRange, [Weekly Average Revenue (Sales Days)] )
			
			```
		lineageTag: 85be96cc-806a-42e6-98f5-fe3d313c6c4c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Show Moving Avg (4 wks)' =
			
			IF (
			    SELECTEDVALUE ( TrendLineOptions[TrendLineOption] )
			        = "Moving Average (4 weeks)",
			    [Moving Avg (4 Weeks)],
			    BLANK ()
			)
		lineageTag: 2dcc259e-3be9-4712-8d9a-da62f2c4c37e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Show Moving Avg (3 mths)' =
			
			IF (
			    SELECTEDVALUE ( TrendLineOptions[TrendLineOption] )
			        = "Moving Average (3 months)",
			    [Moving Avg (3 Months)],
			    BLANK ()
			)
		lineageTag: e34caa40-a22f-4cda-9a98-5138873a3567

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesAmountCard =
			
			COALESCE (
			    SUM ( Fact_Sales[Amount] ),
			    0
			)
		lineageTag: bf29c397-b23e-4aa8-a1c6-f6a76596b5e9

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YAxis Max – Weekly Avg Rev' = ```
			
			VAR MaxWeekly =
			    MAXX (
			        ALLSELECTED ( 'Dim_Date'[WeekStartDate] ),
			        [Weekly Average Revenue (Sales Days)]
			    )
			RETURN
			IF ( ISBLANK ( MaxWeekly ), BLANK (), MaxWeekly + 10000 )
			
			```
		lineageTag: 4a43d27a-7ddf-418e-a372-37c6b7336658

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YAxis Min – Weekly Avg Rev' = ```
			
			VAR MinWeekly =
			    MINX (
			        ALLSELECTED ( 'Dim_Date'[WeekStartDate] ),
			        [Weekly Average Revenue (Sales Days)]
			    )
			VAR RawMin = MinWeekly - 10000
			RETURN
			IF ( ISBLANK ( MinWeekly ), BLANK (), MAX ( 0, RawMin ) )
			
			```
		lineageTag: 3bc877d5-8e70-4925-819b-93bb109d70fe

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders (distinct)' = ```
			
			DISTINCTCOUNT ( Fact_Sales[Customer_Order_Number] )
			
			```
		formatString: 0
		lineageTag: 5b5c99dc-bad1-43a6-876e-147b5f1643ce

		changedProperty = Name

	measure 'OOO - Invoiced + Open Amount – Selected Period (confirmed)' = ```
			
			
			VAR StartDate = [BaseMonthStart]
			VAR EndDate   = [BaseMonthEnd]
			VAR NullDate = DATE(2025,10,1)
			
			VAR ClosedAmtSelectedPeriod =
			    CALCULATE (
			        (SUM ( Fact_Customer_Invoices[LineAmount]) + SUM(Fact_Customer_Invoices[Fuel_Charge]) + SUM(Fact_Customer_Invoices[Freight]) + SUM(Fact_Customer_Invoices[PLT_Brk_Ch]) + SUM(Fact_Customer_Invoices[Tariff_SC])),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= StartDate &&
			            Dim_Date[Date] <= EndDate
			        )
			    )
			
			VAR OpenAmtUpToPeriod_ConfirmedShip =
			    CALCULATE (
			        SUM ( Fact_Sales[Amount] ),
			        Fact_Sales[SalesLine_Status] IN { "Open", "Delivered" },
			        USERELATIONSHIP ( Fact_Sales[SalesLine_ShipDateKey], Dim_Date[DateKey] ),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= NullDate &&
			            Dim_Date[Date] <= EndDate
			        )
			    )
			
			RETURN
			    ClosedAmtSelectedPeriod + OpenAmtUpToPeriod_ConfirmedShip
			
			
			```
		lineageTag: db7320c5-4923-47a8-8bd3-70e67a2b2c7d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Confirmed Orders (distinct)' = ```
			
			VAR EndDate  = [BaseMonthEnd]
			VAR NullDate = DATE ( 2025, 10, 30 )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( Fact_Sales[Customer_Order_Number] ),
			    Fact_Sales[SalesLine_Status] = "Open",
			    USERELATIONSHIP ( Fact_Sales[SalesLine_ShipDateKey], Dim_Date[DateKey] ),
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= NullDate
			    )
			)
			
			```
		formatString: 0
		lineageTag: f5aeb1d7-7975-4d24-abb3-09b5e37a02a0

		changedProperty = Name

	measure 'OOO - Invoiced + Open Quantity – Selected Period (confirmed)' = ```
			
			
			VAR StartDate = [BaseMonthStart]
			VAR EndDate   = [BaseMonthEnd]
			VAR NullDate = DATE(2025,10,1)
			
			VAR ClosedQtySelectedPeriod =
			    CALCULATE (
			        (SUM ( Fact_Customer_Invoices[Quantity_LBs])),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= StartDate &&
			            Dim_Date[Date] <= EndDate
			        )
			    )
			
			VAR OpenQtyUpToPeriod_ConfirmedShip =
			    CALCULATE (
			        SUM ( Fact_Sales[Quantity_LBs] ),
			        Fact_Sales[SalesLine_Status] IN { "Open", "Delivered" },
			        USERELATIONSHIP ( Fact_Sales[SalesLine_ShipDateKey], Dim_Date[DateKey] ),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= NullDate &&
			            Dim_Date[Date] <= EndDate
			        )
			    )
			
			RETURN
			    ClosedQtySelectedPeriod + OpenQtyUpToPeriod_ConfirmedShip
			
			
			```
		lineageTag: 68785a05-4cff-4d56-81a5-aa163f7c4492

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Is Confirmed Open Order' = ```
			
			VAR EndDate  = [BaseMonthEnd]
			VAR NullDate = DATE ( 2025, 10, 1 )
			
			VAR ConfirmedRows =
			    CALCULATE (
			        COUNTROWS ( Fact_Sales ),
			        Fact_Sales[SalesLine_Status] = "Open",
			        USERELATIONSHIP ( Fact_Sales[SalesLine_ShipDateKey], Dim_Date[DateKey] ),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= NullDate
			                && Dim_Date[Date] <= EndDate
			        )
			    )
			RETURN
			IF ( ConfirmedRows > 0, 1, BLANK () )
			
			```
		formatString: 0
		lineageTag: 5787e8f6-20b3-4e86-900c-835a5e51a9d7

		changedProperty = Name

	measure 'OOO - Invoiced Freight – Selected Period' = ```
			
			
			VAR StartDate = [BaseMonthStart]
			VAR EndDate   = [BaseMonthEnd]
			
			VAR MonthDates =
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= StartDate &&
			        Dim_Date[Date] <= EndDate
			    )
			RETURN
			CALCULATE (
			    CALCULATE (
			        (SUM(Fact_Customer_Invoices[Freight])),
			        MonthDates
			))
			
			```
		lineageTag: 33256746-6ae0-42a6-9f5c-f25638cd3f2f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced Tariff – Selected Period' = ```
			
			
			VAR StartDate = [BaseMonthStart]
			VAR EndDate   = [BaseMonthEnd]
			VAR MonthDates =
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= StartDate &&
			        Dim_Date[Date] <= EndDate
			    )
			RETURN
			CALCULATE (
			    CALCULATE (
			        (SUM (Fact_Customer_Invoices[Tariff_SC])),
			        MonthDates
			))
			
			```
		lineageTag: c7505f52-d245-4d01-a525-3accd73504f4

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced Fuel – Selected Period' = ```
			
			
			VAR StartDate = [BaseMonthStart]
			VAR EndDate   = [BaseMonthEnd]
			VAR MonthDates =
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= StartDate &&
			        Dim_Date[Date] <= EndDate
			    )
			RETURN
			CALCULATE (
			    CALCULATE (
			        (SUM(Fact_Customer_Invoices[Fuel_Charge])),
			        MonthDates
			))
			
			```
		lineageTag: 9ef0167c-6099-48cd-a5fb-ac84044bd02e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OOO - Invoiced Pallet Break – Selected Period' = ```
			
			
			VAR StartDate = [BaseMonthStart]
			VAR EndDate   = [BaseMonthEnd]
			VAR MonthDates =
			    FILTER (
			        ALL ( Dim_Date ),
			        Dim_Date[Date] >= StartDate &&
			        Dim_Date[Date] <= EndDate
			    )
			RETURN
			CALCULATE (
			    CALCULATE (
			        (SUM(Fact_Customer_Invoices[PLT_Brk_Ch])),
			        MonthDates
			))
			
			```
		lineageTag: 151eff4b-4908-46a9-a118-67afd6aa6026

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Is Confirmed Open Order (All Dates)' =
			
			VAR EndDate  = [BaseMonthEnd]
			VAR NullDate = DATE ( 2025, 10, 30 )
			
			VAR IsDetailRow =
			    ISINSCOPE ( Fact_Sales[Customer_Order_Number] )
			
			VAR ConfirmedRows =
			    CALCULATE (
			        COUNTROWS ( Fact_Sales ),
			        Fact_Sales[SalesLine_Status] = "Open",
			        USERELATIONSHIP ( Fact_Sales[SalesLine_ShipDateKey], Dim_Date[DateKey] ),
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[Date] >= NullDate
			        )
			    )
			
			RETURN
			    IF (
			        NOT IsDetailRow,
			        BLANK (),
			        IF ( ConfirmedRows > 0, 1, BLANK () )
			    )
		formatString: 0
		lineageTag: db3d2d42-2fd0-4e95-af15-48038e2878bd

		changedProperty = Name

	measure 'Order Book Lifecycle Sales Amount' =
			
			VAR _Bucket =
			    SELECTEDVALUE ( 'Order Lifecycle Bucket'[LifecycleBucket] )
			RETURN
			SWITCH (
			    _Bucket,
			
			    "Invoiced",
			        CALCULATE (
			            [Gross Sales Activity Amount],
			            USERELATIONSHIP (
			                'Fact_Sales'[InvoiceDateKey],
			                'Dim_Date_Secondary'[DateKey]
			            ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] = "Invoiced" ),
			            KEEPFILTERS ( NOT ISBLANK ( 'Fact_Sales'[InvoiceDateKey] ) ),
			            KEEPFILTERS ( 'Fact_Sales'[InvoiceDateKey] <> 19000101 ),
			            KEEPFILTERS ( 'Fact_Sales'[InvoiceDateKey] <> 0 )
			        ),
			
			    "Open - Confirmed",
			        CALCULATE (
			            [Gross Sales Activity Amount],
			            USERELATIONSHIP (
			                'Fact_Sales'[SalesLine_ShipDateKey],
			                'Dim_Date_Secondary'[DateKey]
			            ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Invoiced" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Canceled" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Cancelled" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "None" ),
			            KEEPFILTERS ( NOT ISBLANK ( 'Fact_Sales'[SalesLine_ShipDateKey] ) ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_ShipDateKey] <> 19000101 ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_ShipDateKey] <> 0 )
			        ),
			
			    "Open - Requested",
			        CALCULATE (
			            [Gross Sales Activity Amount],
			            USERELATIONSHIP (
			                'Fact_Sales'[SalesLine_RequestedShipDateKey],
			                'Dim_Date_Secondary'[DateKey]
			            ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Invoiced" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Canceled" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Cancelled" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "None" ),
			            KEEPFILTERS (
			                ISBLANK ( 'Fact_Sales'[SalesLine_ShipDateKey] )
			                    || 'Fact_Sales'[SalesLine_ShipDateKey] = 19000101
			                    || 'Fact_Sales'[SalesLine_ShipDateKey] = 0
			            )
			        )
			)
		lineageTag: 818ab21f-1f64-4723-9274-c1ac0c715648

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Order Book Lifecycle Quantity LBs' =
			
			VAR _Bucket =
			    SELECTEDVALUE ( 'Order Lifecycle Bucket'[LifecycleBucket] )
			RETURN
			SWITCH (
			    _Bucket,
			
			    "Invoiced",
			        CALCULATE (
			            [Gross Sales Activity Quantity (LBs)],
			            USERELATIONSHIP (
			                'Fact_Sales'[InvoiceDateKey],
			                'Dim_Date_Secondary'[DateKey]
			            ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] = "Invoiced" ),
			            KEEPFILTERS ( NOT ISBLANK ( 'Fact_Sales'[InvoiceDateKey] ) ),
			            KEEPFILTERS ( 'Fact_Sales'[InvoiceDateKey] <> 19000101 ),
			            KEEPFILTERS ( 'Fact_Sales'[InvoiceDateKey] <> 0 )
			        ),
			
			    "Open - Confirmed",
			        CALCULATE (
			            [Gross Sales Activity Quantity (LBs)],
			            USERELATIONSHIP (
			                'Fact_Sales'[SalesLine_ShipDateKey],
			                'Dim_Date_Secondary'[DateKey]
			            ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Invoiced" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Canceled" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Cancelled" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "None" ),
			            KEEPFILTERS ( NOT ISBLANK ( 'Fact_Sales'[SalesLine_ShipDateKey] ) ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_ShipDateKey] <> 19000101 ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_ShipDateKey] <> 0 )
			        ),
			
			    "Open - Requested",
			        CALCULATE (
			            [Gross Sales Activity Quantity (LBs)],
			            USERELATIONSHIP (
			                'Fact_Sales'[SalesLine_RequestedShipDateKey],
			                'Dim_Date_Secondary'[DateKey]
			            ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Invoiced" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Canceled" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "Cancelled" ),
			            KEEPFILTERS ( 'Fact_Sales'[SalesLine_Status] <> "None" ),
			            KEEPFILTERS (
			                ISBLANK ( 'Fact_Sales'[SalesLine_ShipDateKey] )
			                    || 'Fact_Sales'[SalesLine_ShipDateKey] = 19000101
			                    || 'Fact_Sales'[SalesLine_ShipDateKey] = 0
			            )
			        )
			)
		lineageTag: dc929c6f-c7cc-4236-94fe-837a040ed7a4

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Sales Activity Amount' =
			
			CALCULATE (
			    SUM ( Fact_Sales[Amount] ),
			    KEEPFILTERS ( Fact_Sales[Amount] > 0 )
			)
		lineageTag: 1a739670-f223-4fc0-bd6a-7f2e2faba7f7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Sales Activity Quantity (LBs)' =
			
			CALCULATE (
			    SUM ( Fact_Sales[Quantity_LBs] ),
			    KEEPFILTERS ( Fact_Sales[Quantity_LBs] > 0 )
			)
		lineageTag: cd5aea0f-5a4e-43e9-a63b-440f9987e2e7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Order Lifecycle Metric' =
			
			VAR _Metric =
			    SELECTEDVALUE ( 'Order Book Metric Selector'[Metric] )
			RETURN
			SWITCH (
			    _Metric,
			    "Revenue", [Order Book Lifecycle Sales Amount],
			    "Quantity", [Order Book Lifecycle Quantity LBs],
			    BLANK ()
			)
		lineageTag: df74f200-5c5f-4803-a965-83324a9684bd

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Order Intake Metric' =
			
			VAR _Metric =
			    SELECTEDVALUE ( 'Order Book Metric Selector'[Metric] )
			RETURN
			SWITCH (
			    _Metric,
			    "Revenue", [Gross Sales Activity Amount],
			    "Quantity", [Gross Sales Activity Quantity (LBs)],
			    BLANK ()
			)
		lineageTag: d51369bb-6029-4c33-884e-89e55305566b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Negative Sales Activity Amount' =
			
			CALCULATE (
			    SUM ( Fact_Sales[Amount] ),
			    KEEPFILTERS ( Fact_Sales[Amount] < 0 )
			)
		lineageTag: c3250434-caeb-4b05-b210-6166c6f3e8b2

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Negative Sales Activity Quantity' =
			
			CALCULATE (
			    SUM ( Fact_Sales[Quantity_LBs] ),
			    KEEPFILTERS ( Fact_Sales[Quantity_LBs] < 0 )
			)
		lineageTag: 17274753-06ee-40ed-bdbf-029e182af7c7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Negative Sales Metric' =
			
			VAR _Metric =
			    SELECTEDVALUE ( 'Order Book Metric Selector'[Metric] )
			RETURN
			SWITCH (
			    _Metric,
			    "Revenue", [Negative Sales Activity Amount],
			    "Quantity", [Negative Sales Activity Quantity],
			    BLANK ()
			)
		lineageTag: 72234e8f-8044-4d53-8583-495dc642ad7f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RecordID
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 82da5ec2-1be8-4419-b073-ecb694c8b73d
		sourceLineageTag: RecordID
		summarizeBy: count
		sourceColumn: RecordID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CMPNY
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4ce5e4f5-7e12-4426-9a5a-822c7cfd5ad0
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		annotation SummarizationSetBy = Automatic

	column SalesLine_Status
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: 49bef406-dd2e-43c4-800e-94d2b7970867
		sourceLineageTag: SalesLine_Status
		summarizeBy: none
		sourceColumn: SalesLine_Status

		annotation SummarizationSetBy = Automatic

	column DATE
		dataType: dateTime
		isHidden
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: f2775153-171a-4872-8887-9dd3116e0ba5
		sourceLineageTag: DATE
		summarizeBy: none
		sourceColumn: DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DATEKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 348288bd-6cb3-449d-ac04-b4d32a104455
		sourceLineageTag: DATEKey
		summarizeBy: none
		sourceColumn: DATEKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column OrderDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: f89cc25a-c207-45f4-9930-a012c2969903
		sourceLineageTag: OrderDate
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column StandardCostKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ee8100f8-676d-43e7-98f3-c427b58571c5
		sourceLineageTag: StandardCostKey
		summarizeBy: none
		sourceColumn: StandardCostKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 00ae3935-5da3-4cce-b333-4e85c22d4c75
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SiteKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 964978c9-391a-4c25-a9c3-e40139e6a3e7
		sourceLineageTag: SiteKey
		summarizeBy: none
		sourceColumn: SiteKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: f9ae8d26-d326-4961-87f6-a61f28920d68
		sourceLineageTag: SalesLine_EmployeeKey
		summarizeBy: none
		sourceColumn: SalesLine_EmployeeKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CustAcct_EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 16194012-1ae6-4a74-b055-1fd5cd660a97
		sourceLineageTag: CustAcct_EmployeeKey
		summarizeBy: none
		sourceColumn: CustAcct_EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		sourceProviderType: varchar(50)
		lineageTag: 94c4448e-33c9-4156-b592-9f2fba1a9104
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column HistoricCustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 17918b3b-83a9-469e-a857-b67bec39bb25
		sourceLineageTag: HistoricCustomerKey
		summarizeBy: none
		sourceColumn: HistoricCustomerKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CustomerKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4998621c-3621-41fc-a34d-1497e1fdb857
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HistoricProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 34caf21e-cd92-442e-aaee-fc52c8fa6365
		sourceLineageTag: HistoricProductKey
		summarizeBy: none
		sourceColumn: HistoricProductKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 12eccb20-fd5a-4ea5-9159-fb12378d3413
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Returned_Amount
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 3e50970c-ac1c-42f2-9537-08341a661a8e
		sourceLineageTag: Returned_Amount
		summarizeBy: sum
		sourceColumn: Returned_Amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesLine_Salesman_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b6b13e51-42d7-4737-892f-38e026f64ccc
		sourceLineageTag: SalesLine_Salesman_ID
		summarizeBy: none
		sourceColumn: SalesLine_Salesman_ID

		annotation SummarizationSetBy = Automatic

	column Customer_Salesman_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 17e030fe-b711-4935-ae0b-e663029b9a4e
		sourceLineageTag: Customer_Salesman_ID
		summarizeBy: none
		sourceColumn: Customer_Salesman_ID

		annotation SummarizationSetBy = Automatic

	column Volume_UoM
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4852dc7d-660d-40b6-bc17-30b8dca697ff
		sourceLineageTag: Volume_UoM
		summarizeBy: none
		sourceColumn: Volume_UoM

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 63105133-c704-4e41-a475-95e99890a01e
		sourceLineageTag: Price
		summarizeBy: sum
		sourceColumn: Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ba0a4a32-e44c-474a-8845-2687827481cb
		sourceLineageTag: Currency
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 63cbbb7a-6a2b-4e82-a182-4f0beadbd1cb
		sourceLineageTag: Amount
		summarizeBy: sum
		sourceColumn: Amount

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Amount_Currency
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7bc5f4ac-6991-48b0-be3e-55baf76af026
		sourceLineageTag: Amount_Currency
		summarizeBy: none
		sourceColumn: Amount_Currency

		annotation SummarizationSetBy = Automatic

	column Returned_Quantity
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 2aa4fe38-44ef-47e4-a266-8719d4430781
		sourceLineageTag: Returned_Quantity
		summarizeBy: sum
		sourceColumn: Returned_Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InvoiceNo
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b679adb6-ec0f-4aaa-9858-13b84efdaecb
		sourceLineageTag: InvoiceNo
		summarizeBy: none
		sourceColumn: InvoiceNo

		annotation SummarizationSetBy = Automatic

	column Customer_Order_Number
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: d5351af2-1c8f-4644-9a23-4820e299bd7b
		sourceLineageTag: Customer_Order_Number
		summarizeBy: none
		sourceColumn: Customer_Order_Number

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 76a384dc-f00b-4e33-b3e1-dc1be71780c4
		sourceLineageTag: Quantity
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity_UoM
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 379d7cbf-2b44-4953-aa97-25ebfd16008c
		sourceLineageTag: Quantity_UoM
		summarizeBy: none
		sourceColumn: Quantity_UoM

		annotation SummarizationSetBy = Automatic

	column Quantity_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: e8eb2bc4-7ad1-4892-b7d8-aa25f4a8754f
		sourceLineageTag: Quantity_LBs
		summarizeBy: sum
		sourceColumn: Quantity_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: f722110c-dad1-464e-94e8-ab4d3516abb2
		sourceLineageTag: Volume
		summarizeBy: sum
		sourceColumn: Volume

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InvoiceDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 6a97bd96-1432-41d8-a1b6-e8ae0d7f7e49
		sourceLineageTag: InvoiceDateKey
		summarizeBy: none
		sourceColumn: InvoiceDateKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column Legal_Entity_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 8fa4eb6e-bad1-4c7a-a0e4-1d0e75c04dd8
		sourceLineageTag: Legal_Entity_ID
		summarizeBy: none
		sourceColumn: Legal_Entity_ID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: b95d366c-ba4c-4f21-a1f6-7a1f7de42144
		sourceLineageTag: CustomerID
		summarizeBy: none
		sourceColumn: CustomerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InvoiceAccount
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ddb0b212-fc2c-4a09-84e3-ffc01f8c6915
		sourceLineageTag: InvoiceAccount
		summarizeBy: none
		sourceColumn: InvoiceAccount

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 4e056096-5793-434a-9529-794ab88e9557
		sourceLineageTag: ProductID
		summarizeBy: none
		sourceColumn: ProductID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CPCID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b4769b41-68f0-4b76-97c8-f96225e0b32b
		sourceLineageTag: CPCID
		summarizeBy: none
		sourceColumn: CPCID

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: cb198040-205e-46e1-b35d-4687280ab434
		sourceLineageTag: OrderDateKey
		summarizeBy: none
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_RequestedShipDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: cd1a51b2-38a3-4a69-85de-0ec70f936bb5
		sourceLineageTag: SalesLine_RequestedShipDate
		summarizeBy: none
		sourceColumn: SalesLine_RequestedShipDate

		annotation SummarizationSetBy = Automatic

	column SalesLine_RequestedShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 95fe7cd0-3179-448d-9dc6-fbd94ef9d733
		sourceLineageTag: SalesLine_RequestedShipDateKey
		summarizeBy: none
		sourceColumn: SalesLine_RequestedShipDateKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column SalesLine_ShipDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 562288e5-06c8-48a1-9eb0-11c7582f2aed
		sourceLineageTag: SalesLine_ShipDate
		summarizeBy: none
		sourceColumn: SalesLine_ShipDate

		annotation SummarizationSetBy = Automatic

	column SalesLine_ShipDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2c0a8aa3-21ff-4835-9050-7f1e47d38914
		sourceLineageTag: SalesLine_ShipDateKey
		summarizeBy: none
		sourceColumn: SalesLine_ShipDateKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column InvoiceDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: d37fc2c7-7a2a-4244-86cd-5ee96aef380b
		sourceLineageTag: InvoiceDate
		summarizeBy: none
		sourceColumn: InvoiceDate

		annotation SummarizationSetBy = Automatic

	column WarehouseKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c52a725d-9071-4baa-b245-0cbf733bd71e
		sourceLineageTag: WarehouseKey
		summarizeBy: none
		sourceColumn: WarehouseKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesLine_DeliveryDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 82df37bb-64a9-4bc9-9977-4eb1a107130b
		sourceLineageTag: SalesLine_DeliveryDate
		summarizeBy: none
		sourceColumn: SalesLine_DeliveryDate

		annotation SummarizationSetBy = Automatic

	column SalesLine_DeliveryDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: bcd76b23-ae37-4a10-b8db-dbb8c32319bc
		sourceLineageTag: SalesLine_DeliveryDateKey
		summarizeBy: none
		sourceColumn: SalesLine_DeliveryDateKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column OnHold
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 291c0373-f551-45c2-a452-66aff5846164
		sourceLineageTag: OnHold
		summarizeBy: sum
		sourceColumn: OnHold

		annotation SummarizationSetBy = Automatic

	column OrderOnHold
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: ae9ad833-a410-458e-8eaf-4d25e2380654
		sourceLineageTag: OrderOnHold
		summarizeBy: none
		sourceColumn: OrderOnHold

		annotation SummarizationSetBy = Automatic

	column HoldCode
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 38666d84-0432-4156-915e-4d9f5d9f93bc
		sourceLineageTag: HoldCode
		summarizeBy: none
		sourceColumn: HoldCode

		annotation SummarizationSetBy = Automatic

	column HoldReasonCode
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 55e556f3-c496-4510-8beb-b12382db52dc
		sourceLineageTag: HoldReasonCode
		summarizeBy: none
		sourceColumn: HoldReasonCode

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: double
		sourceProviderType: decimal(38, 16)
		lineageTag: f9e4d1c8-3f12-4075-92bd-c4485ba2d09d
		sourceLineageTag: SalesOrderLineNumber
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesLineCreatedDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: bd96cb43-bf1e-4570-8bea-bb4ebcd94d97
		sourceLineageTag: SalesLineCreatedDate
		summarizeBy: none
		sourceColumn: SalesLineCreatedDate

		annotation SummarizationSetBy = Automatic

	column SalesLineCreatedDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: d43d73c8-8e0f-4928-a889-56b38d85b411
		sourceLineageTag: SalesLineCreatedDateKey
		summarizeBy: none
		sourceColumn: SalesLineCreatedDateKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column MarketSegmentationKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: b0b3e7be-065a-433c-9a56-c26b9679b439
		sourceLineageTag: MarketSegmentationKey
		summarizeBy: none
		sourceColumn: MarketSegmentationKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column SalesTaker_EmployeeKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: e150e161-48aa-42a4-8521-d9a14c389e5a
		sourceLineageTag: SalesTaker_EmployeeKey
		summarizeBy: count
		sourceColumn: SalesTaker_EmployeeKey

		annotation SummarizationSetBy = Automatic

	column PurchaseOrderFormNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 511da203-8ae9-4350-bbaa-43f05428e266
		sourceLineageTag: PurchaseOrderFormNumber
		summarizeBy: none
		sourceColumn: PurchaseOrderFormNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: cdf6e3d1-c27f-4a15-8b63-00601c9a4bda
		sourceLineageTag: SalesOrderKey
		summarizeBy: count
		sourceColumn: SalesOrderKey

		annotation SummarizationSetBy = Automatic

	column DeliveryAddressKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4e410114-9df2-4ea6-81ef-35acc7490d37
		sourceLineageTag: DeliveryAddressKey
		summarizeBy: count
		sourceColumn: DeliveryAddressKey

		annotation SummarizationSetBy = Automatic

	column CPCID2
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c71d44e6-f920-4c7f-be76-21bb4b80e97c
		sourceLineageTag: CPCID2
		summarizeBy: none
		sourceColumn: CPCID2

		annotation SummarizationSetBy = Automatic

	column ProductID2
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 691c46c4-5ebe-4ec5-a3ab-d3ac4fcabff1
		sourceLineageTag: ProductID2
		summarizeBy: none
		sourceColumn: ProductID2

		annotation SummarizationSetBy = Automatic

	column IsPhantom2
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: d78b64a4-cc95-4e7e-9a25-887aa9a8df0b
		sourceLineageTag: IsPhantom2
		summarizeBy: none
		sourceColumn: IsPhantom2

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_Sales
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

