table Fact_Inventory_Snapshot
	lineageTag: 4c94b953-daaa-481a-8477-ff2bb2697be6
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_Inventory_Snapshot]

	measure 'Available for Reservation' = (([Posted Quantity] + [Received Qty] - [Deducted Qty] + [Registered Qty] - [Picked Qty]) - [Physical Reserved])
		lineageTag: ff152987-6b06-4759-a9f4-19196c3121d5

		changedProperty = Name

	measure 'Available for Reservation LBs' = (([Posted Quantity LBs] + [Received Qty LBs] - [Deducted Qty LBs] + [Registered Qty LBs] - [Picked Qty LBs]) - [Physical Reserved LBs])
		lineageTag: 3855a1cc-11d4-469f-ae67-d4d1e24d420c

		changedProperty = Name

	measure 'Available Physical' = SUM(Fact_Inventory_Snapshot[availphysical])
		lineageTag: 1c333752-6631-43b9-a856-80dc3fd6dd8d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Available Physical LBs' = SUM(Fact_Inventory_Snapshot[availphysical_LBs])
		lineageTag: c80d7dc9-02c2-4b10-8c55-c15c275616d5

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deducted Qty' = SUM(Fact_Inventory_Snapshot[deducted])
		lineageTag: 11c8e566-f04c-499b-8760-ddfd9b5aa42d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deducted Qty LBs' = SUM(Fact_Inventory_Snapshot[deducted_LBs])
		lineageTag: 9e608690-dbb7-40c5-a808-68d80ccfb77d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Order' = SUM(Fact_Inventory_Snapshot[onorder])
		lineageTag: 22d1224f-e453-4c89-bcff-5d7d2c48535c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Order LBs' = SUM(Fact_Inventory_Snapshot[onorder_LBs])
		lineageTag: aea4c34d-ae8f-4a65-8b7c-c6d0900cb491

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ordered Qty' = SUM(Fact_Inventory_Snapshot[ordered])
		lineageTag: 971a56b9-f9ef-411f-b84b-70cb2117385f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ordered Qty LBs' = SUM(Fact_Inventory_Snapshot[ordered_LBs])
		lineageTag: bedd6390-c0fc-48e9-b80e-141717b0739f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ordered Reserved' = SUM(Fact_Inventory_Snapshot[reservordered])
		lineageTag: 8ea53f41-21c9-40e0-851a-2a4a847fc052

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ordered Reserved LBs' = SUM(Fact_Inventory_Snapshot[reservordered_LBs])
		lineageTag: 54a6abb6-250a-47a6-aef4-56c228a03d17

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Inventory' = SUM(Fact_Inventory_Snapshot[physicalinvent])
		lineageTag: 90f43f67-26a9-4067-84dc-c1ead121c605

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Inventory LBs' = SUM(Fact_Inventory_Snapshot[physicalinvent_LBs])
		lineageTag: 9f836e13-dd3c-4ac7-8257-ba963b77864f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Reserved' = SUM(Fact_Inventory_Snapshot[reservphysical])
		lineageTag: a15a5708-7877-448f-b60a-6eeb14da3b10

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Reserved LBs' = SUM(Fact_Inventory_Snapshot[reservphysical_LBs])
		lineageTag: f3c1ee13-b7b0-44df-b45c-b4984e1e36c7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Picked Qty' = SUM(Fact_Inventory_Snapshot[picked])
		lineageTag: edff1894-9fd9-4c22-ae4a-17d127d55247

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Picked Qty LBs' = SUM(Fact_Inventory_Snapshot[picked_LBs])
		lineageTag: 1ee43ab9-3b56-48c9-b561-372f64687eaf

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Posted Quantity' = SUM(Fact_Inventory_Snapshot[postedqty])
		lineageTag: 33a1f75b-d20b-4fa5-a167-3598b919d37a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Posted Quantity LBs' = SUM(Fact_Inventory_Snapshot[postedqty_LBs])
		lineageTag: 018964fc-aad4-4a8d-be09-d4e607debbf2

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Received Qty' = SUM(Fact_Inventory_Snapshot[received])
		lineageTag: 3dc9dc6f-7114-4a74-9059-ec7527bb403d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Received Qty LBs' = SUM(Fact_Inventory_Snapshot[received_LBs])
		lineageTag: a6060db8-2bd5-4170-93ee-43d8956e9eb0

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Registered Qty' = SUM(Fact_Inventory_Snapshot[registered])
		lineageTag: 510f148d-59d6-4156-b8fe-60d968c41e2e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Registered Qty LBs' = SUM(Fact_Inventory_Snapshot[registered_LBs])
		lineageTag: de549284-98ae-4353-a02f-f24fad2ca734

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Available' = ([Available for Reservation] + [Ordered Qty] - [On Order] - [Ordered Reserved])
		lineageTag: 23996d66-c731-4c3e-a307-459c6cad6489

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Available LBs' = ([Available for Reservation LBs] + [Ordered Qty LBs] - [On Order LBs] - [Ordered Reserved LBs])
		lineageTag: 504a2b16-bfa3-4f29-8512-9fd7076f7fda

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders (IS)' = COUNTROWS(Fact_Inventory_Snapshot)
		formatString: 0
		lineageTag: 959908f7-f411-4077-a8cf-3721147853c7

		changedProperty = Name

	measure 'Posted Avg Cost / LB' =
			
			VAR _Qty =
			    [Posted Quantity LBs]
			VAR _Cost =
			    [TotalCostAmount_OnH_Pos]
			RETURN
			    DIVIDE ( _Cost, _Qty )
		lineageTag: cd1903cf-75b0-4ce8-b75a-234e1a5810ce

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Avg Cost / LB' =
			
			VAR _Qty =
			    [Physical Inventory LBs]
			VAR _Cost =
			    [TotalCostAmount_OnH_Phy]
			RETURN
			    DIVIDE ( _Cost, _Qty )
		lineageTag: 4356408b-97ca-418b-833e-5800a7dd868b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMPNY
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: a7d6e78d-2c1f-47fa-a226-026c53dd4943
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Site_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c47bb511-e90c-4801-b4a0-eec14cc034bb
		sourceLineageTag: Site_ID
		summarizeBy: none
		sourceColumn: Site_ID

		annotation SummarizationSetBy = Automatic

	column Warehouse_ID
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: e2691931-52b0-430b-b03e-cccc30a4dc6a
		sourceLineageTag: Warehouse_ID
		summarizeBy: none
		sourceColumn: Warehouse_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Snapshot_Date
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 685de345-1b7c-4fcf-9c3b-66908088d988
		sourceLineageTag: Snapshot_Date
		summarizeBy: none
		sourceColumn: Snapshot_Date

		annotation SummarizationSetBy = Automatic

	column Snapshot_Date_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: ae04cccb-577c-4a56-9ad1-036f9e24ce27
		sourceLineageTag: Snapshot_Date_Key
		summarizeBy: none
		sourceColumn: Snapshot_Date_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: ef53e908-fff9-44f6-b48e-c5e79b9e1321
		sourceLineageTag: Product_ID
		summarizeBy: none
		sourceColumn: Product_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: f71b6e96-a66b-4fbf-b89e-615f5aaf3cbc
		sourceLineageTag: ProductName
		summarizeBy: none
		sourceColumn: ProductName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductSearchName
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: eac4bf16-0c13-490d-b77f-dcebf6f7f6e6
		sourceLineageTag: ProductSearchName
		summarizeBy: none
		sourceColumn: ProductSearchName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Phantom_Product
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 1808abd8-f001-4974-bd8c-c3e64ba8b579
		sourceLineageTag: Phantom_Product
		summarizeBy: none
		sourceColumn: Phantom_Product

		annotation SummarizationSetBy = Automatic

	column Inventory_UoM
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b2b16a5a-e310-44f4-8710-079db51c0b66
		sourceLineageTag: Inventory_UoM
		summarizeBy: none
		sourceColumn: Inventory_UoM

		annotation SummarizationSetBy = Automatic

	column inventstatusid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9fe5fea9-592c-447b-aed0-1b56a3335b15
		sourceLineageTag: inventstatusid
		summarizeBy: none
		sourceColumn: inventstatusid

		annotation SummarizationSetBy = Automatic

	column wmslocationid
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 715957ed-cf2d-4eb6-abc2-1a7184bd8e22
		sourceLineageTag: wmslocationid
		summarizeBy: none
		sourceColumn: wmslocationid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column arrived
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: a1b5073a-ed91-44fc-b2ca-92e68da4af22
		sourceLineageTag: arrived
		summarizeBy: sum
		sourceColumn: arrived

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column availordered
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: c75f9157-76d6-4fbc-a670-5982709052f4
		sourceLineageTag: availordered
		summarizeBy: sum
		sourceColumn: availordered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column availphysical
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: a575f224-7d7e-4269-92bb-937d923f6cc1
		sourceLineageTag: availphysical
		summarizeBy: sum
		sourceColumn: availphysical

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deducted
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 2b6444cc-979e-4429-8dc1-b781c0ec0980
		sourceLineageTag: deducted
		summarizeBy: sum
		sourceColumn: deducted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column onorder
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: aee5d818-5429-4d69-8ba4-896c8754a345
		sourceLineageTag: onorder
		summarizeBy: sum
		sourceColumn: onorder

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ordered
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 6875c271-a58f-448d-b1bf-33ecf5fc29fd
		sourceLineageTag: ordered
		summarizeBy: sum
		sourceColumn: ordered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column physicalinvent
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 508fe511-efd5-4a37-ba8c-21382171b641
		sourceLineageTag: physicalinvent
		summarizeBy: sum
		sourceColumn: physicalinvent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column picked
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: d8260aa1-3271-4720-ba36-e4e914f9246d
		sourceLineageTag: picked
		summarizeBy: sum
		sourceColumn: picked

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column postedqty
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 44d9519c-eeb9-407a-bed1-25236e579547
		sourceLineageTag: postedqty
		summarizeBy: sum
		sourceColumn: postedqty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column received
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 7a9498fb-48a3-4f53-b38b-2a0dd9df1901
		sourceLineageTag: received
		summarizeBy: sum
		sourceColumn: received

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column registered
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: df219bfe-9479-4a98-8e72-0df0669b21fb
		sourceLineageTag: registered
		summarizeBy: sum
		sourceColumn: registered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reservordered
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: dce6e674-ebfe-4061-b95f-6b8e867aefcc
		sourceLineageTag: reservordered
		summarizeBy: sum
		sourceColumn: reservordered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reservphysical
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: cbbb9322-57eb-44f9-977a-9554e8f865c4
		sourceLineageTag: reservphysical
		summarizeBy: sum
		sourceColumn: reservphysical

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column postedcostamount
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 282040c2-39c0-4ec3-a28f-8b03fb83b962
		sourceLineageTag: postedcostamount
		summarizeBy: sum
		sourceColumn: postedcostamount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column arrived_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: a4e7a13e-6ae9-4f70-8235-4a00690e1b63
		sourceLineageTag: arrived_LBs
		summarizeBy: sum
		sourceColumn: arrived_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column availordered_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 7817b3ef-f2a5-4000-a88c-0d3e313fbf92
		sourceLineageTag: availordered_LBs
		summarizeBy: sum
		sourceColumn: availordered_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column availphysical_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: ee49f2d6-7495-4df3-897b-307e95d8d3b4
		sourceLineageTag: availphysical_LBs
		summarizeBy: sum
		sourceColumn: availphysical_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deducted_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: b275b646-0d00-4f51-91cc-a821487e0bfe
		sourceLineageTag: deducted_LBs
		summarizeBy: sum
		sourceColumn: deducted_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column onorder_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 24e8c42f-a7e6-4479-83e4-c705549563c8
		sourceLineageTag: onorder_LBs
		summarizeBy: sum
		sourceColumn: onorder_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ordered_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 4f6506e6-11a8-4d20-a053-bd82fa2839e3
		sourceLineageTag: ordered_LBs
		summarizeBy: sum
		sourceColumn: ordered_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column physicalinvent_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: b04f64ac-5949-461c-87f8-db84402bc96a
		sourceLineageTag: physicalinvent_LBs
		summarizeBy: sum
		sourceColumn: physicalinvent_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column picked_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 9c638e22-14c1-4e41-b509-d119a7d54aeb
		sourceLineageTag: picked_LBs
		summarizeBy: sum
		sourceColumn: picked_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column postedqty_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 9f2407b1-de0b-48c1-8148-083dcc2992ac
		sourceLineageTag: postedqty_LBs
		summarizeBy: sum
		sourceColumn: postedqty_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column received_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: c0005cdc-94de-4dd5-8dc6-d593700f9ae7
		sourceLineageTag: received_LBs
		summarizeBy: sum
		sourceColumn: received_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column registered_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 7a4fdee4-31a1-4bd6-b9fb-71224437f702
		sourceLineageTag: registered_LBs
		summarizeBy: sum
		sourceColumn: registered_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reservordered_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 32063f83-2b1e-4677-b960-0ad3228895d2
		sourceLineageTag: reservordered_LBs
		summarizeBy: sum
		sourceColumn: reservordered_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reservphysical_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 0a099dd5-2766-496a-9659-996b920af058
		sourceLineageTag: reservphysical_LBs
		summarizeBy: sum
		sourceColumn: reservphysical_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column primaryvendorid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 0f8ee844-0a63-4ca2-bc95-55bd97e10a21
		sourceLineageTag: primaryvendorid
		summarizeBy: none
		sourceColumn: primaryvendorid

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		sourceProviderType: varchar(6)
		lineageTag: dd2e2bf4-c484-4194-8781-addd67a3cb4f
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 81337646-2ee9-4086-a055-b52470a3d677
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SiteKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 215204fd-8929-4bd5-bcc5-5c0d2578ad00
		sourceLineageTag: SiteKey
		summarizeBy: none
		sourceColumn: SiteKey

		annotation SummarizationSetBy = Automatic

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5cc942bf-1167-49d2-8736-632b06765708
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WarehouseKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ca410cdc-3352-409a-ae2a-488f3a552f2b
		sourceLineageTag: WarehouseKey
		summarizeBy: none
		sourceColumn: WarehouseKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VendorKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 81621e3c-84fb-43bf-81d2-f86d588851d8
		sourceLineageTag: VendorKey
		summarizeBy: count
		sourceColumn: VendorKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inventorySnapshotKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 16b1d93e-3abb-4006-8707-a5b0c683c5a8
		sourceLineageTag: inventorySnapshotKey
		summarizeBy: count
		sourceColumn: inventorySnapshotKey

		annotation SummarizationSetBy = Automatic

	column StandardCostKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 33999cde-5499-4a9b-8fc7-4de93e2c0e7d
		sourceLineageTag: StandardCostKey
		summarizeBy: none
		sourceColumn: StandardCostKey

		annotation SummarizationSetBy = Automatic

	partition Fact_Inventory_Snapshot = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_Inventory_Snapshot
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

