CREATE TABLE [dbo].[legacy_tbl_DIM_CPC] (

	[CPCID] varchar(50) NULL, 
	[CustomerID] varchar(50) NULL, 
	[Office] varchar(50) NULL, 
	[Customer No] varchar(50) NULL, 
	[Ship To No] varchar(50) NULL, 
	[ProductCode] varchar(50) NULL, 
	[ProductName] varchar(50) NULL, 
	[CPCStatus] varchar(50) NULL, 
	[WonReason] varchar(50) NULL, 
	[LostReason] varchar(50) NULL, 
	[CPCClassification] varchar(50) NULL, 
	[OriginalOPID] varchar(50) NULL, 
	[CPCStage] varchar(50) NULL, 
	[CPC Descriptive] varchar(max) NULL, 
	[CPCType] varchar(50) NULL, 
	[FirstOrderDate] varchar(50) NULL, 
	[MostRecentOrderDate] varchar(50) NULL, 
	[MostRecentPrice] varchar(50) NULL, 
	[Currency] varchar(50) NULL, 
	[INCOTerms] varchar(50) NULL, 
	[Application] varchar(50) NULL, 
	[ApplicationDefinition] varchar(50) NULL, 
	[ApplicationDescription] varchar(50) NULL, 
	[DesiredCharacteristics] varchar(50) NULL, 
	[RegulatoryRequirements] varchar(50) NULL, 
	[ListPrice] varchar(50) NULL, 
	[CurrentPrice] varchar(50) NULL, 
	[CPCTier] varchar(50) NULL, 
	[EstimatedAnnualVolume] int NULL, 
	[EAVUnitOfMeasure] varchar(50) NULL, 
	[EstimatedAnnualRevenue] varchar(50) NULL, 
	[EARCurrency] varchar(50) NULL, 
	[CPCIndustry] varchar(50) NULL, 
	[CPCIndustrySubSegment] varchar(50) NULL, 
	[RecordEffectiveStartDate] datetime2(6) NULL, 
	[RecordEffectiveEndDate] datetime2(6) NULL, 
	[RecordStatus] int NULL, 
	[Source] varchar(10) NULL, 
	[CPC_SID] int NULL
);