CREATE TABLE [dbo].[mtbl_EDW_DIM_PurchaseOrder] (

	[PurchaseOrderKey] bigint NULL, 
	[CMPNY] varchar(8000) NULL, 
	[PurchaseOrderNumber] varchar(8000) NULL, 
	[PurchaseOrderName] varchar(8000) NULL, 
	[VendorAccount] varchar(8000) NULL, 
	[InvoiceVendorAccount] varchar(8000) NULL, 
	[PaymentTerms] varchar(8000) NULL, 
	[PaymentTermsDesc] varchar(8000) NULL, 
	[PaymentTermsNumOfDays] bigint NULL, 
	[VendorReference] varchar(8000) NULL, 
	[currencycode] varchar(8000) NULL, 
	[isencumbrancerequired] bigint NULL, 
	[EncumberanceRequiredYN] varchar(7) NULL, 
	[purchstatus] bigint NULL, 
	[PurchStatusDesc] varchar(8) NULL, 
	[returnreasoncodeid] varchar(8000) NULL, 
	[ReturnReasonDesc] varchar(8000) NULL, 
	[ReturnReasonGroupDesc] varchar(8000) NULL, 
	[createddatetime] datetime2(6) NULL, 
	[Warehouse] varchar(8000) NULL, 
	[SiteID] varchar(8000) NULL, 
	[deliveryname] varchar(8000) NULL, 
	[itembuyergroupid] varchar(8000) NULL, 
	[purchpoolid] varchar(8000) NULL, 
	[PurchPoolName] varchar(8000) NULL, 
	[RequestorPersonnelNumber] varchar(8000) NULL, 
	[RequestorName] varchar(8000) NULL, 
	[POPlacerPersonnelNumber] varchar(8000) NULL, 
	[POPlacerName] varchar(8000) NULL, 
	[dlvterm] varchar(8000) NULL, 
	[dlvmode] varchar(8000) NULL, 
	[minDeliveryDate] datetime2(6) NULL, 
	[maxDeliveryDate] datetime2(6) NULL, 
	[Source] varchar(6) NOT NULL, 
	[RecordEffectiveStartDate] datetime2(3) NULL, 
	[RecordEffectiveEndDate] datetime2(3) NULL, 
	[RecordStatus] int NULL
);