CREATE TABLE [dbo].[mtbl_EDW_Fact_SupplyChain_PickList] (

	[CMPNY] varchar(8000) NULL, 
	[ProdId] varchar(8000) NULL, 
	[itemid] varchar(8000) NULL, 
	[JournalId] varchar(8000) NULL, 
	[LotID] varchar(8000) NULL, 
	[transdate] datetime2(6) NULL, 
	[resource] varchar(8000) NULL, 
	[bomproposal] decimal(38,6) NULL, 
	[bomconsump] decimal(38,6) NULL, 
	[bomunitid] varchar(8000) NULL, 
	[endconsump] bigint NULL, 
	[endconsump_$label] varchar(3) NULL, 
	[matchid] varchar(8000) NULL, 
	[voucher] varchar(8000) NULL, 
	[bomscrap] decimal(38,6) NULL, 
	[errorcause] bigint NULL, 
	[errorcause_$label] varchar(14) NULL, 
	[inventproposal] decimal(38,6) NULL, 
	[inventconsump] decimal(38,6) NULL, 
	[InventoryNumber] varchar(8000) NULL, 
	[oprnum] bigint NULL, 
	[position] varchar(8000) NULL, 
	[inventdimid] varchar(8000) NULL, 
	[journaltype_$Label] varchar(24) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[ProductionBatchOrderKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[BatchKey] bigint NOT NULL, 
	[RouteKey] bigint NOT NULL
);