CREATE TABLE [dbo].[vw_crm_Activity] (

	[USERID] varchar(8) NULL, 
	[ACCOUNTNO] varchar(20) NULL, 
	[SRECTYPE] varchar(1) NULL, 
	[RECTYPE] varchar(10) NULL, 
	[ONDATE] datetime2(3) NULL, 
	[ONTIME] varchar(5) NULL, 
	[ACTVCODE] varchar(3) NULL, 
	[RESULTCODE] varchar(3) NULL, 
	[STATUS] varchar(2) NULL, 
	[DURATION] varchar(14) NULL, 
	[UNITS] varchar(20) NULL, 
	[REF] varchar(80) NULL, 
	[LINKRECID] varchar(15) NULL, 
	[LOPRECID] varchar(15) NULL, 
	[CREATEBY] varchar(8) NULL, 
	[CREATEON] datetime2(3) NULL, 
	[CREATEAT] varchar(5) NULL, 
	[LASTUSER] varchar(8) NULL, 
	[LASTDATE] datetime2(3) NULL, 
	[LASTTIME] varchar(5) NULL, 
	[recid] varchar(15) NULL, 
	[EXT] varchar(5) NULL, 
	[COMPLETEDID] varchar(15) NULL, 
	[NUMBER1] float NULL, 
	[NUMBER2] float NULL
);