table Dim_Date
	lineageTag: cf30afec-23a2-45a1-81b3-456a89e329c4
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_Date]
	dataCategory: Time

	measure 'PPO - Delivery Date' = ```
			
			VAR dk = VALUES ( Fact_Planned_Purchase_Orders[DeliveryDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the delivery-date keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: fbc310f0-b935-4c07-8e0d-10233959f996

		changedProperty = Name

	measure 'PPO - Requested Date' = ```
			
			VAR dk = VALUES ( Fact_Planned_Purchase_Orders[RequestedDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the delivery-date keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: e26d89e0-f9a1-4f7a-ad47-530a85ea03ae

		changedProperty = Name

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 971c7dac-90ad-46eb-9c8c-97b6785433d5
		sourceLineageTag: DateKey
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecId
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3463bf04-4729-422f-bcf1-6b461306cc90
		sourceLineageTag: RecId
		summarizeBy: count
		sourceColumn: RecId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: fa73a0e8-ef8e-409b-91e3-c45da6aa1c75
		sourceLineageTag: FiscalQuarterNum
		summarizeBy: sum
		sourceColumn: FiscalQuarterNum

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 3f95d355-175c-4ae6-854f-a59f12939919
		sourceLineageTag: FiscalYear
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalPeriodNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: dc2f2c64-5ae7-4e55-afb5-a7c1a8e36ac7
		sourceLineageTag: FiscalPeriodNum
		summarizeBy: sum
		sourceColumn: FiscalPeriodNum

		annotation SummarizationSetBy = Automatic

	column FiscalWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 59924b80-8ca6-4b76-ac71-e150dd1a7254
		sourceLineageTag: FiscalWeekNum
		summarizeBy: sum
		sourceColumn: FiscalWeekNum

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 7c132360-766c-40ab-a94e-9830b5597a2e
		sourceLineageTag: CalendarYear
		summarizeBy: sum
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 0088349c-851a-4dd5-b24a-af3a93624e62
		sourceLineageTag: CalendarQuarterNum
		summarizeBy: sum
		sourceColumn: CalendarQuarterNum

		annotation SummarizationSetBy = Automatic

	column MonthNameShort
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 1744f57a-2e2b-4460-a162-13b3cdb4cbde
		sourceLineageTag: MonthNameShort
		summarizeBy: none
		sourceColumn: MonthNameShort

		annotation SummarizationSetBy = Automatic

	column WeekdayNameLong
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: 094d4f7f-3572-44c7-b0b5-67f925166cc1
		sourceLineageTag: WeekdayNameLong
		summarizeBy: none
		sourceColumn: WeekdayNameLong

		annotation SummarizationSetBy = Automatic

	column WeekOfYearNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 99721079-df8f-4542-9179-082f64588b4c
		sourceLineageTag: WeekOfYearNum
		summarizeBy: sum
		sourceColumn: WeekOfYearNum

		annotation SummarizationSetBy = Automatic

	/// Based off of Order Date
	column Date
		dataType: dateTime
		isKey
		formatString: General Date
		sourceProviderType: date
		lineageTag: bcfaed41-9c9d-43e4-9565-9ac3f4542270
		sourceLineageTag: Date
		summarizeBy: none
		sourceColumn: Date

		changedProperty = Description

		annotation SummarizationSetBy = Automatic

	column DayOfMonthNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: cd465efa-5200-472c-8e49-f9de3fe03fa5
		sourceLineageTag: DayOfMonthNum
		summarizeBy: sum
		sourceColumn: DayOfMonthNum

		annotation SummarizationSetBy = Automatic

	column FiscalDayNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: b37c0b90-cfb2-4b2c-83ac-b884c3d75daa
		sourceLineageTag: FiscalDayNum
		summarizeBy: sum
		sourceColumn: FiscalDayNum

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayUs
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 8583398b-3441-4192-b695-c78232de91f4
		sourceLineageTag: IsWorkingDayUs
		summarizeBy: none
		sourceColumn: IsWorkingDayUs

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayBvba
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 041ec743-2b78-4d81-9519-9caabfdf66b4
		sourceLineageTag: IsWorkingDayBvba
		summarizeBy: none
		sourceColumn: IsWorkingDayBvba

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayTeda
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: e70f084b-c738-4c8d-81a5-73dd6a516045
		sourceLineageTag: IsWorkingDayTeda
		summarizeBy: none
		sourceColumn: IsWorkingDayTeda

		annotation SummarizationSetBy = Automatic

	column WeekStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: b86b5e5b-496f-4123-8406-91e590364b1d
		sourceLineageTag: WeekStartDate
		summarizeBy: none
		sourceColumn: WeekStartDate

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 7a551a55-3cb0-4c99-bcfd-d428b6161124
		sourceLineageTag: MonthStartDate
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

	column CurrentFiscalDayNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: bc114ac8-ac0b-418b-8289-d54ee1ec7752
		sourceLineageTag: CurrentFiscalDayNum
		summarizeBy: sum
		sourceColumn: CurrentFiscalDayNum

		annotation SummarizationSetBy = Automatic

	column CurrentFiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 70db215e-0c38-44df-899a-1b87bace7f9c
		sourceLineageTag: CurrentFiscalYear
		summarizeBy: sum
		sourceColumn: CurrentFiscalYear

		annotation SummarizationSetBy = Automatic

	column MonthNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: abae2c14-bfd6-435c-8f81-f5c356e3f74d
		sourceLineageTag: MonthNum
		summarizeBy: sum
		sourceColumn: MonthNum

		annotation SummarizationSetBy = Automatic

	column MonthNameLong
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: 647ae19d-cde5-4682-9dfe-2d3d84b36b99
		sourceLineageTag: MonthNameLong
		summarizeBy: none
		sourceColumn: MonthNameLong

		annotation SummarizationSetBy = Automatic

	column YearMonthNum
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: f49f91a7-0497-467d-8c33-9762014c754c
		sourceLineageTag: YearMonthNum
		summarizeBy: none
		sourceColumn: YearMonthNum

		annotation SummarizationSetBy = Automatic

	column YearMonthLabel
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: 02c51ee9-2028-4a75-af01-cf755a4f41cb
		sourceLineageTag: YearMonthLabel
		summarizeBy: none
		sourceColumn: YearMonthLabel

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterLabel
		dataType: string
		sourceProviderType: varchar(2)
		lineageTag: 211835c5-c1f5-44b1-92be-0b3c86d1a70c
		sourceLineageTag: CalendarQuarterLabel
		summarizeBy: none
		sourceColumn: CalendarQuarterLabel

		annotation SummarizationSetBy = Automatic

	column CalendarYearQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 89b57507-41d2-4f4b-9019-270400f837be
		sourceLineageTag: CalendarYearQuarterNum
		summarizeBy: sum
		sourceColumn: CalendarYearQuarterNum

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterLabel
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: fe02b0aa-c4fa-442d-b34c-4781136cb178
		sourceLineageTag: FiscalQuarterLabel
		summarizeBy: none
		sourceColumn: FiscalQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FiscalYearQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 457eb3b1-cf45-4075-af33-ace86bcd862f
		sourceLineageTag: FiscalYearQuarterNum
		summarizeBy: sum
		sourceColumn: FiscalYearQuarterNum

		annotation SummarizationSetBy = Automatic

	column WeekdayNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: c577ffbb-c96a-4b90-a5c8-429a9c675897
		sourceLineageTag: WeekdayNum
		summarizeBy: sum
		sourceColumn: WeekdayNum

		annotation SummarizationSetBy = Automatic

	column WeekdayNameShort
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: d928e1e6-617b-4fb9-9f7b-a6fbcf4fd13d
		sourceLineageTag: WeekdayNameShort
		summarizeBy: none
		sourceColumn: WeekdayNameShort

		annotation SummarizationSetBy = Automatic

	column YearWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 7033b931-879f-4e7e-b13f-b76ce09cb920
		sourceLineageTag: YearWeekNum
		summarizeBy: sum
		sourceColumn: YearWeekNum

		annotation SummarizationSetBy = Automatic

	column FiscalYearWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 7bab9f03-b1bb-4081-82d5-9b6e4b664441
		sourceLineageTag: FiscalYearWeekNum
		summarizeBy: sum
		sourceColumn: FiscalYearWeekNum

		annotation SummarizationSetBy = Automatic

	column DayOfYearNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 0583c3aa-bbb4-4f2d-a7f6-cbf0a9e8f03a
		sourceLineageTag: DayOfYearNum
		summarizeBy: sum
		sourceColumn: DayOfYearNum

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: e3af2053-dac2-4d21-80ea-e704861f75d2
		sourceLineageTag: IsWeekend
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsToday
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2f25cb51-f4b4-499a-b8da-9b9d99843ab6
		sourceLineageTag: IsToday
		summarizeBy: sum
		sourceColumn: IsToday

		annotation SummarizationSetBy = Automatic

	column IsCurrentMonth
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 4b45b638-4398-4996-8c99-033f7dcb0c54
		sourceLineageTag: IsCurrentMonth
		summarizeBy: none
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentFiscalYear
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: bb89ba96-e81d-4290-89ff-d20d936d93f5
		sourceLineageTag: IsCurrentFiscalYear
		summarizeBy: none
		sourceColumn: IsCurrentFiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalPeriodLabel
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 7f3e1101-be19-4917-97cd-aab53e945ca0
		sourceLineageTag: FiscalPeriodLabel
		summarizeBy: none
		sourceColumn: FiscalPeriodLabel

		annotation SummarizationSetBy = Automatic

	column WeeksInPeriod
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 7e3d93c1-dea3-4cc0-8ede-8e9588d969a9
		sourceLineageTag: WeeksInPeriod
		summarizeBy: sum
		sourceColumn: WeeksInPeriod

		annotation SummarizationSetBy = Automatic

	column 'Original FISCAL YR'
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: bdc21cba-dd27-4e00-97fc-17a625f02310
		sourceLineageTag: Original FISCAL YR
		summarizeBy: sum
		sourceColumn: Original FISCAL YR

		annotation SummarizationSetBy = Automatic

	column 'Original FISCAL PERIOD'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: fe1017b0-656e-4603-8658-b8041179a46d
		sourceLineageTag: Original FISCAL PERIOD
		summarizeBy: sum
		sourceColumn: Original FISCAL PERIOD

		annotation SummarizationSetBy = Automatic

	column 'Reconciliation Year'
		dataType: string
		sourceProviderType: varchar(20)
		lineageTag: e6ccc1b7-fba8-48bb-b5b2-51ce0f401481
		sourceLineageTag: Reconciliation Year
		summarizeBy: none
		sourceColumn: Reconciliation Year

		annotation SummarizationSetBy = Automatic

	column WeekStartDateSunday
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 28a45f4c-25f8-4844-b64e-09dd7c8ea72f
		sourceLineageTag: WeekStartDateSunday
		summarizeBy: none
		sourceColumn: WeekStartDateSunday

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_Date
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

