table Fact_FinishedGoodsRawMaterials
	lineageTag: 58e818a7-18bb-45a3-beac-2905b8070326
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_FinishedGoodsRawMaterials]

	measure FinishedGoodName = ```
			
			VAR dk = VALUES ( 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Product'[Product_Name]),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Product' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Product'[ProductKey] )
			)
			
			```
		lineageTag: 2bf44a36-b94b-4630-8138-876f3d9e9b0e

		changedProperty = Name

	measure FinishedGoodBL = ```
			
			VAR dk = VALUES ( 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Product'[Business_Line]),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Product' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Product'[ProductKey] )
			)
			
			```
		lineageTag: 0a9185ec-d9db-4c92-9309-ed04ea70f4c9

		changedProperty = Name

	measure FinishedGoodPL = ```
			
			VAR dk = VALUES ( 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Product'[Product_Line]),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Product' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Product'[ProductKey] )
			)
			
			```
		lineageTag: 74431b0e-1f74-4c73-8cc5-ac263642bedd

		changedProperty = Name

	measure FinishedGoodTech = ```
			
			VAR dk = VALUES ( 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Product'[Technology]),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Product' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Product'[ProductKey] )
			)
			
			```
		lineageTag: d0355bdc-f417-499a-a7d9-a4d90453a621

		changedProperty = Name

	measure FinishedGoodMat = ```
			
			VAR dk = VALUES ( 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Product'[Material]),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Product' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Product'[ProductKey] )
			)
			
			```
		lineageTag: b98c66fe-32ad-4998-914e-12d349f2ae88

		changedProperty = Name

	measure FinishedGoodItemGroup = ```
			
			VAR dk = VALUES ( 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Product'[ItemGroupName]),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Product' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Product'[ProductKey] )
			)
			
			```
		lineageTag: bc09a769-6615-4588-8420-de8d16c03c9a

		changedProperty = Name

	measure RMPerFG = SUM(Fact_FinishedGoodsRawMaterials[RawMaterialAmtPerLbFG])
		lineageTag: a38310a3-01ae-4d16-b0fd-c919c222ca7b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RMHT - Show FG Detail' =
			
			IF (
			    HASONEVALUE ( 'Dim_Product'[Product_ID] )
			        || HASONEVALUE ( 'Dim_Product'[ProductKey] ),
			    1
			)
		formatString: 0
		lineageTag: 11694f11-82af-430f-9ce2-b5d535517311

		changedProperty = Name

	measure 'RMHT - FG Sold LBs for Selected RM' =
			
			VAR ValidFormulaSites =
			    FILTER (
			        ALL ( 'Fact_FinishedGoodsRawMaterials'[RmSiteId] ),
			        'Fact_FinishedGoodsRawMaterials'[RmSiteId] <> "90"
			    )
			
			VAR FinishedGoodKeys =
			    CALCULATETABLE (
			        VALUES ( 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] ),
			        REMOVEFILTERS ( 'DIM_Site' ),
			        ValidFormulaSites
			    )
			
			RETURN
			    IF (
			        [RMHT - Show FG Detail] = 1
			            && COUNTROWS ( FinishedGoodKeys ) > 0,
			        CALCULATE (
			            [Quantity LBs],
			            REMOVEFILTERS ( 'Dim_Product' ),
			            REMOVEFILTERS ( 'Dim_Date' ),
			            TREATAS (
			                FinishedGoodKeys,
			                'Dim_Product'[ProductKey]
			            )
			        )
			    )
		lineageTag: d3de93b9-e3f9-4206-9c50-f4f4fd38262d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RMHT - RM Per Lb FG' =
			
			DIVIDE (
			    [RMHT - Theoretical RM Demand by FG LBs],
			    [RMHT - FG Sold LBs for Selected RM]
			)
		lineageTag: 811b1c60-4d28-432a-b916-070435314ccf

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RMHT - Theoretical RM Demand by FG LBs' =
			
			VAR ValidFormulaSites =
			    FILTER (
			        ALL ( 'Fact_FinishedGoodsRawMaterials'[RmSiteId] ),
			        'Fact_FinishedGoodsRawMaterials'[RmSiteId] <> "90"
			    )
			
			VAR FinishedGoodKeys =
			    CALCULATETABLE (
			        VALUES ( 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] ),
			        REMOVEFILTERS ( 'DIM_Site' ),
			        ValidFormulaSites
			    )
			
			RETURN
			    IF (
			        [RMHT - Show FG Detail] = 1,
			        SUMX (
			            FinishedGoodKeys,
			            VAR ThisFinishedGoodKey =
			                'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey]
			
			            VAR ThisRMPerLbFG =
			                CALCULATE (
			                    SUM ( 'Fact_FinishedGoodsRawMaterials'[RawMaterialAmtPerLbFG] ),
			                    REMOVEFILTERS ( 'DIM_Site' ),
			                    ValidFormulaSites,
			                    'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey] = ThisFinishedGoodKey
			                )
			
			            VAR FinishedGoodSoldLbs =
			                CALCULATE (
			                    [Quantity LBs],
			                    REMOVEFILTERS ( 'Dim_Product' ),
			                    REMOVEFILTERS ( 'Dim_Date' ),
			                    TREATAS (
			                        { ThisFinishedGoodKey },
			                        'Dim_Product'[ProductKey]
			                    )
			                )
			
			            RETURN
			                FinishedGoodSoldLbs * ThisRMPerLbFG
			        )
			    )
		lineageTag: 4f0eaa51-72fd-4b23-9f1f-994880fcdca1

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RMHT - RM Demand Share %' =
			
			DIVIDE (
			    [RMHT - Theoretical RM Demand by FG LBs],
			    [Historical RM Demand LBs]
			)
		lineageTag: 7275421c-8f89-4645-b0a3-8d1213165056

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExplodedFormulaKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 86117efc-f55f-4851-85b8-a30189d1e386
		sourceLineageTag: ExplodedFormulaKey
		summarizeBy: count
		sourceColumn: ExplodedFormulaKey

		annotation SummarizationSetBy = Automatic

	column DataAreaId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7d930481-f872-44ff-bf60-610cf21cf319
		sourceLineageTag: DataAreaId
		summarizeBy: none
		sourceColumn: DataAreaId

		annotation SummarizationSetBy = Automatic

	column FgItemId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f0ed14a5-b913-4c41-a7cf-e54872cca25a
		sourceLineageTag: FgItemId
		summarizeBy: none
		sourceColumn: FgItemId

		annotation SummarizationSetBy = Automatic

	column FgSiteId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c6a8b531-b70b-41bf-9d38-b85053f12aad
		sourceLineageTag: FgSiteId
		summarizeBy: none
		sourceColumn: FgSiteId

		annotation SummarizationSetBy = Automatic

	column FgBomId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 3372a8ee-5c24-482e-96cf-9b9320517ff1
		sourceLineageTag: FgBomId
		summarizeBy: none
		sourceColumn: FgBomId

		annotation SummarizationSetBy = Automatic

	column RawMaterialProductID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6dbb5357-e1e0-4ecc-9dad-e20782a3c5dd
		sourceLineageTag: RawMaterialProductID
		summarizeBy: none
		sourceColumn: RawMaterialProductID

		annotation SummarizationSetBy = Automatic

	column RmSiteId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a9e93c92-616e-4c9c-8844-0f6798b269a3
		sourceLineageTag: RmSiteId
		summarizeBy: none
		sourceColumn: RmSiteId

		annotation SummarizationSetBy = Automatic

	column RawMaterialAmtPerLbFG
		dataType: double
		sourceProviderType: decimal(28, 8)
		lineageTag: 09422035-6d5c-4bbe-bac5-268328877b18
		sourceLineageTag: RawMaterialAmtPerLbFG
		summarizeBy: sum
		sourceColumn: RawMaterialAmtPerLbFG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BomPath
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 93dbcacb-95b4-4060-b38d-37fe65fb92d5
		sourceLineageTag: BomPath
		summarizeBy: none
		sourceColumn: BomPath

		annotation SummarizationSetBy = Automatic

	column BomLevel
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 9b3a1087-ee74-4be8-ae82-3667174d7c7a
		sourceLineageTag: BomLevel
		summarizeBy: sum
		sourceColumn: BomLevel

		annotation SummarizationSetBy = Automatic

	column PeriodFromDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 9f189d1a-aefc-4b99-bee1-bc7fbda3d28b
		sourceLineageTag: PeriodFromDate
		summarizeBy: none
		sourceColumn: PeriodFromDate

		annotation SummarizationSetBy = Automatic

	column PeriodToDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 0223f2c0-a167-4a5e-8447-e7f06081c945
		sourceLineageTag: PeriodToDate
		summarizeBy: none
		sourceColumn: PeriodToDate

		annotation SummarizationSetBy = Automatic

	column IsCurrent
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 95b274e4-28c7-4b0f-b16c-b5e95a29e993
		sourceLineageTag: IsCurrent
		summarizeBy: sum
		sourceColumn: IsCurrent

		annotation SummarizationSetBy = Automatic

	column Legal_EntityKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 350f3a34-6dc7-4b76-983e-a72848f22822
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		annotation SummarizationSetBy = Automatic

	column FinishedGoodProductKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 41a313b0-9bb7-41a0-8921-dd8e5ccf4bb0
		sourceLineageTag: FinishedGoodProductKey
		summarizeBy: count
		sourceColumn: FinishedGoodProductKey

		annotation SummarizationSetBy = Automatic

	column SiteKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: f9814b8a-36f1-43b5-aadb-3f0dd7bbc1f2
		sourceLineageTag: SiteKey
		summarizeBy: count
		sourceColumn: SiteKey

		annotation SummarizationSetBy = Automatic

	column FromDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 124faa6e-f347-46e3-a74b-7d3c48315495
		sourceLineageTag: FromDateKey
		summarizeBy: count
		sourceColumn: FromDateKey

		annotation SummarizationSetBy = Automatic

	column ToDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 04a3445d-072e-4199-bbc2-51130a095002
		sourceLineageTag: ToDateKey
		summarizeBy: count
		sourceColumn: ToDateKey

		annotation SummarizationSetBy = Automatic

	column RawMaterialProductKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c8be9142-49b2-4977-94e8-424eedae6a7a
		sourceLineageTag: RawMaterialProductKey
		summarizeBy: none
		sourceColumn: RawMaterialProductKey

		annotation SummarizationSetBy = Automatic

	column RawMaterialSiteKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 135e0c00-5fb6-4c52-a04b-bc53ce0b8b09
		sourceLineageTag: RawMaterialSiteKey
		summarizeBy: none
		sourceColumn: RawMaterialSiteKey

		annotation SummarizationSetBy = Automatic

	column PercentControlled
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d3630fd4-796c-4506-aedc-f162deae73e4
		sourceLineageTag: PercentControlled
		summarizeBy: sum
		sourceColumn: PercentControlled

		annotation SummarizationSetBy = Automatic

	column Percent
		dataType: double
		sourceProviderType: decimal(28, 8)
		lineageTag: 69c254e3-3539-492e-819b-79c720e865a6
		sourceLineageTag: Percent
		summarizeBy: sum
		sourceColumn: Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_FinishedGoodsRawMaterials = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_FinishedGoodsRawMaterials
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

