table Fact_Inventory_Snapshot
	lineageTag: bbcedbff-162f-458e-9685-28f109d8635a
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_Inventory_Snapshot]

	defaultDetailRowsDefinition = ```
			DEFINE 
			---- MODEL MEASURES BEGIN ----
			MEASURE Fact_Inventory_Snapshot[Available for Reservation] = (([Posted Quantity] + [Received Qty] - [Deducted Qty] + [Registered Qty] - [Picked Qty]) - [Physical Reserved])
			MEASURE Fact_Inventory_Snapshot[Available for Reservation LBs] = (([Posted Quantity LBs] + [Received Qty LBs] - [Deducted Qty LBs] + [Registered Qty LBs] - [Picked Qty LBs]) - [Physical Reserved LBs])
			MEASURE Fact_Inventory_Snapshot[Available Physical] = SUM(Fact_Inventory_Snapshot[availphysical])
			MEASURE Fact_Inventory_Snapshot[Available Physical LBs] = SUM(Fact_Inventory_Snapshot[availphysical_LBs])
			MEASURE Fact_Inventory_Snapshot[Deducted Qty] = SUM(Fact_Inventory_Snapshot[deducted])
			MEASURE Fact_Inventory_Snapshot[Deducted Qty LBs] = SUM(Fact_Inventory_Snapshot[deducted_LBs])
			MEASURE Fact_Inventory_Snapshot[On Order] = SUM(Fact_Inventory_Snapshot[onorder])
			MEASURE Fact_Inventory_Snapshot[On Order LBs] = SUM(Fact_Inventory_Snapshot[onorder_LBs])
			MEASURE Fact_Inventory_Snapshot[Ordered Qty] = SUM(Fact_Inventory_Snapshot[ordered])
			MEASURE Fact_Inventory_Snapshot[Ordered Qty LBs] = SUM(Fact_Inventory_Snapshot[ordered_LBs])
			MEASURE Fact_Inventory_Snapshot[Ordered Reserved] = SUM(Fact_Inventory_Snapshot[reservordered])
			MEASURE Fact_Inventory_Snapshot[Ordered Reserved LBs] = SUM(Fact_Inventory_Snapshot[reservordered_LBs])
			MEASURE Fact_Inventory_Snapshot[Physical Inventory] = SUM('Fact_Inventory_Snapshot'[physicalinvent])
			MEASURE Fact_Inventory_Snapshot[Physical Inventory LBs] = SUM(Fact_Inventory_Snapshot[physicalinvent_LBs])
			MEASURE Fact_Inventory_Snapshot[Physical Reserved] = SUM(Fact_Inventory_Snapshot[reservphysical])
			MEASURE Fact_Inventory_Snapshot[Physical Reserved LBs] = SUM(Fact_Inventory_Snapshot[reservphysical_LBs])
			MEASURE Fact_Inventory_Snapshot[Picked Qty] = SUM(Fact_Inventory_Snapshot[picked])
			MEASURE Fact_Inventory_Snapshot[Picked Qty LBs] = SUM(Fact_Inventory_Snapshot[picked_LBs])
			MEASURE Fact_Inventory_Snapshot[Posted Quantity] = SUM(Fact_Inventory_Snapshot[postedqty])
			MEASURE Fact_Inventory_Snapshot[Posted Quantity LBs] = SUM(Fact_Inventory_Snapshot[postedqty_LBs])
			MEASURE Fact_Inventory_Snapshot[Received Qty] = SUM(Fact_Inventory_Snapshot[received])
			MEASURE Fact_Inventory_Snapshot[Received Qty LBs] = SUM(Fact_Inventory_Snapshot[received_LBs])
			MEASURE Fact_Inventory_Snapshot[Registered Qty] = SUM(Fact_Inventory_Snapshot[registered])
			MEASURE Fact_Inventory_Snapshot[Registered Qty LBs] = SUM(Fact_Inventory_Snapshot[registered_LBs])
			MEASURE Fact_Inventory_Snapshot[Total Available] = ([Available for Reservation] + [Ordered Qty] - [On Order] - [Ordered Reserved])
			MEASURE Fact_Inventory_Snapshot[Total Available LBs] = ([Available for Reservation LBs] + [Ordered Qty LBs] - [On Order LBs] - [Ordered Reserved LBs])
			MEASURE Fact_PlannedPurchaseTransferProd_Orders[Requirement Quantity] = SUM(Fact_PlannedPurchaseTransferProd_Orders[RequirementQuantity])
			---- MODEL MEASURES END ----
			```

	measure 'Available Physical' = SUM(Fact_Inventory_Snapshot[availphysical])
		lineageTag: c18e8971-e3f4-4730-9113-125a02b42667

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Available Physical LBs' = SUM(Fact_Inventory_Snapshot[availphysical_LBs])
		lineageTag: 445241c9-7885-43b4-a283-4355653e6024

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deducted Qty' = SUM(Fact_Inventory_Snapshot[deducted])
		lineageTag: 8112f820-b721-4bd4-a180-f3ba11c4aeae

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deducted Qty LBs' = SUM(Fact_Inventory_Snapshot[deducted_LBs])
		lineageTag: 7793c4ba-a731-4aca-850b-2b3ec4104ab5

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Order' = SUM(Fact_Inventory_Snapshot[onorder])
		lineageTag: d684fe92-3155-4af9-9235-3a521eaf2280

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Order LBs' = SUM(Fact_Inventory_Snapshot[onorder_LBs])
		lineageTag: c26ca3dd-edff-47c8-a26b-546f461007bb

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ordered Qty' = SUM(Fact_Inventory_Snapshot[ordered])
		lineageTag: 5c43adc7-30bd-4a68-982b-0e895918578f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ordered Qty LBs' = SUM(Fact_Inventory_Snapshot[ordered_LBs])
		lineageTag: ad66f15b-b8fe-42d4-92ec-e06de8787323

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ordered Reserved' = SUM(Fact_Inventory_Snapshot[reservordered])
		lineageTag: 2645c57e-82ee-444b-9f90-706e098f3bfc

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ordered Reserved LBs' = SUM(Fact_Inventory_Snapshot[reservordered_LBs])
		lineageTag: e490e8d5-6ab8-47d9-9e87-41c970a5ffbc

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Inventory' = SUM(Fact_Inventory_Snapshot[physicalinvent])
		lineageTag: 9696fad3-ce29-4d7a-b6f0-8d47d8c29775

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Inventory LBs' = SUM(Fact_Inventory_Snapshot[physicalinvent_LBs])
		lineageTag: 3891e375-fafd-44d5-81f5-d4d300bc08e5

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Reserved' = SUM(Fact_Inventory_Snapshot[reservphysical])
		lineageTag: 05eb9203-face-4c3f-8f5e-00dd7a8cf596

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Physical Reserved LBs' = SUM(Fact_Inventory_Snapshot[reservphysical_LBs])
		lineageTag: 30e6919d-fe5b-4b5f-a7f2-6626ea0b3c4a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Picked Qty' = SUM(Fact_Inventory_Snapshot[picked])
		lineageTag: cd09e1d8-c618-4137-bdd1-1c03e3ac1c97

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Picked Qty LBs' = SUM(Fact_Inventory_Snapshot[picked_LBs])
		lineageTag: a7478bb9-efc4-4052-be74-67c064674f99

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Posted Quantity' = SUM(Fact_Inventory_Snapshot[postedqty])
		lineageTag: 8ec892ac-6c52-4c7a-b5a8-b53e618ebaad

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Posted Quantity LBs' = SUM(Fact_Inventory_Snapshot[postedqty_LBs])
		lineageTag: 8e3f9b47-579c-4b98-9287-10c724f4b3ac

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Received Qty' = SUM(Fact_Inventory_Snapshot[received])
		lineageTag: 17404144-2b3d-4a16-b489-d38fb335560d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Received Qty LBs' = SUM(Fact_Inventory_Snapshot[received_LBs])
		lineageTag: e7fb2a3b-eb91-4896-9e58-b5f0e3dbc6f6

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Registered Qty' = SUM(Fact_Inventory_Snapshot[registered])
		lineageTag: 5a1572af-9ec8-41be-961f-87211182a68f

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Registered Qty LBs' = SUM(Fact_Inventory_Snapshot[registered_LBs])
		lineageTag: 637941af-5171-4d18-95d2-348c11437841

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Available for Reservation' = (([Posted Quantity] + [Received Qty] - [Deducted Qty] + [Registered Qty] - [Picked Qty]) - [Physical Reserved])
		lineageTag: 0506826c-a54e-45ee-a367-18f0774f6c6c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Available for Reservation LBs' = (([Posted Quantity LBs] + [Received Qty LBs] - [Deducted Qty LBs] + [Registered Qty LBs] - [Picked Qty LBs]) - [Physical Reserved LBs])
		lineageTag: 76ebd37d-7b9f-4b5e-a5ec-5dc1a2fe2ddd

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Available' = ([Available for Reservation] + [Ordered Qty] - [On Order] - [Ordered Reserved])
		lineageTag: 8d106e4a-f53e-4e47-8280-c563c92edbde

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Available LBs' = ([Available for Reservation LBs] + [Ordered Qty LBs] - [On Order LBs] - [Ordered Reserved LBs])
		lineageTag: e906b298-c6a0-4370-9b68-7e56440377f4

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = COUNTROWS(Fact_Inventory_Snapshot)
		formatString: 0
		lineageTag: 2149686f-facc-4517-9703-7e2865a6f236

		changedProperty = Name

	measure 'Total Transactions (IS)' = COUNTROWS(Fact_Inventory_Snapshot)
		formatString: 0
		lineageTag: 60ed062e-0fa3-4c25-9ad1-1c1b75232483

		changedProperty = Name

	measure 'Historical RM Demand LBs' =
			
			VAR RawMaterialKeys =
			    VALUES ( 'Dim_Product'[ProductKey] )
			
			VAR ValidFormulaSites =
			    FILTER (
			        ALL ( 'Fact_FinishedGoodsRawMaterials'[RmSiteId] ),
			        'Fact_FinishedGoodsRawMaterials'[RmSiteId] <> "90"
			    )
			
			VAR BomRowsForSelectedRawMaterials =
			    SELECTCOLUMNS (
			        SUMMARIZE (
			            CALCULATETABLE (
			                'Fact_FinishedGoodsRawMaterials',
			                REMOVEFILTERS ( 'Fact_FinishedGoodsRawMaterials' ),
			                REMOVEFILTERS ( 'DIM_Site' ),
			                TREATAS (
			                    RawMaterialKeys,
			                    'Fact_FinishedGoodsRawMaterials'[RawMaterialProductKey]
			                ),
			                ValidFormulaSites
			            ),
			            'Fact_FinishedGoodsRawMaterials'[RawMaterialProductKey],
			            'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey],
			            "RMPerLbFG",
			                SUM ( 'Fact_FinishedGoodsRawMaterials'[RawMaterialAmtPerLbFG] )
			        ),
			        "RawMaterialKey", 'Fact_FinishedGoodsRawMaterials'[RawMaterialProductKey],
			        "FinishedGoodKey", 'Fact_FinishedGoodsRawMaterials'[FinishedGoodProductKey],
			        "RMPerLbFG", [RMPerLbFG]
			    )
			
			VAR Result =
			    SUMX (
			        BomRowsForSelectedRawMaterials,
			        VAR ThisFinishedGoodKey = [FinishedGoodKey]
			        VAR ThisRMPerLbFG = [RMPerLbFG]
			
			        VAR FinishedGoodSoldLbs =
			            CALCULATE (
			                [Quantity LBs],
			                REMOVEFILTERS ( 'Dim_Product' ),
			                REMOVEFILTERS ( 'Dim_Date' ),
			                TREATAS (
			                    { ThisFinishedGoodKey },
			                    'Dim_Product'[ProductKey]
			                )
			            )
			
			        RETURN
			            FinishedGoodSoldLbs * ThisRMPerLbFG
			    )
			
			RETURN
			    COALESCE ( Result, 0 )
		lineageTag: 6cf4f64a-9a9d-4f1e-8994-bd2a5d3d1bb2

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Historical Demand Gap LBs' =
			
			[Physical Inventory LBs] - [Historical RM Demand LBs]
		lineageTag: a483abaf-4c31-436d-ba08-76f435ee456a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Historical Demand Coverage Ratio' =
			
			DIVIDE ( [Physical Inventory LBs], [Historical RM Demand LBs] )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 732083f2-a1f7-4fc8-96a6-9c8f3d9b51e6

		changedProperty = Name

		changedProperty = FormatString

	measure 'Selected Sales Horizon Days' =
			
			VAR DateWindow =
			    CALCULATETABLE (
			        ALLSELECTED ( 'Fact_Sales'[OrderDate] ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Fact_FinishedGoodsRawMaterials' ),
			        REMOVEFILTERS ( 'Dim_Date' )
			    )
			
			VAR MinDate =
			    MINX (
			        DateWindow,
			        INT ( 'Fact_Sales'[OrderDate] )
			    )
			
			VAR MaxDate =
			    MAXX (
			        DateWindow,
			        INT ( 'Fact_Sales'[OrderDate] )
			    )
			
			RETURN
			    IF (
			        NOT ISBLANK ( MinDate )
			            && NOT ISBLANK ( MaxDate ),
			        MaxDate - MinDate + 1
			    )
		formatString: 0
		lineageTag: 58ec56dc-959f-45e5-994d-77c4eac1641f

		changedProperty = Name

	measure 'Avg Daily RM Demand LBs' =
			
			DIVIDE (
			    [Historical RM Demand LBs],
			    [Selected Sales Horizon Days]
			)
		lineageTag: e05489c3-6d4f-45dd-aadf-2dc452a0f879

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Days on Hand' =
			
			DIVIDE (
			    [Physical Inventory LBs],
			    [Avg Daily RM Demand LBs]
			)
		lineageTag: fc4e7f7e-cbe9-4215-be2c-85cc24034c5e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Days Supply incl. On-Order' =
			
			DIVIDE (
			    [Physical Inventory LBs] + [Ordered Qty LBs],
			    [Avg Daily RM Demand LBs]
			)
		lineageTag: 6dc2eba9-40bc-42bd-a417-9accc7165135

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inventory Notes Title' =
			
			"Inventory as of "
			    & FORMAT ( [Most Recent Snapshot Date], "MM/dd/yy" )
		lineageTag: 044f2814-90e7-4758-af5d-2643e1d649eb

		changedProperty = Name

	measure 'Most Recent Snapshot Date' =
			
			MAX ( 'Fact_Inventory_Snapshot'[Snapshot_Date] )
		formatString: General Date
		lineageTag: 0cb9848a-7814-4101-8ffb-f3a8e345dd32

		changedProperty = Name

	measure 'Selected RM Demand Trend Lbs' =
			
			VAR ShowChart =
			    [RMHT - Show FG Detail] = 1
			
			VAR AxisStartDate =
			    MIN ( 'Dim_Date'[Date] )
			
			VAR AxisEndDate =
			    MAX ( 'Dim_Date'[Date] )
			
			VAR HorizonStartDateTime =
			    CALCULATE (
			        MIN ( 'Fact_Sales'[OrderDate] ),
			        REMOVEFILTERS ( 'Dim_Date' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Fact_FinishedGoodsRawMaterials' )
			    )
			
			VAR HorizonEndDateTime =
			    CALCULATE (
			        MAX ( 'Fact_Sales'[OrderDate] ),
			        REMOVEFILTERS ( 'Dim_Date' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Fact_FinishedGoodsRawMaterials' )
			    )
			
			VAR HorizonStartDate =
			    IF (
			        NOT ISBLANK ( HorizonStartDateTime ),
			        INT ( HorizonStartDateTime )
			    )
			
			VAR HorizonEndDate =
			    IF (
			        NOT ISBLANK ( HorizonEndDateTime ),
			        INT ( HorizonEndDateTime )
			    )
			
			VAR AxisOverlapsSalesHorizon =
			    NOT ISBLANK ( AxisStartDate )
			        && NOT ISBLANK ( AxisEndDate )
			        && NOT ISBLANK ( HorizonStartDate )
			        && NOT ISBLANK ( HorizonEndDate )
			        && AxisEndDate >= HorizonStartDate
			        && AxisStartDate <= HorizonEndDate
			
			RETURN
			    IF (
			        ShowChart
			            && AxisOverlapsSalesHorizon,
			        VAR DemandForAxisPeriod =
			            CALCULATE (
			                [Historical RM Demand LBs],
			                REMOVEFILTERS ( 'Dim_Date' ),
			                KEEPFILTERS (
			                    'Fact_Sales'[OrderDate] >= AxisStartDate
			                ),
			                KEEPFILTERS (
			                    'Fact_Sales'[OrderDate] < AxisEndDate + 1
			                )
			            )
			        RETURN
			            IF (
			                DemandForAxisPeriod <> 0,
			                DemandForAxisPeriod
			            )
			    )
		lineageTag: 413bffbf-31e4-47a6-8921-5cae982e9053

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMPNY
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 025484a5-aa25-43ce-b3c9-c1b6708f0dfe
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Site_ID
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 79bbfd51-6667-4606-97b4-742edc1e140d
		sourceLineageTag: Site_ID
		summarizeBy: none
		sourceColumn: Site_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Warehouse_ID
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 731781b2-b26c-46fd-9620-2a3dbc863ba7
		sourceLineageTag: Warehouse_ID
		summarizeBy: none
		sourceColumn: Warehouse_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Snapshot_Date
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: c991682d-b071-4a4f-8f53-f225109e727d
		sourceLineageTag: Snapshot_Date
		summarizeBy: none
		sourceColumn: Snapshot_Date

		annotation SummarizationSetBy = Automatic

	column Snapshot_Date_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 0cef20aa-42e0-4b26-921c-1fec5b5f595c
		sourceLineageTag: Snapshot_Date_Key
		summarizeBy: none
		sourceColumn: Snapshot_Date_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 4ba87ea2-8983-427a-8fa7-580a6a07c8f8
		sourceLineageTag: Product_ID
		summarizeBy: none
		sourceColumn: Product_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: d607f32c-951c-40b8-b5c7-8b8c6708675e
		sourceLineageTag: ProductName
		summarizeBy: none
		sourceColumn: ProductName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductSearchName
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: cdb47916-4184-4249-a4e2-639c08134131
		sourceLineageTag: ProductSearchName
		summarizeBy: none
		sourceColumn: ProductSearchName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Phantom_Product
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: ce04a787-fdad-4323-85ae-162bdf108ade
		sourceLineageTag: Phantom_Product
		summarizeBy: none
		sourceColumn: Phantom_Product

		annotation SummarizationSetBy = Automatic

	column Inventory_UoM
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: fa7ee9fd-20fe-45e2-a3e5-fb55e08012f1
		sourceLineageTag: Inventory_UoM
		summarizeBy: none
		sourceColumn: Inventory_UoM

		annotation SummarizationSetBy = Automatic

	column inventstatusid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 0636d0cb-6c99-4f5e-8153-4cf3690e8c19
		sourceLineageTag: inventstatusid
		summarizeBy: none
		sourceColumn: inventstatusid

		annotation SummarizationSetBy = Automatic

	column wmslocationid
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: e608e038-8d96-4967-b3df-ea12114a6785
		sourceLineageTag: wmslocationid
		summarizeBy: none
		sourceColumn: wmslocationid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column arrived
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 5f661807-75d3-4033-8697-76d8961ac37d
		sourceLineageTag: arrived
		summarizeBy: sum
		sourceColumn: arrived

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column availordered
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 82d4b190-4d7e-4c21-865f-a2139c7e0e67
		sourceLineageTag: availordered
		summarizeBy: sum
		sourceColumn: availordered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column availphysical
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 85e449f1-2969-486e-bcf5-4df014301265
		sourceLineageTag: availphysical
		summarizeBy: sum
		sourceColumn: availphysical

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deducted
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: a41a2969-1af6-4e57-b638-10bda4453ab4
		sourceLineageTag: deducted
		summarizeBy: sum
		sourceColumn: deducted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column onorder
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 06fdcfc0-e828-412d-847b-13502b068d8d
		sourceLineageTag: onorder
		summarizeBy: sum
		sourceColumn: onorder

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ordered
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 658ec712-482a-44cb-8367-11bc79689a94
		sourceLineageTag: ordered
		summarizeBy: sum
		sourceColumn: ordered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column physicalinvent
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: d03cbb02-2323-42ac-a9a8-923d01d68033
		sourceLineageTag: physicalinvent
		summarizeBy: sum
		sourceColumn: physicalinvent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column picked
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 4b43cf41-6ba0-445c-838d-48f0c9028e53
		sourceLineageTag: picked
		summarizeBy: sum
		sourceColumn: picked

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column postedqty
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 9221fb1d-df12-47c8-9b02-0cbc85e2d7bb
		sourceLineageTag: postedqty
		summarizeBy: sum
		sourceColumn: postedqty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column received
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 9b22fac9-9bc7-49f9-992a-951cefb664f8
		sourceLineageTag: received
		summarizeBy: sum
		sourceColumn: received

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column registered
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 3622f7da-2484-4197-80ae-b6dc05713cbd
		sourceLineageTag: registered
		summarizeBy: sum
		sourceColumn: registered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reservordered
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: f780939f-2d43-4bc9-be77-0663167ea6bf
		sourceLineageTag: reservordered
		summarizeBy: sum
		sourceColumn: reservordered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reservphysical
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: fc4ea304-2b11-4f54-b1ca-5e840fa6583f
		sourceLineageTag: reservphysical
		summarizeBy: sum
		sourceColumn: reservphysical

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column postedcostamount
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 3b94464a-ae92-441f-a1b9-40a3f489b60c
		sourceLineageTag: postedcostamount
		summarizeBy: sum
		sourceColumn: postedcostamount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column arrived_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 23d34522-7caf-4c93-9c01-08ee23a5e81d
		sourceLineageTag: arrived_LBs
		summarizeBy: sum
		sourceColumn: arrived_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column availordered_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 76956aaf-eb8c-42fb-8fb4-ea217f5908ec
		sourceLineageTag: availordered_LBs
		summarizeBy: sum
		sourceColumn: availordered_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column availphysical_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 1218571f-ccd9-4912-b6a0-b3b4d7be2553
		sourceLineageTag: availphysical_LBs
		summarizeBy: sum
		sourceColumn: availphysical_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deducted_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: f63e9a91-735f-4990-958f-21aa5af69cab
		sourceLineageTag: deducted_LBs
		summarizeBy: sum
		sourceColumn: deducted_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column onorder_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: e9d661a0-542f-4515-8798-7507f6316967
		sourceLineageTag: onorder_LBs
		summarizeBy: sum
		sourceColumn: onorder_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ordered_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: cfad58c4-69e5-4bd3-80dd-be5e38c1faa8
		sourceLineageTag: ordered_LBs
		summarizeBy: sum
		sourceColumn: ordered_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column physicalinvent_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 278f15f9-e85f-42a5-9e6d-ce2974fc7f39
		sourceLineageTag: physicalinvent_LBs
		summarizeBy: sum
		sourceColumn: physicalinvent_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column picked_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: c98d4f54-7c89-4581-bae2-fd8c6278073a
		sourceLineageTag: picked_LBs
		summarizeBy: sum
		sourceColumn: picked_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column postedqty_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: c5df1c14-d95c-4458-8549-c77777ccbb23
		sourceLineageTag: postedqty_LBs
		summarizeBy: sum
		sourceColumn: postedqty_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column received_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 80347805-c16c-40ba-bd94-891d00d1a988
		sourceLineageTag: received_LBs
		summarizeBy: sum
		sourceColumn: received_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column registered_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 2186b0c6-2cab-471e-93dc-baf47086e340
		sourceLineageTag: registered_LBs
		summarizeBy: sum
		sourceColumn: registered_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reservordered_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 0e199af3-5bfd-4bb2-883d-0a9a62d95d4b
		sourceLineageTag: reservordered_LBs
		summarizeBy: sum
		sourceColumn: reservordered_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reservphysical_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: 90c6d019-50ac-48fa-b330-d61f1fe9fb74
		sourceLineageTag: reservphysical_LBs
		summarizeBy: sum
		sourceColumn: reservphysical_LBs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Source
		dataType: string
		sourceProviderType: varchar(6)
		lineageTag: f467da7d-53ee-4efb-896d-ac4cdf74f378
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: d7395c0d-021b-4e2c-a7f0-73f024e43f2d
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column SiteKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: cd71480e-f66b-4af2-aad1-38820b208fb5
		sourceLineageTag: SiteKey
		summarizeBy: none
		sourceColumn: SiteKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ede41814-955f-4ffc-9ae5-3303248c1751
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column primaryvendorid
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: d924066c-e2be-40b4-b2cc-b70c427033a0
		sourceLineageTag: primaryvendorid
		summarizeBy: none
		sourceColumn: primaryvendorid

		annotation SummarizationSetBy = Automatic

	column WarehouseKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 422de6a1-5a53-4d2f-b1c8-09fdf83a9fa8
		sourceLineageTag: WarehouseKey
		summarizeBy: none
		sourceColumn: WarehouseKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VendorKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 04422734-c64d-41ca-a2d4-78d545a6a913
		sourceLineageTag: VendorKey
		summarizeBy: none
		sourceColumn: VendorKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inventorySnapshotKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4d1f4c12-b2c7-4122-ad96-11dce9782b6f
		sourceLineageTag: inventorySnapshotKey
		summarizeBy: count
		sourceColumn: inventorySnapshotKey

		annotation SummarizationSetBy = Automatic

	column StandardCostKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 7e810983-483c-4abe-971b-7e541d53811e
		sourceLineageTag: StandardCostKey
		summarizeBy: count
		sourceColumn: StandardCostKey

		annotation SummarizationSetBy = Automatic

	partition Fact_Inventory_Snapshot = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_Inventory_Snapshot
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

