table BIDataSet_Opportunity
	lineageTag: 570adf19-7dbf-4b40-a33a-c22062eb84e8
	sourceLineageTag: [dbo].[mtbl_LEG_BIDataSet_Opportunity]

	measure AvgPrice = DIVIDE(SUM(BIDataSet_Opportunity[EstimatedAnnualrevenue]),SUM(BIDataSet_Opportunity[EstimatedAnnualVolume]),0)
		formatString: 0
		lineageTag: e54a1da5-e7d9-4b64-ba23-6c78c2468612

		changedProperty = Name

	measure 'EstimatedAnnualrevenue running total in CloseByDate' =
			
			CALCULATE(
				SUM('BIDataSet_Opportunity'[EstimatedAnnualrevenue]),
				FILTER(
					ALLSELECTED('BIDataSet_Opportunity'[CloseByDate]),
					ISONORAFTER('BIDataSet_Opportunity'[CloseByDate], MAX('BIDataSet_Opportunity'[CloseByDate]), DESC)
				)
			)
		lineageTag: eae6dc28-8f3e-4c76-9aa2-0c874448d0d2

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EstimatedAnnualVolume running total in CloseByDate' =
			
			CALCULATE(
				SUM('BIDataSet_Opportunity'[EstimatedAnnualVolume]),
				FILTER(
					ALLSELECTED('BIDataSet_Opportunity'[CloseByDate]),
					ISONORAFTER('BIDataSet_Opportunity'[CloseByDate], MAX('BIDataSet_Opportunity'[CloseByDate]), DESC)
				)
			)
		formatString: 0
		lineageTag: 9060ed21-3c72-4d18-a717-684cd14e6d78

		changedProperty = Name

	column OpportunityID
		dataType: string
		lineageTag: 470cd46f-9bfe-4077-9d7c-4465b21d4895
		sourceLineageTag: OpportunityID
		summarizeBy: none
		sourceColumn: OpportunityID

		annotation SummarizationSetBy = Automatic

	column RecordType
		dataType: string
		lineageTag: 181a6147-fbe1-4117-ae20-92981be74ccd
		sourceLineageTag: RecordType
		summarizeBy: none
		sourceColumn: RecordType

		annotation SummarizationSetBy = Automatic

	column GMAccountno
		dataType: string
		lineageTag: e08616e1-6f93-4f5b-a5b2-23ca06e33371
		sourceLineageTag: GMAccountno
		summarizeBy: none
		sourceColumn: GMAccountno

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: ad8dac55-f443-4503-81a0-dc69f71a4e6f
		sourceLineageTag: Manager
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 728e6575-ca13-44a6-aada-3a14d3c62fb6
		sourceLineageTag: Company
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Contact
		dataType: string
		lineageTag: 770d6d32-b632-4cec-ae58-3e1d45d9181d
		sourceLineageTag: Contact
		summarizeBy: none
		sourceColumn: Contact

		annotation SummarizationSetBy = Automatic

	column RecordStatus
		dataType: string
		lineageTag: d44f6598-ace0-43dc-a48e-a6e2f5850c82
		sourceLineageTag: RecordStatus
		summarizeBy: none
		sourceColumn: RecordStatus

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 7fe00bbb-7ea5-4d5f-8b07-db8d87d9131b
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column OPP_SID
		dataType: int64
		formatString: 0
		lineageTag: 8d7510ae-ef8b-4b01-8970-005e58d836dc
		sourceLineageTag: OPP_SID
		summarizeBy: count
		sourceColumn: OPP_SID

		annotation SummarizationSetBy = Automatic

	column cloudCRMLink
		dataType: string
		lineageTag: 859526e2-e662-4fdb-b16f-376122d3c8e8
		sourceLineageTag: cloudCRMLink
		summarizeBy: none
		sourceColumn: cloudCRMLink

		annotation SummarizationSetBy = Automatic

	column LOPID
		dataType: string
		lineageTag: ebc7c898-4a5b-42a0-89d5-491fc83af0f2
		sourceLineageTag: LOPID
		summarizeBy: none
		sourceColumn: LOPID

		annotation SummarizationSetBy = Automatic

	column OpportunityType
		dataType: string
		lineageTag: b43998f5-45f1-4e73-a3fc-fff21040e2f5
		sourceLineageTag: OpportunityType
		summarizeBy: none
		sourceColumn: OpportunityType

		annotation SummarizationSetBy = Automatic

	column SpecificApplication
		dataType: string
		lineageTag: f3568242-e505-4b17-afca-025972926408
		sourceLineageTag: SpecificApplication
		summarizeBy: none
		sourceColumn: SpecificApplication

		annotation SummarizationSetBy = Automatic

	column TargetPrice
		dataType: string
		lineageTag: 9f7a3822-2e4e-49c3-a0bd-6673f19f087c
		sourceLineageTag: TargetPrice
		summarizeBy: none
		sourceColumn: TargetPrice

		annotation SummarizationSetBy = Automatic

	column OpportunityPriority
		dataType: string
		lineageTag: 51fa6c1f-f59b-47ba-99f9-1c34ff3bef4b
		sourceLineageTag: OpportunityPriority
		summarizeBy: none
		sourceColumn: OpportunityPriority

		annotation SummarizationSetBy = Automatic

	column RecordID
		dataType: string
		lineageTag: 8a5858c1-7ca8-48b1-b509-f9fe6820c728
		sourceLineageTag: RecordID
		summarizeBy: none
		sourceColumn: RecordID

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveStartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 3318f4da-e5c4-45b8-b033-aec040abdca3
		sourceLineageTag: RecordEffectiveStartDate
		summarizeBy: none
		sourceColumn: RecordEffectiveStartDate

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveEndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: bcaf9bb1-0fc6-4200-b3d8-c623024ea63c
		sourceLineageTag: RecordEffectiveEndDate
		summarizeBy: none
		sourceColumn: RecordEffectiveEndDate

		annotation SummarizationSetBy = Automatic

	column CloseByDate
		dataType: dateTime
		formatString: General Date
		lineageTag: c6565249-8726-4dcf-aab2-a9d31a1faa95
		sourceLineageTag: CloseByDate
		summarizeBy: none
		sourceColumn: CloseByDate

		annotation SummarizationSetBy = Automatic

	column Probability
		dataType: int64
		formatString: 0
		lineageTag: 54872c3d-3bd3-40c1-9adf-1eac96bd48ad
		sourceLineageTag: Probability
		summarizeBy: sum
		sourceColumn: Probability

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: cc19a7fa-7530-4308-a2b4-f2cab5aa10b7
		sourceLineageTag: Notes
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 5527c1f9-cd83-4412-a56d-664fb66c1cce
		sourceLineageTag: ProductName
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column DesiredCharacteristics
		dataType: string
		lineageTag: 9d5aea61-19d8-440c-a5da-cfe1c6127da4
		sourceLineageTag: DesiredCharacteristics
		summarizeBy: none
		sourceColumn: DesiredCharacteristics

		annotation SummarizationSetBy = Automatic

	column EstimatedAnnualVolume
		dataType: double
		formatString: #,0.00
		lineageTag: 9dbddb67-7f87-4d59-9395-1de9ec0e7241
		sourceLineageTag: EstimatedAnnualVolume
		summarizeBy: sum
		sourceColumn: EstimatedAnnualVolume

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column Opportunity
		dataType: string
		lineageTag: dd283957-37bd-41dd-9a27-a8a9c6be6828
		sourceLineageTag: Opportunity
		summarizeBy: none
		sourceColumn: Opportunity

		annotation SummarizationSetBy = Automatic

	column OpportunityStatus
		dataType: string
		lineageTag: 64c147e9-5532-426d-9594-31229dd35269
		sourceLineageTag: OpportunityStatus
		summarizeBy: none
		sourceColumn: OpportunityStatus

		annotation SummarizationSetBy = Automatic

	column OpportunityStage
		dataType: string
		lineageTag: 4cc12088-32d4-4951-8b72-9923eeda7ccc
		sourceLineageTag: OpportunityStage
		summarizeBy: none
		sourceColumn: OpportunityStage

		annotation SummarizationSetBy = Automatic

	column OpportunityIndustry
		dataType: string
		lineageTag: 16bcaff7-6411-4f54-939d-557274eb1bf1
		sourceLineageTag: OpportunityIndustry
		summarizeBy: none
		sourceColumn: OpportunityIndustry

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 96993dcb-ec4d-441a-b424-eb363b7e1416
		sourceLineageTag: StartDate
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

	column ClosedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 3611bc5d-de8c-4edc-bee3-8be80c528eff
		sourceLineageTag: ClosedDate
		summarizeBy: none
		sourceColumn: ClosedDate

		annotation SummarizationSetBy = Automatic

	column EstimatedAnnualrevenue
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d8ce5ef9-6b83-4b7c-93d4-c0a8cab34388
		sourceLineageTag: EstimatedAnnualrevenue
		summarizeBy: sum
		sourceColumn: EstimatedAnnualrevenue

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Office
		dataType: string
		lineageTag: 9ba524c2-0c89-4be4-aeb6-380d5a087085
		sourceLineageTag: Office
		summarizeBy: none
		sourceColumn: Office

		annotation SummarizationSetBy = Automatic

	column 'Probable Value'
		dataType: double
		lineageTag: 2ecbe85b-75c0-447d-94c5-e045a5dd55f2
		sourceLineageTag: Probable Value
		summarizeBy: sum
		sourceColumn: Probable Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition BIDataSet_Opportunity = entity
		mode: directLake
		source
			entityName: mtbl_LEG_BIDataSet_Opportunity
			schemaName: dbo
			expressionSource: 'DirectLake - WH_Curated'

	changedProperty = Name

