-- Auto Generated (Do not modify) D4AA8D69C6A1F8F375F07670C34EED06D73DA581B8535AD1A9A1CF3ADEE6960A

	CREATE   VIEW  DefaultDimensionView
	AS
		SELECT
			T1.DISPLAYVALUE AS DISPLAYVALUE
			, T1.DIMENSIONATTRIBUTEVALUESET AS DEFAULTDIMENSION
			, T1.RECID AS TABLERECID
			, T1.PARTITION AS PARTITION
			, T1.RECID AS RECID
			, T2.ENTITYINSTANCE AS ENTITYINSTANCE
			, T2.PARTITION AS PARTITION#2
			, T3.REPORTCOLUMNNAME AS REPORTCOLUMNNAME
			, T3.RECID AS DIMENSIONATTRIBUTEID
			, T3.BACKINGENTITYTYPE AS BACKINGENTITYTYPE
			, T3.KEYATTRIBUTE AS KEYATTRIBUTE
			, T3.NAMEATTRIBUTE AS NAMEATTRIBUTE
			, T3.NAME AS NAME
			, T3.PARTITION AS PARTITION#3
		FROM DIMENSIONATTRIBUTEVALUESETITEM T1
		CROSS JOIN DIMENSIONATTRIBUTEVALUE T2
		CROSS JOIN DIMENSIONATTRIBUTE T3
		WHERE (
				(
					(T1.DIMENSIONATTRIBUTEVALUE = T2.RECID)
					AND (T1.PARTITION = T2.PARTITION)
					)
				AND (
					(T2.DIMENSIONATTRIBUTE = T3.RECID)
					AND (T2.PARTITION = T3.PARTITION)
					)
				)