
	CREATE   VIEW  [DIMATTRIBUTEOMDEPARTMENT]
	AS
		SELECT
			T1.RECID AS KEY_
			, T1.OMOPERATINGUNITNUMBER AS VALUE
			, T1.PARTITION AS PARTITION
			, T1.RECID AS RECID
			, T2.NAME AS NAME
			, T2.PARTITION AS PARTITION#2
		FROM DIRPARTYTABLE T1
		CROSS JOIN DIRPARTYTABLE T2
		WHERE (
				(
					(T1.OMOPERATINGUNITTYPE = 1)
					AND (
						(T1.RECID = T2.RECID)
						AND (T1.PARTITION = T2.PARTITION)
						)
					)
				)

GO

