
	CREATE   VIEW ECORESPRODUCTATTRIBUTEVALUE
	AS
	SELECT T1.VALUE AS VALUE
		,T1.ATTRIBUTE AS ATTRIBUTE
		,T1.PARTITION AS PARTITION
		,T1.RECID AS RECID
		,T2.PRODUCT AS PRODUCT
		,T2.PARTITION AS PARTITION#2
	FROM ECORESATTRIBUTEVALUE T1
	CROSS JOIN ECORESINSTANCEVALUE T2
	WHERE (
			(
				(T1.INSTANCEVALUE = T2.RECID)
				AND (T1.PARTITION = T2.PARTITION)
				)
		--	AND T2.INSTANCERELATIONTYPE IN (3885)
			)

GO

