
	CREATE   VIEW  [LOGISTICSADDRESSCOUNTRYREGTRANSLFILTERED]
	AS
		SELECT
			T1.COUNTRYREGIONID AS COUNTRYREGIONID
			, T1.LANGUAGEID AS LANGUAGEID
			, T1.SHORTNAME AS SHORTNAME
			, T1.RECID AS TABLERECID
			, T1.PARTITION AS PARTITION
			, T1.RECID AS RECID
			, T2.PARTITION AS PARTITION#2
		FROM LOGISTICSADDRESSCOUNTRYREGIONTRANSLATION T1
		CROSS JOIN SYSTEMPARAMETERS T2
		WHERE (
				(T1.LANGUAGEID = T2.SYSTEMLANGUAGEID)
				AND (T1.PARTITION = T2.PARTITION)
				)

GO

