
	CREATE   VIEW  salesline 
	AS
	SELECT [salesline].[Id] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [Id]
		,[salesline].[SinkCreatedOn] AS [SinkCreatedOn]
		,[salesline].[SinkModifiedOn] AS [SinkModifiedOn]
		,[salesline].[agreementskipautolink] AS [agreementskipautolink]
		,[salesline].[blocked] AS [blocked]
		,[salesline].[casetagging] AS [casetagging]
		,[salesline].[complete] AS [complete]
		,[salesline].[deliverydatecontroltype] AS [deliverydatecontroltype]
		,[salesline].[deliverytype] AS [deliverytype]
		,[salesline].[intercompanyorigin] AS [intercompanyorigin]
		,[salesline].[inventreftype] AS [inventreftype]
		,[salesline].[itemreplaced] AS [itemreplaced]
		,[salesline].[itemtagging] AS [itemtagging]
		,[salesline].[linedeliverytype] AS [linedeliverytype]
		,[salesline].[pallettagging] AS [pallettagging]
		,[salesline].[pdsbatchattribautores] AS [pdsbatchattribautores]
		,[salesline].[pdsexcludefromrebate] AS [pdsexcludefromrebate]
		,[salesline].[pdssamelot] AS [pdssamelot]
		,[salesline].[pdssamelotoverride] AS [pdssamelotoverride]
		,[salesline].[reservation] AS [reservation]
		,[salesline].[returnallowreservation] AS [returnallowreservation]
		,[salesline].[returnstatus] AS [returnstatus]
		,[salesline].[salesstatus] AS [salesstatus]
		,[salesline].[salestype] AS [salestype]
		,[salesline].[scrap] AS [scrap]
		,[salesline].[shipcarrierdlvtype] AS [shipcarrierdlvtype]
		,[salesline].[skipupdate] AS [skipupdate]
		,[salesline].[stattriangulardeal] AS [stattriangulardeal]
		,[salesline].[stockedproduct] AS [stockedproduct]
		,[salesline].[systementrysource] AS [systementrysource]
		,[salesline].[taxautogenerated] AS [taxautogenerated]
		,[salesline].[skipcreatemarkup] AS [skipcreatemarkup]
		,[salesline].[sourcingorigin] AS [sourcingorigin]
		,[salesline].[skipdefaultingsourcingvendor] AS [skipdefaultingsourcingvendor]
		,[salesline].[skipintercompanypurchorderaccountingdistribution] AS [skipintercompanypurchorderaccountingdistribution]
		,[salesline].[syncpurchline] AS [syncpurchline]
		,[salesline].[syncintercompanypurchline] AS [syncintercompanypurchline]
		,[salesline].[skipdeliveryscheduleupdate] AS [skipdeliveryscheduleupdate]
		,[salesline].[skipassigninventtransid] AS [skipassigninventtransid]
		,[salesline].[autocreateintercompanyorders] AS [autocreateintercompanyorders]
		,[salesline].[skippricedisccalc] AS [skippricedisccalc]
		,[salesline].[consignment_mx] AS [consignment_mx]
		,[salesline].[samples_mx] AS [samples_mx]
		,[salesline].[mcrmarginupdated] AS [mcrmarginupdated]
		,[salesline].[salessalesordercreationmethod] AS [salessalesordercreationmethod]
		,[salesline].[overridesalestax] AS [overridesalestax]
		,[salesline].[inventoryserviceautooffset] AS [inventoryserviceautooffset]
		,[salesline].[mpsfullrunctpstatus] AS [mpsfullrunctpstatus]
		,[salesline].[softreserveblocklevel] AS [softreserveblocklevel]
		,[salesline].[issoftreservedexternally] AS [issoftreservedexternally]
		,[salesline].[skippricedisccalcinbulkcreation] AS [skippricedisccalcinbulkcreation]
		,[salesline].[isintegration] AS [isintegration]
		,[salesline].[mpsexcludesalesline] AS [mpsexcludesalesline]
		,[salesline].[mpsupdateexcludesalesline] AS [mpsupdateexcludesalesline]
		,[salesline].[skippricedisccalconimport] AS [skippricedisccalconimport]
		,[salesline].[salesorderintegrationcreationtype] AS [salesorderintegrationcreationtype]
		,[salesline].[defaultlinenumberfromlinecreationsequencenumber] AS [defaultlinenumberfromlinecreationsequencenumber]
		,[salesline].[keepsalespriceandsetdiscount] AS [keepsalespriceandsetdiscount]
		,[salesline].[goodsforfree_it] AS [goodsforfree_it]
		,[salesline].[servicelinetype_it] AS [servicelinetype_it]
		,[salesline].[bundlelinestatus] AS [bundlelinestatus]
		,[salesline].[bundlelinetype] AS [bundlelinetype]
		,[salesline].[domprocessed] AS [domprocessed]
		,[salesline].[domignore] AS [domignore]
		,[salesline].[domexceptiontype] AS [domexceptiontype]
		,[salesline].[kittingskipupdatehelper] AS [kittingskipupdatehelper]
		,[salesline].[tamrebateexcluderebatemanagement] AS [tamrebateexcluderebatemanagement]
		,[salesline].[subbillrevenuesplit] AS [subbillrevenuesplit]
		,[salesline].[subbillrevenuesplitallocationmethod] AS [subbillrevenuesplitallocationmethod]
		,[salesline].[subbillisrevenuesplitchild] AS [subbillisrevenuesplitchild]
		,[salesline].[subbillissplitbilling] AS [subbillissplitbilling]
		,[salesline].[subbillistermsplit] AS [subbillistermsplit]
		,[salesline].[unbilledrevenuecredit] AS [unbilledrevenuecredit]
		,[salesline].[revrecbundle] AS [revrecbundle]
		,[salesline].[revrecisbundlecomponent] AS [revrecisbundlecomponent]
		,[salesline].[revrecbundlesalesstatus] AS [revrecbundlesalesstatus]
		,[salesline].[isfreeitemline] AS [isfreeitemline]
		,[salesline].[sysdatastatecode] AS [sysdatastatecode]
		,[salesline].[activitynumber] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [activitynumber]
		,[salesline].[addressrefrecid] AS [addressrefrecid]
		,[salesline].[addressreftableid] AS [addressreftableid]
		,[salesline].[assetid_ru] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [assetid_ru]
		,[salesline].[barcode] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [barcode]
		,[salesline].[barcodetype] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [barcodetype]
		,[salesline].[confirmeddlv] AS [confirmeddlv]
		,[salesline].[costprice] AS [costprice]
		,[salesline].[countryregionname_ru] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [countryregionname_ru]
		,[salesline].[countyorigdest] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [countyorigdest]
		,[salesline].[creditnoteinternalref_pl] AS [creditnoteinternalref_pl]
		,[salesline].[creditnotereasoncode] AS [creditnotereasoncode]
		,[salesline].[currencycode] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [currencycode]
		,[salesline].[custaccount] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [custaccount]
		,[salesline].[custgroup] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [custgroup]
		,[salesline].[customerlinenum] AS [customerlinenum]
		,[salesline].[customerref] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [customerref]
		,[salesline].[customsdocdate_mx] AS [customsdocdate_mx]
		,[salesline].[customsdocnumber_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [customsdocnumber_mx]
		,[salesline].[customsname_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [customsname_mx]
		,[salesline].[defaultdimension] AS [defaultdimension]
		,[salesline].[deliveryname] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [deliveryname]
		,[salesline].[deliverypostaladdress] AS [deliverypostaladdress]
		,[salesline].[deliverytaxgroup_br] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [deliverytaxgroup_br]
		,[salesline].[deliverytaxitemgroup_br] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [deliverytaxitemgroup_br]
		,[salesline].[dlvmode] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [dlvmode]
		,[salesline].[dlvterm] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [dlvterm]
		,[salesline].[einvoiceaccountcode] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [einvoiceaccountcode]
		,[salesline].[expectedretqty] AS [expectedretqty]
		,[salesline].[externalitemid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [externalitemid]
		,[salesline].[intercompanyinventtransid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [intercompanyinventtransid]
		,[salesline].[intrastatfulfillmentdate_hu] AS [intrastatfulfillmentdate_hu]
		,[salesline].[inventdelivernow] AS [inventdelivernow]
		,[salesline].[inventdimid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [inventdimid]
		,[salesline].[inventrefid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [inventrefid]
		,[salesline].[inventreftransid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [inventreftransid]
		,[salesline].[inventtransid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [inventtransid]
		,[salesline].[inventtransidreturn] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [inventtransidreturn]
		,[salesline].[invoicegtdid_ru] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [invoicegtdid_ru]
		,[salesline].[itembomid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [itembomid]
		,[salesline].[itemid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [itemid]
		,[salesline].[itemrouteid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [itemrouteid]
		,[salesline].[ledgerdimension] AS [ledgerdimension]
		,[salesline].[lineamount] AS [lineamount]
		,[salesline].[linedisc] AS [linedisc]
		,[salesline].[lineheader] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [lineheader]
		,[salesline].[linenum] AS [linenum]
		,[salesline].[linepercent] AS [linepercent]
		,[salesline].[manualentrychangepolicy] AS [manualentrychangepolicy]
		,[salesline].[matchingagreementline] AS [matchingagreementline]
		,[salesline].[mcrorderline2pricehistoryref] AS [mcrorderline2pricehistoryref]
		,[salesline].[multilndisc] AS [multilndisc]
		,[salesline].[multilnpercent] AS [multilnpercent]
		,[salesline].[name] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [name]
		,[salesline].[overdeliverypct] AS [overdeliverypct]
		,[salesline].[packingunit] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [packingunit]
		,[salesline].[packingunitqty] AS [packingunitqty]
		,[salesline].[pdscwexpectedretqty] AS [pdscwexpectedretqty]
		,[salesline].[pdscwinventdelivernow] AS [pdscwinventdelivernow]
		,[salesline].[pdscwqty] AS [pdscwqty]
		,[salesline].[pdscwremaininventfinancial] AS [pdscwremaininventfinancial]
		,[salesline].[pdscwremaininventphysical] AS [pdscwremaininventphysical]
		,[salesline].[pdsitemrebategroupid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [pdsitemrebategroupid]
		,[salesline].[port] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [port]
		,[salesline].[postingprofile_ru] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [postingprofile_ru]
		,[salesline].[priceagreementdate_ru] AS [priceagreementdate_ru]
		,[salesline].[priceunit] AS [priceunit]
		,[salesline].[projcategoryid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [projcategoryid]
		,[salesline].[projid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [projid]
		,[salesline].[projlinepropertyid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [projlinepropertyid]
		,[salesline].[projtransid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [projtransid]
		,[salesline].[propertynumber_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [propertynumber_mx]
		,[salesline].[psacontractlinenum] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [psacontractlinenum]
		,[salesline].[psaprojproposalinventqty] AS [psaprojproposalinventqty]
		,[salesline].[psaprojproposalqty] AS [psaprojproposalqty]
		,[salesline].[purchorderformnum] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [purchorderformnum]
		,[salesline].[qtyordered] AS [qtyordered]
		,[salesline].[receiptdateconfirmed] AS [receiptdateconfirmed]
		,[salesline].[receiptdaterequested] AS [receiptdaterequested]
		,[salesline].[refreturninvoicetrans_w] AS [refreturninvoicetrans_w]
		,[salesline].[remaininventfinancial] AS [remaininventfinancial]
		,[salesline].[remaininventphysical] AS [remaininventphysical]
		,[salesline].[remainsalesfinancial] AS [remainsalesfinancial]
		,[salesline].[remainsalesphysical] AS [remainsalesphysical]
		,[salesline].[retailblockqty] AS [retailblockqty]
		,[salesline].[retailvariantid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [retailvariantid]
		,[salesline].[returnarrivaldate] AS [returnarrivaldate]
		,[salesline].[returncloseddate] AS [returncloseddate]
		,[salesline].[returndeadline] AS [returndeadline]
		,[salesline].[returndispositioncodeid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [returndispositioncodeid]
		,[salesline].[salescategory] AS [salescategory]
		,[salesline].[salesdelivernow] AS [salesdelivernow]
		,[salesline].[salesgroup] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [salesgroup]
		,[salesline].[salesid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [salesid]
		,[salesline].[salesmarkup] AS [salesmarkup]
		,[salesline].[salesprice] AS [salesprice]
		,[salesline].[salesqty] AS [salesqty]
		,[salesline].[salesunit] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [salesunit]
		,[salesline].[serviceorderid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [serviceorderid]
		,[salesline].[shipcarrieraccount] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [shipcarrieraccount]
		,[salesline].[shipcarrieraccountcode] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [shipcarrieraccountcode]
		,[salesline].[shipcarrierid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [shipcarrierid]
		,[salesline].[shipcarriername] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [shipcarriername]
		,[salesline].[shipcarrierpostaladdress] AS [shipcarrierpostaladdress]
		,[salesline].[shippingdateconfirmed] AS [shippingdateconfirmed]
		,[salesline].[shippingdaterequested] AS [shippingdaterequested]
		,[salesline].[sourcedocumentline] AS [sourcedocumentline]
		,[salesline].[statisticvalue_lt] AS [statisticvalue_lt]
		,[salesline].[statprocid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [statprocid]
		,[salesline].[systementrychangepolicy] AS [systementrychangepolicy]
		,[salesline].[taxgroup] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [taxgroup]
		,[salesline].[taxitemgroup] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [taxitemgroup]
		,[salesline].[taxwithholdgroup] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [taxwithholdgroup]
		,[salesline].[taxwithholditemgroupheading_th] AS [taxwithholditemgroupheading_th]
		,[salesline].[transactioncode] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [transactioncode]
		,[salesline].[transport] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [transport]
		,[salesline].[underdeliverypct] AS [underdeliverypct]
		,[salesline].[intrastatcommodity] AS [intrastatcommodity]
		,[salesline].[origcountryregionid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [origcountryregionid]
		,[salesline].[origstateid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [origstateid]
		,[salesline].[sourcingcompanyid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [sourcingcompanyid]
		,[salesline].[sourcinginventsiteid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [sourcinginventsiteid]
		,[salesline].[sourcinginventlocationid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [sourcinginventlocationid]
		,[salesline].[sourcingvendaccount] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [sourcingvendaccount]
		,[salesline].[orderlinereference_no] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [orderlinereference_no]
		,[salesline].[linecreationsequencenumber] AS [linecreationsequencenumber]
		,[salesline].[satproductcode_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [satproductcode_mx]
		,[salesline].[satunitcode_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [satunitcode_mx]
		,[salesline].[accountingdistributiontemplate] AS [accountingdistributiontemplate]
		,[salesline].[satcustomsqty_mx] AS [satcustomsqty_mx]
		,[salesline].[satcustomunitofmeasure_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [satcustomunitofmeasure_mx]
		,[salesline].[sattarifffraction_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [sattarifffraction_mx]
		,[salesline].[mcrmarginpercent] AS [mcrmarginpercent]
		,[salesline].[projfundingsource] AS [projfundingsource]
		,[salesline].[planningpriority] AS [planningpriority]
		,[salesline].[inventoryservicereservationid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [inventoryservicereservationid]
		,[salesline].[fintag] AS [fintag]
		,[salesline].[inventoryserviceadjustmentoffsetdatasource] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [inventoryserviceadjustmentoffsetdatasource]
		,[salesline].[inventoryserviceadjustmentoffsetphysicalmeasure] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [inventoryserviceadjustmentoffsetphysicalmeasure]
		,[salesline].[pricedisclookupcachekey] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [pricedisclookupcachekey]
		,[salesline].[taxid] AS [taxid]
		,[salesline].[createdbyparmid_it] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [createdbyparmid_it]
		,[salesline].[prepaymentrecid_it] AS [prepaymentrecid_it]
		,[salesline].[eximports_in] AS [eximports_in]
		,[salesline].[eximproductgroup_in] AS [eximproductgroup_in]
		,[salesline].[customsmaterialtype_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [customsmaterialtype_mx]
		,[salesline].[customsdocumenttype_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [customsdocumenttype_mx]
		,[salesline].[materialdescription_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [materialdescription_mx]
		,[salesline].[identifiercustomsdocument_mx] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [identifiercustomsdocument_mx]
		,[salesline].[domiterations] AS [domiterations]
		,[salesline].[domprocesseddatetime] AS [domprocesseddatetime]
		,[salesline].[domrecversion] AS [domrecversion]
		,[salesline].[tamrebatetransid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [tamrebatetransid]
		,[salesline].[subbillrevenuesplitparentlinerecid] AS [subbillrevenuesplitparentlinerecid]
		,[salesline].[subbillrevenuesplitparentamount] AS [subbillrevenuesplitparentamount]
		,[salesline].[subbilldetaillinerecid] AS [subbilldetaillinerecid]
		,[salesline].[subbilltermschedulelinerecid] AS [subbilltermschedulelinerecid]
		,[salesline].[revrecrevenuescheduleid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [revrecrevenuescheduleid]
		,[salesline].[revrecoccurrences] AS [revrecoccurrences]
		,[salesline].[revrecbundlenetamount] AS [revrecbundlenetamount]
		,[salesline].[revrecbundleparent] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [revrecbundleparent]
		,[salesline].[revrecbundleqty] AS [revrecbundleqty]
		,[salesline].[revrecbundleratio] AS [revrecbundleratio]
		,[salesline].[revreccontractenddate] AS [revreccontractenddate]
		,[salesline].[revreccontractstartdate] AS [revreccontractstartdate]
		,[salesline].[revrecbundlelinedisc] AS [revrecbundlelinedisc]
		,[salesline].[revrecbundlelinepercent] AS [revrecbundlelinepercent]
		,[salesline].[revrecbundleqtyordered] AS [revrecbundleqtyordered]
		,[salesline].[revrecbundleremaininventphysical] AS [revrecbundleremaininventphysical]
		,[salesline].[revrecbundleremainsalesphysical] AS [revrecbundleremainsalesphysical]
		,[salesline].[revrecbundlesalesprice] AS [revrecbundlesalesprice]
		,[salesline].[revrecbundlemainparent] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [revrecbundlemainparent]
		,[salesline].[gupfreeitemlinerecid] AS [gupfreeitemlinerecid]
		,[salesline].[modifieddatetime] AS [modifieddatetime]
		,[salesline].[modifiedby] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [modifiedby]
		,[salesline].[modifiedtransactionid] AS [modifiedtransactionid]
		,[salesline].[createddatetime] AS [createddatetime]
		,[salesline].[createdby] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [createdby]
		,[salesline].[createdtransactionid] AS [createdtransactionid]
		,[salesline].[dataareaid] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [dataareaid]
		,[salesline].[recversion] AS [recversion]
		,[salesline].[partition] AS [partition]
		,[salesline].[sysrowversion] AS [sysrowversion]
		,[salesline].[recid] AS [recid]
		,[salesline].[tableid] AS [tableid]
		,[salesline].[versionnumber] AS [versionnumber]
		,[salesline].[createdon] AS [createdon]
		,[salesline].[modifiedon] AS [modifiedon]
		,[salesline].[IsDelete] AS [IsDelete]
		,[salesline].[PartitionId] COLLATE Latin1_General_100_CI_AS_KS_WS_SC_UTF8 AS [PartitionId]
		,CASE [salesline].[agreementskipautolink]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS agreementskipautolink_$label
		,CASE [salesline].[autocreateintercompanyorders]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS autocreateintercompanyorders_$label
		,CASE [salesline].[blocked]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS blocked_$label
		,CASE [salesline].[bundlelinestatus]
			WHEN 4
				THEN 'Canceled'
			WHEN 3
				THEN 'Invoiced'
			WHEN 2
				THEN 'Delivered'
			WHEN 1
				THEN 'Backorder'
			WHEN 0
				THEN 'None'
			END AS bundlelinestatus_$label
		,CASE [salesline].[bundlelinetype]
			WHEN 3
				THEN 'BundleComponent'
			WHEN 2
				THEN 'NestedBundleParent'
			WHEN 1
				THEN 'BundleParent'
			WHEN 0
				THEN 'None'
			END AS bundlelinetype_$label
		,CASE [salesline].[casetagging]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS casetagging_$label
		,CASE [salesline].[complete]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS complete_$label
		,CASE [salesline].[consignment_mx]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS consignment_mx_$label
		,CASE [salesline].[defaultlinenumberfromlinecreationsequencenumber]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS defaultlinenumberfromlinecreationsequencenumber_$label
		,CASE [salesline].[deliverydatecontroltype]
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'SalesLeadTime'
			WHEN 2
				THEN 'ATP'
			WHEN 3
				THEN 'ATPPlusIssueMargin'
			WHEN 4
				THEN 'CTP'
			WHEN 5
				THEN 'FullRunCTP'
			END AS deliverydatecontroltype_$label
		,CASE [salesline].[deliverytype]
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'DropShip'
			END AS deliverytype_$label
		,CASE [salesline].[domexceptiontype]
			WHEN 14
				THEN 'InvalidCoordinatesWhenAzureMapsOnException'
			WHEN 13
				THEN 'InvalidCoordinatesWhenBingMapsOffException'
			WHEN 12
				THEN 'InvalidCoordinatesWhenBingMapsOnException'
			WHEN 11
				THEN 'OtherLineReservationFailure'
			WHEN 10
				THEN 'Generic'
			WHEN 9
				THEN 'QuantityCouldNotBeReserved'
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'NoQuantityAvailable'
			WHEN 2
				THEN 'MaximumRejections'
			WHEN 3
				THEN 'DataModificationConflict'
			WHEN 4
				THEN 'OrderLineSpecificException'
			WHEN 5
				THEN 'InvalidCostValue'
			WHEN 6
				THEN 'NoRoadRoute'
			WHEN 7
				THEN 'BingMapsFailure'
			WHEN 8
				THEN 'MaximumOrdersDataModificationConflict'
			END AS domexceptiontype_$label
		,CASE [salesline].[domignore]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS domignore_$label
		,CASE [salesline].[domprocessed]
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'Complete'
			WHEN 2
				THEN 'Exception'
			END AS domprocessed_$label
		,CASE [salesline].[goodsforfree_it]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS goodsforfree_it_$label
		,CASE [salesline].[intercompanyorigin]
			WHEN 0
				THEN 'Source'
			WHEN 1
				THEN 'Derived'
			END AS intercompanyorigin_$label
		,CASE [salesline].[inventoryserviceautooffset]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS inventoryserviceautooffset_$label
		,CASE [salesline].[inventreftype]
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'Sales'
			WHEN 2
				THEN 'Purch'
			WHEN 3
				THEN 'Production'
			WHEN 4
				THEN 'ProdLine'
			WHEN 5
				THEN 'InventJournal'
			WHEN 6
				THEN 'CRMQuotation'
			WHEN 7
				THEN 'InventTransfer'
			WHEN 8
				THEN 'FixedAsset'
			END AS inventreftype_$label
		,CASE [salesline].[isfreeitemline]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS isfreeitemline_$label
		,CASE [salesline].[isintegration]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'CDS'
			WHEN 2
				THEN 'Dynamics365Sales'
			WHEN 3
				THEN 'DataEntity'
			END AS isintegration_$label
		,CASE [salesline].[issoftreservedexternally]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS issoftreservedexternally_$label
		,CASE [salesline].[itemreplaced]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS itemreplaced_$label
		,CASE [salesline].[itemtagging]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS itemtagging_$label
		,CASE [salesline].[keepsalespriceandsetdiscount]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS keepsalespriceandsetdiscount_$label
		,CASE [salesline].[kittingskipupdatehelper]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS kittingskipupdatehelper_$label
		,CASE [salesline].[linedeliverytype]
			WHEN 2
				THEN 'DeliveryLine'
			WHEN 1
				THEN 'OrderLineWithMultipleDeliveries'
			WHEN 0
				THEN 'OrderLine'
			END AS linedeliverytype_$label
		,CASE [salesline].[mcrmarginupdated]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS mcrmarginupdated_$label
		,CASE [salesline].[mpsexcludesalesline]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS mpsexcludesalesline_$label
		,CASE [salesline].[mpsfullrunctpstatus]
			WHEN 1
				THEN 'NotReady'
			WHEN 0
				THEN 'Ready'
			END AS mpsfullrunctpstatus_$label
		,CASE [salesline].[mpsupdateexcludesalesline]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS mpsupdateexcludesalesline_$label
		,CASE [salesline].[overridesalestax]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS overridesalestax_$label
		,CASE [salesline].[pallettagging]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS pallettagging_$label
		,CASE [salesline].[pdsbatchattribautores]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS pdsbatchattribautores_$label
		,CASE [salesline].[pdsexcludefromrebate]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS pdsexcludefromrebate_$label
		,CASE [salesline].[pdssamelot]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS pdssamelot_$label
		,CASE [salesline].[pdssamelotoverride]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS pdssamelotoverride_$label
		,CASE [salesline].[reservation]
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'Automatic'
			WHEN 2
				THEN 'Explosion'
			END AS reservation_$label
		,CASE [salesline].[returnallowreservation]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS returnallowreservation_$label
		,CASE [salesline].[returnstatus]
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'Awaiting'
			WHEN 2
				THEN 'Registered'
			WHEN 3
				THEN 'Quarantine'
			WHEN 4
				THEN 'Received'
			WHEN 5
				THEN 'Invoiced'
			WHEN 6
				THEN 'Canceled'
			END AS returnstatus_$label
		,CASE [salesline].[revrecbundle]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS revrecbundle_$label
		,CASE [salesline].[revrecbundlesalesstatus]
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'Backorder'
			WHEN 2
				THEN 'Delivered'
			WHEN 3
				THEN 'Invoiced'
			WHEN 4
				THEN 'Canceled'
			END AS revrecbundlesalesstatus_$label
		,CASE [salesline].[revrecisbundlecomponent]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS revrecisbundlecomponent_$label
		,CASE [salesline].[salesorderintegrationcreationtype]
			WHEN 0
				THEN 'Unknown'
			WHEN 1
				THEN 'WinQuote'
			END AS salesorderintegrationcreationtype_$label
		,CASE [salesline].[salessalesordercreationmethod]
			WHEN 0
				THEN 'SalesOrder'
			WHEN 1
				THEN 'RetailStatement'
			END AS salessalesordercreationmethod_$label
		,CASE [salesline].[salesstatus]
			WHEN 4
				THEN 'Canceled'
			WHEN 3
				THEN 'Invoiced'
			WHEN 2
				THEN 'Delivered'
			WHEN 1
				THEN 'Open'
			WHEN 0
				THEN 'None'
			END AS salesstatus_$label
		,CASE [salesline].[salestype]
			WHEN 2
				THEN 'Subscription'
			WHEN 3
				THEN 'Sales'
			WHEN 4
				THEN 'ReturnItem'
			WHEN 5
				THEN 'DEL_Blanket'
			WHEN 6
				THEN 'ItemReq'
			WHEN 7
				THEN 'Prepayment'
			WHEN 1
				THEN 'DEL_Quotation'
			WHEN 0
				THEN 'Journal'
			END AS salestype_$label
		,CASE [salesline].[samples_mx]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS samples_mx_$label
		,CASE [salesline].[scrap]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS scrap_$label
		,CASE [salesline].[servicelinetype_it]
			WHEN 1
				THEN 'Prepayment'
			WHEN 0
				THEN 'None'
			END AS servicelinetype_it_$label
		,CASE [salesline].[shipcarrierdlvtype]
			WHEN 3
				THEN 'PickUp'
			WHEN 2
				THEN 'Air'
			WHEN 1
				THEN 'Ground'
			WHEN 0
				THEN 'Misc'
			END AS shipcarrierdlvtype_$label
		,CASE [salesline].[skipassigninventtransid]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS skipassigninventtransid_$label
		,CASE [salesline].[skipcreatemarkup]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS skipcreatemarkup_$label
		,CASE [salesline].[skipdefaultingsourcingvendor]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS skipdefaultingsourcingvendor_$label
		,CASE [salesline].[skipdeliveryscheduleupdate]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS skipdeliveryscheduleupdate_$label
		,CASE [salesline].[skipintercompanypurchorderaccountingdistribution]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS skipintercompanypurchorderaccountingdistribution_$label
		,CASE [salesline].[skippricedisccalc]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS skippricedisccalc_$label
		,CASE [salesline].[skippricedisccalcinbulkcreation]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS skippricedisccalcinbulkcreation_$label
		,CASE [salesline].[skippricedisccalconimport]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS skippricedisccalconimport_$label
		,CASE [salesline].[skipupdate]
			WHEN 3
				THEN 'Both'
			WHEN 2
				THEN 'InterCompany'
			WHEN 1
				THEN 'Internal'
			WHEN 0
				THEN 'No'
			END AS skipupdate_$label
		,CASE [salesline].[softreserveblocklevel]
			WHEN 2
				THEN 'Block'
			WHEN 1
				THEN 'Warning'
			WHEN 0
				THEN 'Ignore'
			END AS softreserveblocklevel_$label
		,CASE [salesline].[sourcingorigin]
			WHEN 3
				THEN 'ExternalVendor'
			WHEN 2
				THEN 'Intercompany'
			WHEN 1
				THEN 'Inventory'
			WHEN 0
				THEN 'Unknown'
			END AS sourcingorigin_$label
		,CASE [salesline].[stattriangulardeal]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS stattriangulardeal_$label
		,CASE [salesline].[stockedproduct]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS stockedproduct_$label
		,CASE [salesline].[subbillisrevenuesplitchild]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS subbillisrevenuesplitchild_$label
		,CASE [salesline].[subbillissplitbilling]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS subbillissplitbilling_$label
		,CASE [salesline].[subbillistermsplit]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS subbillistermsplit_$label
		,CASE [salesline].[subbillrevenuesplit]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS subbillrevenuesplit_$label
		,CASE [salesline].[subbillrevenuesplitallocationmethod]
			WHEN 0
				THEN 'VariableAmount'
			WHEN 1
				THEN 'Percentage'
			WHEN 2
				THEN 'EqualAmount'
			WHEN 3
				THEN 'ZeroAmount'
			WHEN 4
				THEN 'ZeroParentAmount'
			END AS subbillrevenuesplitallocationmethod_$label
		,CASE [salesline].[syncintercompanypurchline]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS syncintercompanypurchline_$label
		,CASE [salesline].[syncpurchline]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS syncpurchline_$label
		,CASE [salesline].[systementrysource]
			WHEN 0
				THEN 'None'
			WHEN 1
				THEN 'CopyFromSalesOrder'
			WHEN 2
				THEN 'CopyFromSalesQuotation'
			WHEN 3
				THEN 'Project'
			WHEN 4
				THEN 'SalesQuotation'
			WHEN 5
				THEN 'CopyFromPurchaseOrder'
			WHEN 6
				THEN 'RequestForQuote'
			WHEN 7
				THEN 'PurchaseReq'
			WHEN 8
				THEN 'ManualEntry'
			WHEN 9
				THEN 'Agreement'
			WHEN 11
				THEN 'ProductConfig'
			WHEN 12
				THEN 'RetailPOS'
			END AS systementrysource_$label
		,CASE [salesline].[tamrebateexcluderebatemanagement]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS tamrebateexcluderebatemanagement_$label
		,CASE [salesline].[taxautogenerated]
			WHEN 0
				THEN 'No'
			WHEN 1
				THEN 'Yes'
			END AS taxautogenerated_$label
		,CASE [salesline].[unbilledrevenuecredit]
			WHEN 1
				THEN 'Yes'
			WHEN 0
				THEN 'No'
			END AS unbilledrevenuecredit_$label
	FROM [dataverse_stiprod_cds2_workspace_unqce8cf9ab47aff01187066045bdff8].dbo.salesline
	WHERE salesline.IsDelete IS NULL

GO

