
CREATE   VIEW [dbo].[vwDefaultDimensionView]
AS
SELECT distinct
	T1.DIMENSIONATTRIBUTEVALUESET AS DEFAULTDIMENSION
	, T1.DISPLAYVALUE AS DISPLAYVALUE
	, T3.NAME AS NAME
FROM DIMENSIONATTRIBUTEVALUESETITEM T1
CROSS JOIN DIMENSIONATTRIBUTEVALUE T2
CROSS JOIN DIMENSIONATTRIBUTE T3
WHERE (
		(
			(T1.DIMENSIONATTRIBUTEVALUE = T2.RECID)
			AND (T1.PARTITION = T2.PARTITION)
			)
		AND (
			(T2.DIMENSIONATTRIBUTE = T3.RECID)
			AND (T2.PARTITION = T3.PARTITION)
			)
		)

GO

