table 'Candidate Order'
	lineageTag: 6f5117d8-4816-470e-9bcb-97d2000cf773

	column qualityorderid
		dataType: string
		lineageTag: 0e59823f-53f5-4bc2-98e7-3d78a8038162
		summarizeBy: none
		sourceColumn: qualityorderid

		annotation SummarizationSetBy = Automatic

	column BatchKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 89e89ffe-940e-4633-b3dd-5e856dca6eb8
		summarizeBy: none
		sourceColumn: BatchKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Batch Number'
		dataType: string
		lineageTag: 67293545-1f8f-4fee-8c19-e8c4a6646991
		summarizeBy: none
		sourceColumn: Batch Number

		annotation SummarizationSetBy = Automatic

	column SerialNumberKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 08e74fe3-cf21-4f03-9821-741823096763
		summarizeBy: none
		sourceColumn: SerialNumberKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Serial Number'
		dataType: string
		lineageTag: 91d8e446-dc24-43a7-90ed-fefaadf72a88
		summarizeBy: none
		sourceColumn: Serial Number

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: eab5c809-eda2-44e9-90ff-08cb9730cf7f
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Product_ID
		dataType: string
		lineageTag: 9bd443b3-54ac-4ea6-85c3-15febebe4354
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: 32006a17-a3f3-4dee-9f4f-f49df1a6e24e
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column QualityOrderStatus
		dataType: string
		lineageTag: d63d12af-fb17-4615-b97e-48ae86df5b6b
		summarizeBy: none
		sourceColumn: QualityOrderStatus

		annotation SummarizationSetBy = Automatic

	column ValidatedDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 2003401c-72d7-4a43-84ba-42cb2e5e3d18
		summarizeBy: none
		sourceColumn: ValidatedDateTime

		variation Variation
			isDefault
			relationship: 31c7a90c-4595-4fef-afb6-a507f4d4d0a5
			defaultHierarchy: LocalDateTable_3f70a1bd-ecf3-4420-af16-3cd33c59bbc4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LineCreatedDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 87bdeec6-d42a-43df-97b2-93543731f226
		summarizeBy: none
		sourceColumn: LineCreatedDateTime

		variation Variation
			isDefault
			relationship: 16cfdf8a-b4ac-45a7-87af-7ba97d85c994
			defaultHierarchy: LocalDateTable_96fd5bbd-3954-40c4-9e24-6d97c9b40662.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Candidate Order' = m
		mode: import
		source =
				let
				  Source = Sql.Database("efrhfadk6eru3b7hpy4j3xs2eu-qg2ask2keqhepf4xm5b72jokau.datawarehouse.fabric.microsoft.com", "WH_Curated", [Query = "SELECT#(lf)    f.qualityorderid,#(lf)#(lf)    f.BatchKey,#(lf)    b.[BatchID] AS [Batch Number],#(lf)#(lf)    f.SerialNumberKey,#(lf)    s.[SerialNumber] AS [Serial Number],#(lf)#(lf)    f.ProductKey,#(lf)    p.Product_ID AS [Product_ID],#(lf)    p.Product_Name AS [Product_Name],#(lf)#(lf)    MAX(f.QuaityOrderStatus) AS QuaityOrderStatus,#(lf)    MAX(f.ValidatedDateTime) AS ValidatedDateTime,#(lf)    MIN(f.LineCreatedDateTime) AS LineCreatedDateTime#(lf)#(lf)FROM dbo.mtbl_EDW_Fact_QualityOrderLineResults AS f#(lf)#(lf)LEFT JOIN [dbo].[mtbl_EDW_DIM_Batch] AS b#(lf)    ON f.BatchKey = b.BatchKey#(lf)#(lf)LEFT JOIN [WH_Curated].[dbo].[mtbl_EDW_Dim_SerialNumber] AS s#(lf)    ON f.SerialNumberKey = s.SerialNumberKey#(lf)#(lf)LEFT JOIN [WH_Curated].[dbo].[mtbl_EDW_Dim_Product] AS p#(lf)    ON f.ProductKey = p.ProductKey#(lf)#(lf)WHERE f.qualityorderid IS NOT NULL#(lf)#(lf)GROUP BY#(lf)    f.qualityorderid,#(lf)    f.BatchKey,#(lf)    b.[BatchID],#(lf)    f.SerialNumberKey,#(lf)    s.[SerialNumber],#(lf)    f.ProductKey,#(lf)    p.Product_ID,#(lf)    p.Product_Name;"]),
				  #"Renamed Columns" = Table.RenameColumns(Source, {{"QuaityOrderStatus", "QualityOrderStatus"}})
				in
				  #"Renamed Columns"

	annotation PBI_ResultType = Exception

