table 'QC Measures'
	lineageTag: ff91c694-d152-46eb-91c2-886cc9889c3a

	measure 'Reference Selection Count' =
			
			DISTINCTCOUNT ( 'Reference Order'[qualityorderid] )
		formatString: 0
		lineageTag: ddda5c84-0a51-43e8-aed3-46a51cdfb115

	measure 'Reference Quality Order ID' =
			
			SELECTEDVALUE ( 'Reference Order'[qualityorderid] )
		lineageTag: d63320f6-f405-4714-a607-3ce5a1f1d776

	measure 'Reference Order Status' =
			
			SELECTEDVALUE ( 'Reference Order'[QualityOrderStatus] )
		lineageTag: 30bb52c2-f88e-4139-8719-60f41a73eeee

	measure 'Reference Selection Status' =
			
			VAR SelectionCount =
			    [Reference Selection Count]
			VAR BatchFiltered =
			    ISFILTERED ( 'Reference Order'[Batch Number] )
			VAR SerialFiltered =
			    ISFILTERED ( 'Reference Order'[Serial Number] )
			VAR RefStatus =
			    [Reference Order Status]
			RETURN
			SWITCH (
			    TRUE (),
			    SelectionCount = 0,
			        "No reference quality order selected.",
			    SelectionCount = 1 && RefStatus = "Open",
			        "Reference order selected, but it is Open. Use a Pass or Fail quality order as the reference.",
			    SelectionCount = 1,
			        "Reference order selected.",
			    SelectionCount > 1 && BatchFiltered && NOT SerialFiltered,
			        "Batch resolves to multiple quality orders. Select a serial number.",
			    SelectionCount > 1,
			        "Selection is ambiguous. Use Quality Order ID or Batch + Serial."
			)
		lineageTag: 3b3c428a-8447-4c5c-a65c-c8f77fef6514

	measure 'Reference Is Valid' =
			
			VAR SelectionCount =
			    [Reference Selection Count]
			VAR RefStatus =
			    [Reference Order Status]
			RETURN
			IF (
			    SelectionCount = 1
			        && RefStatus <> "Open",
			    1,
			    0
			)
		formatString: 0
		lineageTag: 537452ee-9e07-4a06-a3d5-30d8dc311c49

	measure 'Candidate Quality Order ID' =
			
			SELECTEDVALUE ( 'Candidate Order'[qualityorderid] )
		lineageTag: f2fd2f04-f676-4eae-a360-f8e264b098d7

	measure 'Candidate Order Status' =
			
			SELECTEDVALUE ( 'Candidate Order'[QualityOrderStatus] )
		lineageTag: ff8e590f-bf98-4874-8d9f-3b96ad4653ce

	measure 'Candidate Is Open' =
			
			IF ( [Candidate Order Status] = "Open", 1, 0 )
		formatString: 0
		lineageTag: 08fcdcbe-b1b6-4d0a-85e8-92afff7d302e

	measure 'Reference Test Row Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			RETURN
			IF (
			    NOT ISBLANK ( RefOrder )
			        && NOT ISBLANK ( ThisTest ),
			    CALCULATE (
			        COUNTROWS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			    )
			)
		formatString: 0
		lineageTag: d94ffd7c-c209-4b2e-9f98-0200e64a7a09

	measure 'Reference Test Skipped Flag' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			VAR SkippedRows =
			    CALCULATE (
			        COUNTROWS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] ),
			        'Fact_QualityOrderLineResults'[qmsskiptest] = 1
			    )
			RETURN
			IF ( SkippedRows > 0, 1, 0 )
		formatString: 0
		lineageTag: a75a6e1c-995e-456b-a896-f8a04f8ca0ab

	measure 'Reference Required Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			RETURN
			IF (
			    [Reference Is Valid] = 1,
			    CALCULATE (
			        DISTINCTCOUNT ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { RefOrder }, 'Order Test Index'[qualityorderid] ),
			        'Order Test Index'[IsSkipped] = 0
			    )
			)
		formatString: 0
		lineageTag: b8ba2d22-6d55-49da-8ed8-db30d13a338f

	measure 'Reference Lower Limit' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			RETURN
			IF (
			    NOT ISBLANK ( RefOrder )
			        && NOT ISBLANK ( ThisTest ),
			    CALCULATE (
			        MAX ( 'Fact_QualityOrderLineResults'[lowerlimit] ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			    )
			)
		lineageTag: 7ddf52cf-76c9-4988-be58-ae1160e34e73

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reference Upper Limit' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			RETURN
			IF (
			    NOT ISBLANK ( RefOrder )
			        && NOT ISBLANK ( ThisTest ),
			    CALCULATE (
			        MAX ( 'Fact_QualityOrderLineResults'[upperlimit] ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			    )
			)
		lineageTag: 98cda5b5-20a4-46c9-8bee-c1d096acfab6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reference Test Type' =
			
			VAR HasReferenceRow =
			    [Reference Test Row Count] > 0
			VAR AxisVariable =
			    SELECTEDVALUE ( 'Test Axis'[Default Variable] )
			VAR AxisUnit =
			    SELECTEDVALUE ( 'Test Axis'[Default Unit] )
			RETURN
			SWITCH (
			    TRUE (),
			    NOT HasReferenceRow, BLANK (),
			    NOT ISBLANK ( AxisVariable ), "Outcome",
			    NOT ISBLANK ( AxisUnit ), "Numeric",
			    "Review"
			)
		lineageTag: 4610d247-2709-450c-a37e-fd351ecccb32

	measure 'Candidate Test Row Count' =
			
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			RETURN
			IF (
			    NOT ISBLANK ( CandidateOrder )
			        && NOT ISBLANK ( ThisTest ),
			    CALCULATE (
			        COUNTROWS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			    )
			)
		formatString: 0
		lineageTag: 6c6f357d-9b4e-42ea-84ed-8f9c30a77a36

	measure 'Candidate Test Skipped Flag' =
			
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			VAR SkippedRows =
			    CALCULATE (
			        COUNTROWS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] ),
			        'Fact_QualityOrderLineResults'[qmsskiptest] = 1
			    )
			RETURN
			IF ( SkippedRows > 0, 1, 0 )
		formatString: 0
		lineageTag: 961f4a66-a3d7-4e67-b40f-fdbdd009dfaf

	measure 'Candidate Numeric Result' =
			
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			RETURN
			IF (
			    NOT ISBLANK ( CandidateOrder )
			        && NOT ISBLANK ( ThisTest ),
			    CALCULATE (
			        MAX ( 'Fact_QualityOrderLineResults'[pdsorderlineresult] ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			    )
			)
		lineageTag: 6aac5ae3-63e4-4cd3-9e04-a86e925190da

	measure 'Candidate Outcome Display' =
			
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			RETURN
			IF (
			    NOT ISBLANK ( CandidateOrder )
			        && NOT ISBLANK ( ThisTest ),
			    CALCULATE (
			        SELECTEDVALUE ( 'Fact_QualityOrderLineResults'[testresultvalueoutcome] ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			    )
			)
		lineageTag: 1f2156bc-f243-4486-a94a-d58de9eb70c2

	measure 'Candidate Test Result Label' =
			
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			RETURN
			IF (
			    NOT ISBLANK ( CandidateOrder )
			        && NOT ISBLANK ( ThisTest ),
			    CALCULATE (
			        SELECTEDVALUE ( 'Fact_QualityOrderLineResults'[testresult_$label] ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			    )
			)
		lineageTag: 8a33b788-4bcf-4623-844e-95e1666b4ba6

	measure 'Candidate Result Display' =
			
			VAR TestType =
			    [Reference Test Type]
			VAR NumericResult =
			    [Candidate Numeric Result]
			VAR OutcomeResult =
			    [Candidate Outcome Display]
			VAR ResultLabel =
			    [Candidate Test Result Label]
			RETURN
			SWITCH (
			    TRUE (),
			    TestType = "Numeric" && NOT ISBLANK ( NumericResult ),
			        FORMAT ( NumericResult, "0.####" ),
			    TestType = "Outcome" && NOT ISBLANK ( OutcomeResult ),
			        OutcomeResult,
			    NOT ISBLANK ( ResultLabel ),
			        ResultLabel,
			    BLANK ()
			)
		lineageTag: 693b17ba-b789-4b13-b510-887623998cd8

	measure 'Comparison Test Status' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			
			VAR RefExists =
			    [Reference Test Row Count] > 0
			VAR RefSkipped =
			    [Reference Test Skipped Flag] = 1
			
			VAR CandidateExists =
			    [Candidate Test Row Count] > 0
			VAR CandidateSkipped =
			    [Candidate Test Skipped Flag] = 1
			VAR CandidateOpen =
			    [Candidate Order Status] = "Open"
			
			VAR TestType =
			    [Reference Test Type]
			
			VAR RefLower =
			    [Reference Lower Limit]
			VAR RefUpper =
			    [Reference Upper Limit]
			VAR CandidateValue =
			    [Candidate Numeric Result]
			
			VAR CandidateResultLabel =
			    UPPER ( TRIM ( [Candidate Test Result Label] ) )
			
			VAR HasLower =
			    NOT ISBLANK ( RefLower )
			VAR HasUpper =
			    NOT ISBLANK ( RefUpper )
			VAR HasAnyBound =
			    HasLower || HasUpper
			
			VAR WithinLower =
			    NOT HasLower
			        || CandidateValue >= RefLower
			VAR WithinUpper =
			    NOT HasUpper
			        || CandidateValue <= RefUpper
			
			VAR NumericPass =
			    NOT ISBLANK ( CandidateValue )
			        && HasAnyBound
			        && WithinLower
			        && WithinUpper
			
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( RefOrder ) || ISBLANK ( CandidateOrder ) || ISBLANK ( ThisTest ),
			        BLANK (),
			
			    NOT RefExists && CandidateExists,
			        "EXTRA",
			
			    RefSkipped,
			        "REFERENCE SKIPPED",
			
			    RefExists && NOT CandidateExists,
			        "MISSING",
			
			    CandidateOpen,
			        "OPEN",
			
			    CandidateSkipped,
			        "SKIPPED",
			
			    TestType = "Outcome" && CandidateResultLabel = "PASS",
			        "PASS",
			
			    TestType = "Outcome" && CandidateResultLabel = "FAIL",
			        "FAIL",
			
			    TestType = "Outcome",
			        "REVIEW",
			
			    TestType = "Numeric" && ISBLANK ( CandidateValue ),
			        "NO VALUE",
			
			    TestType = "Numeric" && NOT HasAnyBound,
			        "REVIEW",
			
			    TestType = "Numeric" && NumericPass,
			        "PASS",
			
			    TestType = "Numeric",
			        "FAIL",
			
			    "REVIEW"
			)
		formatString: 0
		lineageTag: 39824745-1bb9-4351-b5d5-c98d03e7c688

	measure 'Show Test Row' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR ThisTest =
			    SELECTEDVALUE ( 'Test Axis'[testid] )
			
			VAR RefExists =
			    CALCULATE (
			        COUNTROWS ( 'Order Test Index' ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { RefOrder }, 'Order Test Index'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Order Test Index'[testid] )
			    ) > 0
			
			VAR CandidateExists =
			    CALCULATE (
			        COUNTROWS ( 'Order Test Index' ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] ),
			        TREATAS ( { ThisTest }, 'Order Test Index'[testid] )
			    ) > 0
			
			RETURN
			IF (
			    NOT ISBLANK ( RefOrder )
			        && NOT ISBLANK ( CandidateOrder )
			        && ( RefExists || CandidateExists ),
			    1,
			    0
			)
		formatString: 0
		lineageTag: d8cbb570-a521-4a31-896e-4bf55f42c9cb

	measure 'Matched Reference Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			
			VAR RefTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { RefOrder }, 'Order Test Index'[qualityorderid] ),
			        'Order Test Index'[IsSkipped] = 0
			    )
			
			VAR CandidateTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] )
			    )
			
			RETURN
			IF (
			    [Reference Is Valid] = 1
			        && NOT ISBLANK ( CandidateOrder ),
			    COUNTROWS ( INTERSECT ( RefTests, CandidateTests ) )
			)
		formatString: 0
		lineageTag: 4e781bc2-0ce6-4f7f-a945-5d6607184be6

	measure 'Missing Reference Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			
			VAR RefTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { RefOrder }, 'Order Test Index'[qualityorderid] ),
			        'Order Test Index'[IsSkipped] = 0
			    )
			
			VAR CandidateTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] )
			    )
			
			RETURN
			IF (
			    [Reference Is Valid] = 1
			        && NOT ISBLANK ( CandidateOrder ),
			    COUNTROWS ( EXCEPT ( RefTests, CandidateTests ) )
			)
		formatString: 0
		lineageTag: d307c53a-6d52-44ab-9044-cd61c4f4efed

	measure 'Extra Candidate Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			
			VAR RefTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { RefOrder }, 'Order Test Index'[qualityorderid] ),
			        'Order Test Index'[IsSkipped] = 0
			    )
			
			VAR CandidateTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] )
			    )
			
			RETURN
			IF (
			    [Reference Is Valid] = 1
			        && NOT ISBLANK ( CandidateOrder ),
			    COUNTROWS ( EXCEPT ( CandidateTests, RefTests ) )
			)
		formatString: 0
		lineageTag: 93deac12-3bfa-4835-968b-aa4462d1e65d

	measure 'Failed Matched Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			
			VAR RefTests =
			    CALCULATETABLE (
			        VALUES ( 'Fact_QualityOrderLineResults'[testid] ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        'Fact_QualityOrderLineResults'[qmsskiptest] <> 1
			    )
			
			RETURN
			IF (
			    NOT ISBLANK ( RefOrder )
			        && NOT ISBLANK ( CandidateOrder ),
			    SUMX (
			        RefTests,
			        VAR ThisTest =
			            'Fact_QualityOrderLineResults'[testid]
			        VAR StatusForTest =
			            CALCULATE (
			                [Comparison Test Status],
			                TREATAS ( { ThisTest }, 'Test Axis'[testid] )
			            )
			        RETURN
			            IF ( StatusForTest = "FAIL", 1, 0 )
			    )
			)
		formatString: 0
		lineageTag: 78d62300-a09e-402e-9929-ffd1921452fc

	measure 'Incomplete Matched Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			
			VAR RefTests =
			    CALCULATETABLE (
			        VALUES ( 'Fact_QualityOrderLineResults'[testid] ),
			        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			        REMOVEFILTERS ( 'Dim_Batch' ),
			        REMOVEFILTERS ( 'Dim_Product' ),
			        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			        TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			        'Fact_QualityOrderLineResults'[qmsskiptest] <> 1
			    )
			
			RETURN
			IF (
			    NOT ISBLANK ( RefOrder )
			        && NOT ISBLANK ( CandidateOrder ),
			    SUMX (
			        RefTests,
			        VAR ThisTest =
			            'Fact_QualityOrderLineResults'[testid]
			        VAR StatusForTest =
			            CALCULATE (
			                [Comparison Test Status],
			                TREATAS ( { ThisTest }, 'Test Axis'[testid] )
			            )
			        RETURN
			            IF (
			                StatusForTest IN { "SKIPPED", "OPEN", "NO VALUE", "REVIEW" },
			                1,
			                0
			            )
			    )
			)
		formatString: 0
		lineageTag: fe8e6f30-cbf4-455f-990e-3b2bc1731e57

	measure 'Candidate Match Category' =
			
			VAR Matched =
			    [Matched Reference Test Count]
			VAR Missing =
			    [Missing Reference Test Count]
			VAR Extra =
			    [Extra Candidate Test Count]
			RETURN
			SWITCH (
			    TRUE (),
			    [Reference Is Valid] <> 1 || ISBLANK ( [Candidate Quality Order ID] ),
			        BLANK (),
			    Matched = 0,
			        "No Useful Match",
			    Missing = 0 && Extra = 0,
			        "Exact Match",
			    Missing = 0 && Extra > 0,
			        "Overrepresented",
			    Missing > 0,
			        "Underrepresented",
			    "Review"
			)
		lineageTag: cf95d2c8-79db-4188-aab7-1721946c0c66

	measure 'Candidate Relabel Decision' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR RefRequiredTests =
			    [Reference Required Test Count]
			VAR MissingTests =
			    [Missing Reference Test Count]
			VAR FailedTests =
			    [Failed Matched Test Count]
			VAR IncompleteTests =
			    [Incomplete Matched Test Count]
			VAR CandidateOpen =
			    [Candidate Order Status] = "Open"
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( RefOrder ),
			        "SELECT REFERENCE",
			    ISBLANK ( CandidateOrder ),
			        BLANK (),
			    CandidateOrder = RefOrder,
			        "REFERENCE ORDER",
			    RefRequiredTests = 0,
			        "REFERENCE HAS NO ACTIVE TESTS",
			    CandidateOpen,
			        "NEEDS TESTING",
			    FailedTests > 0,
			        "NOT ELIGIBLE",
			    MissingTests > 0 || IncompleteTests > 0,
			        "NEEDS TESTING",
			    "ELIGIBLE"
			)
		lineageTag: 173f9ed1-1dbc-46f0-8d95-ac98bddb6dda

	measure 'Candidate Score' =
			
			VAR Decision =
			    [Candidate Relabel Decision]
			VAR MatchCategory =
			    [Candidate Match Category]
			VAR Matched =
			    [Matched Reference Test Count]
			VAR Missing =
			    [Missing Reference Test Count]
			VAR Extra =
			    [Extra Candidate Test Count]
			VAR Failed =
			    [Failed Matched Test Count]
			RETURN
			SWITCH (
			    TRUE (),
			    Decision = "ELIGIBLE" && MatchCategory = "Exact Match",
			        100000 + Matched * 100,
			    Decision = "ELIGIBLE" && MatchCategory = "Overrepresented",
			        90000 + Matched * 100 - Extra,
			    Decision = "NEEDS TESTING",
			        50000 + Matched * 100 - Missing * 1000 - Extra,
			    Decision = "NOT ELIGIBLE",
			        10000 + Matched * 100 - Failed * 1000,
			    0
			)
		formatString: 0
		lineageTag: 1be5456c-d9d3-4ede-b14c-03ec7dcf10ed

	measure 'Candidate Visible by Match Mode' =
			
			VAR ModeSelection =
			    SELECTEDVALUE ( 'Match Mode'[Match Mode], "Exact + overrepresented" )
			VAR Decision =
			    [Candidate Relabel Decision]
			VAR MatchCategory =
			    [Candidate Match Category]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateIsOpen =
			    [Candidate Order Status] = "Open"
			RETURN
			IF (
			    ISBLANK ( RefOrder )
			        || ISBLANK ( CandidateOrder )
			        || CandidateOrder = RefOrder
			        || CandidateIsOpen,
			    0,
			    SWITCH (
			        TRUE (),
			        ModeSelection = "All non-open candidates", 1,
			        ModeSelection = "Exact + overrepresented"
			            && MatchCategory IN { "Exact Match", "Overrepresented" }, 1,
			        ModeSelection = "Exact only"
			            && MatchCategory = "Exact Match", 1,
			        ModeSelection = "Overrepresented only"
			            && MatchCategory = "Overrepresented", 1,
			        ModeSelection = "Underrepresented only"
			            && MatchCategory = "Underrepresented", 1,
			        ModeSelection = "Eligible only"
			            && Decision = "ELIGIBLE", 1,
			        0
			    )
			)
		formatString: 0
		lineageTag: 2b2677c7-1972-443d-8b14-d473f29ced75

	measure 'Candidate Decision Color' =
			
			SWITCH (
			    [Candidate Relabel Decision],
			    "ELIGIBLE", "#08911f",
			    "NEEDS TESTING", "#F2C811",
			    "NOT ELIGIBLE", "#D13438",
			    "REFERENCE ORDER", "#605E5C",
			    "SELECT REFERENCE", "#605E5C",
			    "#605E5C"
			)
		lineageTag: 8e3186f4-b525-48d9-9a8c-674d8ae168fd

	measure 'Comparison Status Color' =
			
			SWITCH (
			    [Comparison Test Status],
			    "PASS", "#08911f",
			    "FAIL", "#D13438",
			    "MISSING", "#F2C811",
			    "SKIPPED", "#F2C811",
			    "OPEN", "#F2C811",
			    "NO VALUE", "#F2C811",
			    "REVIEW", "#C239B3",
			    "REFERENCE SKIPPED", "#8A8886",
			    "EXTRA", "#605E5C",
			    "#605E5C"
			)
		lineageTag: 79717ff5-5403-42d0-9457-c5e2e35b014c

	measure 'Candidate Skipped Matched Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			
			VAR RefTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { RefOrder }, 'Order Test Index'[qualityorderid] ),
			        'Order Test Index'[IsSkipped] = 0
			    )
			
			VAR CandidateSkippedTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] ),
			        'Order Test Index'[IsSkipped] = 1
			    )
			
			RETURN
			IF (
			    [Reference Is Valid] = 1
			        && NOT ISBLANK ( CandidateOrder ),
			    COUNTROWS ( INTERSECT ( RefTests, CandidateSkippedTests ) )
			)
		formatString: 0
		lineageTag: a402bbc2-137b-448b-9041-0eb43b5644d1

	measure 'Candidate Coverage Status' =
			
			VAR Matched =
			    [Matched Reference Test Count]
			VAR Missing =
			    [Missing Reference Test Count]
			VAR Skipped =
			    [Candidate Skipped Matched Test Count]
			RETURN
			SWITCH (
			    TRUE (),
			    [Reference Is Valid] <> 1,
			        "Select reference",
			    ISBLANK ( [Candidate Quality Order ID] ),
			        BLANK (),
			    Matched = 0,
			        "No overlap",
			    Missing > 0,
			        "Needs testing - missing tests",
			    Skipped > 0,
			        "Needs testing - skipped tests",
			    "Complete test coverage"
			)
		lineageTag: 67cf1d78-a59d-440a-983a-92a5ae967e0b

	measure 'Candidate Coverage Score' =
			
			VAR Matched =
			    [Matched Reference Test Count]
			VAR Missing =
			    [Missing Reference Test Count]
			VAR Extra =
			    [Extra Candidate Test Count]
			VAR Skipped =
			    [Candidate Skipped Matched Test Count]
			RETURN
			SWITCH (
			    TRUE (),
			    [Reference Is Valid] <> 1, 0,
			    Matched = 0, 0,
			    Missing = 0 && Skipped = 0,
			        100000 + Matched * 100 - Extra,
			    Missing = 0 && Skipped > 0,
			        75000 + Matched * 100 - Skipped * 500 - Extra,
			    Missing > 0,
			        50000 + Matched * 100 - Missing * 1000 - Skipped * 500 - Extra,
			    0
			)
		formatString: 0
		lineageTag: 75216215-c7f7-4b04-9bdc-fcdd27f5fcd4

	measure 'Candidate Visible Fast' =
			
			VAR ModeSelection =
			    SELECTEDVALUE ( 'Match Mode'[Match Mode], "Exact + overrepresented" )
			VAR MatchCategory =
			    [Candidate Match Category]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateIsOpen =
			    SELECTEDVALUE ( 'Candidate Order'[QualityOrderStatus] ) = "Open"
			VAR Missing =
			    [Missing Reference Test Count]
			VAR Skipped =
			    [Candidate Skipped Matched Test Count]
			RETURN
			IF (
			    [Reference Is Valid] <> 1
			        || ISBLANK ( CandidateOrder )
			        || CandidateOrder = RefOrder
			        || CandidateIsOpen,
			    0,
			    SWITCH (
			        TRUE (),
			        ModeSelection = "All non-open candidates", 1,
			
			        ModeSelection = "Exact + overrepresented"
			            && MatchCategory IN { "Exact Match", "Overrepresented" }, 1,
			
			        ModeSelection = "Exact only"
			            && MatchCategory = "Exact Match", 1,
			
			        ModeSelection = "Overrepresented only"
			            && MatchCategory = "Overrepresented", 1,
			
			        ModeSelection = "Underrepresented only"
			            && MatchCategory = "Underrepresented", 1,
			
			        ModeSelection = "Complete coverage only"
			            && Missing = 0
			            && Skipped = 0
			            && MatchCategory IN { "Exact Match", "Overrepresented" }, 1,
			
			        0
			    )
			)
		formatString: 0
		lineageTag: f5342086-cb53-4af3-9f6b-a41a1f76007b

	measure 'Selected Candidate Failed Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			
			VAR RefTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { RefOrder }, 'Order Test Index'[qualityorderid] ),
			        'Order Test Index'[IsSkipped] = 0
			    )
			
			RETURN
			IF (
			    [Reference Is Valid] = 1
			        && NOT ISBLANK ( CandidateOrder ),
			    SUMX (
			        RefTests,
			        VAR ThisTest =
			            'Order Test Index'[testid]
			
			        VAR CandidateExists =
			            CALCULATE (
			                COUNTROWS ( 'Order Test Index' ),
			                REMOVEFILTERS ( 'Order Test Index' ),
			                TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Order Test Index'[testid] )
			            ) > 0
			
			        VAR CandidateSkipped =
			            CALCULATE (
			                MAX ( 'Order Test Index'[IsSkipped] ),
			                REMOVEFILTERS ( 'Order Test Index' ),
			                TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Order Test Index'[testid] )
			            ) = 1
			
			        VAR DefaultVariable =
			            LOOKUPVALUE (
			                'Test Axis'[Default Variable],
			                'Test Axis'[testid], ThisTest
			            )
			
			        VAR HasVariable =
			            NOT ISBLANK ( DefaultVariable )
			                && TRIM ( DefaultVariable & "" ) <> ""
			
			        VAR TestType =
			            IF ( HasVariable, "Outcome", "Numeric" )
			
			        VAR RefLower =
			            CALCULATE (
			                MAX ( 'Fact_QualityOrderLineResults'[lowerlimit] ),
			                REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			                REMOVEFILTERS ( 'Dim_Batch' ),
			                REMOVEFILTERS ( 'Dim_Product' ),
			                REMOVEFILTERS ( 'Dim_SerialNumber' ),
			                TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			            )
			
			        VAR RefUpper =
			            CALCULATE (
			                MAX ( 'Fact_QualityOrderLineResults'[upperlimit] ),
			                REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			                REMOVEFILTERS ( 'Dim_Batch' ),
			                REMOVEFILTERS ( 'Dim_Product' ),
			                REMOVEFILTERS ( 'Dim_SerialNumber' ),
			                TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			            )
			
			        VAR CandidateValue =
			            CALCULATE (
			                MAX ( 'Fact_QualityOrderLineResults'[pdsorderlineresult] ),
			                REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			                REMOVEFILTERS ( 'Dim_Batch' ),
			                REMOVEFILTERS ( 'Dim_Product' ),
			                REMOVEFILTERS ( 'Dim_SerialNumber' ),
			                TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			            )
			
			        VAR CandidateResultLabel =
			            UPPER (
			                TRIM (
			                    CALCULATE (
			                        SELECTEDVALUE ( 'Fact_QualityOrderLineResults'[testresult_$label] ),
			                        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			                        REMOVEFILTERS ( 'Dim_Batch' ),
			                        REMOVEFILTERS ( 'Dim_Product' ),
			                        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			                        TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			                        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			                    )
			                )
			            )
			
			        VAR NumericFails =
			            TestType = "Numeric"
			                && NOT ISBLANK ( CandidateValue )
			                && (
			                    ( NOT ISBLANK ( RefLower ) && CandidateValue < RefLower )
			                        || ( NOT ISBLANK ( RefUpper ) && CandidateValue > RefUpper )
			                )
			
			        VAR OutcomeFails =
			            TestType = "Outcome"
			                && CandidateResultLabel = "FAIL"
			
			        RETURN
			            IF (
			                CandidateExists
			                    && NOT CandidateSkipped
			                    && ( NumericFails || OutcomeFails ),
			                1,
			                0
			            )
			    )
			)
		formatString: 0
		lineageTag: 849f7a38-deb9-4c10-ae3d-375f7457efe6

	measure 'Selected Candidate Incomplete Test Count' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			
			VAR RefTests =
			    CALCULATETABLE (
			        VALUES ( 'Order Test Index'[testid] ),
			        REMOVEFILTERS ( 'Order Test Index' ),
			        TREATAS ( { RefOrder }, 'Order Test Index'[qualityorderid] ),
			        'Order Test Index'[IsSkipped] = 0
			    )
			
			RETURN
			IF (
			    [Reference Is Valid] = 1
			        && NOT ISBLANK ( CandidateOrder ),
			    SUMX (
			        RefTests,
			        VAR ThisTest =
			            'Order Test Index'[testid]
			
			        VAR CandidateExists =
			            CALCULATE (
			                COUNTROWS ( 'Order Test Index' ),
			                REMOVEFILTERS ( 'Order Test Index' ),
			                TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Order Test Index'[testid] )
			            ) > 0
			
			        VAR CandidateSkipped =
			            CALCULATE (
			                MAX ( 'Order Test Index'[IsSkipped] ),
			                REMOVEFILTERS ( 'Order Test Index' ),
			                TREATAS ( { CandidateOrder }, 'Order Test Index'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Order Test Index'[testid] )
			            ) = 1
			
			        VAR DefaultVariable =
			            LOOKUPVALUE (
			                'Test Axis'[Default Variable],
			                'Test Axis'[testid], ThisTest
			            )
			
			        VAR HasVariable =
			            NOT ISBLANK ( DefaultVariable )
			                && TRIM ( DefaultVariable & "" ) <> ""
			
			        VAR TestType =
			            IF ( HasVariable, "Outcome", "Numeric" )
			
			        VAR RefLower =
			            CALCULATE (
			                MAX ( 'Fact_QualityOrderLineResults'[lowerlimit] ),
			                REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			                REMOVEFILTERS ( 'Dim_Batch' ),
			                REMOVEFILTERS ( 'Dim_Product' ),
			                REMOVEFILTERS ( 'Dim_SerialNumber' ),
			                TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			            )
			
			        VAR RefUpper =
			            CALCULATE (
			                MAX ( 'Fact_QualityOrderLineResults'[upperlimit] ),
			                REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			                REMOVEFILTERS ( 'Dim_Batch' ),
			                REMOVEFILTERS ( 'Dim_Product' ),
			                REMOVEFILTERS ( 'Dim_SerialNumber' ),
			                TREATAS ( { RefOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			            )
			
			        VAR CandidateValue =
			            CALCULATE (
			                MAX ( 'Fact_QualityOrderLineResults'[pdsorderlineresult] ),
			                REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			                REMOVEFILTERS ( 'Dim_Batch' ),
			                REMOVEFILTERS ( 'Dim_Product' ),
			                REMOVEFILTERS ( 'Dim_SerialNumber' ),
			                TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			                TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			            )
			
			        VAR CandidateResultLabel =
			            UPPER (
			                TRIM (
			                    CALCULATE (
			                        SELECTEDVALUE ( 'Fact_QualityOrderLineResults'[testresult_$label] ),
			                        REMOVEFILTERS ( 'Fact_QualityOrderLineResults' ),
			                        REMOVEFILTERS ( 'Dim_Batch' ),
			                        REMOVEFILTERS ( 'Dim_Product' ),
			                        REMOVEFILTERS ( 'Dim_SerialNumber' ),
			                        TREATAS ( { CandidateOrder }, 'Fact_QualityOrderLineResults'[qualityorderid] ),
			                        TREATAS ( { ThisTest }, 'Fact_QualityOrderLineResults'[testid] )
			                    )
			                )
			            )
			
			        VAR HasAnyBound =
			            NOT ISBLANK ( RefLower )
			                || NOT ISBLANK ( RefUpper )
			
			        VAR IsIncomplete =
			            SWITCH (
			                TRUE (),
			                NOT CandidateExists, 0,
			                CandidateSkipped, 1,
			                TestType = "Numeric" && ISBLANK ( CandidateValue ), 1,
			                TestType = "Numeric" && NOT HasAnyBound, 1,
			                TestType = "Outcome"
			                    && NOT CandidateResultLabel IN { "PASS", "FAIL" }, 1,
			                0
			            )
			
			        RETURN
			            IsIncomplete
			    )
			)
		formatString: 0
		lineageTag: fedd67d6-6314-40f0-9e9a-d742a8dcccf2

	measure 'Selected Candidate Relabel Decision' =
			
			VAR RefOrder =
			    [Reference Quality Order ID]
			VAR CandidateOrder =
			    [Candidate Quality Order ID]
			VAR CandidateOpen =
			    SELECTEDVALUE ( 'Candidate Order'[QualityOrderStatus] ) = "Open"
			VAR RefRequiredTests =
			    [Reference Required Test Count]
			VAR MissingTests =
			    [Missing Reference Test Count]
			VAR FailedTests =
			    [Selected Candidate Failed Test Count]
			VAR IncompleteTests =
			    [Selected Candidate Incomplete Test Count]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( RefOrder ), "SELECT REFERENCE",
			    ISBLANK ( CandidateOrder ), BLANK (),
			    CandidateOrder = RefOrder, "REFERENCE ORDER",
			    RefRequiredTests = 0, "REFERENCE HAS NO ACTIVE TESTS",
			    CandidateOpen, "NEEDS TESTING",
			    FailedTests > 0, "NOT ELIGIBLE",
			    MissingTests > 0 || IncompleteTests > 0, "NEEDS TESTING",
			    "ELIGIBLE"
			)
		lineageTag: 6a0778b5-5e14-4dd9-9de6-113688654411

	column 'Measure Group'
		isHidden
		lineageTag: 203a77a4-dad0-4dfb-a2da-9d5098d3a292
		summarizeBy: none
		isNameInferred
		sourceColumn: [Measure Group]

		annotation SummarizationSetBy = Automatic

	partition 'QC Measures' = calculated
		mode: import
		source =
				
				DATATABLE (
				    "Measure Group", STRING,
				    {
				        { "QC Measures" }
				    }
				)

	annotation PBI_Id = 51bb21ad84cc4c029c8bf508621f5732

