-- Auto Generated (Do not modify) C18F9E8B37A786C7DD00852B789BE53EC000E480B61BCE78C7960251AD87E47C

	CREATE   VIEW  [LOGISTICSENTITYPOSTALADDRESSVIEW]
	AS
		SELECT
			T1.ISPRIMARY AS ISPRIMARY
			, T1.LOCATION AS LOCATION
			, T1.ENTITYLOCATION AS ENTITYLOCATION
			, T1.ENTITY AS ENTITY
			, T1.ENTITYTYPE AS ENTITYTYPE
			, T1.PARTITION AS PARTITION
			, T1.RECID AS RECID
			, T2.PARTITION AS PARTITION#2
			, T2.ADDRESS AS ADDRESS
			, T2.BUILDINGCOMPLIMENT AS BUILDINGCOMPLIMENT
			, T2.CITY AS CITY
			, T2.COUNTRYCURRENCYCODE AS COUNTRYCURRENCYCODE
			, T2.COUNTRYREGIONID AS COUNTRYREGIONID
			, T2.COUNTY AS COUNTY
			, T2.DISTRICT AS DISTRICT
			, T2.LATITUDE AS LATITUDE
			, T2.LOCATIONNAME AS LOCATIONNAME
			, T2.LONGITUDE AS LONGITUDE
			, T2.POSTBOX AS POSTBOX
			, T2.POSTALADDRESS AS POSTALADDRESS
			, T2.STATE AS STATE
			, T2.STREET AS STREET
			, T2.STREETNUMBER AS STREETNUMBER
			, T2.TIMEZONE AS TIMEZONE
			, T2.VALIDFROM AS VALIDFROM
			, T2.VALIDTO AS VALIDTO
			, T2.ZIPCODE AS ZIPCODE
		FROM LOGISTICSENTITYLOCATIONVIEW T1
		CROSS JOIN LOGISTICSPOSTALADDRESSVIEW T2
		WHERE (
				T1.LOCATION = T2.LOCATION
				AND (T1.PARTITION = T2.PARTITION)
				)