CREATE TABLE [dbo].[legacy_tbl_DIM_Product] (
    [ProductKey]                BIGINT        NULL,
    [ItemKey]                   VARCHAR (50)  NULL,
    [Desc1]                     VARCHAR (50)  NULL,
    [PrintableDesc]             VARCHAR (MAX) NULL,
    [ProdLineAcctg]             VARCHAR (50)  NULL,
    [ProductLineFunctional]     VARCHAR (50)  NULL,
    [ProductLineCategory]       VARCHAR (50)  NULL,
    [ProductFamily]             VARCHAR (50)  NULL,
    [pct_PTFEContent]           VARCHAR (50)  NULL,
    [PrimaryMfgLocation]        VARCHAR (50)  NULL,
    [PackageType]               VARCHAR (50)  NULL,
    [PackageLiner]              VARCHAR (50)  NULL,
    [PackageWeight]             VARCHAR (50)  NULL,
    [PackageTare]               VARCHAR (50)  NULL,
    [LeadTime]                  VARCHAR (50)  NULL,
    [st_ProductionStatus]       VARCHAR (50)  NULL,
    [st_ObsoletionStatus]       VARCHAR (50)  NULL,
    [ProductDescPublic]         VARCHAR (MAX) NULL,
    [ProductDescInternal]       VARCHAR (MAX) NULL,
    [ApplBenefit]               VARCHAR (MAX) NULL,
    [LevelOfAddition]           VARCHAR (MAX) NULL,
    [ExperimentalProductName]   VARCHAR (MAX) NULL,
    [BaseProduct]               VARCHAR (MAX) NULL,
    [gyro_US_InksAndCoatings]   VARCHAR (50)  NULL,
    [gyro_US_Thermoplastics]    VARCHAR (50)  NULL,
    [gyro_US_Lubricants]        VARCHAR (50)  NULL,
    [gyro_US_PersonalCare]      VARCHAR (50)  NULL,
    [gyro_US_Other]             VARCHAR (50)  NULL,
    [gyro_APAC_InksAndCoatings] VARCHAR (50)  NULL,
    [gyro_APAC_Thermoplastics]  VARCHAR (50)  NULL,
    [gyro_APAC_Lubricants]      VARCHAR (50)  NULL,
    [gyro_APAC_PersonalCare]    VARCHAR (50)  NULL,
    [gyro_APAC_Other]           VARCHAR (50)  NULL,
    [gyro_EMEA_InksAndCoatings] VARCHAR (50)  NULL,
    [gyro_EMEA_Thermoplastics]  VARCHAR (50)  NULL,
    [gyro_EMEA_Lubricants]      VARCHAR (50)  NULL,
    [gyro_EMEA_PersonalCare]    VARCHAR (50)  NULL,
    [gyro_EMEA_Other]           VARCHAR (50)  NULL,
    [RecordEffectiveStartDate]  DATETIME2 (6) NULL,
    [RecordEffectiveEndDate]    DATETIME2 (6) NULL,
    [RecordStatus]              INT           NULL,
    [Source]                    VARCHAR (10)  NULL,
    [PRD_SID]                   INT           NULL
);


GO

