CREATE TABLE [dbo].[legacy_tbl_DIM_CPC] (
    [CPCID]                    VARCHAR (50)  NULL,
    [CustomerID]               VARCHAR (50)  NULL,
    [Office]                   VARCHAR (50)  NULL,
    [Customer No]              VARCHAR (50)  NULL,
    [Ship To No]               VARCHAR (50)  NULL,
    [ProductCode]              VARCHAR (50)  NULL,
    [ProductName]              VARCHAR (50)  NULL,
    [CPCStatus]                VARCHAR (50)  NULL,
    [WonReason]                VARCHAR (50)  NULL,
    [LostReason]               VARCHAR (50)  NULL,
    [CPCClassification]        VARCHAR (50)  NULL,
    [OriginalOPID]             VARCHAR (50)  NULL,
    [CPCStage]                 VARCHAR (50)  NULL,
    [CPC Descriptive]          VARCHAR (MAX) NULL,
    [CPCType]                  VARCHAR (50)  NULL,
    [FirstOrderDate]           VARCHAR (50)  NULL,
    [MostRecentOrderDate]      VARCHAR (50)  NULL,
    [MostRecentPrice]          VARCHAR (50)  NULL,
    [Currency]                 VARCHAR (50)  NULL,
    [INCOTerms]                VARCHAR (50)  NULL,
    [Application]              VARCHAR (50)  NULL,
    [ApplicationDefinition]    VARCHAR (50)  NULL,
    [ApplicationDescription]   VARCHAR (50)  NULL,
    [DesiredCharacteristics]   VARCHAR (50)  NULL,
    [RegulatoryRequirements]   VARCHAR (50)  NULL,
    [ListPrice]                VARCHAR (50)  NULL,
    [CurrentPrice]             VARCHAR (50)  NULL,
    [CPCTier]                  VARCHAR (50)  NULL,
    [EstimatedAnnualVolume]    INT           NULL,
    [EAVUnitOfMeasure]         VARCHAR (50)  NULL,
    [EstimatedAnnualRevenue]   VARCHAR (50)  NULL,
    [EARCurrency]              VARCHAR (50)  NULL,
    [CPCIndustry]              VARCHAR (50)  NULL,
    [CPCIndustrySubSegment]    VARCHAR (50)  NULL,
    [RecordEffectiveStartDate] DATETIME2 (6) NULL,
    [RecordEffectiveEndDate]   DATETIME2 (6) NULL,
    [RecordStatus]             INT           NULL,
    [Source]                   VARCHAR (10)  NULL,
    [CPC_SID]                  INT           NULL
);


GO

