CREATE TABLE [dbo].[legacy_tbl_Dim_StandardCost] (
    [PRODUCT CODE]          VARCHAR (8000) NULL,
    [SHIPPED LBS]           VARCHAR (8000) NULL,
    [MATERIAL COST/LB]      VARCHAR (8000) NULL,
    [LABOR COST/LB]         VARCHAR (8000) NULL,
    [UTILITY COST/LB]       VARCHAR (8000) NULL,
    [OS PROCESSING COST/LB] VARCHAR (8000) NULL,
    [PACKAGING COST/LB]     VARCHAR (8000) NULL,
    [OVERHEAD COST/LB]      VARCHAR (8000) NULL
);


GO

