CREATE TABLE [dbo].[mtbl_EDW_Fact_GeneralLedgerBudget] (

	[CMPNY] varchar(8000) NULL, 
	[GL_Account] varchar(8000) NULL, 
	[date] datetime2(6) NULL, 
	[BudgetDateKey] int NULL, 
	[BudgetModel] varchar(8000) NULL, 
	[BudgetTypeDesc] varchar(7) NULL, 
	[CurrencyCode] varchar(8000) NULL, 
	[BudgetTransactionType] varchar(18) NULL, 
	[accountingcurrencyamount] decimal(38,6) NULL, 
	[accountingcurrencyamount_USD] decimal(38,6) NULL, 
	[accountingcurrencyamount_EUR] decimal(38,6) NULL, 
	[accountingcurrencyamount_CNY] decimal(38,6) NULL, 
	[transactioncurrencyamount] decimal(38,6) NULL, 
	[transactioncurrencyamount_USD] decimal(38,6) NULL, 
	[transactioncurrencyamount_EUR] decimal(38,6) NULL, 
	[transactioncurrencyamount_CNY] decimal(38,6) NULL, 
	[quantity] decimal(38,6) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[BudgetModelKey] bigint NOT NULL, 
	[DepartmentKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[Txn_Source_Currency] varchar(8000) NULL, 
	[Cost_Source_Currency] varchar(8000) NULL, 
	[Txn_USD_Rate_Missing] int NULL, 
	[Txn_EUR_Rate_Missing] int NULL, 
	[Txn_CNY_Rate_Missing] int NULL, 
	[Acct_USD_Rate_Missing] int NULL, 
	[Acct_EUR_Rate_Missing] int NULL, 
	[Acct_CNY_Rate_Missing] int NULL 
);
