CREATE TABLE [dbo].[mtbl_EDW_Fact_GeneralLedger] (

	[GL_Account] varchar(8000) NULL, 
	[GL_AccountKey] bigint NOT NULL, 
	[accountingdate] datetime2(6) NULL, 
	[accountingdatekey] int NULL, 
	[transactioncurrencyamount] decimal(38,6) NULL, 
	[accountingcurrencyamount] decimal(38,6) NULL, 
	[reportingcurrencyamount] decimal(38,6) NULL, 
	[quantity] decimal(38,6) NULL, 
	[iscorrection] bigint NULL, 
	[iscorrection_$label] varchar(3) NULL, 
	[iscredit] bigint NULL, 
	[iscredit_$label] varchar(3) NULL, 
	[transactioncurrencycode] varchar(8000) NULL, 
	[paymentreference] varchar(8000) NULL, 
	[postingtype] bigint NULL, 
	[postingtype_$label] varchar(34) NULL, 
	[ledgerdimension] bigint NULL, 
	[generaljournalentry] bigint NULL, 
	[mainaccount] bigint NULL, 
	[TEXT] varchar(8000) NULL, 
	[reasonref] bigint NULL, 
	[recid] bigint NULL, 
	[ledgeraccount] varchar(8000) NULL, 
	[documentdate] datetime2(6) NULL, 
	[createdby] varchar(8000) NULL, 
	[createddatetime] datetime2(6) NULL, 
	[fiscalcalendarperiod] bigint NULL, 
	[FiscalCalendarPeriodType] bigint NULL, 
	[FiscalCalendarPeriodType_$label] varchar(9) NULL, 
	[journalcategory] bigint NULL, 
	[journalcategory_$label] varchar(49) NULL, 
	[journalnumber] varchar(8000) NULL, 
	[ledger] bigint NULL, 
	[Legal_Entity] varchar(8000) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[ledgerentryjournal] bigint NULL, 
	[postinglayer] bigint NULL, 
	[postinglayer_$label] varchar(15) NULL, 
	[subledgervoucher] varchar(8000) NULL, 
	[subledgervoucherdataareaid] varchar(8000) NULL, 
	[lej_journalnumber] varchar(8000) NULL, 
	[ledgerjournaltabledataareaid] varchar(8000) NULL, 
	[approver] bigint NULL, 
	[dataareaid] varchar(8000) NULL, 
	[journalnum] varchar(8000) NULL, 
	[Business_Unit] varchar(8000) NULL, 
	[Department] varchar(8000) NULL, 
	[Product_Line] varchar(8000) NULL, 
	[Site] varchar(8000) NULL, 
	[DepartmentKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL
);