CREATE TABLE [dbo].[mtbl_EDW_Fact_SupplyChain_JobCard] (
    [CMPNY]                   VARCHAR (8000)   NULL,
    [ProdId]                  VARCHAR (8000)   NULL,
    [ItemId]                  VARCHAR (8000)   NULL,
    [JournalId]               VARCHAR (8000)   NULL,
    [linenum]                 DECIMAL (38, 16) NULL,
    [OprNum]                  BIGINT           NULL,
    [OprId]                   VARCHAR (8000)   NULL,
    [oprpriority]             BIGINT           NULL,
    [oprpriority_$label]      VARCHAR (11)     NULL,
    [posteddatetime]          DATETIME2 (6)    NULL,
    [JobHours]                DECIMAL (38, 6)  NULL,
    [JobQtyGood]              DECIMAL (38, 6)  NULL,
    [JobQtyError]             DECIMAL (38, 6)  NULL,
    [wrkctrid]                VARCHAR (8000)   NULL,
    [worker]                  BIGINT           NULL,
    [person]                  BIGINT           NULL,
    [personnelnumber]         VARCHAR (8000)   NULL,
    [transdate]               DATETIME2 (6)    NULL,
    [dataareaid]              VARCHAR (8000)   NULL,
    [oprfinished_$label]      VARCHAR (3)      NULL,
    [jobtype_$label]          VARCHAR (11)     NULL,
    [jobfinished_$label]      VARCHAR (3)      NULL,
    [voucher]                 VARCHAR (8000)   NULL,
    [executedpct]             DECIMAL (38, 6)  NULL,
    [jobid]                   VARCHAR (8000)   NULL,
    [inventdimid]             VARCHAR (8000)   NULL,
    [journaltype_$Label]      VARCHAR (24)     NULL,
    [fromtime]                BIGINT           NULL,
    [totime]                  BIGINT           NULL,
    [description]             VARCHAR (8000)   NULL,
    [Legal_EntityKey]         BIGINT           NOT NULL,
    [ProductKey]              BIGINT           NOT NULL,
    [ProductionBatchOrderKey] BIGINT           NOT NULL,
    [EmployeeKey]             BIGINT           NOT NULL,
    [SiteKey]                 BIGINT           NOT NULL,
    [WarehouseKey]            BIGINT           NOT NULL,
    [BatchKey]                BIGINT           NOT NULL,
    [RouteKey]                BIGINT           NOT NULL
);


GO

