CREATE TABLE [dbo].[mtbl_EDW_Fact_QualityOrderLineResults] (

	[CMPNY] varchar(8000) NULL, 
	[qualityorderid] varchar(8000) NULL, 
	[testsequence] bigint NULL, 
	[linenum] decimal(38,16) NULL, 
	[testid] varchar(8000) NULL, 
	[qmsskiptest] bigint NULL, 
	[qmsskiptest_$label] varchar(3) NULL, 
	[testresult] bigint NULL, 
	[testresult_$label] varchar(4) NULL, 
	[testresultquantity] decimal(38,6) NULL, 
	[testresultvalueoutcome] varchar(8000) NULL, 
	[testresultvaluereal] decimal(38,6) NULL, 
	[lowerlimit] decimal(38,6) NULL, 
	[lowertolerance] decimal(38,6) NULL, 
	[pdsattribvalue] varchar(8000) NULL, 
	[pdsbatchattribid] varchar(8000) NULL, 
	[pdsorderlineresult] varchar(8000) NULL, 
	[standardvalue] decimal(38,6) NULL, 
	[testinstrumentid] varchar(8000) NULL, 
	[testunitid] varchar(8000) NULL, 
	[upperlimit] decimal(38,6) NULL, 
	[uppertolerance] decimal(38,6) NULL, 
	[variableid] varchar(8000) NULL, 
	[variableoutcomeidstandard] varchar(8000) NULL, 
	[inventrefid] varchar(8000) NULL, 
	[inventsiteid] varchar(8000) NULL, 
	[inventlocationid] varchar(8000) NULL, 
	[inventbatchid] varchar(8000) NULL, 
	[inventserialid] varchar(8000) NULL, 
	[licenseplateid] varchar(8000) NULL, 
	[wmslocationid] varchar(8000) NULL, 
	[inventstatusid] varchar(8000) NULL, 
	[LineCreatedDateTime] datetime2(6) NULL, 
	[LineCreatedDateKey] int NULL, 
	[validatedbyworker] bigint NULL, 
	[ValidatedDateTime] datetime2(6) NULL, 
	[ValidatedDateKey] int NULL, 
	[accountrelation] varchar(8000) NULL, 
	[wrkctrid] varchar(8000) NULL, 
	[testgroupid] varchar(8000) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[ProductionBatchOrderKey] bigint NOT NULL, 
	[PurchaseOrderKey] bigint NOT NULL, 
	[SalesOrderKey] bigint NOT NULL, 
	[RouteKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[BatchKey] bigint NOT NULL, 
	[SerialNumberKey] bigint NOT NULL, 
	[VendorKey] bigint NOT NULL, 
	[CustomerKey] bigint NOT NULL, 
	[WorkCenterKey] bigint NOT NULL, 
	[TestGroupKey] bigint NOT NULL, 
	[QuaityOrderStatus] varchar(4) NULL
);