CREATE TABLE [dbo].[mtbl_EDW_Fact_Customer_Invoices] (
    [CMPNY]                 VARCHAR (8000)   NULL,
    [Invoice_ID]            VARCHAR (8000)   NULL,
    [InvoiceDate]           DATETIME2 (6)    NULL,
    [InvoiceDateKey]        INT              NULL,
    [Sales_ID]              VARCHAR (8000)   NULL,
    [Order_Account]         VARCHAR (8000)   NULL,
    [Invoice_Account]       VARCHAR (8000)   NULL,
    [Tax_Group]             VARCHAR (8000)   NULL,
    [Country]               VARCHAR (8000)   NULL,
    [Invoice_Line_Name]     VARCHAR (8000)   NULL,
    [InvoiceAmount]         DECIMAL (38, 6)  NULL,
    [InvoiceAmountMST]      DECIMAL (38, 6)  NULL,
    [Freight]               DECIMAL (38, 6)  NULL,
    [Fuel_Charge]           DECIMAL (38, 6)  NULL,
    [Comms]                 DECIMAL (38, 6)  NULL,
    [PLT_Brk_Ch]            DECIMAL (38, 6)  NULL,
    [Tariff_SC]             DECIMAL (38, 6)  NULL,
    [LineNumber]            DECIMAL (38, 16) NULL,
    [Product_ID]            VARCHAR (8000)   NULL,
    [Site_ID]               VARCHAR (8000)   NULL,
    [Warehouse_ID]          VARCHAR (8000)   NULL,
    [LineAmount]            DECIMAL (38, 6)  NULL,
    [LineAmountMST]         DECIMAL (38, 6)  NULL,
    [Current_Code]          VARCHAR (8000)   NULL,
    [salesunit]             VARCHAR (8000)   NULL,
    [Qty]                   DECIMAL (38, 6)  NULL,
    [Quantity_LBs]          DECIMAL (38, 6)  NULL,
    [SalesPrice]            DECIMAL (38, 6)  NULL,
    [CostAmount]            DECIMAL (38, 6)  NULL,
    [CostAmountPhysical]    DECIMAL (38, 6)  NULL,
    [Margin]                DECIMAL (38, 6)  NULL,
    [InventTransID]         VARCHAR (8000)   NULL,
    [InventDimID]           VARCHAR (8000)   NULL,
    [postedstateID]         BIGINT           NULL,
    [PostedState]           VARCHAR (12)     NULL,
    [Source]                VARCHAR (6)      NOT NULL,
    [CustomerKey]           BIGINT           NOT NULL,
    [InvoiceCustomerKey]    BIGINT           NOT NULL,
    [ProductKey]            BIGINT           NOT NULL,
    [Legal_EntityKey]       BIGINT           NOT NULL,
    [SiteKey]               BIGINT           NOT NULL,
    [StandardCostKey]       BIGINT           NULL,
    [MarketSegmentationKey] BIGINT           NOT NULL,
    [SalesOrderKey]         BIGINT           NOT NULL,
    [DeliveryAddressKey]    BIGINT           NOT NULL
);


GO

