CREATE TABLE [dbo].[mtbl_EDW_Fact_QualityOrderLineResults] (
    [CMPNY]                     VARCHAR (8000)   NULL,
    [qualityorderid]            VARCHAR (8000)   NULL,
    [testsequence]              BIGINT           NULL,
    [linenum]                   DECIMAL (38, 16) NULL,
    [testid]                    VARCHAR (8000)   NULL,
    [qmsskiptest]               BIGINT           NULL,
    [qmsskiptest_$label]        VARCHAR (3)      NULL,
    [testresult]                BIGINT           NULL,
    [testresult_$label]         VARCHAR (4)      NULL,
    [testresultquantity]        DECIMAL (38, 6)  NULL,
    [testresultvalueoutcome]    VARCHAR (8000)   NULL,
    [testresultvaluereal]       DECIMAL (38, 6)  NULL,
    [lowerlimit]                DECIMAL (38, 6)  NULL,
    [lowertolerance]            DECIMAL (38, 6)  NULL,
    [pdsattribvalue]            VARCHAR (8000)   NULL,
    [pdsbatchattribid]          VARCHAR (8000)   NULL,
    [pdsorderlineresult]        VARCHAR (8000)   NULL,
    [standardvalue]             DECIMAL (38, 6)  NULL,
    [testinstrumentid]          VARCHAR (8000)   NULL,
    [testunitid]                VARCHAR (8000)   NULL,
    [upperlimit]                DECIMAL (38, 6)  NULL,
    [uppertolerance]            DECIMAL (38, 6)  NULL,
    [variableid]                VARCHAR (8000)   NULL,
    [variableoutcomeidstandard] VARCHAR (8000)   NULL,
    [inventrefid]               VARCHAR (8000)   NULL,
    [inventsiteid]              VARCHAR (8000)   NULL,
    [inventlocationid]          VARCHAR (8000)   NULL,
    [inventbatchid]             VARCHAR (8000)   NULL,
    [inventserialid]            VARCHAR (8000)   NULL,
    [licenseplateid]            VARCHAR (8000)   NULL,
    [wmslocationid]             VARCHAR (8000)   NULL,
    [inventstatusid]            VARCHAR (8000)   NULL,
    [LineCreatedDateTime]       DATETIME2 (6)    NULL,
    [LineCreatedDateKey]        INT              NULL,
    [validatedbyworker]         BIGINT           NULL,
    [ValidatedDateTime]         DATETIME2 (6)    NULL,
    [ValidatedDateKey]          INT              NULL,
    [accountrelation]           VARCHAR (8000)   NULL,
    [wrkctrid]                  VARCHAR (8000)   NULL,
    [testgroupid]               VARCHAR (8000)   NULL,
    [Legal_EntityKey]           BIGINT           NOT NULL,
    [ProductKey]                BIGINT           NOT NULL,
    [ProductionBatchOrderKey]   BIGINT           NOT NULL,
    [PurchaseOrderKey]          BIGINT           NOT NULL,
    [SalesOrderKey]             BIGINT           NOT NULL,
    [RouteKey]                  BIGINT           NOT NULL,
    [SiteKey]                   BIGINT           NOT NULL,
    [WarehouseKey]              BIGINT           NOT NULL,
    [BatchKey]                  BIGINT           NOT NULL,
    [SerialNumberKey]           BIGINT           NOT NULL,
    [VendorKey]                 BIGINT           NOT NULL,
    [CustomerKey]               BIGINT           NOT NULL,
    [WorkCenterKey]             BIGINT           NOT NULL,
    [QuaityOrderStatus]         VARCHAR (4)      NULL
);


GO

