CREATE TABLE [dbo].[mtbl_EDW_Fact_GeneralLedger] (
    [GL_Account]                      VARCHAR (8000)  NULL,
    [GL_AccountKey]                   BIGINT          NOT NULL,
    [accountingdate]                  DATETIME2 (6)   NULL,
    [accountingdatekey]               INT             NULL,
    [transactioncurrencyamount]       DECIMAL (38, 6) NULL,
    [accountingcurrencyamount]        DECIMAL (38, 6) NULL,
    [reportingcurrencyamount]         DECIMAL (38, 6) NULL,
    [quantity]                        DECIMAL (38, 6) NULL,
    [iscorrection]                    BIGINT          NULL,
    [iscorrection_$label]             VARCHAR (3)     NULL,
    [iscredit]                        BIGINT          NULL,
    [iscredit_$label]                 VARCHAR (3)     NULL,
    [transactioncurrencycode]         VARCHAR (8000)  NULL,
    [paymentreference]                VARCHAR (8000)  NULL,
    [postingtype]                     BIGINT          NULL,
    [postingtype_$label]              VARCHAR (34)    NULL,
    [ledgerdimension]                 BIGINT          NULL,
    [generaljournalentry]             BIGINT          NULL,
    [mainaccount]                     BIGINT          NULL,
    [TEXT]                            VARCHAR (8000)  NULL,
    [reasonref]                       BIGINT          NULL,
    [recid]                           BIGINT          NULL,
    [ledgeraccount]                   VARCHAR (8000)  NULL,
    [documentdate]                    DATETIME2 (6)   NULL,
    [createdby]                       VARCHAR (8000)  NULL,
    [createddatetime]                 DATETIME2 (6)   NULL,
    [fiscalcalendarperiod]            BIGINT          NULL,
    [FiscalCalendarPeriodType]        BIGINT          NULL,
    [FiscalCalendarPeriodType_$label] VARCHAR (9)     NULL,
    [journalcategory]                 BIGINT          NULL,
    [journalcategory_$label]          VARCHAR (49)    NULL,
    [journalnumber]                   VARCHAR (8000)  NULL,
    [ledger]                          BIGINT          NULL,
    [Legal_Entity]                    VARCHAR (8000)  NULL,
    [Legal_EntityKey]                 BIGINT          NOT NULL,
    [ledgerentryjournal]              BIGINT          NULL,
    [postinglayer]                    BIGINT          NULL,
    [postinglayer_$label]             VARCHAR (15)    NULL,
    [subledgervoucher]                VARCHAR (8000)  NULL,
    [subledgervoucherdataareaid]      VARCHAR (8000)  NULL,
    [lej_journalnumber]               VARCHAR (8000)  NULL,
    [ledgerjournaltabledataareaid]    VARCHAR (8000)  NULL,
    [approver]                        BIGINT          NULL,
    [dataareaid]                      VARCHAR (8000)  NULL,
    [journalnum]                      VARCHAR (8000)  NULL,
    [Business_Unit]                   VARCHAR (8000)  NULL,
    [Department]                      VARCHAR (8000)  NULL,
    [Product_Line]                    VARCHAR (8000)  NULL,
    [Site]                            VARCHAR (8000)  NULL,
    [DepartmentKey]                   BIGINT          NOT NULL,
    [SiteKey]                         BIGINT          NOT NULL
);


GO

