CREATE TABLE [dbo].[mtbl_EDW_Dim_Date] (

	[DateKey] int NULL, 
	[RecId] bigint NULL, 
	[FiscalQuarterNum] int NULL, 
	[FiscalYear] smallint NULL, 
	[FiscalPeriodNum] int NULL, 
	[WeeksInPeriod] int NULL, 
	[FiscalWeekNum] int NULL, 
	[CalendarYear] smallint NULL, 
	[CalendarQuarterNum] int NULL, 
	[MonthNameShort] varchar(3) NULL, 
	[WeekdayNameLong] varchar(9) NULL, 
	[WeekOfYearNum] int NULL, 
	[Date] date NULL, 
	[DayOfMonthNum] int NULL, 
	[FiscalDayNum] smallint NULL, 
	[IsWorkingDayUs] bit NULL, 
	[IsWorkingDayBvba] bit NULL, 
	[IsWorkingDayTeda] bit NULL, 
	[WeekStartDate] date NULL, 
	[WeekStartDateSunday] date NULL, 
	[MonthStartDate] date NULL, 
	[CurrentFiscalDayNum] smallint NULL, 
	[CurrentFiscalYear] smallint NULL, 
	[MonthNum] int NULL, 
	[MonthNameLong] varchar(30) NULL, 
	[YearMonthNum] varchar(10) NOT NULL, 
	[YearMonthLabel] varchar(9) NULL, 
	[CalendarQuarterLabel] varchar(2) NULL, 
	[CalendarYearQuarterNum] int NULL, 
	[FiscalQuarterLabel] varchar(9) NULL, 
	[FiscalYearQuarterNum] int NULL, 
	[WeekdayNum] int NULL, 
	[WeekdayNameShort] varchar(3) NULL, 
	[YearWeekNum] int NULL, 
	[FiscalYearWeekNum] int NULL, 
	[DayOfYearNum] smallint NULL, 
	[IsWeekend] bit NULL, 
	[IsToday] int NOT NULL, 
	[IsCurrentMonth] bit NULL, 
	[IsCurrentFiscalYear] bit NULL, 
	[FiscalPeriodLabel] varchar(5) NULL, 
	[Original FISCAL YR] smallint NULL, 
	[Original FISCAL PERIOD] int NULL, 
	[Reconciliation Year] varchar(20) NULL
);