CREATE TABLE [dbo].[mtbl_EDW_BIDataSet_Opportunity] (

	[OpportunityID] varchar(50) NULL, 
	[RecordType] varchar(50) NULL, 
	[GMAccountno] varchar(50) NULL, 
	[Manager] varchar(50) NULL, 
	[Company] varchar(50) NULL, 
	[Contact] varchar(50) NULL, 
	[Opportunity] varchar(150) NULL, 
	[OpportunityStatus] varchar(50) NULL, 
	[OpportunityStage] varchar(50) NULL, 
	[OpportunityIndustry] varchar(50) NULL, 
	[StartDate] datetime2(6) NULL, 
	[ClosedDate] datetime2(6) NULL, 
	[CloseByDate] datetime2(6) NULL, 
	[Probability] smallint NULL, 
	[Notes] varchar(8000) NULL, 
	[ProductName] varchar(50) NULL, 
	[DesiredCharacteristics] varchar(80) NULL, 
	[EstimatedAnnualVolume] numeric(16,4) NULL, 
	[SpecificApplication] varchar(80) NULL, 
	[TargetPrice] float NULL, 
	[OpportunityPriority] varchar(20) NULL, 
	[RecordID] varchar(15) NULL, 
	[RecordEffectiveStartDate] datetime2(6) NULL, 
	[RecordEffectiveEndDate] datetime2(6) NULL, 
	[RecordStatus] int NULL, 
	[Source] varchar(10) NULL, 
	[OPP_SID] int NULL, 
	[cloudCRMLink] varchar(50) NULL, 
	[LOPID] varchar(15) NULL, 
	[OpportunityType] varchar(200) NULL, 
	[EstimatedAnnualrevenue] decimal(37,12) NULL, 
	[Office] varchar(4) NOT NULL, 
	[Probable Value] numeric(38,6) NULL
);