CREATE TABLE [dbo].[mtbl_EDW_Fact_PurchaseOrderItemConsumptionSummary] (

	[CMPNY] varchar(8000) NULL, 
	[PurchaseOrderNumber] varchar(8000) NULL, 
	[linenumber] bigint NULL, 
	[ProductID] varchar(8000) NULL, 
	[inventdimid] varchar(8000) NULL, 
	[BatchID] varchar(8000) NULL, 
	[SiteID] varchar(8000) NULL, 
	[Warehouse] varchar(8000) NULL, 
	[licenseplateid] varchar(8000) NULL, 
	[pl_purchstatus_label] varchar(8) NULL, 
	[pt_purchstatus_label] varchar(8) NULL, 
	[inventtransid] varchar(8000) NULL, 
	[lineamount] decimal(38,6) NULL, 
	[purchqty] decimal(38,6) NULL, 
	[qtyordered] decimal(38,6) NULL, 
	[purchunit] varchar(8000) NULL, 
	[QtyOrdered_LBs] decimal(38,6) NULL, 
	[QtyOrdered_KGs] decimal(38,6) NULL, 
	[vendaccount] varchar(8000) NULL, 
	[Inventory_UoM] varchar(8000) NULL, 
	[NumberFinishedGoods] int NULL, 
	[remaining_qty] decimal(38,6) NULL, 
	[consumed_qty] decimal(38,6) NULL, 
	[remaining_pct] decimal(38,6) NULL, 
	[consumed_pct] decimal(38,6) NULL, 
	[costamountphysical] decimal(38,6) NULL, 
	[costamountadjustment] decimal(38,6) NULL, 
	[costamountposted] decimal(38,6) NULL, 
	[costamountNet] decimal(38,6) NULL, 
	[VendorKey] bigint NOT NULL, 
	[InvoiceVendorKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[EmployeeKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[PurchaseOrerKey] bigint NOT NULL, 
	[BatchKey] bigint NOT NULL
);