CREATE TABLE [dbo].[mtbl_EDW_Fact_PurchaseOrders] (

	[CMPNY] varchar(8000) NULL, 
	[PurchaseOrderNumber] varchar(8000) NULL, 
	[inventtransid] varchar(8000) NULL, 
	[itemid] varchar(8000) NULL, 
	[vendaccount] varchar(8000) NULL, 
	[invoiceaccount] varchar(8000) NULL, 
	[procurementcategory] bigint NULL, 
	[procurementcategoryname] varchar(8000) NULL, 
	[name] varchar(8000) NULL, 
	[purchunit] varchar(8000) NULL, 
	[qtyordered] decimal(38,6) NULL, 
	[QtyOrdered_LBs] decimal(38,6) NULL, 
	[remainpurchphysical] decimal(38,6) NULL, 
	[remainpurchfinancial] decimal(38,6) NULL, 
	[OutstandingQTY] decimal(38,6) NULL, 
	[purchstatus] bigint NULL, 
	[purchstatus_$label] varchar(8) NULL, 
	[returnstatus] bigint NULL, 
	[returnstatus_$label] varchar(10) NULL, 
	[lineamount] decimal(38,6) NULL, 
	[OutstandingLineAmount] decimal(38,6) NULL, 
	[inventdimid] varchar(8000) NULL, 
	[inventbatchid] varchar(8000) NULL, 
	[inventlocationid] varchar(8000) NULL, 
	[inventsiteid] varchar(8000) NULL, 
	[inventstatusid] varchar(8000) NULL, 
	[purchasetype] bigint NULL, 
	[purchasetype_$label] varchar(16) NULL, 
	[currencycode] varchar(8000) NULL, 
	[deliverydate] datetime2(6) NULL, 
	[DeliveryDateKey] int NULL, 
	[purchprice] decimal(38,6) NULL, 
	[linenumber] bigint NULL, 
	[priceunit] decimal(38,12) NULL, 
	[confirmeddlv] datetime2(6) NULL, 
	[ConfirmedDeliveryDateKey] int NULL, 
	[ConfirmedOrRequestedReceiptDate] datetime2(6) NULL, 
	[ConfirmedOrRequestedReceiptDateKey] int NULL, 
	[createddatetime] datetime2(6) NULL, 
	[CreatedDateKey] int NULL, 
	[PurchOrder_CreatedDateTime] datetime2(6) NULL, 
	[PurchOrder_CreatedDateKey] int NULL, 
	[personnelnumber] varchar(8000) NULL, 
	[DiscountPrice] decimal(38,6) NULL, 
	[DiscountPriceUnit] decimal(38,12) NULL, 
	[VendorKey] bigint NOT NULL, 
	[InvoiceVendorKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[EmployeeKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[PurchaseOrerKey] bigint NOT NULL, 
	[BatchKey] bigint NOT NULL
);