CREATE TABLE [dbo].[mtbl_EDW_Fact_PlannedPurchaseTransferProd_Orders] (

	[RecordID] bigint NULL, 
	[CMPNY] varchar(8000) NULL, 
	[RefId] varchar(8000) NULL, 
	[reftype] bigint NULL, 
	[reftype_$label] varchar(29) NULL, 
	[ItemId] varchar(8000) NULL, 
	[reqplanid] varchar(8000) NULL, 
	[ReqPlanName] varchar(8000) NULL, 
	[RequirementQuantity] decimal(38,6) NULL, 
	[Inventory_UoM] varchar(8000) NULL, 
	[Purchasing_UoM] varchar(8000) NULL, 
	[Sales_UoM] varchar(8000) NULL, 
	[OrderDate] datetime2(6) NULL, 
	[OrderDateKey] int NULL, 
	[DeliveryDate] datetime2(6) NULL, 
	[DeliveryDateKey] int NULL, 
	[RequestedDate] datetime2(6) NULL, 
	[RequestedDateKey] int NULL, 
	[Delay_days] bigint NOT NULL, 
	[actiontype] bigint NULL, 
	[actiontype_$label] varchar(18) NULL, 
	[Vendor] varchar(8000) NULL, 
	[isderiveddirectly] bigint NULL, 
	[isderiveddirectly_$label] varchar(3) NULL, 
	[ReqPOStatus] bigint NULL, 
	[reqpostatus_$label] varchar(14) NULL, 
	[leadtime] bigint NULL, 
	[Warehouse] varchar(8000) NULL, 
	[SiteID] varchar(8000) NULL, 
	[ProductKey] bigint NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[VendorKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL
);