CREATE TABLE [dbo].[mtbl_EDW_Fact_Customer_Invoices] (

	[CMPNY] varchar(8000) NULL, 
	[Invoice_ID] varchar(8000) NULL, 
	[InvoiceDate] datetime2(6) NULL, 
	[InvoiceDateKey] int NULL, 
	[Sales_ID] varchar(8000) NULL, 
	[Order_Account] varchar(8000) NULL, 
	[Invoice_Account] varchar(8000) NULL, 
	[Tax_Group] varchar(8000) NULL, 
	[Country] varchar(8000) NULL, 
	[Invoice_Line_Name] varchar(8000) NULL, 
	[InvoiceAmount] decimal(38,6) NULL, 
	[InvoiceAmount_USD] decimal(38,6) NULL, 
	[InvoiceAmount_EUR] decimal(38,6) NULL, 
	[InvoiceAmount_CNY] decimal(38,6) NULL, 
	[InvoiceAmountMST] decimal(38,6) NULL, 
	[Freight] decimal(38,6) NULL, 
	[Freight_USD] decimal(38,6) NULL, 
	[Freight_EUR] decimal(38,6) NULL, 
	[Freight_CNY] decimal(38,6) NULL, 
	[Fuel_Charge] decimal(38,6) NULL, 
	[Fuel_Charge_USD] decimal(38,6) NULL, 
	[Fuel_Charge_EUR] decimal(38,6) NULL, 
	[Fuel_Charge_CNY] decimal(38,6) NULL, 
	[Comms] decimal(38,6) NULL, 
	[Comms_USD] decimal(38,6) NULL, 
	[Comms_EUR] decimal(38,6) NULL, 
	[Comms_CNY] decimal(38,6) NULL, 
	[PLT_Brk_Ch] decimal(38,6) NULL, 
	[PLT_Brk_Ch_USD] decimal(38,6) NULL, 
	[PLT_Brk_Ch_EUR] decimal(38,6) NULL, 
	[PLT_Brk_Ch_CNY] decimal(38,6) NULL, 
	[Tariff_SC] decimal(38,6) NULL, 
	[Tariff_SC_USD] decimal(38,6) NULL, 
	[Tariff_SC_EUR] decimal(38,6) NULL, 
	[Tariff_SC_CNY] decimal(38,6) NULL, 
	[LineNumber] decimal(38,16) NULL, 
	[Product_ID] varchar(8000) NULL, 
	[Site_ID] varchar(8000) NULL, 
	[Warehouse_ID] varchar(8000) NULL, 
	[LineAmount] decimal(38,6) NULL, 
	[LineAmount_USD] decimal(38,6) NULL, 
	[LineAmount_EUR] decimal(38,6) NULL, 
	[LineAmount_CNY] decimal(38,6) NULL, 
	[LineAmountMST] decimal(38,6) NULL, 
	[Currency_Code] varchar(8000) NULL, 
	[salesunit] varchar(8000) NULL, 
	[Qty] decimal(38,6) NULL, 
	[Quantity_LBs] decimal(38,6) NULL, 
	[Quantity_KGs] decimal(38,6) NULL, 
	[SalesPrice] decimal(38,6) NULL, 
	[SalesPrice_USD] decimal(38,6) NULL, 
	[SalesPrice_EUR] decimal(38,6) NULL, 
	[SalesPrice_CNY] decimal(38,6) NULL, 
	[CostAmount] decimal(38,6) NULL, 
	[CostAmount_USD] decimal(38,6) NULL, 
	[CostAmount_EUR] decimal(38,6) NULL, 
	[CostAmount_CNY] decimal(38,6) NULL, 
	[CostAmountPhysical] decimal(38,6) NULL, 
	[CostAmountPhysical_USD] decimal(38,6) NULL, 
	[CostAmountPhysical_EUR] decimal(38,6) NULL, 
	[CostAmountPhysical_CNY] decimal(38,6) NULL, 
	[Margin] decimal(38,6) NULL, 
	[InventTransID] varchar(8000) NULL, 
	[InventDimID] varchar(8000) NULL, 
	[postedstateID] bigint NULL, 
	[PostedState] varchar(12) NULL, 
	[Source] varchar(6) NOT NULL, 
	[CustomerKey] bigint NOT NULL, 
	[InvoiceCustomerKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[StandardCostKey] bigint NULL, 
	[MarketSegmentationKey] bigint NOT NULL, 
	[SalesOrderKey] bigint NOT NULL, 
	[DeliveryAddressKey] bigint NOT NULL, 
	[Txn_Source_Currency] varchar(8000) NULL, 
	[Cost_Source_Currency] varchar(8000) NULL, 
	[Txn_USD_Rate_Missing] int NULL, 
	[Txn_EUR_Rate_Missing] int NULL, 
	[Txn_CNY_Rate_Missing] int NULL, 
	[Cost_USD_Rate_Missing] int NULL, 
	[Cost_EUR_Rate_Missing] int NULL, 
	[Cost_CNY_Rate_Missing] int NULL 
);
