CREATE TABLE [dbo].[mtbl_EDW_Fact_PurchaseOrders] (
    [CMPNY]                              VARCHAR (8000)   NULL,
    [PurchaseOrderNumber]                VARCHAR (8000)   NULL,
    [inventtransid]                      VARCHAR (8000)   NULL,
    [itemid]                             VARCHAR (8000)   NULL,
    [vendaccount]                        VARCHAR (8000)   NULL,
    [invoiceaccount]                     VARCHAR (8000)   NULL,
    [procurementcategory]                BIGINT           NULL,
    [procurementcategoryname]            VARCHAR (8000)   NULL,
    [name]                               VARCHAR (8000)   NULL,
    [purchunit]                          VARCHAR (8000)   NULL,
    [qtyordered]                         DECIMAL (38, 6)  NULL,
    [QtyOrdered_LBs]                     DECIMAL (38, 6)  NULL,
    [remainpurchphysical]                DECIMAL (38, 6)  NULL,
    [remainpurchfinancial]               DECIMAL (38, 6)  NULL,
    [OutstandingQTY]                     DECIMAL (38, 6)  NULL,
    [purchstatus]                        BIGINT           NULL,
    [purchstatus_$label]                 VARCHAR (8)      NULL,
    [returnstatus]                       BIGINT           NULL,
    [returnstatus_$label]                VARCHAR (10)     NULL,
    [lineamount]                         DECIMAL (38, 6)  NULL,
    [OutstandingLineAmount]              DECIMAL (38, 6)  NULL,
    [inventdimid]                        VARCHAR (8000)   NULL,
    [inventbatchid]                      VARCHAR (8000)   NULL,
    [inventlocationid]                   VARCHAR (8000)   NULL,
    [inventsiteid]                       VARCHAR (8000)   NULL,
    [inventstatusid]                     VARCHAR (8000)   NULL,
    [purchasetype]                       BIGINT           NULL,
    [purchasetype_$label]                VARCHAR (16)     NULL,
    [currencycode]                       VARCHAR (8000)   NULL,
    [deliverydate]                       DATETIME2 (6)    NULL,
    [DeliveryDateKey]                    INT              NULL,
    [purchprice]                         DECIMAL (38, 6)  NULL,
    [linenumber]                         BIGINT           NULL,
    [priceunit]                          DECIMAL (38, 12) NULL,
    [confirmeddlv]                       DATETIME2 (6)    NULL,
    [ConfirmedDeliveryDateKey]           INT              NULL,
    [ConfirmedOrRequestedReceiptDate]    DATETIME2 (6)    NULL,
    [ConfirmedOrRequestedReceiptDateKey] INT              NULL,
    [createddatetime]                    DATETIME2 (6)    NULL,
    [CreatedDateKey]                     INT              NULL,
    [PurchOrder_CreatedDateTime]         DATETIME2 (6)    NULL,
    [PurchOrder_CreatedDateKey]          INT              NULL,
    [personnelnumber]                    VARCHAR (8000)   NULL,
    [DiscountPrice]                      DECIMAL (38, 6)  NULL,
    [DiscountPriceUnit]                  DECIMAL (38, 12) NULL,
    [VendorKey]                          BIGINT           NOT NULL,
    [InvoiceVendorKey]                   BIGINT           NOT NULL,
    [ProductKey]                         BIGINT           NOT NULL,
    [Legal_EntityKey]                    BIGINT           NOT NULL,
    [EmployeeKey]                        BIGINT           NOT NULL,
    [SiteKey]                            BIGINT           NOT NULL,
    [WarehouseKey]                       BIGINT           NOT NULL,
    [PurchaseOrerKey]                    BIGINT           NOT NULL,
    [BatchKey]                           BIGINT           NOT NULL
);


GO

