CREATE TABLE [dbo].[mtbl_EDW_Dim_Date] (
    [DateKey]                INT          NULL,
    [RecId]                  BIGINT       NULL,
    [FiscalQuarterNum]       INT          NULL,
    [FiscalYear]             SMALLINT     NULL,
    [FiscalPeriodNum]        INT          NULL,
    [WeeksInPeriod]          INT          NULL,
    [FiscalWeekNum]          INT          NULL,
    [CalendarYear]           SMALLINT     NULL,
    [CalendarQuarterNum]     INT          NULL,
    [MonthNameShort]         VARCHAR (3)  NULL,
    [WeekdayNameLong]        VARCHAR (9)  NULL,
    [WeekOfYearNum]          INT          NULL,
    [Date]                   DATE         NULL,
    [DayOfMonthNum]          INT          NULL,
    [FiscalDayNum]           SMALLINT     NULL,
    [IsWorkingDayUs]         BIT          NULL,
    [IsWorkingDayBvba]       BIT          NULL,
    [IsWorkingDayTeda]       BIT          NULL,
    [WeekStartDate]          DATE         NULL,
    [WeekStartDateSunday]    DATE         NULL,
    [MonthStartDate]         DATE         NULL,
    [CurrentFiscalDayNum]    SMALLINT     NULL,
    [CurrentFiscalYear]      SMALLINT     NULL,
    [MonthNum]               INT          NULL,
    [MonthNameLong]          VARCHAR (30) NULL,
    [YearMonthNum]           VARCHAR (10) NOT NULL,
    [YearMonthLabel]         VARCHAR (9)  NULL,
    [CalendarQuarterLabel]   VARCHAR (2)  NULL,
    [CalendarYearQuarterNum] INT          NULL,
    [FiscalQuarterLabel]     VARCHAR (9)  NULL,
    [FiscalYearQuarterNum]   INT          NULL,
    [WeekdayNum]             INT          NULL,
    [WeekdayNameShort]       VARCHAR (3)  NULL,
    [YearWeekNum]            INT          NULL,
    [FiscalYearWeekNum]      INT          NULL,
    [DayOfYearNum]           SMALLINT     NULL,
    [IsWeekend]              BIT          NULL,
    [IsToday]                INT          NOT NULL,
    [IsCurrentMonth]         BIT          NULL,
    [IsCurrentFiscalYear]    BIT          NULL,
    [FiscalPeriodLabel]      VARCHAR (5)  NULL,
    [Original FISCAL YR]     SMALLINT     NULL,
    [Original FISCAL PERIOD] INT          NULL,
    [Reconciliation Year]    VARCHAR (20) NULL
);


GO

