CREATE TABLE [dbo].[mtbl_EDW_Fact_Sales] (
    [RecordID]                       BIGINT           NULL,
    [CMPNY]                          VARCHAR (8000)   NULL,
    [SalesLine_Status]               VARCHAR (12)     NULL,
    [DATE]                           DATETIME2 (6)    NULL,
    [DATEKey]                        INT              NULL,
    [OrderDate]                      DATETIME2 (6)    NULL,
    [OrderDateKey]                   INT              NULL,
    [SalesLine_RequestedShipDate]    DATETIME2 (6)    NULL,
    [SalesLine_RequestedShipDateKey] INT              NULL,
    [SalesLine_ShipDate]             DATETIME2 (6)    NULL,
    [SalesLine_ShipDateKey]          INT              NULL,
    [SalesLine_DeliveryDate]         DATETIME2 (6)    NULL,
    [SalesLine_DeliveryDateKey]      INT              NULL,
    [InvoiceDate]                    DATETIME2 (6)    NULL,
    [InvoiceDateKey]                 INT              NULL,
    [Legal_Entity_ID]                VARCHAR (8000)   NULL,
    [CustomerID]                     VARCHAR (8000)   NULL,
    [InvoiceAccount]                 VARCHAR (8000)   NULL,
    [ProductID]                      VARCHAR (8000)   NULL,
    [CPCID]                          VARCHAR (8000)   NULL,
    [InvoiceNo]                      VARCHAR (MAX)    NULL,
    [Customer_Order_Number]          VARCHAR (8000)   NULL,
    [Quantity]                       DECIMAL (38, 6)  NULL,
    [Quantity_UoM]                   VARCHAR (8000)   NULL,
    [Quantity_LBs]                   DECIMAL (38, 6)  NULL,
    [Volume]                         DECIMAL (38, 6)  NULL,
    [Volume_UoM]                     VARCHAR (8000)   NULL,
    [Price]                          DECIMAL (38, 6)  NULL,
    [Currency]                       VARCHAR (8000)   NULL,
    [Amount]                         DECIMAL (38, 6)  NULL,
    [Amount_Currency]                VARCHAR (8000)   NULL,
    [Returned_Quantity]              DECIMAL (38, 6)  NULL,
    [Returned_Amount]                DECIMAL (38, 6)  NULL,
    [SalesLine_Salesman_ID]          VARCHAR (8000)   NULL,
    [Customer_Salesman_ID]           VARCHAR (8000)   NULL,
    [Source]                         VARCHAR (50)     NULL,
    [HistoricCustomerKey]            BIGINT           NOT NULL,
    [CustomerKey]                    BIGINT           NOT NULL,
    [HistoricProductKey]             BIGINT           NULL,
    [ProductKey]                     BIGINT           NULL,
    [StandardCostKey]                BIGINT           NULL,
    [Legal_EntityKey]                BIGINT           NOT NULL,
    [SiteKey]                        BIGINT           NOT NULL,
    [SalesLine_EmployeeKey]          BIGINT           NOT NULL,
    [CustAcct_EmployeeKey]           BIGINT           NULL,
    [SalesTaker_EmployeeKey]         BIGINT           NOT NULL,
    [WarehouseKey]                   BIGINT           NOT NULL,
    [SalesOrderKey]                  BIGINT           NOT NULL,
    [OnHold]                         BIGINT           NULL,
    [OrderOnHold]                    VARCHAR (10)     NULL,
    [HoldCode]                       VARCHAR (8000)   NULL,
    [HoldReasonCode]                 VARCHAR (8000)   NULL,
    [SalesOrderLineNumber]           DECIMAL (38, 16) NULL,
    [SalesLineCreatedDate]           DATETIME2 (6)    NULL,
    [SalesLineCreatedDateKey]        INT              NULL,
    [MarketSegmentationKey]          BIGINT           NOT NULL,
    [PurchaseOrderFormNumber]        VARCHAR (8000)   NULL,
    [DeliveryAddressKey]             BIGINT           NOT NULL
);


GO

