CREATE TABLE [dbo].[mtbl_EDW_Dim_SalesOrder] (
    [SalesOrderKey]               BIGINT         NULL,
    [CMPNY]                       VARCHAR (8000) NULL,
    [SalesOrderId]                VARCHAR (8000) NULL,
    [SalesType]                   BIGINT         NULL,
    [SalesTypeDesc]               VARCHAR (13)   NULL,
    [SalesStatus]                 BIGINT         NULL,
    [SalesStatusDesc]             VARCHAR (9)    NULL,
    [DocumentStatus]              BIGINT         NULL,
    [DocumentStatusDesc]          VARCHAR (28)   NULL,
    [SalesOriginId]               VARCHAR (8000) NULL,
    [SalesPoolId]                 VARCHAR (8000) NULL,
    [DeliveryModeCode]            VARCHAR (8000) NULL,
    [DeliveryModeDescription]     VARCHAR (8000) NULL,
    [DeliveryTermCode]            VARCHAR (8000) NULL,
    [DeliveryTermDescription]     VARCHAR (8000) NULL,
    [DeliveryName]                VARCHAR (8000) NULL,
    [DeliveryReason]              VARCHAR (8000) NULL,
    [SiteId]                      VARCHAR (8000) NULL,
    [WarehouseId]                 VARCHAR (8000) NULL,
    [PaymentTermId]               VARCHAR (8000) NULL,
    [PaymentTermDescription]      VARCHAR (8000) NULL,
    [CurrencyCode]                VARCHAR (8000) NULL,
    [SalesResponsiblePersonnelNo] VARCHAR (8000) NULL,
    [SalesResponsibleName]        VARCHAR (8000) NULL,
    [SalesTakerPersonnelNo]       VARCHAR (8000) NULL,
    [SalesTakerName]              VARCHAR (8000) NULL,
    [CustomerPONumber]            VARCHAR (8000) NULL,
    [QuotationId]                 VARCHAR (8000) NULL,
    [ProjectId]                   VARCHAR (8000) NULL,
    [ReturnItemNum]               VARCHAR (8000) NULL,
    [OrderCreatedDate]            DATE           NULL,
    [ShippingDateRequested]       DATE           NULL,
    [ShippingDateConfirmed]       DATE           NULL,
    [ReceiptDateRequested]        DATE           NULL,
    [ReceiptDateConfirmed]        DATE           NULL,
    [CreatedDateTime]             DATETIME2 (6)  NULL,
    [ModifiedDateTime]            DATETIME2 (6)  NULL,
    [Source]                      VARCHAR (6)    NULL,
    [RecordEffectiveStartDate]    DATETIME2 (3)  NULL,
    [RecordEffectiveEndDate]      DATETIME2 (3)  NULL,
    [RecordStatus]                INT            NULL
);


GO

