CREATE TABLE [dbo].[mtbl_EDW_Fact_Production_Job_Routes] (
    [CMPNY]                   VARCHAR (8000)  NULL,
    [ProdID]                  VARCHAR (8000)  NULL,
    [WrkCtrID]                VARCHAR (8000)  NULL,
    [oprnum]                  BIGINT          NULL,
    [oprpriority]             BIGINT          NULL,
    [oprpriority_$label]      VARCHAR (11)    NULL,
    [Operation]               VARCHAR (8000)  NULL,
    [ProdIDandOprNum]         VARCHAR (8000)  NULL,
    [Name]                    VARCHAR (8000)  NULL,
    [jobtype]                 BIGINT          NULL,
    [jobtype_$label]          VARCHAR (11)    NULL,
    [link]                    BIGINT          NULL,
    [link_$label]             VARCHAR (4)     NULL,
    [linktype]                BIGINT          NULL,
    [linktype_$label]         VARCHAR (4)     NULL,
    [jobid]                   VARCHAR (8000)  NULL,
    [Resource]                VARCHAR (8000)  NULL,
    [propertyid]              VARCHAR (8000)  NULL,
    [jobcontrol]              BIGINT          NULL,
    [JobManagement]           VARCHAR (3)     NULL,
    [jobstatus]               BIGINT          NULL,
    [jobstatus_$label]        VARCHAR (9)     NULL,
    [jobpaytype]              BIGINT          NULL,
    [jobpaytype_$label]       VARCHAR (9)     NULL,
    [schedcancelled]          BIGINT          NULL,
    [Canceled]                VARCHAR (3)     NULL,
    [CalculatedTime]          DECIMAL (38, 6) NULL,
    [ResourceTime]            DECIMAL (38, 6) NULL,
    [ProcessingPercentage]    NUMERIC (38, 6) NULL,
    [SchedStartDateTime]      DATETIME2 (6)   NULL,
    [SchedEndDateTime]        DATETIME2 (6)   NULL,
    [ActualStartDateTime]     DATETIME2 (6)   NULL,
    [ActualEndDateTime]       DATETIME2 (6)   NULL,
    [SchedStartDateKey]       INT             NULL,
    [ActualStartDateKey]      INT             NULL,
    [inventsiteid]            VARCHAR (8000)  NULL,
    [Warehouse]               VARCHAR (8000)  NULL,
    [ProductionProductID]     VARCHAR (8000)  NULL,
    [routeid]                 VARCHAR (8000)  NULL,
    [Legal_EntityKey]         BIGINT          NOT NULL,
    [HistoricalProductKey]    BIGINT          NOT NULL,
    [ProductKey]              BIGINT          NOT NULL,
    [ProductionBatchOrderKey] BIGINT          NOT NULL,
    [SiteKey]                 BIGINT          NOT NULL,
    [WarehouseKey]            BIGINT          NOT NULL,
    [RouteKey]                BIGINT          NOT NULL,
    [WorkCenterKey]           BIGINT          NOT NULL
);


GO

