CREATE TABLE [dbo].[mtbl_EDW_Fact_WorkOrderCycleCountTransactions] (
    [CMPNY]                    VARCHAR (8000)   NULL,
    [WorkId]                   VARCHAR (8000)   NULL,
    [LicensePlateId]           VARCHAR (8000)   NULL,
    [InventStatusId]           VARCHAR (8000)   NULL,
    [QtyExpected]              DECIMAL (38, 6)  NULL,
    [QtyCounted]               DECIMAL (38, 6)  NULL,
    [QtyVariance]              DECIMAL (38, 6)  NULL,
    [ReasonCode]               VARCHAR (8000)   NULL,
    [ReasonDescription]        VARCHAR (8000)   NULL,
    [LineNum]                  DECIMAL (38, 16) NULL,
    [WorkTransType]            VARCHAR (22)     NULL,
    [IsCounted]                VARCHAR (3)      NULL,
    [AcceptReject]             VARCHAR (6)      NULL,
    [ReconcileStatus]          VARCHAR (3)      NULL,
    [WMSLocationId]            VARCHAR (8000)   NULL,
    [IsAnchored]               VARCHAR (3)      NULL,
    [IsCountMandatory]         VARCHAR (3)      NULL,
    [IsCountSkipped]           VARCHAR (3)      NULL,
    [WorkLineStatus]           VARCHAR (13)     NULL,
    [IsWorkStopped]            VARCHAR (3)      NULL,
    [WorkLineType]             VARCHAR (24)     NULL,
    [AdjustmentWorkId]         VARCHAR (8000)   NULL,
    [AdjWorkTransType]         VARCHAR (22)     NULL,
    [AdjWorkStatus]            VARCHAR (13)     NULL,
    [AdjWorkCreatedBy]         VARCHAR (8000)   NULL,
    [AdjWorkStartedUTC]        DATETIME2 (6)    NULL,
    [AdjWorkClosedUTC]         DATETIME2 (6)    NULL,
    [AdjWorkType]              VARCHAR (24)     NULL,
    [AdjQtyWork]               DECIMAL (38, 6)  NULL,
    [AdjWMSLocationId]         VARCHAR (8000)   NULL,
    [AdjUnitId]                VARCHAR (8000)   NULL,
    [Legal_EntityKey]          BIGINT           NOT NULL,
    [WorkOrderKey]             BIGINT           NOT NULL,
    [AdjustmentWorkOrderKey]   BIGINT           NOT NULL,
    [ProductKey]               BIGINT           NOT NULL,
    [SiteKey]                  BIGINT           NOT NULL,
    [WarehouseKey]             BIGINT           NOT NULL,
    [BatchKey]                 BIGINT           NOT NULL,
    [SerialNumberKey]          BIGINT           NOT NULL,
    [StandardCostKey]          BIGINT           NULL,
    [WorkCancelledUTCDateKey]  INT              NULL,
    [WorkStartedUTCDateKey]    INT              NULL,
    [WorkClosedUTCDateKey]     INT              NULL,
    [CreatedDateTimeDateKey]   INT              NULL,
    [ModifiedDateTimeDateKey]  INT              NULL,
    [AdjWorkStartedUTCDateKey] INT              NOT NULL,
    [AdjWorkClosedUTCDateKey]  INT              NOT NULL
);
GO

