CREATE TABLE [dbo].[tbl_DIM_Opportunity_Header] (

	[Salesman] varchar(8000) NULL, 
	[Customer] varchar(8000) NULL, 
	[StartDate] datetime2(6) NULL, 
	[CloseByDate] datetime2(6) NULL, 
	[ActualCloseDate] datetime2(6) NULL, 
	[OpportunityName] varchar(8000) NULL, 
	[Status] varchar(8000) NULL, 
	[CYCLE] varchar(8000) NULL, 
	[Stage] varchar(8000) NULL, 
	[Source] varchar(8000) NULL, 
	[Probability] float NULL, 
	[EstAnnualVolume] float NULL, 
	[EstAnnualRevenue] float NULL, 
	[Product] varchar(8000) NULL, 
	[DesiredCharacteristics] varchar(8000) NULL, 
	[UEAV] float NULL, 
	[SpecificApplication] varchar(8000) NULL, 
	[TargetPrice] float NULL, 
	[UTSPROJID] varchar(8000) NULL, 
	[OPID] varchar(8000) NULL, 
	[ACCOUNTNO] varchar(8000) NULL, 
	[RECID] varchar(8000) NULL
);