CREATE TABLE [dbo].[tbl_crm_Activity_CY] (

	[USERID] varchar(8) NULL, 
	[ACCOUNTNO] varchar(20) NULL, 
	[SRECTYPE] varchar(1) NULL, 
	[RECTYPE] varchar(10) NULL, 
	[ONDATE] datetime2(6) NULL, 
	[ONTIME] varchar(5) NULL, 
	[ACTVCODE] varchar(3) NULL, 
	[RESULTCODE] varchar(3) NULL, 
	[STATUS] varchar(2) NULL, 
	[DURATION] varchar(14) NULL, 
	[UNITS] varchar(20) NULL, 
	[REF] varchar(255) NULL, 
	[LINKRECID] varchar(15) NULL, 
	[LOPRECID] varchar(15) NULL, 
	[CREATEBY] varchar(8) NULL, 
	[CREATEON] datetime2(6) NULL, 
	[CREATEAT] varchar(5) NULL, 
	[LASTUSER] varchar(8) NULL, 
	[LASTDATE] datetime2(6) NULL, 
	[LASTTIME] varchar(5) NULL, 
	[recid] varchar(15) NULL, 
	[EXT] varchar(5) NULL, 
	[COMPLETEDID] varchar(15) NULL, 
	[NUMBER1] varchar(20) NULL, 
	[NUMBER2] varchar(20) NULL, 
	[SnapShotDate] datetime2(6) NULL, 
	[DataUpdateDate] datetime2(6) NULL, 
	[Source] varchar(10) NULL, 
	[ACT_SID] int NULL
);