CREATE TABLE [dbo].[tbl_DIM_Product] (
    [ProductKey]               BIGINT          NULL,
    [CMPNY]                    VARCHAR (8000)  NULL,
    [Product_ID]               VARCHAR (8000)  NULL,
    [ProductName]              VARCHAR (8000)  NULL,
    [ProductSearchName]        VARCHAR (8000)  NULL,
    [Commercial_Name]          VARCHAR (8000)  NULL,
    [Technology]               VARCHAR (8000)  NULL,
    [Material]                 VARCHAR (8000)  NULL,
    [Business_Line]            VARCHAR (8000)  NULL,
    [Product_Line]             VARCHAR (8000)  NULL,
    [MiscRevenue]              VARCHAR (8000)  NULL,
    [Lifecycle]                INT             NULL,
    [Inventory_UoM]            VARCHAR (8000)  NULL,
    [Purchasing_UoM]           VARCHAR (8000)  NULL,
    [Sales_UoM]                VARCHAR (8000)  NULL,
    [Item_Type]                VARCHAR (12)    NULL,
    [PTFE_Flag]                INT             NULL,
    [Reorder_Point]            DECIMAL (20, 4) NULL,
    [itemmodelgroupid]         VARCHAR (8000)  NULL,
    [producttype]              BIGINT          NULL,
    [producttype_desc]         VARCHAR (20)    NULL,
    [itemgroupid]              VARCHAR (8000)  NULL,
    [ItemGroupName]            VARCHAR (8000)  NULL,
    [ItemGroupType]            BIGINT          NULL,
    [ItemGroupTypeName]        VARCHAR (20)    NULL,
    [ItemBuyerGroupID]         VARCHAR (8000)  NULL,
    [ItemBuyerGroupDesc]       VARCHAR (8000)  NULL,
    [Phantom]                  BIGINT          NULL,
    [IsPhantom]                VARCHAR (3)     NULL,
    [min_purchase_qty]         DECIMAL (38, 6) NULL,
    [multiple_purchase_qty]    DECIMAL (38, 6) NULL,
    [std_purchase_order_qty]   DECIMAL (38, 6) NULL,
    [max_purchase_order_qty]   DECIMAL (38, 6) NULL,
    [purchase_leadtime]        BIGINT          NULL,
    [min_inventory_qty]        DECIMAL (38, 6) NULL,
    [multiple_inventory_qty]   DECIMAL (38, 6) NULL,
    [std_inventory_order_qty]  DECIMAL (38, 6) NULL,
    [max_inventory_order_qty]  DECIMAL (38, 6) NULL,
    [inventory_leadtime]       BIGINT          NULL,
    [min_sales_qty]            DECIMAL (38, 6) NULL,
    [multiple_sales_qty]       DECIMAL (38, 6) NULL,
    [std_sales_order_qty]      DECIMAL (38, 6) NULL,
    [max_sales_order_qty]      DECIMAL (38, 6) NULL,
    [sales_leadtime]           BIGINT          NULL,
    [BaseSalesPrice]           DECIMAL (38, 6) NULL,
    [BaseSalesPricePerLB]      DECIMAL (38, 6) NULL,
    [RecordEffectiveStartDate] DATETIME2 (3)   NULL,
    [RecordEffectiveEndDate]   DATETIME2 (3)   NULL,
    [RecordStatus]             INT             NULL,
    [Source]                   VARCHAR (6)     NOT NULL
);


GO

