CREATE TABLE [dbo].[tbl_Fact_SupplyChain_RAF] (

	[CMPNY] varchar(8000) NULL, 
	[ProdId] varchar(8000) NULL, 
	[ItemId] varchar(8000) NULL, 
	[JournalId] varchar(8000) NULL, 
	[journalnameid] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[posteddatetime] datetime2(6) NULL, 
	[PostedDateKey] int NULL, 
	[QTYGood] decimal(38,6) NULL, 
	[qtyerror] decimal(38,6) NULL, 
	[transdate] datetime2(6) NULL, 
	[TransDateKey] int NULL, 
	[voucher] varchar(8000) NULL, 
	[prodfinished] bigint NULL, 
	[prodfinished_$label] varchar(3) NULL, 
	[journaltype_$Label] varchar(24) NULL, 
	[wrkctrid] varchar(8000) NULL, 
	[inventsiteid] varchar(8000) NULL, 
	[inventlocationid] varchar(8000) NULL, 
	[inventbatchid] varchar(8000) NULL, 
	[inventserialid] varchar(8000) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[ProductionBatchOrderKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[BatchKey] bigint NOT NULL, 
	[RouteKey] bigint NOT NULL, 
	[WorkCenterKey] bigint NOT NULL, 
	[SerialNumberKey] bigint NOT NULL, 
	[QRankTestResult] varchar(8000) NULL, 
	[QuaityOrderStatus] varchar(4) NULL
);