CREATE TABLE [dbo].[tbl_Fact_SupplyChain_JobCard] (

	[CMPNY] varchar(8000) NULL, 
	[ProdId] varchar(8000) NULL, 
	[ItemId] varchar(8000) NULL, 
	[JournalId] varchar(8000) NULL, 
	[linenum] decimal(38,16) NULL, 
	[OprNum] bigint NULL, 
	[OprId] varchar(8000) NULL, 
	[oprpriority] bigint NULL, 
	[oprpriority_$label] varchar(11) NULL, 
	[posteddatetime] datetime2(6) NULL, 
	[JobHours] decimal(38,6) NULL, 
	[JobQtyGood] decimal(38,6) NULL, 
	[JobQtyError] decimal(38,6) NULL, 
	[wrkctrid] varchar(8000) NULL, 
	[worker] bigint NULL, 
	[person] bigint NULL, 
	[personnelnumber] varchar(8000) NULL, 
	[transdate] datetime2(6) NULL, 
	[dataareaid] varchar(8000) NULL, 
	[oprfinished_$label] varchar(3) NULL, 
	[jobtype_$label] varchar(11) NULL, 
	[jobfinished_$label] varchar(3) NULL, 
	[voucher] varchar(8000) NULL, 
	[executedpct] decimal(38,6) NULL, 
	[jobid] varchar(8000) NULL, 
	[inventdimid] varchar(8000) NULL, 
	[journaltype_$Label] varchar(24) NULL, 
	[fromtime] bigint NULL, 
	[totime] bigint NULL, 
	[description] varchar(8000) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[ProductionBatchOrderKey] bigint NOT NULL, 
	[EmployeeKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[BatchKey] bigint NOT NULL, 
	[RouteKey] bigint NOT NULL
);