CREATE TABLE [dbo].[tbl_Fact_Sales] (

	[RecordID] bigint NULL, 
	[CMPNY] varchar(8000) NULL, 
	[SalesLine_Status] varchar(9) NULL, 
	[DATE] datetime2(6) NULL, 
	[DATEKey] int NULL, 
	[OrderDate] datetime2(6) NULL, 
	[OrderDateKey] int NULL, 
	[SalesLine_RequestedShipDate] datetime2(6) NULL, 
	[SalesLine_RequestedShipDateKey] int NULL, 
	[SalesLine_ShipDate] datetime2(6) NULL, 
	[SalesLine_ShipDateKey] int NULL, 
	[SalesLine_DeliveryDate] datetime2(6) NULL, 
	[SalesLine_DeliveryDateKey] int NULL, 
	[InvoiceDate] datetime2(6) NULL, 
	[InvoiceDateKey] int NULL, 
	[Legal_Entity_ID] varchar(8000) NULL, 
	[CustomerID] varchar(8000) NULL, 
	[InvoiceAccount] varchar(8000) NULL, 
	[ProductID] varchar(8000) NULL, 
	[CPCID] varchar(8000) NULL, 
	[InvoiceNo] varchar(8000) NULL, 
	[Customer_Order_Number] varchar(8000) NULL, 
	[Quantity] decimal(38,6) NULL, 
	[Quantity_UoM] varchar(8000) NULL, 
	[Quantity_LBs] decimal(38,6) NULL, 
	[Quantity_KGs] decimal(38,6) NULL, 
	[Volume] decimal(38,6) NULL, 
	[Volume_UoM] varchar(8000) NULL, 
	[Price] decimal(38,6) NULL, 
	[Currency] varchar(8000) NULL, 
	[Amount] decimal(38,6) NULL, 
	[Amount_Currency] varchar(8000) NULL, 
	[Returned_Quantity] decimal(38,6) NULL, 
	[Returned_Amount] decimal(38,6) NULL, 
	[SalesLine_Salesman_ID] varchar(8000) NULL, 
	[Customer_Salesman_ID] varchar(8000) NULL, 
	[Total_Direct_Cost_Standard] decimal(38,6) NULL, 
	[Total_Overhead_Cost_Standard] decimal(38,6) NULL, 
	[Packaging_Cost_Standard] decimal(38,6) NULL, 
	[TotalCost] decimal(38,6) NULL, 
	[Source] varchar(6) NOT NULL, 
	[HistoricCustomerKey] bigint NOT NULL, 
	[CustomerKey] bigint NOT NULL, 
	[HistoricProductKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[StandardCostKey] bigint NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[SalesLine_EmployeeKey] bigint NOT NULL, 
	[CustAcct_EmployeeKey] bigint NOT NULL, 
	[SalesTaker_EmployeeKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[SalesOrderKey] bigint NOT NULL, 
	[OnHold] bigint NULL, 
	[OrderOnHold] varchar(10) NULL, 
	[HoldCode] varchar(8000) NULL, 
	[HoldReasonCode] varchar(8000) NULL, 
	[SalesOrderLineNumber] decimal(38,16) NULL, 
	[SalesLineCreatedDate] datetime2(6) NULL, 
	[SalesLineCreatedDateKey] int NULL, 
	[MarketSegmentationKey] bigint NOT NULL, 
	[PurchaseOrderFormNumber] varchar(8000) NULL, 
	[DeliveryAddressKey] bigint NOT NULL
);