CREATE TABLE [dbo].[tbl_DIM_Accounts] (
    [RECID]                    VARCHAR (8000) NULL,
    [CustomerID]               VARCHAR (8000) NULL,
    [GMAccountno]              VARCHAR (8000) NULL,
    [GMRecid]                  VARCHAR (8000) NULL,
    [CustomerNo]               VARCHAR (8000) NULL,
    [ShipToNo]                 VARCHAR (8000) NULL,
    [NationalOrgID]            VARCHAR (8000) NULL,
    [RegionalOrgID]            VARCHAR (8000) NULL,
    [GlobalOrgID]              VARCHAR (8000) NULL,
    [Source]                   VARCHAR (8000) NULL,
    [CustomerName]             VARCHAR (8000) NULL,
    [Address1]                 VARCHAR (8000) NULL,
    [Address2]                 VARCHAR (8000) NULL,
    [Address3]                 VARCHAR (8000) NULL,
    [Address4]                 VARCHAR (8000) NULL,
    [City]                     VARCHAR (8000) NULL,
    [State]                    VARCHAR (8000) NULL,
    [ZIP]                      VARCHAR (8000) NULL,
    [Country]                  VARCHAR (8000) NULL,
    [Contact]                  VARCHAR (8000) NULL,
    [Phone]                    VARCHAR (8000) NULL,
    [Fax]                      VARCHAR (8000) NULL,
    [Salesman]                 VARCHAR (8000) NULL,
    [Salesman No]              VARCHAR (8000) NULL,
    [Sales Channel]            VARCHAR (8000) NULL,
    [Bus Unit]                 VARCHAR (8000) NULL,
    [Industry]                 VARCHAR (8000) NULL,
    [Industry Mgr]             VARCHAR (8000) NULL,
    [Mkt Mgr]                  VARCHAR (8000) NULL,
    [Application]              VARCHAR (8000) NULL,
    [CMPNY]                    VARCHAR (8000) NULL,
    [Obsoleted]                VARCHAR (8000) NULL,
    [ShipToType]               VARCHAR (8000) NULL,
    [LocationName]             VARCHAR (8000) NULL,
    [Location Type]            VARCHAR (8000) NULL,
    [NationalName]             VARCHAR (8000) NULL,
    [RegionalName]             VARCHAR (8000) NULL,
    [GlobalName]               VARCHAR (8000) NULL,
    [EffectiveSalesman]        VARCHAR (8000) NULL,
    [EffectiveCountry]         VARCHAR (8000) NULL,
    [Tier]                     VARCHAR (8000) NULL,
    [Contact Type]             VARCHAR (8000) NULL,
    [Longitude]                FLOAT (53)     NULL,
    [Latitude]                 FLOAT (53)     NULL,
    [GMOwnership]              VARCHAR (50)   NULL,
    [RecordCurtainingLevel]    VARCHAR (50)   NULL,
    [RowStatus]                VARCHAR (50)   NULL,
    [RowChangeReason]          VARCHAR (50)   NULL,
    [InitialLoadSystem]        VARCHAR (50)   NULL,
    [LastChangeSystem]         VARCHAR (50)   NULL,
    [RecordEffectiveStartDate] DATETIME2 (6)  NULL,
    [RecordEffectiveEndDate]   DATETIME2 (6)  NULL,
    [RecordStatus]             CHAR (8000)    NULL,
    [ACC_SID]                  INT            NULL
);


GO

