CREATE TABLE [dbo].[tbl_Fact_VendorInvoiceTransactions](
	[CMPNY] [varchar](8000) NULL,
	[PurchaseOrder] [varchar](8000) NULL,
	[VendorAccount] [varchar](8000) NULL,
	[InvoiceID] [varchar](8000) NULL,
	[InvoiceAmount] [decimal](38, 6) NULL,
	[InvoiceAmount_USD] [numeric](38, 6) NULL,
	[InvoiceAmount_EUR] [numeric](38, 6) NULL,
	[InvoiceAmount_CNY] [numeric](38, 6) NULL,
	[InvoiceDate] [datetime2](6) NULL,
	[LineNumber] [decimal](38, 16) NULL,
	[ProductID] [varchar](8000) NULL,
	[ProcurementCategory] [varchar](8000) NOT NULL,
	[Description] [varchar](8000) NULL,
	[Quantity] [decimal](38, 6) NULL,
	[Quantity_UoM] [varchar](8000) NULL,
	[Quantity_LBs] [decimal](38, 6) NULL,
	[Quantity_KGs] [decimal](38, 6) NULL,
	[VIT_CURRENCYCODE] [varchar](8000) NULL,
	[CHG_CURRENCYCODE] [varchar](8000) NOT NULL,
	[UnitPrice] [decimal](38, 6) NULL,
	[UnitPrice_USD] [numeric](38, 6) NULL,
	[UnitPrice_EUR] [numeric](38, 6) NULL,
	[UnitPrice_CNY] [numeric](38, 6) NULL,
	[Discount] [decimal](38, 6) NULL,
	[Discount_USD] [numeric](38, 6) NULL,
	[Discount_EUR] [numeric](38, 6) NULL,
	[Discount_CNY] [numeric](38, 6) NULL,
	[DiscountPercent] [decimal](38, 6) NULL,
	[LineAmount] [decimal](38, 6) NULL,
	[LineAmount_USD] [numeric](38, 6) NULL,
	[LineAmount_EUR] [numeric](38, 6) NULL,
	[LineAmount_CNY] [numeric](38, 6) NULL,
	[SalesTaxIncluded] [decimal](38, 6) NULL,
	[SalesTaxIncluded_USD] [numeric](38, 6) NULL,
	[SalesTaxIncluded_EUR] [numeric](38, 6) NULL,
	[SalesTaxIncluded_CNY] [numeric](38, 6) NULL,
	[1099Box] [bigint] NOT NULL,
	[1099Amount] [decimal](38, 6) NULL,
	[1099Amount_USD] [numeric](38, 6) NULL,
	[1099Amount_EUR] [numeric](38, 6) NULL,
	[1099Amount_CNY] [numeric](38, 6) NULL,
	[StateProvince] [varchar](8000) NOT NULL,
	[1099StateAmount] [decimal](38, 6) NULL,
	[1099StateAmount_USD] [numeric](38, 6) NULL,
	[1099StateAmount_EUR] [numeric](38, 6) NULL,
	[1099StateAmount_CNY] [numeric](38, 6) NULL,
	[ReasonCode] [varchar](8000) NOT NULL,
	[ReasonComment] [varchar](8000) NOT NULL,
	[FreightCharge] [numeric](38, 6) NULL,
	[FreightCharge_USD] [numeric](38, 6) NULL,
	[FreightCharge_EUR] [numeric](38, 6) NULL,
	[FreightCharge_CNY] [numeric](38, 6) NULL,
	[PalletCharge] [numeric](38, 6) NULL,
	[PalletCharge_USD] [numeric](38, 6) NULL,
	[PalletCharge_EUR] [numeric](38, 6) NULL,
	[PalletCharge_CNY] [numeric](38, 6) NULL,
	[PetrolCharge] [numeric](38, 6) NULL,
	[PetrolCharge_USD] [numeric](38, 6) NULL,
	[PetrolCharge_EUR] [numeric](38, 6) NULL,
	[PetrolCharge_CNY] [numeric](38, 6) NULL,
	[SalesTaxCharge] [numeric](38, 6) NULL,
	[SalesTaxCharge_USD] [numeric](38, 6) NULL,
	[SalesTaxCharge_EUR] [numeric](38, 6) NULL,
	[SalesTaxCharge_CNY] [numeric](38, 6) NULL,
	[SetupFeeCharge] [numeric](38, 6) NULL,
	[SetupFeeCharge_USD] [numeric](38, 6) NULL,
	[SetupFeeCharge_EUR] [numeric](38, 6) NULL,
	[SetupFeeCharge_CNY] [numeric](38, 6) NULL,
	[ToteDepCharge] [numeric](38, 6) NULL,
	[ToteDepCharge_USD] [numeric](38, 6) NULL,
	[ToteDepCharge_EUR] [numeric](38, 6) NULL,
	[ToteDepCharge_CNY] [numeric](38, 6) NULL,
	[OtherCharge] [numeric](38, 6) NULL,
	[OtherCharge_USD] [numeric](38, 6) NULL,
	[OtherCharge_EUR] [numeric](38, 6) NULL,
	[OtherCharge_CNY] [numeric](38, 6) NULL,
	[TotalCharge] [numeric](38, 6) NULL,
	[TotalCharge_USD] [numeric](38, 6) NULL,
	[TotalCharge_EUR] [numeric](38, 6) NULL,
	[TotalCharge_CNY] [numeric](38, 6) NULL,
	[VendorKey] [bigint] NOT NULL,
	[ProductKey] [bigint] NOT NULL,
	[Legal_EntityKey] [bigint] NOT NULL,
	[PurchaseOrerKey] [bigint] NOT NULL,
	[InvoiceDateKey] [int] NULL,
	[Txn_USD_Rate_Missing] [int] NOT NULL,
	[Txn_EUR_Rate_Missing] [int] NOT NULL,
	[Txn_CNY_Rate_Missing] [int] NOT NULL,
	[Cost_USD_Rate_Missing] [int] NOT NULL,
	[Cost_EUR_Rate_Missing] [int] NOT NULL,
	[Cost_CNY_Rate_Missing] [int] NOT NULL
) 
GO


