CREATE TABLE [dbo].[tbl_custtrans] (
    [Id]                                     VARCHAR (8000)   NULL,
    [SinkCreatedOn]                          DATETIME2 (6)    NULL,
    [SinkModifiedOn]                         DATETIME2 (6)    NULL,
    [approved]                               BIGINT           NULL,
    [billofexchangestatus]                   BIGINT           NULL,
    [cancelledpayment]                       BIGINT           NULL,
    [cashpayment]                            BIGINT           NULL,
    [collectionletter]                       BIGINT           NULL,
    [collectionlettercode]                   BIGINT           NULL,
    [correct]                                BIGINT           NULL,
    [eurotriangulation]                      BIGINT           NULL,
    [fixedexchrate]                          BIGINT           NULL,
    [interest]                               BIGINT           NULL,
    [invoiceproject]                         BIGINT           NULL,
    [paymmethod]                             BIGINT           NULL,
    [prepayment]                             BIGINT           NULL,
    [retailcusttrans]                        BIGINT           NULL,
    [settlement]                             BIGINT           NULL,
    [transtype]                              BIGINT           NULL,
    [custautomationexclude]                  BIGINT           NULL,
    [custautomationpredunningsent]           BIGINT           NULL,
    [custautomationpredictionsent]           BIGINT           NULL,
    [invoicetype_it]                         BIGINT           NULL,
    [credmanexcludefromcreditcontrol]        BIGINT           NULL,
    [sks_dd_isdirectdebit]                   BIGINT           NULL,
    [sks_br_ddr_isselected]                  BIGINT           NULL,
    [sysdatastatecode]                       BIGINT           NULL,
    [postingprofileclose]                    VARCHAR (8000)   NULL,
    [accountingevent]                        BIGINT           NULL,
    [accountnum]                             VARCHAR (8000)   NULL,
    [amountcur]                              DECIMAL (38, 6)  NULL,
    [amountmst]                              DECIMAL (38, 6)  NULL,
    [approver]                               BIGINT           NULL,
    [bankcentralbankpurposecode]             VARCHAR (8000)   NULL,
    [bankcentralbankpurposetext]             VARCHAR (8000)   NULL,
    [banklcexportline]                       BIGINT           NULL,
    [bankremittancefileid]                   VARCHAR (8000)   NULL,
    [billofexchangeid]                       VARCHAR (8000)   NULL,
    [billofexchangeseqnum]                   BIGINT           NULL,
    [cashdisccode]                           VARCHAR (8000)   NULL,
    [cashdiscbasedate]                       DATETIME2 (6)    NULL,
    [closed]                                 DATETIME2 (6)    NULL,
    [companybankaccountid]                   VARCHAR (8000)   NULL,
    [controlnum]                             VARCHAR (8000)   NULL,
    [currencycode]                           VARCHAR (8000)   NULL,
    [custbillingclassification]              BIGINT           NULL,
    [custexchadjustmentrealized]             DECIMAL (38, 6)  NULL,
    [custexchadjustmentunrealized]           DECIMAL (38, 6)  NULL,
    [defaultdimension]                       BIGINT           NULL,
    [deliverymode]                           VARCHAR (8000)   NULL,
    [directdebitmandate]                     BIGINT           NULL,
    [documentdate]                           DATETIME2 (6)    NULL,
    [documentnum]                            VARCHAR (8000)   NULL,
    [duedate]                                DATETIME2 (6)    NULL,
    [exchadjustment]                         DECIMAL (38, 6)  NULL,
    [exchadjustmentreporting]                DECIMAL (38, 6)  NULL,
    [exchrate]                               DECIMAL (38, 16) NULL,
    [exchratesecond]                         DECIMAL (38, 16) NULL,
    [invoice]                                VARCHAR (8000)   NULL,
    [lastexchadj]                            DATETIME2 (6)    NULL,
    [lastexchadjrate]                        DECIMAL (38, 16) NULL,
    [lastexchadjratereporting]               DECIMAL (38, 16) NULL,
    [lastexchadjvoucher]                     VARCHAR (8000)   NULL,
    [lastsettleaccountnum]                   VARCHAR (8000)   NULL,
    [lastsettlecompany]                      VARCHAR (8000)   NULL,
    [lastsettledate]                         DATETIME2 (6)    NULL,
    [lastsettlevoucher]                      VARCHAR (8000)   NULL,
    [mcrpaymorderid]                         VARCHAR (8000)   NULL,
    [offsetrecid]                            BIGINT           NULL,
    [orderaccount]                           VARCHAR (8000)   NULL,
    [paymid]                                 VARCHAR (8000)   NULL,
    [paymmode]                               VARCHAR (8000)   NULL,
    [paymreference]                          VARCHAR (8000)   NULL,
    [paymspec]                               VARCHAR (8000)   NULL,
    [postingprofile]                         VARCHAR (8000)   NULL,
    [reasonrefrecid]                         BIGINT           NULL,
    [reportingcurrencyamount]                DECIMAL (38, 6)  NULL,
    [reportingcurrencyexchrate]              DECIMAL (38, 16) NULL,
    [reportingcurrencyexchratesecondary]     DECIMAL (38, 16) NULL,
    [reportingcurrencycrossrate]             DECIMAL (38, 16) NULL,
    [reportingexchadjustmentrealized]        DECIMAL (38, 6)  NULL,
    [reportingexchadjustmentunrealized]      DECIMAL (38, 6)  NULL,
    [retailstoreid]                          VARCHAR (8000)   NULL,
    [retailterminalid]                       VARCHAR (8000)   NULL,
    [retailtransactionid]                    VARCHAR (8000)   NULL,
    [settleamountcur]                        DECIMAL (38, 6)  NULL,
    [settleamountmst]                        DECIMAL (38, 6)  NULL,
    [settleamountreporting]                  DECIMAL (38, 6)  NULL,
    [taxinvoicesalesid]                      VARCHAR (8000)   NULL,
    [thirdpartybankaccountid]                VARCHAR (8000)   NULL,
    [transdate]                              DATETIME2 (6)    NULL,
    [txt]                                    VARCHAR (8000)   NULL,
    [voucher]                                VARCHAR (8000)   NULL,
    [paymschedid]                            VARCHAR (8000)   NULL,
    [paymtermid]                             VARCHAR (8000)   NULL,
    [settleamount_mx]                        DECIMAL (38, 6)  NULL,
    [modifieddatetime]                       DATETIME2 (6)    NULL,
    [modifiedby]                             VARCHAR (8000)   NULL,
    [modifiedtransactionid]                  BIGINT           NULL,
    [createddatetime]                        DATETIME2 (6)    NULL,
    [createdby]                              VARCHAR (8000)   NULL,
    [createdtransactionid]                   BIGINT           NULL,
    [dataareaid]                             VARCHAR (8000)   NULL,
    [recversion]                             BIGINT           NULL,
    [partition]                              BIGINT           NULL,
    [sysrowversion]                          BIGINT           NULL,
    [recid]                                  BIGINT           NULL,
    [tableid]                                BIGINT           NULL,
    [versionnumber]                          BIGINT           NULL,
    [createdon]                              DATETIME2 (6)    NULL,
    [modifiedon]                             DATETIME2 (6)    NULL,
    [IsDelete]                               BIT              NULL,
    [PartitionId]                            VARCHAR (2048)   NULL,
    [approved_$label]                        VARCHAR (3)      NULL,
    [billofexchangestatus_$label]            VARCHAR (18)     NULL,
    [cancelledpayment_$label]                VARCHAR (3)      NULL,
    [cashpayment_$label]                     VARCHAR (3)      NULL,
    [collectionletter_$label]                VARCHAR (3)      NULL,
    [collectionlettercode_$label]            VARCHAR (17)     NULL,
    [correct_$label]                         VARCHAR (3)      NULL,
    [credmanexcludefromcreditcontrol_$label] VARCHAR (3)      NULL,
    [custautomationexclude_$label]           VARCHAR (3)      NULL,
    [custautomationpredictionsent_$label]    VARCHAR (3)      NULL,
    [custautomationpredunningsent_$label]    VARCHAR (3)      NULL,
    [eurotriangulation_$label]               VARCHAR (3)      NULL,
    [fixedexchrate_$label]                   VARCHAR (3)      NULL,
    [interest_$label]                        VARCHAR (3)      NULL,
    [invoiceproject_$label]                  VARCHAR (3)      NULL,
    [invoicetype_it_$label]                  VARCHAR (17)     NULL,
    [paymmethod_$label]                      VARCHAR (12)     NULL,
    [prepayment_$label]                      VARCHAR (3)      NULL,
    [retailcusttrans_$label]                 VARCHAR (3)      NULL,
    [settlement_$label]                      VARCHAR (3)      NULL,
    [sks_br_ddr_isselected_$label]           VARCHAR (3)      NULL,
    [sks_dd_isdirectdebit_$label]            VARCHAR (3)      NULL,
    [transtype_$label]                       VARCHAR (49)     NULL
);


GO

