CREATE TABLE [dbo].[tbl_Fact_Inventory_Snapshot] (

	[inventorySnapshotKey] bigint NULL, 
	[CMPNY] varchar(8000) NULL, 
	[Site_ID] varchar(8000) NULL, 
	[Warehouse_ID] varchar(8000) NULL, 
	[Snapshot_Date] date NULL, 
	[Snapshot_Date_Key] int NULL, 
	[Product_ID] varchar(8000) NULL, 
	[ProductName] varchar(8000) NULL, 
	[ProductSearchName] varchar(8000) NULL, 
	[Phantom_Product] varchar(3) NULL, 
	[Inventory_UoM] varchar(8000) NULL, 
	[inventstatusid] varchar(8000) NULL, 
	[wmslocationid] varchar(8000) NULL, 
	[arrived] decimal(38,6) NULL, 
	[availordered] decimal(38,6) NULL, 
	[availphysical] decimal(38,6) NULL, 
	[deducted] decimal(38,6) NULL, 
	[onorder] decimal(38,6) NULL, 
	[ordered] decimal(38,6) NULL, 
	[physicalinvent] decimal(38,6) NULL, 
	[picked] decimal(38,6) NULL, 
	[postedqty] decimal(38,6) NULL, 
	[received] decimal(38,6) NULL, 
	[registered] decimal(38,6) NULL, 
	[reservordered] decimal(38,6) NULL, 
	[reservphysical] decimal(38,6) NULL, 
	[postedcostamount] decimal(38,6) NULL, 
	[arrived_LBs] decimal(38,6) NULL, 
	[availordered_LBs] decimal(38,6) NULL, 
	[availphysical_LBs] decimal(38,6) NULL, 
	[deducted_LBs] decimal(38,6) NULL, 
	[onorder_LBs] decimal(38,6) NULL, 
	[ordered_LBs] decimal(38,6) NULL, 
	[physicalinvent_LBs] decimal(38,6) NULL, 
	[picked_LBs] decimal(38,6) NULL, 
	[postedqty_LBs] decimal(38,6) NULL, 
	[received_LBs] decimal(38,6) NULL, 
	[registered_LBs] decimal(38,6) NULL, 
	[reservordered_LBs] decimal(38,6) NULL, 
	[reservphysical_LBs] decimal(38,6) NULL, 

	[arrived_KGs] decimal(38,6) NULL, 
	[availordered_KGs] decimal(38,6) NULL, 
	[availphysical_KGs] decimal(38,6) NULL, 
	[deducted_KGs] decimal(38,6) NULL, 
	[onorder_KGs] decimal(38,6) NULL, 
	[ordered_KGs] decimal(38,6) NULL, 
	[physicalinvent_KGs] decimal(38,6) NULL, 
	[picked_KGs] decimal(38,6) NULL, 
	[postedqty_KGs] decimal(38,6) NULL, 
	[received_KGs] decimal(38,6) NULL, 
	[registered_KGs] decimal(38,6) NULL, 
	[reservordered_KGs] decimal(38,6) NULL, 
	[reservphysical_KGs] decimal(38,6) NULL, 

	[primaryvendorid] varchar(8000) NULL, 
	[Source] varchar(6) NOT NULL, 
	[ProductKey] bigint NULL, 
	[SiteKey] bigint NULL, 
	[Legal_EntityKey] bigint NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[VendorKey] bigint NOT NULL, 
	[StandardCostKey] bigint NULL
);