CREATE TABLE [dbo].[tbl_Fact_ProjectPostedTransactions] (

	[CMPNY] varchar(8000) NULL, 
	[ProjId] varchar(8000) NULL, 
	[TransactionDate] datetime2(6) NULL, 
	[TransactionDateKey] int NULL, 
	[CategoryId] varchar(8000) NULL, 
	[ResourceName] varchar(8000) NULL, 
	[ItemId] varchar(8000) NULL, 
	[TotalSalesAmount] decimal(38,6) NULL, 
	[TotalSalesAmount_USD] decimal(38,6) NULL, 
	[TotalSalesAmount_EUR] decimal(38,6) NULL, 
	[TotalSalesAmount_CNY] decimal(38,6) NULL, 
	[AmountInTransaction] decimal(38,6) NULL, 
	[AmountInTransaction_USD] decimal(38,6) NULL, 
	[AmountInTransaction_EUR] decimal(38,6) NULL, 
	[AmountInTransaction_CNY] decimal(38,6) NULL, 
	[TotalCostAmount] numeric(38,6) NULL, 
	[TotalCostAmount_USD] decimal(38,6) NULL, 
	[TotalCostAmount_EUR] decimal(38,6) NULL, 
	[TotalCostAmount_CNY] decimal(38,6) NULL, 
	[InvoiceStatus] varchar(27) NOT NULL, 
	[TransType] varchar(17) NULL, 
	[TransCurrencyCode] varchar(8000) NULL, 
	[LegalEntityCurrencyCode] varchar(8000) NULL, 
	[Txn_Source_Currency] varchar(8000) NULL, 
	[Cost_Source_Currency] varchar(8000) NULL, 
	[Txn_USD_Rate_Missing] int NULL, 
	[Txn_EUR_Rate_Missing] int NULL, 
	[Txn_CNY_Rate_Missing] int NULL, 
	[Cost_USD_Rate_Missing] int NULL, 
	[Cost_EUR_Rate_Missing] int NULL, 
	[Cost_CNY_Rate_Missing] int NULL, 
	[TransId] varchar(8000) NULL, 
	[Qty] decimal(38,6) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[ProjectKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[WorkCenterKey] bigint NOT NULL, 
	[VendorKey] bigint NOT NULL 
);
