CREATE TABLE [dbo].[tbl_Fact_Production_Batch_Orders] (
    [CMPNY]                               VARCHAR (8000)  NULL,
    [ProductionBatchOrder]                VARCHAR (8000)  NULL,
    [Product_ID]                          VARCHAR (8000)  NULL,
    [bomid]                               VARCHAR (8000)  NULL,
    [BOMDate]                             DATETIME2 (6)   NULL,
    [unitid]                              VARCHAR (8000)  NULL,
    [RouteID]                             VARCHAR (8000)  NULL,
    [PBOFinishedDate]                     DATETIME2 (6)   NULL,
    [PBOFinishedDatekey]                  INT             NULL,
    [qtysched]                            DECIMAL (38, 6) NULL,
    [schedstartdate]                      DATETIME2 (6)   NULL,
    [schedstartdatekey]                   INT             NULL,
    [schedenddate]                        DATETIME2 (6)   NULL,
    [schedenddatekey]                     INT             NULL,
    [RequestedDeliveryDate]               DATETIME2 (6)   NULL,
    [RequestedDeliveryDatekey]            INT             NULL,
    [ScheduledFinishOnTime]               INT             NOT NULL,
    [ScheduledFinishDelayed]              INT             NOT NULL,
    [LastPhysicalInventoryReceiptDate]    DATETIME2 (6)   NULL,
    [LastPhysicalInventoryReceiptDatekey] INT             NULL,
    [ActualFinishOnTime]                  INT             NOT NULL,
    [ActualFinishDelayed]                 INT             NOT NULL,
    [QtyGood]                             DECIMAL (38, 6) NOT NULL,
    [ReportRemainder]                     DECIMAL (38, 6) NULL,
    [ScheduledStartDateTime]              DATETIME2 (6)   NULL,
    [ScheduledEndDateTime]                DATETIME2 (6)   NULL,
    [ScheduledCalendarDurationHrs]        NUMERIC (17, 6) NULL,
    [warehouse]                           VARCHAR (8000)  NULL,
    [configid]                            VARCHAR (8000)  NULL,
    [inventcolorid]                       VARCHAR (8000)  NULL,
    [inventbatchid]                       VARCHAR (8000)  NULL,
    [SerialNumber]                        VARCHAR (8000)  NULL,
    [inventsiteid]                        VARCHAR (8000)  NULL,
    [inventsizeid]                        VARCHAR (8000)  NULL,
    [wmslocationid]                       VARCHAR (8000)  NULL,
    [licenseplateid]                      VARCHAR (8000)  NULL,
    [inventstatusid]                      VARCHAR (8000)  NULL,
    [PalletID]                            VARCHAR (8000)  NULL,
    [accountingcurrency]                  VARCHAR (8000)  NULL,
    [qtystup]                             DECIMAL (38, 6) NULL,
    [qtycalc]                             DECIMAL (38, 6) NULL,
    [inventrefid]                         VARCHAR (8000)  NULL,
    [inventreftransid]                    VARCHAR (8000)  NULL,
    [inventreftype]                       BIGINT          NULL,
    [inventreftype_$label]                VARCHAR (14)    NULL,
    [inventtransid]                       VARCHAR (8000)  NULL,
    [prodorigid]                          VARCHAR (8000)  NULL,
    [DateSchedulingPerformed]             DATETIME2 (6)   NULL,
    [DateSchedulingPerformedkey]          INT             NULL,
    [stupdate]                            DATETIME2 (6)   NULL,
    [stupdatekey]                         INT             NULL,
    [CostCalcutaionDate]                  DATETIME2 (6)   NULL,
    [CostCalcutaionDatekey]               INT             NULL,
    [LatestSchedDateTime]                 DATETIME2 (3)   NULL,
    [latestscheddatekey]                  INT             NULL,
    [RealiztionDate]                      DATETIME2 (6)   NULL,
    [realdatekey]                         INT             NULL,
    [ReleasedDate]                        DATETIME2 (6)   NULL,
    [releaseddatekey]                     INT             NULL,
    [projcategoryid]                      VARCHAR (8000)  NULL,
    [projcostamount]                      DECIMAL (38, 6) NULL,
    [projcostprice]                       DECIMAL (38, 6) NULL,
    [projsalesprice]                      DECIMAL (38, 6) NULL,
    [pmfyieldpct]                         DECIMAL (38, 6) NULL,
    [IsOpen]                              VARCHAR (3)     NOT NULL,
    [IsLate]                              VARCHAR (3)     NOT NULL,
    [IsLateOpenOrder]                     VARCHAR (3)     NOT NULL,
    [Legal_EntityKey]                     BIGINT          NOT NULL,
    [HistoricalProductKey]                BIGINT          NOT NULL,
    [ProductKey]                          BIGINT          NOT NULL,
    [ProductionBatchOrderKey]             BIGINT          NOT NULL,
    [SiteKey]                             BIGINT          NOT NULL,
    [WarehouseKey]                        BIGINT          NOT NULL,
    [RouteKey]                            BIGINT          NOT NULL
);


GO

