CREATE TABLE [dbo].[tbl_Fact_Production_Batch_Orders] (

	[CMPNY] varchar(8000) NULL, 
	[ProductionBatchOrder] varchar(8000) NULL, 
	[Product_ID] varchar(8000) NULL, 
	[bomid] varchar(8000) NULL, 
	[BOMDate] datetime2(6) NULL, 
	[unitid] varchar(8000) NULL, 
	[RouteID] varchar(8000) NULL, 
	[PBOFinishedDate] datetime2(6) NULL, 
	[PBOFinishedDatekey] int NULL, 
	[qtysched] decimal(38,6) NULL, 
	[schedstartdate] datetime2(6) NULL, 
	[schedstartdatekey] int NULL, 
	[schedenddate] datetime2(6) NULL, 
	[schedenddatekey] int NULL, 
	[RequestedDeliveryDate] datetime2(6) NULL, 
	[RequestedDeliveryDatekey] int NULL, 
	[ScheduledFinishOnTime] int NOT NULL, 
	[ScheduledFinishDelayed] int NOT NULL, 
	[LastPhysicalInventoryReceiptDate] datetime2(6) NULL, 
	[LastPhysicalInventoryReceiptDatekey] int NULL, 
	[ActualFinishOnTime] int NOT NULL, 
	[ActualFinishDelayed] int NOT NULL, 
	[QtyGood] decimal(38,6) NOT NULL, 
	[ReportRemainder] decimal(38,6) NULL, 
	[ScheduledStartDateTime] datetime2(6) NULL, 
	[ScheduledEndDateTime] datetime2(6) NULL, 
	[ScheduledCalendarDurationHrs] numeric(17,6) NULL, 
	[warehouse] varchar(8000) NULL, 
	[configid] varchar(8000) NULL, 
	[inventcolorid] varchar(8000) NULL, 
	[inventbatchid] varchar(8000) NULL, 
	[SerialNumber] varchar(8000) NULL, 
	[inventsiteid] varchar(8000) NULL, 
	[inventsizeid] varchar(8000) NULL, 
	[wmslocationid] varchar(8000) NULL, 
	[licenseplateid] varchar(8000) NULL, 
	[inventstatusid] varchar(8000) NULL, 
	[PalletID] varchar(8000) NULL, 
	[accountingcurrency] varchar(8000) NULL, 
	[qtystup] decimal(38,6) NULL, 
	[qtycalc] decimal(38,6) NULL, 
	[inventrefid] varchar(8000) NULL, 
	[inventreftransid] varchar(8000) NULL, 
	[inventreftype] bigint NULL, 
	[inventreftype_$label] varchar(14) NULL, 
	[inventtransid] varchar(8000) NULL, 
	[prodorigid] varchar(8000) NULL, 
	[DateSchedulingPerformed] datetime2(6) NULL, 
	[DateSchedulingPerformedkey] int NULL, 
	[stupdate] datetime2(6) NULL, 
	[stupdatekey] int NULL, 
	[CostCalcutaionDate] datetime2(6) NULL, 
	[CostCalcutaionDatekey] int NULL, 
	[LatestSchedDateTime] datetime2(3) NULL, 
	[latestscheddatekey] int NULL, 
	[RealiztionDate] datetime2(6) NULL, 
	[realdatekey] int NULL, 
	[ReleasedDate] datetime2(6) NULL, 
	[releaseddatekey] int NULL, 
	[projcategoryid] varchar(8000) NULL, 
	[projcostamount] decimal(38,6) NULL, 
	[projcostprice] decimal(38,6) NULL, 
	[projsalesprice] decimal(38,6) NULL, 
	[pmfyieldpct] decimal(38,6) NULL, 
	[IsOpen] varchar(3) NOT NULL, 
	[IsLate] varchar(3) NOT NULL, 
	[IsLateOpenOrder] varchar(3) NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[HistoricalProductKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[ProductionBatchOrderKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[RouteKey] bigint NOT NULL
);