CREATE TABLE [dbo].[tbl_Fact_PurchaseOrderItemConsumption] (

	[CMPNY] varchar(8000) NULL, 
	[PurchaseOrderNumber] varchar(8000) NULL, 
	[linenumber] bigint NULL, 
	[ProductID] varchar(8000) NULL, 
	[inventdimid] varchar(8000) NULL, 
	[BatchID] varchar(8000) NULL, 
	[SiteID] varchar(8000) NULL, 
	[Warehouse] varchar(8000) NULL, 
	[licenseplateid] varchar(8000) NULL, 
	[pl_purchstatus_label] varchar(8) NULL, 
	[pt_purchstatus_label] varchar(8) NULL, 
	[inventtransid] varchar(8000) NULL, 
	[Currency_Code] varchar(8000) NULL, 
	[lineamount] decimal(38,6) NULL, 
	[lineamount_USD] decimal(38,6) NULL, 
	[lineamount_EUR] decimal(38,6) NULL, 
	[lineamount_CNY] decimal(38,6) NULL, 
	[purchqty] decimal(38,6) NULL, 
	[qtyordered] decimal(38,6) NULL, 
	[purchunit] varchar(8000) NULL, 
	[QtyOrdered_LBs] decimal(38,6) NULL, 
	[QtyOrdered_KGs] decimal(38,6) NULL, 
	[vendaccount] varchar(8000) NULL, 
	[referencecategory] bigint NULL, 
	[referencecategory_$label] varchar(48) NULL, 
	[referenceid] varchar(8000) NULL, 
	[FinishedGoodProductID] varchar(8000) NULL, 
	[FinishedGoodName] varchar(8000) NULL, 
	[FinishedGoodCommercialName] varchar(8000) NULL, 
	[Inventory_UoM] varchar(8000) NULL, 
	[qty] decimal(38,6) NULL, 
	[costamountphysical] decimal(38,6) NULL, 
	[costamountphysical_USD] decimal(38,6) NULL, 
	[costamountphysical_EUR] decimal(38,6) NULL, 
	[costamountphysical_CNY] decimal(38,6) NULL, 
	[costamountadjustment] decimal(38,6) NULL, 
	[costamountadjustment_USD] decimal(38,6) NULL, 
	[costamountadjustment_EUR] decimal(38,6) NULL, 
	[costamountadjustment_CNY] decimal(38,6) NULL, 
	[costamountposted] decimal(38,6) NULL, 
	[costamountposted_USD] decimal(38,6) NULL, 
	[costamountposted_EUR] decimal(38,6) NULL, 
	[costamountposted_CNY] decimal(38,6) NULL, 
	[costamountNet] decimal(38,6) NULL, 
	[costamountNet_USD] decimal(38,6) NULL, 
	[costamountNet_EUR] decimal(38,6) NULL, 
	[costamountNet_CNY] decimal(38,6) NULL, 
	[currencycode] varchar(8000) NULL, 
	[dateexpected] datetime2(6) NULL, 
	[datephysical] datetime2(6) NULL, 
	[datefinancial] datetime2(6) NULL, 
	[inventtransorigin] bigint NULL, 
	[invoiceid] varchar(8000) NULL, 
	[packingslipid] varchar(8000) NULL, 
	[voucher] varchar(8000) NULL, 
	[voucherphysical] varchar(8000) NULL, 
	[statusissue] bigint NULL, 
	[statusissue_$label] varchar(14) NULL, 
	[statusreceipt] bigint NULL, 
	[statusreceipt_$label] varchar(16) NULL, 
	[VendorKey] bigint NOT NULL, 
	[InvoiceVendorKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[EmployeeKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[PurchaseOrerKey] bigint NOT NULL, 
	[BatchKey] bigint NOT NULL, 
	[Cost_Source_Currency] varchar(8000) NULL, 
	[Txn_Source_Currency] varchar(8000) NULL, 
	[Txn_USD_Rate_Missing] int NULL, 
	[Txn_EUR_Rate_Missing] int NULL, 
	[Txn_CNY_Rate_Missing] int NULL, 
	[Cost_USD_Rate_Missing] int NULL, 
	[Cost_EUR_Rate_Missing] int NULL, 
	[Cost_CNY_Rate_Missing] int NULL 
);