CREATE TABLE [dbo].[tbl_RESULTSSLSBYYR_BVBA_Thru2025] (

	[Sales Mo] varchar(50) NULL, 
	[Sales Yr] varchar(50) NULL, 
	[Fiscal Yr] varchar(50) NULL, 
	[Cmpny] varchar(50) NULL, 
	[Order No] varchar(50) NULL, 
	[Ord Date] datetime2(3) NULL, 
	[Warehouse] varchar(50) NULL, 
	[Ship Date] varchar(50) NULL, 
	[Invoice No] varchar(50) NULL, 
	[Invoice Date] varchar(50) NULL, 
	[Customer No] varchar(50) NULL, 
	[Customer Name] varchar(50) NULL, 
	[Salesman No] varchar(50) NULL, 
	[Salesman Name] varchar(50) NULL, 
	[Sales Manager No] varchar(50) NULL, 
	[Sales Manager Name] varchar(50) NULL, 
	[Ship To Name] varchar(50) NULL, 
	[Ship To Address1] varchar(50) NULL, 
	[Ship To Address2] varchar(50) NULL, 
	[Ship To Address3] varchar(50) NULL, 
	[Ship To Address4] varchar(50) NULL, 
	[Product Line] varchar(50) NULL, 
	[Product] varchar(50) NULL, 
	[Lbs Ordered] varchar(50) NULL, 
	[Lbs Shipped] decimal(20,2) NULL, 
	[Price] varchar(50) NULL, 
	[Extension] decimal(20,2) NULL, 
	[Newark Price] varchar(50) NULL, 
	[Newark Extension] varchar(50) NULL, 
	[Cost Per Lb] varchar(50) NULL, 
	[Ship To No] varchar(50) NULL, 
	[Cust Address1] varchar(50) NULL, 
	[Cust Address2] varchar(50) NULL, 
	[Cust Address3] varchar(50) NULL, 
	[Cust Address4] varchar(50) NULL, 
	[MasterAcct] varchar(50) NULL, 
	[MasterAcctName] varchar(50) NULL, 
	[Location] varchar(50) NULL, 
	[Industry] varchar(50) NULL, 
	[Cust City] varchar(50) NULL, 
	[Cust State] varchar(50) NULL, 
	[Cust Zip] varchar(50) NULL, 
	[Ship To City] varchar(50) NULL, 
	[Ship To State] varchar(50) NULL, 
	[Ship To Zip] varchar(50) NULL, 
	[Country] varchar(50) NULL, 
	[Region] varchar(50) NULL, 
	[Customer PO] varchar(50) NULL, 
	[Contact] varchar(50) NULL, 
	[FOB Terms] varchar(50) NULL, 
	[Freight] varchar(50) NULL, 
	[Handling] varchar(50) NULL, 
	[Sales Supervisor] varchar(50) NULL, 
	[Sales Supervisor Name] varchar(50) NULL, 
	[Warehouse name] varchar(50) NULL, 
	[DataUpdateDate] varchar(50) NULL, 
	[Results_ID] varchar(50) NULL, 
	[SnapShotDate] datetime2(3) NULL, 
	[Source] varchar(10) NULL, 
	[SLS_SID] int NULL
);