CREATE TABLE [dbo].[tbl_RESULTSSLSBYYR_BVBA] (
    [Sales Mo]              VARCHAR (50)    NULL,
    [Sales Yr]              VARCHAR (50)    NULL,
    [Fiscal Yr]             VARCHAR (50)    NULL,
    [Cmpny]                 VARCHAR (50)    NULL,
    [Order No]              VARCHAR (50)    NULL,
    [Ord Date]              DATETIME2 (3)   NULL,
    [Warehouse]             VARCHAR (50)    NULL,
    [Ship Date]             VARCHAR (50)    NULL,
    [Invoice No]            VARCHAR (50)    NULL,
    [Invoice Date]          VARCHAR (50)    NULL,
    [Customer No]           VARCHAR (50)    NULL,
    [Customer Name]         VARCHAR (50)    NULL,
    [Salesman No]           VARCHAR (50)    NULL,
    [Salesman Name]         VARCHAR (50)    NULL,
    [Sales Manager No]      VARCHAR (50)    NULL,
    [Sales Manager Name]    VARCHAR (50)    NULL,
    [Ship To Name]          VARCHAR (50)    NULL,
    [Ship To Address1]      VARCHAR (50)    NULL,
    [Ship To Address2]      VARCHAR (50)    NULL,
    [Ship To Address3]      VARCHAR (50)    NULL,
    [Ship To Address4]      VARCHAR (50)    NULL,
    [Product Line]          VARCHAR (50)    NULL,
    [Product]               VARCHAR (50)    NULL,
    [Lbs Ordered]           VARCHAR (50)    NULL,
    [Lbs Shipped]           DECIMAL (20, 2) NULL,
    [Price]                 VARCHAR (50)    NULL,
    [Extension]             DECIMAL (20, 2) NULL,
    [Newark Price]          VARCHAR (50)    NULL,
    [Newark Extension]      VARCHAR (50)    NULL,
    [Cost Per Lb]           VARCHAR (50)    NULL,
    [Ship To No]            VARCHAR (50)    NULL,
    [Cust Address1]         VARCHAR (50)    NULL,
    [Cust Address2]         VARCHAR (50)    NULL,
    [Cust Address3]         VARCHAR (50)    NULL,
    [Cust Address4]         VARCHAR (50)    NULL,
    [MasterAcct]            VARCHAR (50)    NULL,
    [MasterAcctName]        VARCHAR (50)    NULL,
    [Location]              VARCHAR (50)    NULL,
    [Industry]              VARCHAR (50)    NULL,
    [Cust City]             VARCHAR (50)    NULL,
    [Cust State]            VARCHAR (50)    NULL,
    [Cust Zip]              VARCHAR (50)    NULL,
    [Ship To City]          VARCHAR (50)    NULL,
    [Ship To State]         VARCHAR (50)    NULL,
    [Ship To Zip]           VARCHAR (50)    NULL,
    [Country]               VARCHAR (50)    NULL,
    [Region]                VARCHAR (50)    NULL,
    [Customer PO]           VARCHAR (50)    NULL,
    [Contact]               VARCHAR (50)    NULL,
    [FOB Terms]             VARCHAR (50)    NULL,
    [Freight]               VARCHAR (50)    NULL,
    [Handling]              VARCHAR (50)    NULL,
    [Sales Supervisor]      VARCHAR (50)    NULL,
    [Sales Supervisor Name] VARCHAR (50)    NULL,
    [Warehouse name]        VARCHAR (50)    NULL,
    [DataUpdateDate]        VARCHAR (50)    NULL,
    [Results_ID]            VARCHAR (50)    NULL,
    [SnapShotDate]          DATETIME2 (3)   NULL,
    [Source]                VARCHAR (10)    NULL,
    [SLS_SID]               INT             NULL
);


GO

