CREATE TABLE [dbo].[vw_OpportunityList] (

	[OpportunityID] varchar(15) NULL, 
	[RecordType] varchar(3) NULL, 
	[GMAccountno] varchar(20) NULL, 
	[Manager] varchar(8) NULL, 
	[Company] varchar(40) NULL, 
	[Contact] varchar(40) NULL, 
	[Opportunity] varchar(50) NULL, 
	[OpportunityStatus] varchar(50) NULL, 
	[OpportunityStage] varchar(30) NULL, 
	[OpportunityIndustry] varchar(30) NULL, 
	[StartDate] datetime2(3) NULL, 
	[ClosedDate] datetime2(3) NULL, 
	[CloseByDate] datetime2(3) NULL, 
	[Probability] smallint NULL, 
	[Notes] varchar(8000) NULL, 
	[ProductName] varchar(50) NULL, 
	[DesiredCharacteristics] varchar(80) NULL, 
	[EstimatedAnnualVolume] int NULL, 
	[SpecificApplication] varchar(80) NULL, 
	[TargetPrice] float NULL, 
	[OpportunityPriority] varchar(20) NULL, 
	[RecordID] varchar(15) NULL
);