CREATE TABLE [dbo].[vw_OpMgr] (

	[OPID] varchar(15) NULL, 
	[RECTYPE] varchar(3) NULL, 
	[ACCOUNTNO] varchar(20) NULL, 
	[USERID] varchar(8) NULL, 
	[FLAGS] varchar(10) NULL, 
	[COMPANY] varchar(40) NULL, 
	[CONTACT] varchar(40) NULL, 
	[NAME] varchar(50) NULL, 
	[STATUS] varchar(50) NULL, 
	[CYCLE] varchar(50) NULL, 
	[STAGE] varchar(30) NULL, 
	[SOURCE] varchar(30) NULL, 
	[F1] varchar(20) NULL, 
	[F2] varchar(20) NULL, 
	[F3] varchar(20) NULL, 
	[STARTDATE] datetime2(3) NULL, 
	[CLOSEDDATE] datetime2(3) NULL, 
	[CLOSEBY] datetime2(3) NULL, 
	[FORAMT] float NULL, 
	[FORPROB] smallint NULL, 
	[CLOSEAMT] float NULL, 
	[NOTES] varchar(8000) NULL, 
	[PRODUCTNAME] varchar(50) NULL, 
	[UDESCHAR] varchar(80) NULL, 
	[UEAV] int NULL, 
	[USPECAPP] varchar(80) NULL, 
	[UTPRICE] float NULL, 
	[UTSPROJID] varchar(20) NULL, 
	[U_STAGE] varchar(30) NULL, 
	[recid] varchar(15) NULL
);