CREATE TABLE [dbo].[mtbl_EDW_Fact_Customer_Invoices] (

	[CMPNY] varchar(8000) NULL, 
	[Invoice_ID] varchar(8000) NULL, 
	[InvoiceDate] datetime2(6) NULL, 
	[InvoiceDateKey] int NULL, 
	[Sales_ID] varchar(8000) NULL, 
	[Order_Account] varchar(8000) NULL, 
	[Invoice_Account] varchar(8000) NULL, 
	[Tax_Group] varchar(8000) NULL, 
	[Country] varchar(8000) NULL, 
	[Invoice_Line_Name] varchar(8000) NULL, 
	[InvoiceAmount] decimal(38,6) NULL, 
	[InvoiceAmountMST] decimal(38,6) NULL, 
	[Freight] decimal(38,6) NULL, 
	[Fuel_Charge] decimal(38,6) NULL, 
	[Comms] decimal(38,6) NULL, 
	[PLT_Brk_Ch] decimal(38,6) NULL, 
	[Tariff_SC] decimal(38,6) NULL, 
	[LineNumber] decimal(38,16) NULL, 
	[Product_ID] varchar(8000) NULL, 
	[Site_ID] varchar(8000) NULL, 
	[Warehouse_ID] varchar(8000) NULL, 
	[LineAmount] decimal(38,6) NULL, 
	[LineAmountMST] decimal(38,6) NULL, 
	[Current_Code] varchar(8000) NULL, 
	[salesunit] varchar(8000) NULL, 
	[Qty] decimal(38,6) NULL, 
	[Quantity_LBs] decimal(38,6) NULL, 
	[SalesPrice] decimal(38,6) NULL, 
	[CostAmount] decimal(38,6) NULL, 
	[CostAmountPhysical] decimal(38,6) NULL, 
	[Margin] decimal(38,6) NULL, 
	[InventTransID] varchar(8000) NULL, 
	[InventDimID] varchar(8000) NULL, 
	[postedstateID] bigint NULL, 
	[PostedState] varchar(12) NULL, 
	[Source] varchar(6) NOT NULL, 
	[CustomerKey] bigint NOT NULL, 
	[InvoiceCustomerKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[StandardCostKey] bigint NULL, 
	[MarketSegmentationKey] bigint NOT NULL, 
	[SalesOrderKey] bigint NOT NULL, 
	[DeliveryAddressKey] bigint NOT NULL
);