CREATE TABLE [dbo].[mtbl_EDW_Fact_CustTrans] (

	[Company] varchar(8000) NULL, 
	[voucher] varchar(8000) NULL, 
	[Customer_ID] varchar(8000) NULL, 
	[TransactionDate] datetime2(6) NULL, 
	[TransactionDateKey] int NULL, 
	[GL_TransType] bigint NULL, 
	[GLTransTypeDesc] varchar(49) NULL, 
	[currencycode] varchar(8000) NULL, 
	[Invoice_ID] varchar(8000) NULL, 
	[closed] datetime2(6) NULL, 
	[ClosedDateKey] int NULL, 
	[duedate] datetime2(6) NULL, 
	[DueDateKey] int NULL, 
	[OpenID] int NOT NULL, 
	[DaysOverdue] int NULL, 
	[AgingBucketKey] int NULL, 
	[Description] varchar(10) NULL, 
	[amountcur] decimal(38,6) NULL, 
	[amountmst] decimal(38,6) NULL, 
	[custexchadjustmentrealized] decimal(38,6) NULL, 
	[custexchadjustmentunrealized] decimal(38,6) NULL, 
	[settleamountmst] decimal(38,6) NULL, 
	[Amount] decimal(38,6) NULL, 
	[DaysOutstanding] int NULL, 
	[lastsettledate] datetime2(6) NULL, 
	[CustomerKey] bigint NOT NULL, 
	[Legal_EntityKey] bigint NOT NULL
);