CREATE TABLE [dbo].[mtbl_EDW_Fact_Production_Job_Routes] (

	[CMPNY] varchar(8000) NULL, 
	[ProdID] varchar(8000) NULL, 
	[WrkCtrID] varchar(8000) NULL, 
	[oprnum] bigint NULL, 
	[oprpriority] bigint NULL, 
	[oprpriority_$label] varchar(11) NULL, 
	[Operation] varchar(8000) NULL, 
	[ProdIDandOprNum] varchar(8000) NULL, 
	[Name] varchar(8000) NULL, 
	[jobtype] bigint NULL, 
	[jobtype_$label] varchar(11) NULL, 
	[link] bigint NULL, 
	[link_$label] varchar(4) NULL, 
	[linktype] bigint NULL, 
	[linktype_$label] varchar(4) NULL, 
	[jobid] varchar(8000) NULL, 
	[Resource] varchar(8000) NULL, 
	[propertyid] varchar(8000) NULL, 
	[jobcontrol] bigint NULL, 
	[JobManagement] varchar(3) NULL, 
	[jobstatus] bigint NULL, 
	[jobstatus_$label] varchar(9) NULL, 
	[jobpaytype] bigint NULL, 
	[jobpaytype_$label] varchar(9) NULL, 
	[schedcancelled] bigint NULL, 
	[Canceled] varchar(3) NULL, 
	[CalculatedTime] decimal(38,6) NULL, 
	[ResourceTime] decimal(38,6) NULL, 
	[ProcessingPercentage] numeric(38,6) NULL, 
	[SchedStartDateTime] datetime2(6) NULL, 
	[SchedEndDateTime] datetime2(6) NULL, 
	[ActualStartDateTime] datetime2(6) NULL, 
	[ActualEndDateTime] datetime2(6) NULL, 
	[SchedStartDateKey] int NULL, 
	[ActualStartDateKey] int NULL, 
	[inventsiteid] varchar(8000) NULL, 
	[Warehouse] varchar(8000) NULL, 
	[ProductionProductID] varchar(8000) NULL, 
	[routeid] varchar(8000) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[HistoricalProductKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[ProductionBatchOrderKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[RouteKey] bigint NOT NULL, 
	[WorkCenterKey] bigint NOT NULL
);