CREATE TABLE [dbo].[tbl_Fact_WorkOrderCycleCountTransactions] (

	[CMPNY] varchar(8000) NULL, 
	[WorkId] varchar(8000) NULL, 
	[LicensePlateId] varchar(8000) NULL, 
	[InventStatusId] varchar(8000) NULL, 
	[QtyExpected] decimal(38,6) NULL, 
	[QtyCounted] decimal(38,6) NULL, 
	[QtyVariance] decimal(38,6) NULL, 
	[ReasonCode] varchar(8000) NULL, 
	[ReasonDescription] varchar(8000) NULL, 
	[LineNum] decimal(38,16) NULL, 
	[WorkTransType] varchar(22) NULL, 
	[IsCounted] varchar(3) NULL, 
	[AcceptReject] varchar(6) NULL, 
	[ReconcileStatus] varchar(3) NULL, 
	[WMSLocationId] varchar(8000) NULL, 
	[IsAnchored] varchar(3) NULL, 
	[IsCountMandatory] varchar(3) NULL, 
	[IsCountSkipped] varchar(3) NULL, 
	[WorkLineStatus] varchar(13) NULL, 
	[IsWorkStopped] varchar(3) NULL, 
	[WorkLineType] varchar(24) NULL, 
	[AdjustmentWorkId] varchar(8000) NULL, 
	[AdjWorkTransType] varchar(22) NULL, 
	[AdjWorkStatus] varchar(13) NULL, 
	[AdjWorkCreatedBy] varchar(8000) NULL, 
	[AdjWorkStartedUTC] datetime2(6) NULL, 
	[AdjWorkClosedUTC] datetime2(6) NULL, 
	[AdjWorkType] varchar(24) NULL, 
	[AdjQtyWork] decimal(38,6) NULL, 
	[AdjWMSLocationId] varchar(8000) NULL, 
	[AdjUnitId] varchar(8000) NULL, 
	[Legal_EntityKey] bigint NOT NULL, 
	[WorkOrderKey] bigint NOT NULL, 
	[AdjustmentWorkOrderKey] bigint NOT NULL, 
	[ProductKey] bigint NOT NULL, 
	[SiteKey] bigint NOT NULL, 
	[WarehouseKey] bigint NOT NULL, 
	[BatchKey] bigint NOT NULL, 
	[SerialNumberKey] bigint NOT NULL, 
	[StandardCostKey] bigint NULL, 
	[WorkCancelledUTCDateKey] int NULL, 
	[WorkStartedUTCDateKey] int NULL, 
	[WorkClosedUTCDateKey] int NULL, 
	[CreatedDateTimeDateKey] int NULL, 
	[ModifiedDateTimeDateKey] int NULL, 
	[AdjWorkStartedUTCDateKey] int NOT NULL, 
	[AdjWorkClosedUTCDateKey] int NOT NULL
);