CREATE TABLE [dbo].[tbl_ExplodedFormula_ByVersion] (

	[ExplodedFormulaKey] bigint NULL, 
	[DataAreaId] varchar(8000) NULL, 
	[FgItemId] varchar(8000) NULL, 
	[FgSiteId] varchar(8000) NULL, 
	[FgBomId] varchar(8000) NULL, 
	[PeriodFromDate] datetime2(3) NULL, 
	[PeriodToDate] datetime2(3) NULL, 
	[RmItemId] varchar(8000) NULL, 
	[RmSiteId] varchar(8000) NULL, 
	[LbsPerLbFG] decimal(28,8) NULL, 
	[NativeLbsPerLbFG] decimal(28,8) NULL, 
	[RmNativeUomId] varchar(8000) NULL, 
	[UomConverted] int NULL, 
	[UomConversionMissing] int NULL, 
	[PercentControlled] int NULL, 
	[Percent] decimal(28,8) NULL, 
	[BomPath] varchar(8000) NULL, 
	[BomLevel] int NULL, 
	[FgFormulaUomId] varchar(8000) NULL, 
	[FgFormulaQtyLbs] decimal(28,8) NULL, 
	[FgItemName] varchar(8000) NULL, 
	[FgItemGroupId] varchar(8000) NULL, 
	[RmItemName] varchar(8000) NULL, 
	[RmItemGroupId] varchar(8000) NULL, 
	[IsCurrentPeriod] int NULL, 
	[LoadedAtUtc] datetime2(3) NULL
);