CREATE TABLE [dbo].[tbl_dlyorder] (

	[Cono] varchar(50) NULL, 
	[Order#] varchar(50) NULL, 
	[Cust #] varchar(50) NULL, 
	[Customer] varchar(50) NULL, 
	[Shipto Name] varchar(50) NULL, 
	[Shipto Addr1] varchar(50) NULL, 
	[Ship To] varchar(50) NULL, 
	[St] varchar(50) NULL, 
	[Shipto Addr4] varchar(50) NULL, 
	[Date Ord] varchar(50) NULL, 
	[Date Req] varchar(50) NULL, 
	[Cust Po] varchar(50) NULL, 
	[Whse] varchar(50) NULL, 
	[Via] varchar(50) NULL, 
	[Product] varchar(50) NULL, 
	[Prod Line] varchar(50) NULL, 
	[Lbs] varchar(50) NULL, 
	[Price $] varchar(50) NULL, 
	[Ext] varchar(50) NULL, 
	[MoYr] varchar(50) NULL, 
	[Dir  Cost LB] varchar(50) NULL, 
	[Contr LB] varchar(50) NULL, 
	[Contribution] varchar(50) NULL, 
	[Tot  Cost LB] varchar(50) NULL, 
	[Profit LB] varchar(50) NULL, 
	[Gross Margin] varchar(50) NULL, 
	[Salesman] varchar(50) NULL, 
	[SnapShotDate] datetime2(6) NULL, 
	[DataUpdateDate] datetime2(6) NULL, 
	[Source] varchar(10) NULL
);