table Dim_Address
	lineageTag: 3742a365-5363-45bd-8fe3-e621a73a2393
	sourceLineageTag: [dbo].[mtbl_EDW_DIM_Address]

	measure 'CPCID State' =
			
			VAR StateCount =
			    CALCULATE (
			        DISTINCTCOUNT ( 'Dim_Address'[State] ),
			        ALLEXCEPT ( 'Fact_Sales', 'Fact_Sales'[CPCID] )
			    )
			VAR SingleState =
			    CALCULATE (
			        SELECTEDVALUE ( 'Dim_Address'[State] ),
			        ALLEXCEPT ( 'Fact_Sales', 'Fact_Sales'[CPCID] )
			    )
			RETURN
			    SWITCH (
			        TRUE (),
			        StateCount = 0, BLANK (),
			        StateCount = 1, SingleState,
			        "Multiple"
			    )
		lineageTag: c1634c3a-2f1c-4eff-a096-a000ea28799f

		changedProperty = Name

	measure 'CPCID Country' =
			
			VAR CountryCount =
			    CALCULATE (
			        DISTINCTCOUNT ( 'Dim_Address'[Country] ),
			        ALLEXCEPT ( 'Fact_Sales', 'Fact_Sales'[CPCID] )
			    )
			VAR SingleCountry =
			    CALCULATE (
			        SELECTEDVALUE ( 'Dim_Address'[Country] ),
			        ALLEXCEPT ( 'Fact_Sales', 'Fact_Sales'[CPCID] )
			    )
			RETURN
			    SWITCH (
			        TRUE (),
			        CountryCount = 0, BLANK (),
			        CountryCount = 1, SingleCountry,
			        "Multiple"
			    )
		lineageTag: b619acac-4ab9-4092-8e74-9894fccec5e9

		changedProperty = Name

	column AddressKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 9a085534-05f4-4af3-95fa-04eaf117e0b8
		sourceLineageTag: AddressKey
		summarizeBy: none
		sourceColumn: AddressKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AddressRecId
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3b2d8008-daaf-44e5-8bca-1e95c6d7f652
		sourceLineageTag: AddressRecId
		summarizeBy: none
		sourceColumn: AddressRecId

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: e6167b27-581d-4dab-a3f9-effe0723f6fa
		sourceLineageTag: Location
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Street
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c3c129fe-b13d-4b64-963c-cbf4d1fc64d9
		sourceLineageTag: Street
		summarizeBy: none
		sourceColumn: Street

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 00f02813-4a5a-4fc8-9aeb-50b7e79863f2
		sourceLineageTag: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 89e5e5e7-5c7d-4dcc-9ef6-079c161d404c
		sourceLineageTag: State
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column ZipCode
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 346daa3e-02b7-4de0-b4eb-21af3280a0ed
		sourceLineageTag: ZipCode
		summarizeBy: none
		sourceColumn: ZipCode

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ee203c11-d48a-4460-9124-52006a732f65
		sourceLineageTag: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column ValidFrom
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 67ac1ecd-31db-4916-926d-a95549137e30
		sourceLineageTag: ValidFrom
		summarizeBy: none
		sourceColumn: ValidFrom

		annotation SummarizationSetBy = Automatic

	column ValidTo
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: c8807834-1275-461f-bb20-25b4d2bb98b6
		sourceLineageTag: ValidTo
		summarizeBy: none
		sourceColumn: ValidTo

		annotation SummarizationSetBy = Automatic

	column LocationName
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 3ad17d99-d658-4826-a2da-df2aac53424a
		sourceLineageTag: LocationName
		summarizeBy: none
		sourceColumn: LocationName

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		sourceProviderType: varchar(6)
		lineageTag: aac6eac1-566b-4097-979d-834b21d3875e
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 7a800d87-5602-42ba-96b8-81d69968322f
		sourceLineageTag: RecordEffectiveStartDate
		summarizeBy: none
		sourceColumn: RecordEffectiveStartDate

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveEndDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 0e287caf-9d52-4dee-b075-8cd272487475
		sourceLineageTag: RecordEffectiveEndDate
		summarizeBy: none
		sourceColumn: RecordEffectiveEndDate

		annotation SummarizationSetBy = Automatic

	column RecordStatus
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ca381c3f-c63b-479a-93ba-46110e2621c3
		sourceLineageTag: RecordStatus
		summarizeBy: none
		sourceColumn: RecordStatus

		annotation SummarizationSetBy = Automatic

	partition Dim_Address = entity
		mode: directLake
		source
			entityName: mtbl_EDW_DIM_Address
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

