CREATE TABLE [dbo].[tbl_DIM_Customer] (

	[CustomerKey] bigint NULL, 
	[CMPNY] varchar(8000) NULL, 
	[Customer_ID] varchar(8000) NULL, 
	[Invoice_Account] varchar(8000) NULL, 
	[Legacy_Customer_ID] int NULL, 
	[GMAccountNo] int NULL, 
	[GMRecID] int NULL, 
	[CustomerName] varchar(8000) NULL, 
	[Harmonized_Name] varchar(8000) NULL, 
	[Address] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[State] varchar(8000) NULL, 
	[ZIP] varchar(8000) NULL, 
	[Country] varchar(8000) NULL, 
	[Territory_ID] varchar(8000) NULL, 
	[Salesman_ID] varchar(8000) NULL, 
	[SalesChannel] varchar(8000) NULL, 
	[Industry_Segment] varchar(8000) NULL, 
	[Subsegment] varchar(8000) NULL, 
	[Status] int NULL, 
	[EffectiveCountry] int NULL, 
	[Account_Tier] int NULL, 
	[Longitude] decimal(38,10) NULL, 
	[Latitude] decimal(38,10) NULL, 
	[PaymentTerms] varchar(8000) NULL, 
	[PhoneNumber] varchar(8000) NULL, 
	[PurchasingEmail] varchar(8000) NULL, 
	[InvoicingEmail] varchar(8000) NULL, 
	[customergroup] varchar(8000) NULL, 
	[customer_currency] varchar(8000) NULL, 
	[Source] varchar(6) NOT NULL, 
	[RecordEffectiveStartDate] datetime2(3) NULL, 
	[RecordEffectiveEndDate] datetime2(3) NULL, 
	[RecordStatus] int NULL
);