


CREATE TABLE [dbo].[tbl_forecastsales_Snapshot](
	[Snapshot_Date] [date] NULL,
	[Snapshot_Date_Key] [int] NULL,
	[Id] [varchar](8000) NULL,
	[SinkCreatedOn] [datetime2](6) NULL,
	[SinkModifiedOn] [datetime2](6) NULL,
	[active] [bigint] NULL,
	[allocatemethod] [bigint] NULL,
	[cov] [bigint] NULL,
	[freqcode] [bigint] NULL,
	[projforecastbudgettype] [bigint] NULL,
	[report] [bigint] NULL,
	[sysdatastatecode] [bigint] NULL,
	[activitynumber] [varchar](8000) NULL,
	[amount] [decimal](38, 6) NULL,
	[comment] [varchar](8000) NULL,
	[costprice] [decimal](38, 6) NULL,
	[covstatus] [bigint] NULL,
	[currency] [varchar](8000) NULL,
	[custaccountid] [varchar](8000) NULL,
	[custgroupid] [varchar](8000) NULL,
	[defaultdimension] [bigint] NULL,
	[discamount] [decimal](38, 6) NULL,
	[discpercent] [decimal](38, 6) NULL,
	[enddate] [datetime2](6) NULL,
	[expandid] [bigint] NULL,
	[freq] [bigint] NULL,
	[inventdimid] [varchar](8000) NULL,
	[inventqty] [decimal](38, 6) NULL,
	[itemallocateid] [varchar](8000) NULL,
	[itembomid] [varchar](8000) NULL,
	[itemgroupid] [varchar](8000) NULL,
	[itemid] [varchar](8000) NULL,
	[itemrouteid] [varchar](8000) NULL,
	[keyid] [varchar](8000) NULL,
	[modelid] [varchar](8000) NULL,
	[pdscwqty] [decimal](38, 6) NULL,
	[pdscwunitid] [varchar](8000) NULL,
	[priceunit] [decimal](38, 12) NULL,
	[projcategoryid] [varchar](8000) NULL,
	[projforecastcostpaymdate] [datetime2](6) NULL,
	[projforecasteliminationdate] [datetime2](6) NULL,
	[projforecastinvoicedate] [datetime2](6) NULL,
	[projforecastsalespaymdate] [datetime2](6) NULL,
	[projfundingsource] [bigint] NULL,
	[projid] [varchar](8000) NULL,
	[projlinepropertyid] [varchar](8000) NULL,
	[projtransid] [varchar](8000) NULL,
	[psarefpurchline] [bigint] NULL,
	[salesmarkup] [decimal](38, 6) NULL,
	[salesprice] [decimal](38, 6) NULL,
	[salesqty] [decimal](38, 6) NULL,
	[salesunitid] [varchar](8000) NULL,
	[startdate] [datetime2](6) NULL,
	[taxgroupid] [varchar](8000) NULL,
	[taxitemgroupid] [varchar](8000) NULL,
	[forecastentrynumber] [varchar](8000) NULL,
	[description] [varchar](8000) NULL,
	[planningpriority] [decimal](38, 2) NULL,
	[itemdescription] [varchar](8000) NULL,
	[contractlineid] [varchar](8000) NULL,
	[kittinginventtransid] [varchar](8000) NULL,
	[kittinglinenum] [decimal](38, 16) NULL,
	[modifieddatetime] [datetime2](6) NULL,
	[modifiedby] [varchar](8000) NULL,
	[modifiedtransactionid] [bigint] NULL,
	[createddatetime] [datetime2](6) NULL,
	[createdby] [varchar](8000) NULL,
	[createdtransactionid] [bigint] NULL,
	[dataareaid] [varchar](8000) NULL,
	[recversion] [bigint] NULL,
	[partition] [bigint] NULL,
	[sysrowversion] [bigint] NULL,
	[recid] [bigint] NULL,
	[tableid] [bigint] NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime2](6) NULL,
	[modifiedon] [datetime2](6) NULL,
	[IsDelete] [bit] NULL,
	[PartitionId] [varchar](2048) NULL,
	[active_$label] [varchar](3) NULL,
	[allocatemethod_$label] [varchar](6) NULL,
	[cov_$label] [varchar](3) NULL,
	[freqcode_$label] [varchar](5) NULL,
	[projforecastbudgettype_$label] [varchar](15) NULL,
	[report_$label] [varchar](3) NULL
) 
GO



