CREATE TABLE [dbo].[tbl_Fact_Inventory_Snapshot] (
    [inventorySnapshotKey] BIGINT          NULL,
    [CMPNY]                VARCHAR (8000)  NULL,
    [Site_ID]              VARCHAR (8000)  NULL,
    [Warehouse_ID]         VARCHAR (8000)  NULL,
    [Snapshot_Date]        DATE            NULL,
    [Snapshot_Date_Key]    INT             NULL,
    [Product_ID]           VARCHAR (8000)  NULL,
    [ProductName]          VARCHAR (8000)  NULL,
    [ProductSearchName]    VARCHAR (8000)  NULL,
    [Phantom_Product]      VARCHAR (3)     NULL,
    [Inventory_UoM]        VARCHAR (8000)  NULL,
    [inventstatusid]       VARCHAR (8000)  NULL,
    [wmslocationid]        VARCHAR (8000)  NULL,
    [arrived]              DECIMAL (38, 6) NULL,
    [availordered]         DECIMAL (38, 6) NULL,
    [availphysical]        DECIMAL (38, 6) NULL,
    [deducted]             DECIMAL (38, 6) NULL,
    [onorder]              DECIMAL (38, 6) NULL,
    [ordered]              DECIMAL (38, 6) NULL,
    [physicalinvent]       DECIMAL (38, 6) NULL,
    [picked]               DECIMAL (38, 6) NULL,
    [postedqty]            DECIMAL (38, 6) NULL,
    [received]             DECIMAL (38, 6) NULL,
    [registered]           DECIMAL (38, 6) NULL,
    [reservordered]        DECIMAL (38, 6) NULL,
    [reservphysical]       DECIMAL (38, 6) NULL,
    [postedcostamount]     DECIMAL (38, 6) NULL,
    [arrived_LBs]          DECIMAL (38, 6) NULL,
    [availordered_LBs]     DECIMAL (38, 6) NULL,
    [availphysical_LBs]    DECIMAL (38, 6) NULL,
    [deducted_LBs]         DECIMAL (38, 6) NULL,
    [onorder_LBs]          DECIMAL (38, 6) NULL,
    [ordered_LBs]          DECIMAL (38, 6) NULL,
    [physicalinvent_LBs]   DECIMAL (38, 6) NULL,
    [picked_LBs]           DECIMAL (38, 6) NULL,
    [postedqty_LBs]        DECIMAL (38, 6) NULL,
    [received_LBs]         DECIMAL (38, 6) NULL,
    [registered_LBs]       DECIMAL (38, 6) NULL,
    [reservordered_LBs]    DECIMAL (38, 6) NULL,
    [reservphysical_LBs]   DECIMAL (38, 6) NULL,
    [primaryvendorid]      VARCHAR (8000)  NULL,
    [Source]               VARCHAR (6)     NOT NULL,
    [ProductKey]           BIGINT          NULL,
    [SiteKey]              BIGINT          NULL,
    [Legal_EntityKey]      BIGINT          NULL,
    [WarehouseKey]         BIGINT          NOT NULL,
    [VendorKey]            BIGINT          NOT NULL,
    [StandardCostKey]      BIGINT          NULL
);


GO

