CREATE TABLE [dbo].[tbl_ExplodedBOM_StandardCost_Snapshot_v1_backup] (
    [Snapshot_Date_Key]          INT              NULL,
    [DATAAREAID]                 VARCHAR (8000)   NULL,
    [ITEMID]                     VARCHAR (8000)   NULL,
    [InventSiteID]               VARCHAR (8000)   NULL,
    [ACTIVATIONDATE]             DATETIME2 (6)    NULL,
    [dw_id]                      BIGINT           NULL,
    [BOMPath]                    VARCHAR (8000)   NULL,
    [BomDepth]                   INT              NOT NULL,
    [RESOURCE]                   VARCHAR (8000)   NULL,
    [BOM]                        BIGINT           NULL,
    [bom_$label]                 VARCHAR (3)      NULL,
    [CALCTYPE]                   BIGINT           NULL,
    [calctype_$label]            VARCHAR (22)     NULL,
    [costgroupid]                VARCHAR (8000)   NULL,
    [CostGroup]                  VARCHAR (8000)   NULL,
    [root_CONSUMPTIONVARIABLE]   DECIMAL (38, 16) NULL,
    [Parent_Resource]            VARCHAR (8000)   NULL,
    [LEVEL]                      BIGINT           NULL,
    [QTY]                        DECIMAL (38, 6)  NULL,
    [COSTPRICE]                  DECIMAL (38, 16) NULL,
    [CONSUMPTIONVARIABLE]        DECIMAL (38, 16) NULL,
    [Parent_CONSUMPTIONVARIABLE] DECIMAL (38, 16) NULL,
    [parent_QTY]                 DECIMAL (38, 6)  NULL,
    [ConsumptionVariableLevel1]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel2]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel3]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel4]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel5]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel6]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel7]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel8]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel9]  DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel10] DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel11] DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel12] DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel13] DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel14] DECIMAL (38, 16) NULL,
    [ConsumptionVariableLevel15] DECIMAL (38, 16) NULL,
    [Level1Consumption]          DECIMAL (38, 6)  NULL,
    [Level2Consumption]          DECIMAL (38, 6)  NULL,
    [Level3Consumption]          DECIMAL (38, 6)  NULL,
    [Level4Consumption]          DECIMAL (38, 6)  NULL,
    [Level5Consumption]          DECIMAL (38, 6)  NULL,
    [Level6Consumption]          DECIMAL (38, 6)  NULL,
    [Level7Consumption]          DECIMAL (38, 6)  NULL,
    [Level8Consumption]          DECIMAL (38, 6)  NULL,
    [Level9Consumption]          DECIMAL (38, 6)  NULL,
    [Level10Consumption]         DECIMAL (38, 6)  NULL,
    [Level11Consumption]         DECIMAL (38, 6)  NULL,
    [Level12Consumption]         DECIMAL (38, 6)  NULL,
    [Level13Consumption]         DECIMAL (38, 6)  NULL,
    [Level14Consumption]         DECIMAL (38, 6)  NULL,
    [Level15Consumption]         DECIMAL (38, 6)  NULL,
    [ConsumptionPerLotSize]      DECIMAL (38, 6)  NULL,
    [CostPerUnit]                DECIMAL (38, 6)  NULL,
    [ITEMPRICECALCID]            VARCHAR (8000)   NULL,
    [versionid]                  VARCHAR (8000)   NULL,
    [CurrentActiveCost]          INT              NOT NULL,
    [accountingcurrency]         VARCHAR (8000)   NULL
);


GO

