CREATE TABLE [dbo].[tbl_InventSum_Snapshot] (
    [Snapshot_Date]                       DATE            NULL,
    [Snapshot_Date_Key]                   INT             NULL,
    [Id]                                  VARCHAR (8000)  NULL,
    [SinkCreatedOn]                       DATETIME2 (6)   NULL,
    [SinkModifiedOn]                      DATETIME2 (6)   NULL,
    [closed]                              BIGINT          NULL,
    [closedqty]                           BIGINT          NULL,
    [isexcludedfrominventoryvalue]        BIGINT          NULL,
    [sysdatastatecode]                    BIGINT          NULL,
    [arrived]                             DECIMAL (38, 6) NULL,
    [availordered]                        DECIMAL (38, 6) NULL,
    [availphysical]                       DECIMAL (38, 6) NULL,
    [deducted]                            DECIMAL (38, 6) NULL,
    [inventdimid]                         VARCHAR (8000)  NULL,
    [itemid]                              VARCHAR (8000)  NULL,
    [lastupddateexpected]                 DATETIME2 (6)   NULL,
    [lastupddatephysical]                 DATETIME2 (6)   NULL,
    [onorder]                             DECIMAL (38, 6) NULL,
    [ordered]                             DECIMAL (38, 6) NULL,
    [pdscwarrived]                        DECIMAL (38, 6) NULL,
    [pdscwavailordered]                   DECIMAL (38, 6) NULL,
    [pdscwavailphysical]                  DECIMAL (38, 6) NULL,
    [pdscwdeducted]                       DECIMAL (38, 6) NULL,
    [pdscwonorder]                        DECIMAL (38, 6) NULL,
    [pdscwordered]                        DECIMAL (38, 6) NULL,
    [pdscwphysicalinvent]                 DECIMAL (38, 6) NULL,
    [pdscwpicked]                         DECIMAL (38, 6) NULL,
    [pdscwpostedqty]                      DECIMAL (38, 6) NULL,
    [pdscwquotationissue]                 DECIMAL (38, 6) NULL,
    [pdscwquotationreceipt]               DECIMAL (38, 6) NULL,
    [pdscwreceived]                       DECIMAL (38, 6) NULL,
    [pdscwregistered]                     DECIMAL (38, 6) NULL,
    [pdscwreservordered]                  DECIMAL (38, 6) NULL,
    [pdscwreservphysical]                 DECIMAL (38, 6) NULL,
    [physicalinvent]                      DECIMAL (38, 6) NULL,
    [physicalvalue]                       DECIMAL (38, 6) NULL,
    [physicalvalueseccur_ru]              DECIMAL (38, 6) NULL,
    [picked]                              DECIMAL (38, 6) NULL,
    [postedqty]                           DECIMAL (38, 6) NULL,
    [postedvalue]                         DECIMAL (38, 6) NULL,
    [postedvalueseccur_ru]                DECIMAL (38, 6) NULL,
    [quotationissue]                      DECIMAL (38, 6) NULL,
    [quotationreceipt]                    DECIMAL (38, 6) NULL,
    [received]                            DECIMAL (38, 6) NULL,
    [registered]                          DECIMAL (38, 6) NULL,
    [reservordered]                       DECIMAL (38, 6) NULL,
    [reservphysical]                      DECIMAL (38, 6) NULL,
    [configid]                            VARCHAR (8000)  NULL,
    [inventbatchid]                       VARCHAR (8000)  NULL,
    [inventcolorid]                       VARCHAR (8000)  NULL,
    [inventgtdid_ru]                      VARCHAR (8000)  NULL,
    [inventlocationid]                    VARCHAR (8000)  NULL,
    [inventownerid_ru]                    VARCHAR (8000)  NULL,
    [inventprofileid_ru]                  VARCHAR (8000)  NULL,
    [inventserialid]                      VARCHAR (8000)  NULL,
    [inventsiteid]                        VARCHAR (8000)  NULL,
    [inventsizeid]                        VARCHAR (8000)  NULL,
    [inventstatusid]                      VARCHAR (8000)  NULL,
    [inventstyleid]                       VARCHAR (8000)  NULL,
    [inventversionid]                     VARCHAR (8000)  NULL,
    [licenseplateid]                      VARCHAR (8000)  NULL,
    [wmslocationid]                       VARCHAR (8000)  NULL,
    [wmspalletid]                         VARCHAR (8000)  NULL,
    [inventdimension1]                    VARCHAR (8000)  NULL,
    [inventdimension2]                    VARCHAR (8000)  NULL,
    [inventdimension3]                    VARCHAR (8000)  NULL,
    [inventdimension4]                    VARCHAR (8000)  NULL,
    [inventdimension5]                    VARCHAR (8000)  NULL,
    [inventdimension6]                    VARCHAR (8000)  NULL,
    [inventdimension7]                    VARCHAR (8000)  NULL,
    [inventdimension8]                    VARCHAR (8000)  NULL,
    [inventdimension9]                    DATETIME2 (6)   NULL,
    [inventdimension10]                   DECIMAL (38, 6) NULL,
    [inventdimension11]                   VARCHAR (8000)  NULL,
    [inventdimension12]                   VARCHAR (8000)  NULL,
    [modifieddatetime]                    DATETIME2 (6)   NULL,
    [modifiedby]                          VARCHAR (8000)  NULL,
    [modifiedtransactionid]               BIGINT          NULL,
    [createddatetime]                     DATETIME2 (6)   NULL,
    [createdby]                           VARCHAR (8000)  NULL,
    [createdtransactionid]                BIGINT          NULL,
    [dataareaid]                          VARCHAR (8000)  NULL,
    [recversion]                          BIGINT          NULL,
    [partition]                           BIGINT          NULL,
    [sysrowversion]                       BIGINT          NULL,
    [recid]                               BIGINT          NULL,
    [tableid]                             BIGINT          NULL,
    [versionnumber]                       BIGINT          NULL,
    [createdon]                           DATETIME2 (6)   NULL,
    [modifiedon]                          DATETIME2 (6)   NULL,
    [IsDelete]                            BIT             NULL,
    [PartitionId]                         VARCHAR (2048)  NULL,
    [closed_$label]                       VARCHAR (3)     NULL,
    [closedqty_$label]                    VARCHAR (3)     NULL,
    [isexcludedfrominventoryvalue_$label] VARCHAR (3)     NULL
);


GO

