table vw360_Fact_Sales
	lineageTag: 2a3f72b2-24a9-478e-8699-7e8fcbe766ac
	sourceLineageTag: [dbo].[mtbl_LEG_vw360_Fact_Sales]

	measure 'Revenue running total in FISCAL Period' =
			
			CALCULATE(
				SUM('vw360_Fact_Sales'[Revenue]),
				FILTER(
					ALLSELECTED('vw360_Dim_InvoiceDate'[FISCAL PERIOD]),
					ISONORAFTER('vw360_Dim_InvoiceDate'[FISCAL PERIOD], MAX('vw360_Dim_InvoiceDate'[FISCAL PERIOD]), DESC)
				)
			)
		lineageTag: dfc978e8-10f0-4fc2-919f-917ec901e876

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Volume running total in FISCAL Period' =
			
			CALCULATE(
				SUM('vw360_Fact_Sales'[Volume]),
				FILTER(
					ALLSELECTED('vw360_Dim_InvoiceDate'[FISCAL PERIOD]),
					ISONORAFTER('vw360_Dim_InvoiceDate'[FISCAL PERIOD], MAX('vw360_Dim_InvoiceDate'[FISCAL PERIOD]), DESC)
				)
			)
		lineageTag: 36f90fd3-c878-4f1d-9f3a-1c9b1d8959ee

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BudgetRevenueDiff = Sum(vw360_Fact_Sales[CYTDRevenue]) - Sum(vw360_Fact_Sales[BudgetRevenue])
		lineageTag: 64cb92f3-081d-4cfa-a95a-61b0dbf57e7d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BudgetRevenuePct = (Sum(vw360_Fact_Sales[CYTDRevenue])-Sum(vw360_Fact_Sales[BudgetRevenue]))/Sum(vw360_Fact_Sales[BudgetRevenue])
		lineageTag: f0c188b0-9e6f-4edc-84dc-14adebbbfc6a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BudgetVolumeDiff = Sum(vw360_Fact_Sales[CYTDVolume]) - Sum(vw360_Fact_Sales[BudgetVolume])
		lineageTag: 1453d2cb-33e0-42f6-bec0-fb4b727a5255

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BudgetVolumePct = (Sum(vw360_Fact_Sales[CYTDVolume])-Sum(vw360_Fact_Sales[BudgetVolume]))/Sum(vw360_Fact_Sales[BudgetVolume])
		lineageTag: 7dab6c28-95a1-4785-bbb8-bbe904aca545

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RangeRevenue =
			
			MAXX(
			    VALUES (vw360_Dim_InvoiceDate[YYYYMM]), [Revenue running total in FISCAL Period]
			)
		lineageTag: e543efc9-7c7f-4e70-89e2-d7d0e15cf123

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RangeVolume =
			
			MAXX(
			    VALUES (vw360_Dim_InvoiceDate[YYYYMM]), [Volume running total in FISCAL Period]
			)
		lineageTag: bb406e28-94fe-43da-9812-0a13b4a4e35b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesPriceAvg = ```
			SUM([Revenue]) /Sum([Volume]) 
			```
		lineageTag: 169d35eb-4e04-4dc6-8de0-053fa6aa4d28

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YoYRevenueDiff = Sum(vw360_Fact_Sales[CYTDRevenue]) - Sum(vw360_Fact_Sales[LFYTDRevenue])
		lineageTag: 932fe450-8ae9-43d8-a308-7a2d60c68a45

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YoYRevenuePct = (Sum(vw360_Fact_Sales[CYTDRevenue])-Sum(vw360_Fact_Sales[LFYTDRevenue]))/Sum(vw360_Fact_Sales[LFYTDRevenue])
		lineageTag: 293fcc61-7abf-48bc-b2a3-c3aa59e9db43

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YoYVolumeDiff = Sum(vw360_Fact_Sales[CYTDVolume]) - Sum(vw360_Fact_Sales[LFYTDVolume])
		lineageTag: bcf17d25-29d5-4258-8c50-a70cb1f56d77

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YoYVolumePct = (Sum(vw360_Fact_Sales[CYTDVolume])-Sum(vw360_Fact_Sales[LFYTDVolume]))/Sum(vw360_Fact_Sales[LFYTDVolume])
		lineageTag: e7cf0860-cf17-4327-9222-cc47eee6bc14

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue running total in MyMonth' =
			
			CALCULATE(
				SUM('vw360_Fact_Sales'[Revenue]),
				FILTER(
					ALLSELECTED('vw360_Dim_InvoiceDate'[MyMonth]),
					ISONORAFTER('vw360_Dim_InvoiceDate'[MyMonth], MAX('vw360_Dim_InvoiceDate'[MyMonth]), DESC)
				)
			)
		lineageTag: adf64ed5-acc7-42fb-89a7-37ba1307d33b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Revenue_Budget = ```
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Revenue]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) = MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Budget 2025"
			)
			
			```
		lineageTag: 594bd61f-9c76-4dd0-b285-d3c0c2445de7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Revenue_Open = ```
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Revenue]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) = MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Open Order"
			)
			
			```
		lineageTag: f4436aaa-24bc-402b-b2b6-473b05290332

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Revenue_Shipped = ```
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Revenue]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) = MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Closed Order"
			)
			
			```
		lineageTag: bc766d39-96e9-4425-817b-04ead2f1c225

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Revenue_Total =
			
			[MTD_Revenue_Open] + [MTD_Revenue_Shipped]
		lineageTag: 9c11557e-9912-4f7a-acd8-262c70fd3f25

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Revenue_Variance =
			
			VAR __BASELINE_VALUE = [MTD_Revenue_Budget]
			VAR __VALUE_TO_COMPARE = [MTD_Revenue_Total]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		lineageTag: 9f79c57f-045c-4714-8df1-5fff933e2c17

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Volume_Budget = ```
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Volume]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) = MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Budget 2025"
			)
			
			```
		lineageTag: e1febded-c190-40ab-a898-e1a6d2b8e9d6

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Volume_Open = ```
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Volume]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) = MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Open Order"
			)
			
			```
		lineageTag: 82bfc980-3135-4911-9f54-49fd10db8293

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Volume_Shipped = ```
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Volume]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) = MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Closed Order"
			)
			
			```
		lineageTag: ec41b53d-2ed2-472a-b174-96e35978b91b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Volume_Total =
			
			[MTD_Volume_Open] + [MTD_Volume_Shipped]
		lineageTag: 02f6190a-6c20-4ecf-a985-d22a195b3041

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Volume_Variance =
			
			VAR __BASELINE_VALUE = [MTD_Volume_Budget]
			VAR __VALUE_TO_COMPARE = [MTD_Volume_Total]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		lineageTag: b1452774-8844-4756-87f9-fda8c16e881a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Revenue_Budget =
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Revenue]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) < MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Budget 2025"
			)
		lineageTag: e9ef2043-d2dc-4769-894f-7cfbabaa78a0

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Revenue_Open =
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Revenue]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) < MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Open Order"
			)
		lineageTag: 22f929c2-8aa7-46ff-8a51-9513365568eb

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Revenue_Shipped =
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Revenue]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) < MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Closed Order"
			)
		lineageTag: ce6dce08-2821-4705-938b-836105c2de47

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Revenue_Total =
			
			[YTD_Revenue_Open] + [YTD_Revenue_Shipped]
		lineageTag: a23c1550-dfe5-4472-a8a7-5c010f89692e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Revenue_Variance =
			
			VAR __BASELINE_VALUE = [YTD_Revenue_Budget]
			VAR __VALUE_TO_COMPARE = [YTD_Revenue_Total]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		lineageTag: f9e2c934-fbd7-4c19-9910-20ea79a05d79

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Volume_Budget =
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Volume]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) < MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Budget 2025"
			)
		lineageTag: 01e4265e-6d1f-4f35-9d45-fcbaafbb5f04

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Volume_Open =
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Volume]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) < MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Open Order"
			)
		lineageTag: 66e51b4b-2179-46ad-803d-e4a0b67dcfdc

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Volume_Shipped =
			
			CALCULATE(
			    SUM('vw360_Fact_Sales'[Volume]),
			    FILTER(
			        'vw360_Dim_InvoiceDate',
			        YEAR('vw360_Dim_InvoiceDate'[DATE]) = YEAR(TODAY()) &&
			        MONTH('vw360_Dim_InvoiceDate'[DATE]) < MONTH(TODAY())
			    ),
			    'vw360_Fact_Sales'[RecordType] = "Closed Order"
			)
		lineageTag: 8fb25121-aa51-4bb1-bb0d-3c70bc37403d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Volume_Total =
			
			[YTD_Volume_Open] + [YTD_Volume_Shipped]
		lineageTag: bd237981-9e2a-41b6-b38e-3835ea7c9728

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Volume_Variance =
			
			VAR __BASELINE_VALUE = [YTD_Volume_Budget]
			VAR __VALUE_TO_COMPARE = [YTD_Volume_Total]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		lineageTag: 844b5c36-eb26-4fe5-9771-58f77e86d61d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Revenue Deficit' = ```
			
			SUMX(
			    // 1) build the list of salesman–account pairs in the current filter context
			    FILTER(
			        SUMMARIZE(
			            'vw360_Fact_Sales',
			            'vw360_Salesman_Hierarchy'[RegionalSalesman],
			            'vw360_Dim_Account'[GlobalName],
			            'vw360_Fact_Sales'[Product]
			        ),
			        // 2) only keep those pairs whose variance is below zero
			        CALCULATE( [YTD_Volume_Variance] ) < 0
			    ),
			    // 3) for each remaining pair, compute (Total – Budget) and add them up
			    CALCULATE( [YTD_Revenue_Total] ) 
			    - CALCULATE( [YTD_Revenue_Budget] )
			)
			
			```
		lineageTag: f2fe29f4-d37f-4360-9c68-e44554f0df05

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Volume Deficit' = ```
			
			SUMX(
			    // 1) build the list of salesman–account pairs in the current filter context
			    FILTER(
			        SUMMARIZE(
			            'vw360_Fact_Sales',
			            'vw360_Salesman_Hierarchy'[RegionalSalesman],
			            'vw360_Dim_Account'[GlobalName],
			            'vw360_Fact_Sales'[Product]
			        ),
			        // 2) only keep those pairs whose variance is below zero
			        CALCULATE( [YTD_Volume_Variance] ) < 0
			    ),
			    // 3) for each remaining pair, compute (Total – Budget) and add them up
			    CALCULATE( [YTD_Volume_Total] ) 
			    - CALCULATE( [YTD_Volume_Budget] )
			)
			
			```
		lineageTag: 2e63a443-b006-45a1-bb19-9e2bef03e9a8

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cmpny
		dataType: string
		lineageTag: 980d4a85-45e7-4e51-ae34-0819eab6870a
		sourceLineageTag: Cmpny
		summarizeBy: none
		sourceColumn: Cmpny

		annotation SummarizationSetBy = Automatic

	column MaterialCostPerPound
		dataType: double
		lineageTag: c35986b5-c1df-4154-b3be-afa829305a87
		sourceLineageTag: MaterialCostPerPound
		summarizeBy: sum
		sourceColumn: MaterialCostPerPound

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DirectCostPerPound
		dataType: double
		lineageTag: 08e3c9da-2fef-44f4-9dc4-e535bf33e65c
		sourceLineageTag: DirectCostPerPound
		summarizeBy: sum
		sourceColumn: DirectCostPerPound

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OSProcessingCostPerPound
		dataType: double
		lineageTag: 015b2bea-5703-470a-ae38-ad0821477f56
		sourceLineageTag: OSProcessingCostPerPound
		summarizeBy: sum
		sourceColumn: OSProcessingCostPerPound

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OverheadCostPerPound
		dataType: double
		lineageTag: 0a41f453-7054-4930-ba61-1b0b4653f977
		sourceLineageTag: OverheadCostPerPound
		summarizeBy: sum
		sourceColumn: OverheadCostPerPound

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Source
		dataType: string
		lineageTag: b90b8378-f970-4d18-a368-5c29af75ce21
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column CPCID
		dataType: string
		lineageTag: 374b0d2c-eb94-4b59-9da7-9a36a7db3738
		sourceLineageTag: CPCID
		summarizeBy: none
		sourceColumn: CPCID

		annotation SummarizationSetBy = Automatic

	column CPAID
		dataType: string
		lineageTag: e216c5ee-47bc-4ac7-b186-b08eb825279a
		sourceLineageTag: CPAID
		summarizeBy: none
		sourceColumn: CPAID

		annotation SummarizationSetBy = Automatic

	column CostingLinkID
		dataType: string
		lineageTag: b85e21fc-8257-4948-86a5-0efc45b048ef
		sourceLineageTag: CostingLinkID
		summarizeBy: none
		sourceColumn: CostingLinkID

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 4aa4f61c-5852-4efb-b844-19849f340d2c
		sourceLineageTag: Product
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		lineageTag: e684b698-8251-4ea0-9c3b-cf2fa1c88999
		sourceLineageTag: Revenue
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: double
		lineageTag: c8d88bf7-d670-4670-974b-b24197692691
		sourceLineageTag: Volume
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 5e3fcfed-07b2-46a6-aefb-75f5d3f9b4a6
		sourceLineageTag: OrderDate
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column InvoiceDate
		dataType: dateTime
		formatString: General Date
		lineageTag: a9fe242b-3b23-4645-95e0-569003fab828
		sourceLineageTag: InvoiceDate
		summarizeBy: none
		sourceColumn: InvoiceDate

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 64671bc2-6cc7-4d4a-a56a-a8875735439b
		sourceLineageTag: ShipDate
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

	column 'Customer No'
		dataType: string
		lineageTag: 7225592f-fe00-45b9-8b3b-dac921adb02e
		sourceLineageTag: Customer No
		summarizeBy: none
		sourceColumn: Customer No

		annotation SummarizationSetBy = Automatic

	column 'Ship To No'
		dataType: string
		lineageTag: d85976a1-4a24-45c5-9f83-cb2269b16eed
		sourceLineageTag: Ship To No
		summarizeBy: none
		sourceColumn: Ship To No

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		lineageTag: 474cb4ee-e24f-48fb-af52-11aa589cbca7
		sourceLineageTag: CustomerID
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column 'Order No'
		dataType: string
		lineageTag: 4b444794-05b9-4e06-85af-3a7d944fb9b3
		sourceLineageTag: Order No
		summarizeBy: none
		sourceColumn: Order No

		annotation SummarizationSetBy = Automatic

	column 'Customer PO'
		dataType: string
		lineageTag: 7075b104-60dc-4f3f-bea2-bccb479de2ce
		sourceLineageTag: Customer PO
		summarizeBy: none
		sourceColumn: Customer PO

		annotation SummarizationSetBy = Automatic

	column 'Invoice No'
		dataType: string
		lineageTag: 7b839256-8996-42d0-94cd-a6dab1f5e839
		sourceLineageTag: Invoice No
		summarizeBy: none
		sourceColumn: Invoice No

		annotation SummarizationSetBy = Automatic

	column IncoTerms
		dataType: string
		lineageTag: 57862bd1-29d8-4f4d-adeb-b5ff83046632
		sourceLineageTag: IncoTerms
		summarizeBy: none
		sourceColumn: IncoTerms

		annotation SummarizationSetBy = Automatic

	column Warehouse
		dataType: string
		lineageTag: d6046c82-4a9b-403a-92cb-2268bf1ee061
		sourceLineageTag: Warehouse
		summarizeBy: none
		sourceColumn: Warehouse

		annotation SummarizationSetBy = Automatic

	column RecordType
		dataType: string
		lineageTag: 59f80b02-a649-49a7-ab3b-9facfe0a5bcb
		sourceLineageTag: RecordType
		summarizeBy: none
		sourceColumn: RecordType

		annotation SummarizationSetBy = Automatic

	column LFYTDVolume
		dataType: double
		lineageTag: 4104c366-2aa4-4126-85ab-b70afbcfefa3
		sourceLineageTag: LFYTDVolume
		summarizeBy: sum
		sourceColumn: LFYTDVolume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ClusterColumn
		dataType: string
		lineageTag: 696b1b80-f3fd-47a4-8a69-479d1969b5c4
		sourceLineageTag: ClusterColumn
		summarizeBy: none
		sourceColumn: ClusterColumn

		annotation SummarizationSetBy = Automatic

	column Budget2024Revenue
		dataType: double
		lineageTag: 69d477ff-85b8-4373-82d3-4a32119ad955
		sourceLineageTag: Budget2024Revenue
		summarizeBy: sum
		sourceColumn: Budget2024Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BudgetRevenue
		dataType: double
		lineageTag: 334d87bc-eeb3-40f1-ac86-83af27e40cce
		sourceLineageTag: BudgetRevenue
		summarizeBy: sum
		sourceColumn: BudgetRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BudgetVolume
		dataType: double
		lineageTag: c50421c0-723e-4e44-b51a-bf6d5eae86b8
		sourceLineageTag: BudgetVolume
		summarizeBy: sum
		sourceColumn: BudgetVolume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CYTDRevenue
		dataType: double
		lineageTag: fa11ea2a-e784-4aa1-93d4-5f9861bcccd7
		sourceLineageTag: CYTDRevenue
		summarizeBy: sum
		sourceColumn: CYTDRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CYTDVolume
		dataType: double
		lineageTag: 96eab884-b99e-43c2-b60a-26d2003c3da8
		sourceLineageTag: CYTDVolume
		summarizeBy: sum
		sourceColumn: CYTDVolume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LFYTDRevenue
		dataType: double
		lineageTag: b97a6c06-897c-43db-9096-7ed48eecaea2
		sourceLineageTag: LFYTDRevenue
		summarizeBy: sum
		sourceColumn: LFYTDRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AvgPrice
		dataType: double
		lineageTag: a57177cf-6d8c-4676-9bdf-0f0836784a44
		sourceLineageTag: AvgPrice
		summarizeBy: sum
		sourceColumn: AvgPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Today
		dataType: dateTime
		formatString: General Date
		lineageTag: fd0a1d90-8725-471f-ad8d-22190b1d2312
		sourceLineageTag: Today
		summarizeBy: none
		sourceColumn: Today

		annotation SummarizationSetBy = Automatic

	column Salesperson
		dataType: string
		lineageTag: 5fc447a7-aacf-4eef-9fe9-26d8716a2a95
		sourceLineageTag: Salesperson
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: bafcde80-8426-4f7d-b80b-af15eaea2280
		sourceLineageTag: Location
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column RecTypeLong
		dataType: string
		lineageTag: 55f24012-52d0-419e-bd01-73d6250be3fc
		sourceLineageTag: RecTypeLong
		summarizeBy: none
		sourceColumn: RecTypeLong

		annotation SummarizationSetBy = Automatic

	column RecTypeLong2
		dataType: string
		lineageTag: eaf7eb44-bf6e-4995-bef0-19c30d23f0aa
		sourceLineageTag: RecTypeLong2
		summarizeBy: none
		sourceColumn: RecTypeLong2

		annotation SummarizationSetBy = Automatic

	partition vw360_Fact_Sales = entity
		mode: directLake
		source
			entityName: mtbl_LEG_vw360_Fact_Sales
			schemaName: dbo
			expressionSource: 'DirectLake - WH_Curated'

	changedProperty = Name

