table Dim_Account
	lineageTag: 3cdf4889-bcb3-4cc2-9f53-4023d2238b12
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_Account]

	measure 'CustName Order' =
			
			VAR _OrderCustomerKey =
			    SELECTEDVALUE ( 'Fact_Customer_Invoices'[CustomerKey] )
			RETURN
			    IF (
			        ISBLANK ( _OrderCustomerKey ),
			        BLANK (),
			        CALCULATE (
			            SELECTEDVALUE ( 'Dim_Account'[CustomerName] ),
			            REMOVEFILTERS ( 'Dim_Account' ),
			            TREATAS (
			                { _OrderCustomerKey },
			                'Dim_Account'[CustomerKey]
			            )
			        )
			    )
		lineageTag: aa828471-d5b7-4675-877d-f43bef97dd0a

		changedProperty = Name

	measure CustomerCountry = ```
			
			
			VAR dk = VALUES ( 'Fact_Customer_Invoices'[CustomerKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Account'[Country] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Account' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Account'[CustomerKey] )
			)
			
			```
		lineageTag: 4610905e-8509-4852-bb42-a259d50f242e

		changedProperty = Name

	measure 'CustState Order' = ```
			
			VAR _SalesOrderKey =
			    SELECTEDVALUE ( 'Fact_Customer_Invoices'[SalesOrderKey] )
			VAR _CustomerKey =
			    SELECTEDVALUE ( 'Fact_Customer_Invoices'[CustomerKey] )
			RETURN
			IF (
			    ISBLANK ( _SalesOrderKey ) || ISBLANK ( _CustomerKey ),
			    BLANK (),
			    CALCULATE (
			        SELECTEDVALUE ( 'Dim_Account'[State] ),
			        USERELATIONSHIP (
			            'Fact_Customer_Invoices'[CustomerKey],
			            'Dim_Account'[CustomerKey]
			        )
			    )
			)
			
			```
		lineageTag: b274bbce-9b8e-40ae-875e-55c7a4f713d4

		changedProperty = Name

	column CustomerKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 8b15de13-96d2-46c8-96e9-f765330fb64b
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column CMPNY
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f7a878c9-3b0f-4c7f-9d4e-1ed8ec883eb0
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		annotation SummarizationSetBy = Automatic

	column Customer_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a47263be-4323-4c97-8adf-a3fcbc084e19
		sourceLineageTag: Customer_ID
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Invoice_Account
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6797d035-31d8-492c-9a25-85ecbd50f30f
		sourceLineageTag: Invoice_Account
		summarizeBy: none
		sourceColumn: Invoice_Account

		annotation SummarizationSetBy = Automatic

	column Legacy_Customer_ID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: cc0758a3-7fe0-4f3e-93b0-762571ff2f2f
		sourceLineageTag: Legacy_Customer_ID
		summarizeBy: count
		sourceColumn: Legacy_Customer_ID

		annotation SummarizationSetBy = Automatic

	column GMAccountNo
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 22a088cf-d04f-43b4-bdbe-343789688aa2
		sourceLineageTag: GMAccountNo
		summarizeBy: sum
		sourceColumn: GMAccountNo

		annotation SummarizationSetBy = Automatic

	column GMRecID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1846bc91-7a48-4200-85bd-62b679d8e961
		sourceLineageTag: GMRecID
		summarizeBy: count
		sourceColumn: GMRecID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 61b7d0ab-6acc-4aa4-8cd7-41f391627d69
		sourceLineageTag: CustomerName
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Harmonized_Name
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 86e8c672-5c8b-489d-ba37-aae6c90d6ec1
		sourceLineageTag: Harmonized_Name
		summarizeBy: none
		sourceColumn: Harmonized_Name

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c68896e3-9b61-47a0-87c1-7cabfe32cbfa
		sourceLineageTag: Address
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 36790fe2-c047-4a3b-9521-53bf97a05f11
		sourceLineageTag: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 30ff1217-c65f-4c88-969e-1f5127f4553f
		sourceLineageTag: State
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ad20ed75-b8bb-4a65-96a9-b47c74e712fd
		sourceLineageTag: ZIP
		summarizeBy: none
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9a32a48b-0516-4cba-85f0-de46a06ea24e
		sourceLineageTag: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column CityState
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1f55e7a7-afac-4954-9e7a-baaa094ba513
		sourceLineageTag: CityState
		summarizeBy: none
		sourceColumn: CityState

		annotation SummarizationSetBy = Automatic

	column Territory_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4de7b611-9621-4105-8f9a-85f5c7026c90
		sourceLineageTag: Territory_ID
		summarizeBy: none
		sourceColumn: Territory_ID

		annotation SummarizationSetBy = Automatic

	column Salesman_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f3bee924-ccd3-42ad-9364-875b5ae7819d
		sourceLineageTag: Salesman_ID
		summarizeBy: none
		sourceColumn: Salesman_ID

		annotation SummarizationSetBy = Automatic

	column SalesChannel
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 0a304eb7-3f11-4eff-98cf-7651ab653969
		sourceLineageTag: SalesChannel
		summarizeBy: none
		sourceColumn: SalesChannel

		annotation SummarizationSetBy = Automatic

	column Industry_Segment
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 773a5ed7-c2da-4fef-82e1-f7b41bce3bd6
		sourceLineageTag: Industry_Segment
		summarizeBy: none
		sourceColumn: Industry_Segment

		annotation SummarizationSetBy = Automatic

	column Subsegment
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 039c232c-e289-4edb-b44a-970323d5adcf
		sourceLineageTag: Subsegment
		summarizeBy: none
		sourceColumn: Subsegment

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2df64991-045f-4121-ab05-ca2b1212f1c1
		sourceLineageTag: Status
		summarizeBy: sum
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column EffectiveCountry
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: dfa6241b-36f0-465b-bd2d-efdfa5296f78
		sourceLineageTag: EffectiveCountry
		summarizeBy: sum
		sourceColumn: EffectiveCountry

		annotation SummarizationSetBy = Automatic

	column Account_Tier
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 534f384c-2cad-449b-8410-658ac1316988
		sourceLineageTag: Account_Tier
		summarizeBy: sum
		sourceColumn: Account_Tier

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		sourceProviderType: decimal(38, 10)
		lineageTag: 377fc44f-5f88-4016-be5c-a25f1362b395
		sourceLineageTag: Longitude
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Latitude
		dataType: double
		sourceProviderType: decimal(38, 10)
		lineageTag: 6b1314c8-8265-4fb7-9065-328472f4aaf3
		sourceLineageTag: Latitude
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PaymentTerms
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 938a0b01-c7a1-4545-85c7-75ca9dbabbe3
		sourceLineageTag: PaymentTerms
		summarizeBy: none
		sourceColumn: PaymentTerms

		annotation SummarizationSetBy = Automatic

	column PhoneNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ea7afbd8-626c-4831-9040-58ba78c94e87
		sourceLineageTag: PhoneNumber
		summarizeBy: none
		sourceColumn: PhoneNumber

		annotation SummarizationSetBy = Automatic

	column PurchasingEmail
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 24c2df2b-d201-44a7-b652-138422798a56
		sourceLineageTag: PurchasingEmail
		summarizeBy: none
		sourceColumn: PurchasingEmail

		annotation SummarizationSetBy = Automatic

	column InvoicingEmail
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5d26ce67-f43f-4524-a0ab-592c84781cf4
		sourceLineageTag: InvoicingEmail
		summarizeBy: none
		sourceColumn: InvoicingEmail

		annotation SummarizationSetBy = Automatic

	column customergroup
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 79752f7a-e93f-4112-aeb6-691d922fb8cd
		sourceLineageTag: customergroup
		summarizeBy: none
		sourceColumn: customergroup

		annotation SummarizationSetBy = Automatic

	column customer_currency
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6c85aaac-45b7-4e1e-997e-ed41c3fcf08f
		sourceLineageTag: customer_currency
		summarizeBy: none
		sourceColumn: customer_currency

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		sourceProviderType: varchar(6)
		lineageTag: ab2b8ec0-d475-415d-9165-4e046b88e2de
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 2cd71338-82d5-4645-8bd2-572534488b82
		sourceLineageTag: RecordEffectiveStartDate
		summarizeBy: none
		sourceColumn: RecordEffectiveStartDate

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveEndDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 893e100d-d94b-4d96-be36-721108403ccd
		sourceLineageTag: RecordEffectiveEndDate
		summarizeBy: none
		sourceColumn: RecordEffectiveEndDate

		annotation SummarizationSetBy = Automatic

	column RecordStatus
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 969e9860-b170-42e6-afe1-f497db44818d
		sourceLineageTag: RecordStatus
		summarizeBy: sum
		sourceColumn: RecordStatus

		annotation SummarizationSetBy = Automatic

	partition Dim_Account = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_Account
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

