table Dim_Date
	lineageTag: 9eca578a-4f5f-4ed8-937f-4fa4ebd05d87
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_Date]
	dataCategory: Time

	measure 'Selected Dates (Orders Only)' = ```
			
			VAR DatesWithOrders =
			    CALCULATETABLE(
			        VALUES('Dim_Date'[Date]),
			        KEEPFILTERS(
			            FILTER(ALLSELECTED('Dim_Date'[Date]), [Total Orders] > 0)
			        )
			    )
			RETURN
			IF(
			    COUNTROWS(DatesWithOrders) = 0,
			    "No dates selected",
			    CONCATENATEX(
			        DatesWithOrders,
			        FORMAT('Dim_Date'[Date], "MMMM DD, YYYY"),
			        ", "
			    )
			)
			
			```
		lineageTag: 1521795c-530f-4090-810c-399ad6b8e27a

		changedProperty = Name

	measure 'Selected Date Range (Orders Only)' = ```
			
			VAR DatesWithOrders =
			    CALCULATETABLE(
			        VALUES('Dim_Date'[Date]),
			        KEEPFILTERS(
			            FILTER(ALLSELECTED('Dim_Date'[Date]), [Total Orders] > 0)
			        )
			    )
			VAR MinDate = MINX(DatesWithOrders, 'Dim_Date'[Date])
			VAR MaxDate = MAXX(DatesWithOrders, 'Dim_Date'[Date])
			VAR CountDates = COUNTROWS(DatesWithOrders)
			RETURN
			SWITCH(
			    TRUE(),
			    CountDates = 0, "No dates selected",
			    MinDate = MaxDate, FORMAT(MinDate, "MMMM DD, YYYY"),
			    FORMAT(MinDate, "MMMM DD, YYYY") & " - " & FORMAT(MaxDate, "MMMM DD, YYYY")
			)
			
			```
		lineageTag: d16b925e-1a50-4204-af44-52950966915a

		changedProperty = Name

	measure 'Requested Ship Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_RequestedShipDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 084aed39-00c8-4eb4-84f2-59ae863295d7

		changedProperty = Name

	measure InvoiceDate = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[InvoiceDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 1f6a5b9e-2ab5-4832-948f-79f1f61e9e77

		changedProperty = Name

	measure 'Sales Order Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[OrderDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 1c13498a-cec7-4a00-ae73-bd01f0cbd6bc

		changedProperty = Name

	measure 'Week Start (Mon)' = ```
			
			VAR d = MAX ( 'Dim_Date'[Date] )         -- the date in the current filter context
			RETURN
			d - WEEKDAY ( d, 2 ) + 1                 -- 2 => Monday=1 ... Sunday=7
			
			```
		formatString: General Date
		lineageTag: 67e24fe5-df34-4462-9c79-02fea7f9ad51

		changedProperty = Name

	measure 'Requested Ship Date (Max)' = ```
			
			VAR dk =
			    VALUES ( 'Fact_Sales'[SalesLine_RequestedShipDateKey] )
			RETURN
			CALCULATE (
			    MAX ( 'Dim_Date'[Date] ),          -- get the furthest date
			    REMOVEFILTERS ( 'Dim_Date' ),      -- ignore existing date filters
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 0f43fdb9-c73d-418b-bdb4-e49c52fd22e5

		changedProperty = Name

	measure BaseMonthStart =
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )   -- default: This Month
			VAR Anchor =
			    EDATE ( TODAY(), Offset )                  -- same day in shifted month
			RETURN
			    DATE ( YEAR ( Anchor ), MONTH ( Anchor ), 1 )
		formatString: General Date
		lineageTag: d9427f5f-de4f-4641-bd5a-c843655b57df

		changedProperty = Name

	measure BaseMonthEnd =
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )
			VAR Anchor =
			    EDATE ( TODAY(), Offset )
			RETURN
			    EOMONTH ( Anchor, 0 )
		formatString: General Date
		lineageTag: 0ccb3d88-c607-438c-bf0c-307980ed0f76

		changedProperty = Name

	measure NextMonthStart =
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )
			VAR Anchor =
			    EDATE ( TODAY(), Offset + 1 )              -- one month after base
			RETURN
			    DATE ( YEAR ( Anchor ), MONTH ( Anchor ), 1 )
		formatString: General Date
		lineageTag: 11366254-0e84-4bde-8b9b-9c6c9c147c16

		changedProperty = Name

	measure NextMonthEnd =
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )
			VAR Anchor =
			    EDATE ( TODAY(), Offset + 1 )
			RETURN
			    EOMONTH ( Anchor, 0 )
		formatString: General Date
		lineageTag: f916be4e-b6e9-4650-ba1e-c2a00baed9dd

		changedProperty = Name

	measure 'Month View Title' = ```
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )
			VAR Anchor =
			    EDATE ( TODAY (), Offset )
			VAR LabelText =
			    SWITCH (
			        Offset,
			        0,  "This Month",
			       -1,  "Previous Month",
			           "Selected Month"
			    )
			RETURN
			    FORMAT ( Anchor, "MMMM 'yy" )
			
			```
		lineageTag: 17bb1a03-cf47-435f-88ca-b48335744153

		changedProperty = Name

	measure 'Confirmed Delivery Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_DeliveryDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 28ae2439-2214-477c-a715-37040bf407e3

		changedProperty = Name

	measure 'Confirmed Ship Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_ShipDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: efd2b9a9-6571-404f-956f-334ef3a87075

		changedProperty = Name

	measure 'Confirmed Delivery Date (Max)' = ```
			
			VAR dk =
			    VALUES ( 'Fact_Sales'[SalesLine_DeliveryDateKey] )
			RETURN
			CALCULATE (
			    MAX ( 'Dim_Date'[Date] ),          -- get the furthest date
			    REMOVEFILTERS ( 'Dim_Date' ),      -- ignore existing date filters
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 23ee242b-f42f-406e-9f8d-2f8d0e984e3b

		changedProperty = Name

	measure 'Selected Date Range (Invoices Only)' = ```
			
			VAR DatesWithOrders =
			    CALCULATETABLE(
			        VALUES('Dim_Date'[Date]),
			        KEEPFILTERS(
			            FILTER(ALLSELECTED('Dim_Date'[Date]), [Total Invoices] > 0)
			        )
			    )
			VAR MinDate = MINX(DatesWithOrders, 'Dim_Date'[Date])
			VAR MaxDate = MAXX(DatesWithOrders, 'Dim_Date'[Date])
			VAR CountDates = COUNTROWS(DatesWithOrders)
			RETURN
			SWITCH(
			    TRUE(),
			    CountDates = 0, "No dates selected",
			    MinDate = MaxDate, FORMAT(MinDate, "MMMM DD, YYYY"),
			    FORMAT(MinDate, "MMMM DD, YYYY") & " - " & FORMAT(MaxDate, "MMMM DD, YYYY")
			)
			
			```
		lineageTag: 9ceebfec-bc04-41a4-8a4f-24c5b9025637

		changedProperty = Name

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 8ae7cc31-8543-4f64-b7d2-a665f1122e4e
		sourceLineageTag: DateKey
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		sourceProviderType: datetime2
		lineageTag: a69ca1b1-d60e-48c5-b797-c6f90fad19be
		sourceLineageTag: Date
		summarizeBy: none
		sourceColumn: Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column RecId
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5b5b1c3e-a3f7-426f-a5b8-2bc974f4493d
		sourceLineageTag: RecId
		summarizeBy: none
		sourceColumn: RecId

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d0d621e4-8183-4ef8-9628-9dde843f135f
		sourceLineageTag: FiscalQuarterNum
		summarizeBy: none
		sourceColumn: FiscalQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: f4e290e9-f8fd-40f9-864e-19b89cd17089
		sourceLineageTag: FiscalYear
		summarizeBy: none
		sourceColumn: FiscalYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalPeriodNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 080731ba-d6b1-4e04-8af3-6bacf63939de
		sourceLineageTag: FiscalPeriodNum
		summarizeBy: sum
		sourceColumn: FiscalPeriodNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column FiscalWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 6a293b1c-7edc-4996-961b-548ae91ab296
		sourceLineageTag: FiscalWeekNum
		summarizeBy: sum
		sourceColumn: FiscalWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: c26687e8-1147-4447-8287-373c4255c1b3
		sourceLineageTag: CalendarYear
		summarizeBy: none
		sourceColumn: CalendarYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CalendarQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a96c6e77-3718-4e43-a12a-d4b0f8d9bf77
		sourceLineageTag: CalendarQuarterNum
		summarizeBy: none
		sourceColumn: CalendarQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column MonthNameShort
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 90cea45a-9177-4883-924f-e9ce95171b0a
		sourceLineageTag: MonthNameShort
		summarizeBy: none
		sourceColumn: MonthNameShort
		sortByColumn: MonthNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WeekdayNameLong
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: 043fe674-45a6-4938-986e-1e70080e6633
		sourceLineageTag: WeekdayNameLong
		summarizeBy: none
		sourceColumn: WeekdayNameLong

		annotation SummarizationSetBy = Automatic

	column WeekOfYearNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e7093d9c-99a0-4ec9-af73-3e252f035ae1
		sourceLineageTag: WeekOfYearNum
		summarizeBy: sum
		sourceColumn: WeekOfYearNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column DayOfMonthNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 05f8e4c6-6e08-4852-9d83-03578b125d32
		sourceLineageTag: DayOfMonthNum
		summarizeBy: sum
		sourceColumn: DayOfMonthNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column FiscalDayNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 7f3d1559-7d70-4467-bfa9-1ea5ff774977
		sourceLineageTag: FiscalDayNum
		summarizeBy: none
		sourceColumn: FiscalDayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsWorkingDayUs
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 53890f07-1422-4030-bf4a-0254393cfe57
		sourceLineageTag: IsWorkingDayUs
		summarizeBy: none
		sourceColumn: IsWorkingDayUs

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayBvba
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: a676f56c-8b9e-4f64-9994-3042c895b231
		sourceLineageTag: IsWorkingDayBvba
		summarizeBy: none
		sourceColumn: IsWorkingDayBvba

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayTeda
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 8cca0db0-4a8f-465f-bec0-5f8573f5676d
		sourceLineageTag: IsWorkingDayTeda
		summarizeBy: none
		sourceColumn: IsWorkingDayTeda

		annotation SummarizationSetBy = Automatic

	column WeekStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: e9021f4c-93a4-4232-952c-441ad4c4cf0f
		sourceLineageTag: WeekStartDate
		summarizeBy: none
		sourceColumn: WeekStartDate

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 4a22e59c-deb8-429c-a296-1da7846964fc
		sourceLineageTag: MonthStartDate
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

	column CurrentFiscalDayNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 15026d74-2d4e-42eb-abde-80e85ff5746e
		sourceLineageTag: CurrentFiscalDayNum
		summarizeBy: none
		sourceColumn: CurrentFiscalDayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CurrentFiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 9923cc7a-d224-4bb9-b03d-0d8a80db0a28
		sourceLineageTag: CurrentFiscalYear
		summarizeBy: none
		sourceColumn: CurrentFiscalYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column MonthNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ce46f699-ee9f-43a4-a684-f66b51bb3102
		sourceLineageTag: MonthNum
		summarizeBy: sum
		sourceColumn: MonthNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column MonthNameLong
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: e08ab0c4-5c40-4c3b-a8e1-047eba9934b8
		sourceLineageTag: MonthNameLong
		summarizeBy: none
		sourceColumn: MonthNameLong
		sortByColumn: MonthNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column YearMonthNum
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: fe2a7725-b9a8-44e5-94e3-34a4d81364d9
		sourceLineageTag: YearMonthNum
		summarizeBy: none
		sourceColumn: YearMonthNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column YearMonthLabel
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: 8a0fc1dd-368b-47b8-9d23-84f8f0360129
		sourceLineageTag: YearMonthLabel
		summarizeBy: none
		sourceColumn: YearMonthLabel
		sortByColumn: YearMonthNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterLabel
		dataType: string
		sourceProviderType: varchar(2)
		lineageTag: b28c52f9-6c16-43a7-a794-d083ecb9632a
		sourceLineageTag: CalendarQuarterLabel
		summarizeBy: none
		sourceColumn: CalendarQuarterLabel
		sortByColumn: CalendarQuarterNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column CalendarYearQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 37a419d4-ec0d-41b0-aba8-99e64d15c111
		sourceLineageTag: CalendarYearQuarterNum
		summarizeBy: none
		sourceColumn: CalendarYearQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalQuarterLabel
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: 1b159268-a983-432b-9b6d-9c4f4b84dd7e
		sourceLineageTag: FiscalQuarterLabel
		summarizeBy: none
		sourceColumn: FiscalQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FiscalYearQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 537ae7a2-45b9-4b3c-afc1-fc6e441ed621
		sourceLineageTag: FiscalYearQuarterNum
		summarizeBy: none
		sourceColumn: FiscalYearQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WeekdayNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d796d6f7-ebb0-4ff8-a1f7-21c582a6ff9a
		sourceLineageTag: WeekdayNum
		summarizeBy: none
		sourceColumn: WeekdayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WeekdayNameShort
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 1b4770b4-a1dd-4b6a-b173-0d55fb2ef9ac
		sourceLineageTag: WeekdayNameShort
		summarizeBy: none
		sourceColumn: WeekdayNameShort

		annotation SummarizationSetBy = Automatic

	column YearWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 01e32854-5f00-4aad-bd7c-994055351646
		sourceLineageTag: YearWeekNum
		summarizeBy: none
		sourceColumn: YearWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalYearWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: fa3c4d70-8532-47f4-b3f0-e023cf855c24
		sourceLineageTag: FiscalYearWeekNum
		summarizeBy: none
		sourceColumn: FiscalYearWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column DayOfYearNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: dd02956a-a5f5-4492-beaf-41eafc659cfa
		sourceLineageTag: DayOfYearNum
		summarizeBy: none
		sourceColumn: DayOfYearNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 5fa7b0c0-9b78-4d31-a048-b13800d3a8cc
		sourceLineageTag: IsWeekend
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsToday
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 277801a5-a54f-4b9b-b7d9-5817b122e75d
		sourceLineageTag: IsToday
		summarizeBy: none
		sourceColumn: IsToday

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsCurrentMonth
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 50cf15c8-4398-493e-a252-b876ed9eb67d
		sourceLineageTag: IsCurrentMonth
		summarizeBy: none
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentFiscalYear
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: afd07372-db1a-4861-95c2-0087e813319f
		sourceLineageTag: IsCurrentFiscalYear
		summarizeBy: none
		sourceColumn: IsCurrentFiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalPeriodLabel
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 2e8370c6-bf63-4c51-b1ce-06b1dc3f240d
		sourceLineageTag: FiscalPeriodLabel
		summarizeBy: none
		sourceColumn: FiscalPeriodLabel

		annotation SummarizationSetBy = Automatic

	column 'Original FISCAL YR'
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: d8176192-242f-4acf-8c1a-343eed0788ac
		sourceLineageTag: Original FISCAL YR
		summarizeBy: none
		sourceColumn: Original FISCAL YR

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column 'Original FISCAL PERIOD'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: fb9f1f16-14c6-46e1-8d95-15da2d15e02c
		sourceLineageTag: Original FISCAL PERIOD
		summarizeBy: none
		sourceColumn: Original FISCAL PERIOD

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column 'Reconciliation Year'
		dataType: string
		sourceProviderType: varchar(20)
		lineageTag: fa212546-d366-480f-ba63-af2693860f82
		sourceLineageTag: Reconciliation Year
		summarizeBy: none
		sourceColumn: Reconciliation Year

		annotation SummarizationSetBy = Automatic

	column WeeksInPeriod
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 9c05e514-2bd7-4bc1-a4ab-8d20806c8413
		sourceLineageTag: WeeksInPeriod
		summarizeBy: sum
		sourceColumn: WeeksInPeriod

		annotation SummarizationSetBy = Automatic

	column WeekStartDateSunday
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c966ba2-112c-4c44-86a7-a2df729ac46d
		sourceLineageTag: WeekStartDateSunday
		summarizeBy: none
		sourceColumn: WeekStartDateSunday

		annotation SummarizationSetBy = Automatic

	hierarchy 'Fiscal Hierarchy'
		lineageTag: ac1102b4-5a2d-4f4c-8002-fc8dd58666be

		level FiscalYear
			lineageTag: b8b8c765-3406-42d0-b4b7-a41203a46674
			column: FiscalYear

		level CalendarQuarterNum
			lineageTag: 59a5499d-f367-4dd8-b70c-d9f197cc4fb0
			column: CalendarQuarterNum

		level FiscalPeriodNum
			lineageTag: 2f6c0a6e-1d7c-4c9e-99b2-f3ff9250946e
			column: FiscalPeriodNum

		changedProperty = Name

	hierarchy 'Year Hierarchy'
		lineageTag: 08df1b28-2c1c-4f63-9918-3945812176e2

		level Year
			lineageTag: 9b2d0df1-b10b-44ac-b0fc-05c1dd9b48e0
			column: FiscalYear

		level Quarter
			lineageTag: 885aa587-9553-4dfd-b712-8652aa130986
			column: CalendarQuarterLabel

		level Month
			lineageTag: f99cda19-f3a6-4e99-85ac-e2ec35df2492
			column: MonthNameShort

		changedProperty = Name

	partition Dim_Date = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_Date
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

