table Dim_Date
	lineageTag: 5317e5ef-e441-4789-84e2-a31ac3668ecf
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_Date]
	dataCategory: Time

	measure 'Selected Dates (Orders Only)' = ```
			
			VAR DatesWithOrders =
			    CALCULATETABLE(
			        VALUES('Dim_Date'[Date]),
			        KEEPFILTERS(
			            FILTER(ALLSELECTED('Dim_Date'[Date]), [Total Orders] > 0)
			        )
			    )
			RETURN
			IF(
			    COUNTROWS(DatesWithOrders) = 0,
			    "No dates selected",
			    CONCATENATEX(
			        DatesWithOrders,
			        FORMAT('Dim_Date'[Date], "MMMM DD, YYYY"),
			        ", "
			    )
			)
			
			```
		lineageTag: 806ae44d-6cf1-4f88-8765-cd754d0f857a

		changedProperty = Name

	measure 'Selected Date Range (Orders Only)' = ```
			
			VAR DatesWithOrders =
			    CALCULATETABLE(
			        VALUES('Dim_Date'[Date]),
			        KEEPFILTERS(
			            FILTER(ALLSELECTED('Dim_Date'[Date]), [Total Orders] > 0)
			        )
			    )
			VAR MinDate = MINX(DatesWithOrders, 'Dim_Date'[Date])
			VAR MaxDate = MAXX(DatesWithOrders, 'Dim_Date'[Date])
			VAR CountDates = COUNTROWS(DatesWithOrders)
			RETURN
			SWITCH(
			    TRUE(),
			    CountDates = 0, "No dates selected",
			    MinDate = MaxDate, FORMAT(MinDate, "MMMM DD, YYYY"),
			    FORMAT(MinDate, "MMMM DD, YYYY") & " - " & FORMAT(MaxDate, "MMMM DD, YYYY")
			)
			
			```
		lineageTag: 8d9b64f6-0d29-40e5-942d-3726526453f0

		changedProperty = Name

	measure 'Requested Ship Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_RequestedShipDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: fb25a6ff-707e-4716-b911-08066482fd98

		changedProperty = Name

	measure 'Requested Ship Date (Earliest)' =
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_RequestedShipDateKey] )
			RETURN
			CALCULATE (
			    MIN ( 'Dim_Date'[Date] ),
			    REMOVEFILTERS ( 'Dim_Date' ),
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
		formatString: General Date
		lineageTag: fe66dd44-ea73-4cd2-be30-41e8f2b42b4d

		changedProperty = Name

	measure 'Requested Ship Date (Latest)' =
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_RequestedShipDateKey] )
			RETURN
			CALCULATE (
			    MAX ( 'Dim_Date'[Date] ),
			    REMOVEFILTERS ( 'Dim_Date' ),
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
		formatString: General Date
		lineageTag: f8e8b3c3-29aa-42dd-b51f-a523357d5968

		changedProperty = Name

	measure 'Month View Title' = ```
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )
			VAR Anchor =
			    EDATE ( TODAY (), Offset )
			VAR LabelText =
			    SWITCH (
			        Offset,
			        0,  "This Month",
			       -1,  "Previous Month",
			           "Selected Month"
			    )
			RETURN
			    FORMAT ( Anchor, "MMMM 'yy" )
			
			```
		lineageTag: 1b344f26-b293-4dce-a3a0-c275e015c6d6

		changedProperty = Name

	measure NextMonthEnd =
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )
			VAR Anchor =
			    EDATE ( TODAY(), Offset + 1 )
			RETURN
			    EOMONTH ( Anchor, 0 )
		formatString: General Date
		lineageTag: 53a219e0-44f8-4893-b66b-51c107f27a09

		changedProperty = Name

	measure NextMonthStart =
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )
			VAR Anchor =
			    EDATE ( TODAY(), Offset + 1 )              -- one month after base
			RETURN
			    DATE ( YEAR ( Anchor ), MONTH ( Anchor ), 1 )
		formatString: General Date
		lineageTag: 62f4dbe1-1a29-4244-a0e5-b70f110e88e8

		changedProperty = Name

	measure BaseMonthEnd =
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )
			VAR Anchor =
			    EDATE ( TODAY(), Offset )
			RETURN
			    EOMONTH ( Anchor, 0 )
		formatString: General Date
		lineageTag: ba2d1656-b7b6-4307-8cc3-649d5cf556e0

		changedProperty = Name

	measure BaseMonthStart =
			
			VAR Offset =
			    SELECTEDVALUE ( 'Month View'[Offset], 0 )   -- default: This Month
			VAR Anchor =
			    EDATE ( TODAY(), Offset )                  -- same day in shifted month
			RETURN
			    DATE ( YEAR ( Anchor ), MONTH ( Anchor ), 1 )
		formatString: General Date
		lineageTag: e24a23a4-3fa9-47ef-a03f-b889a05f6a89

		changedProperty = Name

	measure InvoiceDate =
			
			VAR dk =
			    VALUES ( 'Fact_Sales'[InvoiceDateKey] )
			RETURN
			CALCULATE (
			    MAX ( 'Dim_Date'[Date] ),
			    REMOVEFILTERS ( 'Dim_Date' ),
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
		formatString: General Date
		lineageTag: f9047694-4416-4358-a3d7-78e804dc40a1

		changedProperty = Name

	measure 'Confirmed Delivery Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_DeliveryDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 17527534-c791-4fe4-a179-0a0b1293ee69

		changedProperty = Name

	measure 'Confirmed Delivery Date (Max)' = ```
			
			VAR dk =
			    VALUES ( 'Fact_Sales'[SalesLine_DeliveryDateKey] )
			RETURN
			CALCULATE (
			    MAX ( 'Dim_Date'[Date] ),          -- get the furthest date
			    REMOVEFILTERS ( 'Dim_Date' ),      -- ignore existing date filters
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: ffbea992-5730-41b9-8985-a04d7209330f

		changedProperty = Name

	measure 'Confirmed Ship Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_ShipDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 5fa49a64-de69-4d31-8496-f083a12ce297

		changedProperty = Name

	measure 'Order Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[OrderDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 8b89ff7a-4775-4136-9757-97daeb01db40

		changedProperty = Name

	measure 'Delivery Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLine_DeliveryDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 10b17a49-b242-4234-a9b9-c2add4289134

		changedProperty = Name

	measure 'SalesLine Created Date' = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesLineCreatedDateKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Date'[Date] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Date' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Date'[DateKey] )
			)
			
			```
		formatString: General Date
		lineageTag: 30242e14-8840-4dfe-8499-6fb27f27d0b8

		changedProperty = Name

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: ea8cb3e8-c4c9-40ba-a6f0-cc51926bdb1c
		sourceLineageTag: DateKey
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		sourceProviderType: datetime2
		lineageTag: 899ce3c9-3d37-4e21-bafa-d11b15d7d1a3
		sourceLineageTag: Date
		summarizeBy: none
		sourceColumn: Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column RecId
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: e776bf7e-0997-41a1-b2f2-e2dde59376c9
		sourceLineageTag: RecId
		summarizeBy: none
		sourceColumn: RecId

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 311e302b-880f-4bdb-81d8-36787fee43cc
		sourceLineageTag: FiscalQuarterNum
		summarizeBy: none
		sourceColumn: FiscalQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 70c11c0b-5ab0-4f82-9cc0-ea068f1babf4
		sourceLineageTag: FiscalYear
		summarizeBy: none
		sourceColumn: FiscalYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalPeriodNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 189f9340-f00d-494d-afdf-7e06535d4f5f
		sourceLineageTag: FiscalPeriodNum
		summarizeBy: sum
		sourceColumn: FiscalPeriodNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column FiscalWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 85b3e1a8-6320-4843-af66-7a57be35a401
		sourceLineageTag: FiscalWeekNum
		summarizeBy: sum
		sourceColumn: FiscalWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 3a513d7d-5ff1-4da5-bb0d-46f72276b558
		sourceLineageTag: CalendarYear
		summarizeBy: none
		sourceColumn: CalendarYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CalendarQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 51831058-321f-400f-874e-39992199b56b
		sourceLineageTag: CalendarQuarterNum
		summarizeBy: none
		sourceColumn: CalendarQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column MonthNameShort
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 80885412-20c2-4217-ad3b-941849a2afb5
		sourceLineageTag: MonthNameShort
		summarizeBy: none
		sourceColumn: MonthNameShort
		sortByColumn: FiscalPeriodNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WeekdayNameLong
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: fe28ead2-9434-4379-965d-971fa28dd600
		sourceLineageTag: WeekdayNameLong
		summarizeBy: none
		sourceColumn: WeekdayNameLong

		annotation SummarizationSetBy = Automatic

	column WeekOfYearNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 371b3f50-08fe-4d09-b024-f42050629044
		sourceLineageTag: WeekOfYearNum
		summarizeBy: sum
		sourceColumn: WeekOfYearNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column DayOfMonthNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f21e527e-e6f3-4a95-8e28-3ddfff0bbef7
		sourceLineageTag: DayOfMonthNum
		summarizeBy: sum
		sourceColumn: DayOfMonthNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column FiscalDayNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 69148b23-5d3d-48fc-bed4-a8a718fffca0
		sourceLineageTag: FiscalDayNum
		summarizeBy: none
		sourceColumn: FiscalDayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsWorkingDayUs
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 0d8fd7f4-77f7-4311-9caf-477dcce851fa
		sourceLineageTag: IsWorkingDayUs
		summarizeBy: none
		sourceColumn: IsWorkingDayUs

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayBvba
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 783536df-9603-410f-8eac-9e5a61d5a0c9
		sourceLineageTag: IsWorkingDayBvba
		summarizeBy: none
		sourceColumn: IsWorkingDayBvba

		annotation SummarizationSetBy = Automatic

	column IsWorkingDayTeda
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 476aa2a9-b872-4125-ba44-d83d191c64c3
		sourceLineageTag: IsWorkingDayTeda
		summarizeBy: none
		sourceColumn: IsWorkingDayTeda

		annotation SummarizationSetBy = Automatic

	column WeekStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 22ae5fa5-4cfe-4122-8fb5-5f618b4bfa8e
		sourceLineageTag: WeekStartDate
		summarizeBy: none
		sourceColumn: WeekStartDate

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: d1cce868-e7be-4fc1-aae4-ef61a2f83286
		sourceLineageTag: MonthStartDate
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

	column CurrentFiscalDayNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 7538039f-70f5-4121-92ec-eb8594ef946d
		sourceLineageTag: CurrentFiscalDayNum
		summarizeBy: none
		sourceColumn: CurrentFiscalDayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CurrentFiscalYear
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: d9f57b47-cd88-46ad-ae36-d07786f786e1
		sourceLineageTag: CurrentFiscalYear
		summarizeBy: none
		sourceColumn: CurrentFiscalYear

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column MonthNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1b555bac-6476-46af-867b-f97df4b05206
		sourceLineageTag: MonthNum
		summarizeBy: sum
		sourceColumn: MonthNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column MonthNameLong
		dataType: string
		sourceProviderType: varchar(9)
		lineageTag: 5aa59341-1c96-4a2e-87fa-9e40c2bbe0d1
		sourceLineageTag: MonthNameLong
		summarizeBy: none
		sourceColumn: MonthNameLong

		annotation SummarizationSetBy = Automatic

	column YearMonthNum
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: 11c7405a-1564-49d7-ad3a-1369e3e1ecda
		sourceLineageTag: YearMonthNum
		summarizeBy: none
		sourceColumn: YearMonthNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = Automatic

	column YearMonthLabel
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: 14ee3012-dd0c-4a7f-9a82-dcefa4cb2fb0
		sourceLineageTag: YearMonthLabel
		summarizeBy: none
		sourceColumn: YearMonthLabel

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterLabel
		dataType: string
		sourceProviderType: varchar(2)
		lineageTag: 1fef673d-4a4e-45b5-b0a3-87bed52592a6
		sourceLineageTag: CalendarQuarterLabel
		summarizeBy: none
		sourceColumn: CalendarQuarterLabel

		annotation SummarizationSetBy = Automatic

	column CalendarYearQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b8a966a6-31df-44c9-8ceb-7cc47071b75b
		sourceLineageTag: CalendarYearQuarterNum
		summarizeBy: none
		sourceColumn: CalendarYearQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalQuarterLabel
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: 99b5890e-ecb4-4de2-b748-99b56e1a38d7
		sourceLineageTag: FiscalQuarterLabel
		summarizeBy: none
		sourceColumn: FiscalQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FiscalYearQuarterNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: bf3312e7-09bb-4f68-a171-c1b153c898c2
		sourceLineageTag: FiscalYearQuarterNum
		summarizeBy: none
		sourceColumn: FiscalYearQuarterNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WeekdayNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 25ee0eb3-e0c2-49a9-a713-835d6f25f543
		sourceLineageTag: WeekdayNum
		summarizeBy: none
		sourceColumn: WeekdayNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column WeekdayNameShort
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 48287e31-659e-4304-81db-2804270e937d
		sourceLineageTag: WeekdayNameShort
		summarizeBy: none
		sourceColumn: WeekdayNameShort

		annotation SummarizationSetBy = Automatic

	column YearWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: c3a3fd76-8c9d-4f46-8b90-b386e62e2f16
		sourceLineageTag: YearWeekNum
		summarizeBy: none
		sourceColumn: YearWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column FiscalYearWeekNum
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e4fc6ab3-b109-4ed9-9558-805ed3666c76
		sourceLineageTag: FiscalYearWeekNum
		summarizeBy: none
		sourceColumn: FiscalYearWeekNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column DayOfYearNum
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: c6d99fe4-0486-4897-95b9-25c342a77674
		sourceLineageTag: DayOfYearNum
		summarizeBy: none
		sourceColumn: DayOfYearNum

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: f9e6709d-2118-4aca-b39e-2161335e829a
		sourceLineageTag: IsWeekend
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsToday
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3c2def34-75c8-43f1-ae8f-cc9be0307828
		sourceLineageTag: IsToday
		summarizeBy: none
		sourceColumn: IsToday

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column IsCurrentMonth
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: ed1f99f8-3edd-4020-ba55-a85c8f967c87
		sourceLineageTag: IsCurrentMonth
		summarizeBy: none
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentFiscalYear
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: cd3f129b-6b3e-40c1-a25b-ba1949273fb9
		sourceLineageTag: IsCurrentFiscalYear
		summarizeBy: none
		sourceColumn: IsCurrentFiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalPeriodLabel
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: c432681a-26d6-416c-b358-2b90e91f75fa
		sourceLineageTag: FiscalPeriodLabel
		summarizeBy: none
		sourceColumn: FiscalPeriodLabel

		annotation SummarizationSetBy = Automatic

	column 'Original FISCAL YR'
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: e841bf14-a17a-436e-bd04-26ca8c7d672c
		sourceLineageTag: Original FISCAL YR
		summarizeBy: sum
		sourceColumn: Original FISCAL YR

		annotation SummarizationSetBy = Automatic

	column 'Original FISCAL PERIOD'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f44bb96f-64a7-4eb2-87e4-a17034e7cf3b
		sourceLineageTag: Original FISCAL PERIOD
		summarizeBy: sum
		sourceColumn: Original FISCAL PERIOD

		annotation SummarizationSetBy = Automatic

	column 'Reconciliation Year'
		dataType: string
		sourceProviderType: varchar(20)
		lineageTag: bdab118d-16cd-404a-ab4f-f517933b7c97
		sourceLineageTag: Reconciliation Year
		summarizeBy: none
		sourceColumn: Reconciliation Year

		annotation SummarizationSetBy = Automatic

	column WeeksInPeriod
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 78adf2d4-5d1b-4643-9f97-5e081c58696e
		sourceLineageTag: WeeksInPeriod
		summarizeBy: sum
		sourceColumn: WeeksInPeriod

		annotation SummarizationSetBy = Automatic

	column WeekStartDateSunday
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 18d4a6be-6e3b-444e-91a7-bf06f539a22d
		sourceLineageTag: WeekStartDateSunday
		summarizeBy: none
		sourceColumn: WeekStartDateSunday

		annotation SummarizationSetBy = Automatic

	hierarchy 'Fiscal Hierarchy'
		lineageTag: d12aab9e-1927-41a4-abcb-0376001aec0c

		level Date
			lineageTag: 80fe726f-12ea-44e3-a8b9-2a57214a3e5e
			column: Date

		changedProperty = Name

	hierarchy 'Calendar Hierarchy'
		lineageTag: d178742e-f168-40e7-bf32-b7b100cd0f04

		level Date
			lineageTag: 5dbe86d6-144d-49d0-8c05-5eb7a73d3b64
			column: Date

		changedProperty = Name

	partition Dim_Date = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_Date
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

