table Dim_Account
	lineageTag: eb6dbe57-5bef-4633-be70-54e0d844768f
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_Account]

	measure 'Duplicate Rep Count by Customer PO' = ```
			
			
			CALCULATE(
			    DISTINCTCOUNT('Fact_Sales'[SalesTaker_EmployeeKey]),
			    ALLEXCEPT(
			        'Fact_Sales',
			        'Fact_Sales'[PurchaseOrderFormNumber],
			        'Fact_Sales'[CustomerKey]   -- replace with the fact-side customer key that joins to Dim_Account
			    )
			)
			
			```
		formatString: 0
		lineageTag: e76e0dfa-464c-4d03-8901-cf352e2fd109

		changedProperty = Name

	measure 'Customer Selection Grain' =
			
			VAR _OneCustomer =
			    HASONEVALUE ( 'Dim_Account'[CustomerKey] )
			VAR _OneChain =
			    HASONEVALUE ( 'Dim_Account'[Harmonized_Name] )
			RETURN
			    SWITCH (
			        TRUE (),
			        _OneCustomer, "Customer",
			        _OneChain, "Chain",
			        "None"
			    )
		lineageTag: 065d46cd-a04a-47c9-97ff-994f2f0e0032

		changedProperty = Name

	measure 'Customer ID Display' =
			
			VAR _Grain =
			    [Customer Selection Grain]
			RETURN
			    SWITCH (
			        _Grain,
			        "Customer", SELECTEDVALUE ( 'Dim_Account'[Customer_ID] ) & "",
			        "Chain", "Multiple Customer IDs",
			        "Select a customer"
			    )
		lineageTag: 1ce099d1-8ae9-4b90-b919-3e305af7dac5

		changedProperty = Name

	measure 'Customer Name Display' =
			
			VAR _Grain =
			    [Customer Selection Grain]
			RETURN
			    SWITCH (
			        _Grain,
			        "Customer", SELECTEDVALUE ( 'Dim_Account'[CustomerName] ),
			        "Chain", SELECTEDVALUE ( 'Dim_Account'[Harmonized_Name] ),
			        "Select a customer"
			    )
		lineageTag: c051b589-7a99-48cd-bbb6-71090c452949

		changedProperty = Name

	measure 'Last Purchase Date Display' =
			
			VAR _Grain =
			    [Customer Selection Grain]
			VAR _DateKey =
			    [Last Purchase DateKey]
			RETURN
			    SWITCH (
			        TRUE (),
			        _Grain = "None", "Select a customer",
			        ISBLANK ( _DateKey ), "No purchases",
			        FORMAT (
			            CALCULATE (
			                MAX ( 'Dim_Date'[Date] ),
			                REMOVEFILTERS ( 'Dim_Date' ),
			                TREATAS ( { _DateKey }, 'Dim_Date'[DateKey] )
			            ),
			            "MM/dd/yyyy"
			        )
			    )
		lineageTag: 01d62b38-fa24-4bce-a8df-40e5ec59edc6

		changedProperty = Name

	measure 'Last Purchase Volume Display' =
			
			VAR _Grain =
			    [Customer Selection Grain]
			VAR _DateKey =
			    [Last Purchase DateKey]
			RETURN
			    SWITCH (
			        TRUE (),
			        _Grain = "None", "Select a customer",
			        ISBLANK ( _DateKey ), "No purchases",
			        FORMAT (
			            CALCULATE (
			                SUM ( 'Fact_Sales'[Quantity_LBs] ),
			                REMOVEFILTERS ( 'Dim_Date' ),
			                TREATAS ( { _DateKey }, 'Fact_Sales'[OrderDateKey] )
			            ),
			            "#,0"
			        ) & " LBs"
			    )
		lineageTag: 97a48d1e-6fdf-4752-8588-59184bdfac0c

		changedProperty = Name

	measure 'Last Purchase Product Display' =
			
			VAR _Grain =
			    [Customer Selection Grain]
			VAR _DateKey =
			    [Last Purchase DateKey]
			RETURN
			    SWITCH (
			        TRUE (),
			        _Grain = "None", "Select a customer",
			        ISBLANK ( _DateKey ), "No purchases",
			
			        VAR _ProductsAtLastDate =
			            CALCULATETABLE (
			                VALUES ( 'Fact_Sales'[ProductKey] ),
			                REMOVEFILTERS ( 'Dim_Date' ),
			                TREATAS ( { _DateKey }, 'Fact_Sales'[OrderDateKey] ),
			                KEEPFILTERS ( 'Fact_Sales'[Quantity_LBs] <> 0 )
			            )
			        VAR _ProductCount =
			            COUNTROWS ( _ProductsAtLastDate )
			        VAR _ProductName =
			            CALCULATE (
			                SELECTEDVALUE ( 'Dim_Product'[Product_Name] ),
			                TREATAS ( _ProductsAtLastDate, 'Dim_Product'[ProductKey] )
			            )
			        RETURN
			            IF (
			                _ProductCount = 1,
			                COALESCE ( _ProductName, "Unknown Product" ),
			                "Multiple Products"
			            )
			    )
		lineageTag: 954d99e7-569b-4987-b36f-bb5da333f2b0

		changedProperty = Name

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 44ed0075-4475-4eff-9a30-b1f23918905a
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CMPNY
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: cc0489dc-f6a8-4c37-badd-d480661e34a1
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		annotation SummarizationSetBy = Automatic

	column Customer_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 86c47ef1-f563-4809-9c1e-698c06d8c14c
		sourceLineageTag: Customer_ID
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Invoice_Account
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f3031f6c-b4f5-4a0e-953e-85919f05c6aa
		sourceLineageTag: Invoice_Account
		summarizeBy: none
		sourceColumn: Invoice_Account

		annotation SummarizationSetBy = Automatic

	column Legacy_Customer_ID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ad650957-5786-4d34-bcc8-938187060c2a
		sourceLineageTag: Legacy_Customer_ID
		summarizeBy: count
		sourceColumn: Legacy_Customer_ID

		annotation SummarizationSetBy = Automatic

	column GMAccountNo
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 0b037451-2c67-4d52-8f45-bec91f2bd589
		sourceLineageTag: GMAccountNo
		summarizeBy: sum
		sourceColumn: GMAccountNo

		annotation SummarizationSetBy = Automatic

	column GMRecID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 05c3d559-4e6d-4004-bb96-b4a844439ecf
		sourceLineageTag: GMRecID
		summarizeBy: count
		sourceColumn: GMRecID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4a338b1c-e5a2-4df7-ae0d-3cb7d487d438
		sourceLineageTag: CustomerName
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Harmonized_Name
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b34fccc7-17ae-4024-be29-9251acc08490
		sourceLineageTag: Harmonized_Name
		summarizeBy: none
		sourceColumn: Harmonized_Name

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 511d5069-550a-42fd-8c29-0cb1dc56c1b0
		sourceLineageTag: Address
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 8814b01e-33a7-4711-9d75-eff84846a37c
		sourceLineageTag: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e7fbcbc5-66b1-4f3f-9eb5-93c26356141e
		sourceLineageTag: State
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c8917162-58ca-48a8-885a-499e7e06f476
		sourceLineageTag: ZIP
		summarizeBy: none
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: abacf543-e385-4fe5-a7f9-d35a54af5856
		sourceLineageTag: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column CityState
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4dd9e11a-e7ce-4b8f-b770-13f4ffd65d1c
		sourceLineageTag: CityState
		summarizeBy: none
		sourceColumn: CityState

		annotation SummarizationSetBy = Automatic

	column Territory_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ff3bd10b-781f-450a-9e43-c48894a6e90a
		sourceLineageTag: Territory_ID
		summarizeBy: none
		sourceColumn: Territory_ID

		annotation SummarizationSetBy = Automatic

	column Salesman_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c4b38245-2b91-439f-b914-fa7cc6d96919
		sourceLineageTag: Salesman_ID
		summarizeBy: none
		sourceColumn: Salesman_ID

		annotation SummarizationSetBy = Automatic

	column SalesChannel
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6281815d-dabb-4a3c-b9f6-03add3f4ac0e
		sourceLineageTag: SalesChannel
		summarizeBy: none
		sourceColumn: SalesChannel

		annotation SummarizationSetBy = Automatic

	column Industry_Segment
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b603cbaa-1ed4-468c-944e-faf850d9cf5a
		sourceLineageTag: Industry_Segment
		summarizeBy: none
		sourceColumn: Industry_Segment

		annotation SummarizationSetBy = Automatic

	column Subsegment
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 33adfe4f-def3-4cfa-8cb1-98d516f57eb0
		sourceLineageTag: Subsegment
		summarizeBy: none
		sourceColumn: Subsegment

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 9644ad9d-e835-485b-8d0e-cfa842369554
		sourceLineageTag: Status
		summarizeBy: sum
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column EffectiveCountry
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ee064463-4c11-41ea-8067-d87d60eb407c
		sourceLineageTag: EffectiveCountry
		summarizeBy: sum
		sourceColumn: EffectiveCountry

		annotation SummarizationSetBy = Automatic

	column Account_Tier
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 16f61eca-047c-4690-be24-cef0ba488ce0
		sourceLineageTag: Account_Tier
		summarizeBy: sum
		sourceColumn: Account_Tier

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		sourceProviderType: decimal(38, 10)
		lineageTag: d70a134c-1875-4929-a720-29760d32aad6
		sourceLineageTag: Longitude
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Latitude
		dataType: double
		sourceProviderType: decimal(38, 10)
		lineageTag: f99846f4-baca-42c3-99f5-93d4dc4b8fd0
		sourceLineageTag: Latitude
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PaymentTerms
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: da5f21cd-e44a-40d4-8ef7-e77ddcb0b9e0
		sourceLineageTag: PaymentTerms
		summarizeBy: none
		sourceColumn: PaymentTerms

		annotation SummarizationSetBy = Automatic

	column PhoneNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4e428a41-9bf5-4ce9-9a37-3d31b2aac200
		sourceLineageTag: PhoneNumber
		summarizeBy: none
		sourceColumn: PhoneNumber

		annotation SummarizationSetBy = Automatic

	column PurchasingEmail
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9e86bf14-6c42-431d-9ab4-9c02a00fdf50
		sourceLineageTag: PurchasingEmail
		summarizeBy: none
		sourceColumn: PurchasingEmail

		annotation SummarizationSetBy = Automatic

	column InvoicingEmail
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a1b20d1d-8db8-4b83-930f-d90861ecc816
		sourceLineageTag: InvoicingEmail
		summarizeBy: none
		sourceColumn: InvoicingEmail

		annotation SummarizationSetBy = Automatic

	column customergroup
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ba041cc8-f9af-4029-8f13-71c6c84dbb3b
		sourceLineageTag: customergroup
		summarizeBy: none
		sourceColumn: customergroup

		annotation SummarizationSetBy = Automatic

	column customer_currency
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: d1f55e70-26d9-48ff-affb-b3127c47bafa
		sourceLineageTag: customer_currency
		summarizeBy: none
		sourceColumn: customer_currency

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		sourceProviderType: varchar(6)
		lineageTag: 6f95c2ef-a819-4013-967c-43ee140b278e
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 7130e78b-f8d1-417b-9f7a-26f218afc570
		sourceLineageTag: RecordEffectiveStartDate
		summarizeBy: none
		sourceColumn: RecordEffectiveStartDate

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveEndDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: f85d015b-7f94-4bd9-a43c-cde4acdda57a
		sourceLineageTag: RecordEffectiveEndDate
		summarizeBy: none
		sourceColumn: RecordEffectiveEndDate

		annotation SummarizationSetBy = Automatic

	column RecordStatus
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2514ba95-703f-4633-add7-1ea825e2a763
		sourceLineageTag: RecordStatus
		summarizeBy: sum
		sourceColumn: RecordStatus

		annotation SummarizationSetBy = Automatic

	partition Dim_Account = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_Account
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

