table Dim_Employee
	lineageTag: 9815a912-0621-4193-9b4a-20b4076cb19c
	sourceLineageTag: [dbo].[mtbl_EDW_Dim_Employee]

	measure CustServRep = ```
			
			VAR dk = VALUES ( 'Fact_Sales'[SalesTaker_EmployeeKey] )
			RETURN
			CALCULATE (
			    SELECTEDVALUE ( 'Dim_Employee'[Employee_Name] ),
			    -- neutralize any existing Dim_Date filter coming from the active relationship
			    REMOVEFILTERS ( 'Dim_Employee' ),
			    -- apply the requested-ship keys as a filter on the date dimension
			    TREATAS ( dk, 'Dim_Employee'[EmployeeKey] )
			)
			
			```
		lineageTag: 034eed00-b426-4b2f-b416-d9a850880bc2

		changedProperty = Name

	column EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: a26bc66b-8d23-42d9-9bfa-02dfdb41d33d
		sourceLineageTag: EmployeeKey
		summarizeBy: none
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Personnel_Number
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b0da148e-95f9-49ac-9646-2b23fb8ef111
		sourceLineageTag: Personnel_Number
		summarizeBy: none
		sourceColumn: Personnel_Number

		annotation SummarizationSetBy = Automatic

	column Employee_Name
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 2ea6f121-156e-4a7a-88d8-3231d924fba9
		sourceLineageTag: Employee_Name
		summarizeBy: none
		sourceColumn: Employee_Name

		annotation SummarizationSetBy = Automatic

	column Employment_Type
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c74a7bcd-d159-4c0c-8d80-6b67c741e3da
		sourceLineageTag: Employment_Type
		summarizeBy: sum
		sourceColumn: Employment_Type

		annotation SummarizationSetBy = Automatic

	column Employment_Type_Desc
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: ca199b76-3402-42d6-99c2-c84fa3f216e8
		sourceLineageTag: Employment_Type_Desc
		summarizeBy: none
		sourceColumn: Employment_Type_Desc

		annotation SummarizationSetBy = Automatic

	column IsPerson
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: b8b3b57e-4174-4e82-b60e-970fcdb23d01
		sourceLineageTag: IsPerson
		summarizeBy: none
		sourceColumn: IsPerson

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		sourceProviderType: varchar(6)
		lineageTag: 12845f12-f6f5-47a7-9e29-6ec2fc5060ea
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveStartDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 83e986a9-b68e-400a-b990-2f71e5935bf0
		sourceLineageTag: RecordEffectiveStartDate
		summarizeBy: none
		sourceColumn: RecordEffectiveStartDate

		annotation SummarizationSetBy = Automatic

	column RecordEffectiveEndDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 63bda4eb-56ca-4329-b03b-754ddc8a398b
		sourceLineageTag: RecordEffectiveEndDate
		summarizeBy: none
		sourceColumn: RecordEffectiveEndDate

		annotation SummarizationSetBy = Automatic

	column RecordStatus
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 701ac3bc-0abb-4870-92ff-6af118b37110
		sourceLineageTag: RecordStatus
		summarizeBy: sum
		sourceColumn: RecordStatus

		annotation SummarizationSetBy = Automatic

	partition Dim_Employee = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Dim_Employee
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

