table Fact_Budget
	lineageTag: 2376e6cb-46ca-4200-8699-9ac394af5f9b
	sourceLineageTag: [dbo].[mtbl_EDW_Fact_SalesBudget]

	measure MTD_Volume_Budget = ```
			
			CALCULATE(
			    SUM('Fact_Budget'[Quantity_LBs]),
			
			    -- Current month filter
			    FILTER(
			        ALL('Dim_Date'),
			        YEAR('Dim_Date'[DATE]) = YEAR(TODAY()) &&
			        MONTH('Dim_Date'[DATE]) = MONTH(TODAY())
			    )
			)
			
			```
		lineageTag: 0b964904-558e-428a-95dd-13242a27bbb8

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MTD_Volume_Variance =
			
			VAR __BASELINE_VALUE = [MTD_Volume_Budget]
			VAR __VALUE_TO_COMPARE = [MTD_Volume_Total]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		lineageTag: 4dd4370f-79c8-4e5e-a4d5-fdf49be40bc8

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Volume_Budget = ```
			
			CALCULATE(
			    SUM('Fact_Budget'[Quantity_LBs]),
			
			    -- Current month filter
			    FILTER(
			        ALL('Dim_Date'),
			        YEAR('Dim_Date'[DATE]) = YEAR(TODAY()) &&
			        MONTH('Dim_Date'[DATE]) < MONTH(TODAY())
			    )
			)
			
			```
		formatString: #,0
		lineageTag: 6e55ad8d-064d-4c63-b93b-176f7199cca2

		changedProperty = Name

		changedProperty = FormatString

	measure MTD_Revenue_Budget = ```
			
			CALCULATE(
			    SUM('Fact_Budget'[Amount]),
			
			    -- Current month filter
			    FILTER(
			        ALL('Dim_Date'),
			        YEAR('Dim_Date'[DATE]) = YEAR(TODAY()) &&
			        MONTH('Dim_Date'[DATE]) = MONTH(TODAY())
			    )
			)
			
			```
		lineageTag: 9357e337-93ad-4e99-9a68-087ec45291cd

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YTD_Revenue_Budget = ```
			
			CALCULATE(
			    SUM('Fact_Budget'[Amount]),
			
			
			    -- Current month filter
			    FILTER(
			        ALL('Dim_Date'),
			        YEAR('Dim_Date'[DATE]) = YEAR(TODAY()) &&
			        MONTH('Dim_Date'[DATE]) < MONTH(TODAY())
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 81d5185e-4442-438d-988f-dcba6ea29339

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure MTD_Revenue_Variance =
			
			VAR __BASELINE_VALUE = [MTD_Revenue_Budget]
			VAR __VALUE_TO_COMPARE = [MTD_Revenue_Total]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 3595d823-3272-447f-97ab-7cf97bd960ad

		changedProperty = Name

		changedProperty = FormatString

	measure YTD_Revenue_Variance =
			
			VAR __BASELINE_VALUE = [YTD_Revenue_Budget]
			VAR __VALUE_TO_COMPARE = [YTD_Revenue_Total]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		formatString: 0%;-0%;0%
		lineageTag: 8276cc26-c86a-4fe2-8e2c-2e67c83c0202

		changedProperty = Name

		changedProperty = FormatString

	measure YTD_Volume_Variance =
			
			VAR __BASELINE_VALUE = [YTD_Volume_Budget]
			VAR __VALUE_TO_COMPARE = [YTD_Volume_Total]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: b7c52f73-0950-498d-9700-2bd8a9eb909c

		changedProperty = Name

		changedProperty = FormatString

	measure 'Budget Quantity' = SUM(Fact_Budget[Quantity_LBs])
		lineageTag: b62d0e38-b5ee-441c-b665-aeb621af0bc8

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Budget Amount' = SUM(Fact_Budget[Amount])
		lineageTag: 75982aaa-872c-427e-ab6f-7b53e70b0c4d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMPNY
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7b3b5b68-b576-410b-bcce-37dcfb4162a9
		sourceLineageTag: CMPNY
		summarizeBy: none
		sourceColumn: CMPNY

		annotation SummarizationSetBy = Automatic

	column SalesLine_Status
		dataType: string
		sourceProviderType: varchar(12)
		lineageTag: 8c47b61b-c23b-4b2d-b0db-4b624762ada2
		sourceLineageTag: SalesLine_Status
		summarizeBy: none
		sourceColumn: SalesLine_Status

		annotation SummarizationSetBy = Automatic

	column DATE
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 7d433dc1-135e-48d9-a2b2-66e393e98251
		sourceLineageTag: DATE
		summarizeBy: none
		sourceColumn: DATE

		annotation SummarizationSetBy = Automatic

	column DATEKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: c4220dda-0fe4-4291-8c35-530273bc3cd3
		sourceLineageTag: DATEKey
		summarizeBy: none
		sourceColumn: DATEKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column CustomerID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c08b6716-641d-4676-adb3-8070fa4d115c
		sourceLineageTag: CustomerID
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 0cd6101c-3ee4-4c37-9147-49c45e980ca8
		sourceLineageTag: ProductID
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column CPCID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c3a78344-2f54-42c5-8bbe-18b17bdffad4
		sourceLineageTag: CPCID
		summarizeBy: none
		sourceColumn: CPCID

		annotation SummarizationSetBy = Automatic

	column CPCID_Legacy
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 48a4b106-aff9-4237-8d22-04639386ffa5
		sourceLineageTag: CPCID_Legacy
		summarizeBy: none
		sourceColumn: CPCID_Legacy

		annotation SummarizationSetBy = Automatic

	column Quantity_LBs
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: b698410d-afb8-49a9-b9b5-fa10c8cdb1ac
		sourceLineageTag: Quantity_LBs
		summarizeBy: none
		sourceColumn: Quantity_LBs

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Amount
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 6)
		lineageTag: f422e767-8b36-44c9-a7ce-9b1e3d27762c
		sourceLineageTag: Amount
		summarizeBy: none
		sourceColumn: Amount

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LegalEntityTranslatedToD365
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 95d93822-37aa-4ad7-ac46-99e1893efef2
		sourceLineageTag: LegalEntityTranslatedToD365
		summarizeBy: none
		sourceColumn: LegalEntityTranslatedToD365

		annotation SummarizationSetBy = Automatic

	column AccountTranslatedToD365
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 9bddeec4-6ed5-4bdd-aa03-22c9c935acfb
		sourceLineageTag: AccountTranslatedToD365
		summarizeBy: none
		sourceColumn: AccountTranslatedToD365

		annotation SummarizationSetBy = Automatic

	column ProductTranslatedToD365
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 8acb9284-831b-4c73-a0d9-8b981ce07d1e
		sourceLineageTag: ProductTranslatedToD365
		summarizeBy: none
		sourceColumn: ProductTranslatedToD365

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		sourceProviderType: varchar(50)
		lineageTag: f9aeb721-e99c-4d64-bc42-27c939c1bf50
		sourceLineageTag: Source
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 8f13d880-e115-454c-9fef-6fae7acf7169
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2a56243a-c86e-4a04-bd07-46e913c375f3
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Legal_EntityKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c30fe6fa-2429-4142-a43c-614a4b7da78f
		sourceLineageTag: Legal_EntityKey
		summarizeBy: none
		sourceColumn: Legal_EntityKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 0bbec947-085e-4811-8d95-e8dddec2a5ef
		sourceLineageTag: EmployeeKey
		summarizeBy: none
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MarketSegmentationKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 24d22be2-4cfc-4648-82a6-ae15d739c662
		sourceLineageTag: MarketSegmentationKey
		summarizeBy: none
		sourceColumn: MarketSegmentationKey

		changedProperty = IsHidden

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	partition Fact_Budget = entity
		mode: directLake
		source
			entityName: mtbl_EDW_Fact_SalesBudget
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

